### ISSUE TITLE
Codes-Verschicken

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#1003]
- [ ] Feld Wieviele Tage im Vorraus ergänzen
- [ ] Versand an cb_manager & Stations-E-Mail
- [ ] Automatischer Versand der E-Mail 1 Mal im Monat optional anklickbar

**Comment by datengraben** [comment]
@hansmorb @printpagestopdf @chriwen 

Bezogen auf das Ursprungs-Issue:

> * [ ]  Feld Wieviele Tage im Vorraus ergänzen

Ich denke hier geht es um das Versenden der Liste der Buchungs-Codes, habe ich in den Settings und auch im Timeframe-Backend noch nicht gefunden.

> * [x]  Versand an cb_manager & Stations-E-Mail

Das ist gelöst.

> * [ ]  Automatischer Versand der E-Mail 1 Mal im Monat optional anklickbar

Das läuft über die Cron-Jobs aber ist in den Settings noch nicht konfigurierbar. Ich habe es zumindest nicht gefunden.

Wenn das so stimmt würde ich das Issue anpassen, aber nicht schließen. Wenn nicht korrigiert mich bitte.
