### ISSUE TITLE
User-Berechtigung

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#101]
Als Administrator möchte ich die Backend-Berechtigungen in Wordpress einschränken können, sodass nur berechtigte Nutzer beispielsweise Standorte und Artikel bearbeiten und pflegen können.

Folgende Szenarien sollen abgebildet werden können (evtl. Sub-Issues anlegen)

- [x] 1. Nutzerrollen erweitern
- Es soll eine weitere Nutzerrolle "Location-Admin" und eine Rolle "Item-Admin" geben

- [x] 2a. Administratoren sollen an einer Location über Advanced Custom Fields 1-n Nutzer definieren können, die anschließend diese Location und alle damit verknüpften Daten verwalten können. Die Auswahl der Nutzer soll auf Nutzer mit der Rolle "Location-Admin" beschränkt sein.

- [x] 2b. Administratoren sollen an einem Item über Advanced Custom Fields 1-n Nutzer definieren können, die anschließend dieses Item bearbeiten können. Die Auswahl der Nutzer soll auf Nutzer mit der Rolle "Item-Admin" beschränkt sein.

- [x] 3. Item anlegen / 
Nutzer mit der Rolle "Item-Admin" können generell ein neues Item anlegen.

- [x] 4. Item bearbeiten
- Items können nur von Administratoren oder von Nutzern bearbeitet werden, die 
 - die Rolle "Item-Admin" haben und dem Item als Autor zugewiesen
- oder: die wie in Szenario 2b dem Item als Admin zugewiesen wurden.

- [x] 5. Zeitfenster anlegen
- Nur Admins und Nutzer mit der Rolle "Location-Admin" können Zeitfenster anlegen. Als Auswahl der Location sind nur die Locations möglich, denen der Nutzer wie in Szenario 2 beschrieben, zugewiesen ist. 

- [x] 6. Zeitfenster bearbeiten
- Nutzer mit der Rolle "Location-Admin" können alle Zeitfenster bearbeiten, die mit der Location verknüpft sind, für die die Nutzer entsprechend Szenario 2 zugewiesen wurde. 

- [x] 7. Detailaufruf für unerlaubte Posts unterbinden
- Item-Admin ruft Item über Edit-URL auf

Hinweise zur technischeb Umsetzung. 
- Metafield Location -> User zuweisen (CMB User Select)
- Einschränkung nur Admin kann alles sehen
- Berechtigung an Location binden
- Timeframes (Einschränkung Location)
- Items nur sehen, von denen man Autor ist oder wenn Autor Teil der für eine Location freigegeben Nutzer ist
- 

https://wordpress.org/support/topic/read-only-field-for-specific-user-role/

**Comment by markus-mw** [comment]
@farbschein : Das CMB2 User-Select Feld ist leider nur für einen User. Ich schau mal nach, ob/wie man das eventuell für mehrere Erweitert bekommt.

**Comment by markus-mw** [comment]
@farbschein : Ich habe jetzt die neuen Rollen sowie die Auswahl für die Item- sowie Location-Admins im Branch feature/issue-101 eingebaut. Du kannst da ja schonmal einen Blick drauf werfen...

**Comment by markus-mw** [comment]
@farbschein : Die Einschränkung der Sichtbarkeit von Posts in den Admin-Listen über das Author-Feld sowie die Admin-Zuweisung bei Items und Locations funktioniert jetzt auch.
Was noch fehlt:

- Sichtbarkeit für Timeframes
- Zusätzliche Prüfung, wenn Post-Edit-Seiten direkt aufgerufen werden

**Comment by farbschein** [comment]
@markus-mw : Super, danke schonmal für die schnelle Umsetzung. Anscheinen greifen bei mir aber die Rechte noch nicht.
Ich hab folgendes gemacht:
User mit Rolle location_admin angelegt.
In der Rolle Administrator diesem Nutzer einer location über das Userfeld zugewiesen.
Als User mit der Rolle location_admin eingeloggt.
Ergebnis: Der location_admin alle Location sehen, denen er NICHT zugeordnet ist. Die Location, mit der er verknüpft wurde erscheint nicht in der Liste.
Kannst du das nochmal prüfen?
Danke.

**Comment by farbschein** [comment]
@markus-mw : Hab mal einen kleinen fix gebaut. Bitte check mal, ob das so passt. Problem lag wohl daran, dass beim auslesen des Metafields entweder ein array (bei mehreren Werten) oder ein String zurückgegeben werden. Das hat die nachfolgende Abfrage irgendwie zerstört.
Kann man das besser lösen?

**Comment by markus-mw** [comment]
@farbschein : Die Änderungen sind jetzt im Master.
