### ISSUE TITLE
Holiday feature fertigstellen

### ISSUE THREAD

**Issue by dirkdrutschmann** [wielebenwir/commonsbooking#1013]
# branch experiment/timeframe-multiselect
- [x] Mehrfachauswahl von Locations/Items in Holiday Timeframe
- [x] Mehrfachauswahl von Locations in Buchbaren Timeframe inkl. Validierung
- [ ] Möglichkeit von Eingabge von Feiertage (@hansmorb ist dran)
- [ ] Feiertagsfunktion per Kategorie (tbd @chriwen: lass uns da mal noch einmal drüber sprechen, wie das funktionieren soll)
- [ ] ?

# branch feature/holidays
- [x] API Curl
- [x] OptionsPage Timeframe => Manuelles Eingabe Feld nur sichtbar, wenn Repetition->Manual und Type->Bookable||Holiday ausgewählt ist.
- [x] Import der API_Daten ins Manuelle Feld => Feld nur sichtbar bei Repetition->Manual und Type -> 'Holiday'
- [x] Logik was passiert mit den Daten => String To Timeframe 
- [ ] Timeframevalidierung für manuelle Felder erweitern
- [ ] Buchungsvalidierung für manuelle Felder erweitern
- [ ] Description und angezeigte Namen der Felder auf der Options-Seite

**Comment by chriwen** [comment]
Anforderungen aus Dopplung #9210

Übertrag aus Anforderung Hannes:

Alternativ zur Auswahl von Startdatum und Enddatum gibt es beim Anlegen eines Zeitrahmens die Möglichkeit, einzelne Tage kommagetrennt in ein Textfeld einzugeben.

Checkbox "Freie Eingabe von Tagen" unter dem Enddatum (default: nicht aktiv)
bei Aktivierung der Checkbox: Ausblenden von Startdatum und Enddatum, Einblenden eines Textfeld
Übernahme aller im Textfeld aufgelisteten Daten in den Zeitrahmen. Format z.B. (05.05.2021,06.03.2022,usw.)
Erklärtext zum Datumsformat inkl. Beispiele unter dem Textfeld
Vorteile:
Diese Option kann dann genutzt werden, um spezielle Datumskombinationen in nur einen Zeitrahmen einzugeben, anstatt viele Zeitrahmen nutzen zu müssen. Weiterhin ist es möglich, eine einmal zusammengestellte Kombination auch in weitere Zeitrahmen anderer Artikel/Stations-Kombinationen zu kopieren.

Nutzung z.B. für

Feiertage
Regelmäßige Ausleihtermine, die aktuell nicht abbildbar sind (z.B. jeder erste Donnerstag im Monat)

Idee: sowohl feste Datumsangaben (kommasepariert) + relative Datumsangaben (http://docs.php.net/manual/en/datetime.formats.relative.php) ermöglichen, z.B.
second monday next month

**Comment by hansmorb** [comment]
Ich würde lieber ein npm package mit Feiertagen statt einer Webseite als API nehmen, ich halte das für zukunftssicherer.

**Comment by markus-mw** [comment]
@chriwen , @hansmorb : Ich hab jetzt im experiment/timeframe-multiselect die Funktion für den Multiselect für Urlaub/Blockiert umgesetzt. Es wäre gut, wenn ihr das mal testen könntet. Sollte das soweit funktionieren, können wir noch einmal wegen der Kategorieeinstellung sprechen.

**Comment by chriwen** [comment]
@markus-mw : Vielen Dank für die Umsetzung. Ergebnis erste Tests:
- scheint grundsätzlich gut zu funktionieren
- Habe testweise die Multi-Artikel-Auswahl für Buchungen eingeblendet (in der admin.js) und auch das scheint erstmal direkt zu funktionieren. Also: eine Station + mehrere Artikel. Das wäre natürlich super, wenn wir das in dem Feature direkt mit ausrollen können.  

Was mir noch aufgefallen ist:
- Wir bräuchten beim Typ Buchungen eine Validierung auf Überlappung der Artikel mit bereits bestehenden Timeframes. Das gibt es ja schon auf Einzel-Artikelebene, müsste nun auch irgendwie mit der Multiauswahl zurechtkommen.

**Comment by markus-mw** [comment]
@chriwen, @hansmorb  : Ich habe die Multi-Item Auswahl für Buchbare Timeframes inkl. der Übernahme einer eventuell vorhandenen Single-Item Auswahl (Abwärtskompatibilität) und der Validierung bzgl. bestehender Timeframes umgesetzt. Bitte teste das auch noch einmal.
Was aus meiner Sicht noch offen wäre:
- die Konfiguration von Feiertagen/Geschlossen über eine Kategorie, wobei wir dazu noch einmal Videofonieren sollten
- die Sache mit den Feiertagen per API blockieren, da würde ich aber ebenfalls gern noch einmal sprechen, wie genau das laufen soll
- die "Alle" Option für Items/Locations sollten wir auch noch einmal besprechen, das ist nicht ganz so einfach wie es vielleicht aussieht, weil wir dabei ja die Nutzerberechtigungen einbeziehen müssen
