### ISSUE TITLE
Der Zeitrahmen Urlaub soll die Option bekommen, überbuchbar zu sein.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#1016]
Die Anzahl der Urlaubstage soll dann  nicht in die Anzahl der buchbaren Tagen einberechnet werden.

**Comment by hansmorb** [comment]
Sollte mit #702 behoben sein

**Comment by datengraben** [comment]
@hansmorb das heißt es ist ein Duplikat mit #702
