### ISSUE TITLE
Gruppierung von gleichen Zeitrahmenenden im Frontend

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1020]
Wenn ein Artikel an einem Standort mehrere Zeitrahmen hat, werden diese in der Frontend-Darstellung einfach stumpf abgearbeitet. Übersichtlicher wäre es, wenn die Zeitrahmen zusammengruppiert wären.

![image](https://user-images.githubusercontent.com/6433480/163676579-964c2ebe-95ff-4e46-89d7-f3dcec1153d6.png)

Noch intuitiver wäre es wahrscheinlich, wenn immer nur ein Zeitrahmen, nämlich der am längesten gültige Zeitrahmen angeben würde wie lange der Artikel an der entsprechenden Station verfügbar ist.

**Comment by datengraben** [comment]
Was ist mit "Löchern" im Zeitrahmen? Also zum Beispiel: 
```
Fall 1
-----------------------------------------------
Zeitrahmen für eine Location

Zeitrahmen 1    |-----------|
Zeitrahmen 2                          |----------------|

------------------------------------------------
Mögliche Ausgaben

Ausgabe 1        |-------------------------------------|
Ausgabe 2        |------------|       |----------------|
```


```
Fall 2:
-----------------------------------------------
Zeitrahmen für eine Location

Zeitrahmen 1    |--------------------------|
Zeitrahmen 2                          |----------------|

------------------------------------------------
Mögliche Ausgaben

Ausgabe 1        |-------------------------------------|
```

Also wenn sie überschneide, dann kann ich sie vereinfachen. Aber wenn sich keine überschneiden, dann doch alle getrennt anzeigen oder? Wobei die Beispiele noch nicht gut die "dauerhaft" Option zeigen.

**Comment by datengraben** [comment]
Ich denke mal das ist die Stelle die du meinst:
https://github.com/wielebenwir/commonsbooking/blob/ee2693b9c14a74ec99d9fab74a5b39212adca0fc/templates/timeframe-withlocation.php#L36

**Comment by datengraben** [comment]
Können "Restrictions" einen Zeitrahmen verändern? Also an dieser Stelle.

**Comment by hansmorb** [comment]
> Können "Restrictions" einen Zeitrahmen verändern? Also an dieser Stelle.

Nein, tun sie nicht die Daten kommen aus \CommonsBooking\View\Item::shortcode bzw. \View\Location::shortcode und die nehmen mit der getShortcodeData nur die Daten rein, die für den Shortcode auch gebraucht werden. Bei den Items sind das ziemlich sicher nur die ranges. Am Besten schreibst du vielleicht eine Funktion, die aus mehreren ranges ein BookableDate bastelt.



> Was ist mit "Löchern" im Zeitrahmen? Also zum Beispiel:
> 
> ```
> Fall 1
> -----------------------------------------------
> Zeitrahmen für eine Location
> 
> Zeitrahmen 1    |-----------|
> Zeitrahmen 2                          |----------------|
> 
> ------------------------------------------------
> Mögliche Ausgaben
> 
> Ausgabe 1        |-------------------------------------|
> Ausgabe 2        |------------|       |----------------|
> ```
> 
> ```
> Fall 2:
> -----------------------------------------------
> Zeitrahmen für eine Location
> 
> Zeitrahmen 1    |--------------------------|
> Zeitrahmen 2                          |----------------|
> 
> ------------------------------------------------
> Mögliche Ausgaben
> 
> Ausgabe 1        |-------------------------------------|
> ```
> 
> Also wenn sie überschneide, dann kann ich sie vereinfachen. Aber wenn sich keine überschneiden, dann doch alle getrennt anzeigen oder? Wobei die Beispiele noch nicht gut die "dauerhaft" Option zeigen.

Genau wie du es sagst, nur zusammenfassen bei Überschneidung oder Dopplung.In dem oben genannten Beispiel sind zwei Slots mit dauerhafter, Slotweiser, Buchung die einfach untereinander dargestellt werden.

**Comment by datengraben** [comment]
Also überschneiden können sich Timeframes nicht generell sondern in Ausnahme-Fällen. Das habe ich gerade beim Testen herausgefunden. Das wusste ich noch nicht, bzw. das hast du glaube letztes mal hier auch beschrieben.

> In dem oben genannten Beispiel sind zwei Slots mit dauerhafter, Slotweiser, Buchung die einfach untereinander dargestellt werden.

![image](https://user-images.githubusercontent.com/105302830/221558719-7f0aceb2-95d6-4769-a324-eeb3a12c8fd1.png)
So sieht das dann im Fronted aus, durch `[cb_items]` gerendert.
![image](https://user-images.githubusercontent.com/105302830/221558852-d8a4d3d8-00fa-4d88-b666-ae63fda2838c.png)

Ich habe es bisher noch nicht geschafft die php-unit tests auszuführen. Das ist aber ein anderes Thema. Ich verstehe noch nicht wie ich meine wordpress php core files via composer in mein setup einbinde. Liegt euer Plugin folder direkt im wordpress installations verzeichnis?

**Comment by datengraben** [comment]
Ok die Tests sind jetzt zumindest in der Pipeline gelaufen.

**Comment by datengraben** [comment]
Offene Punkte die ich noch sehe
- [ ] Die aktuelle Implementierung führt überlappende Timeframes zusammen, aber es wird nicht unbedingt der längste gültige Timeframe angezeigt (wie in Hans letzer Nachricht empfohlen). Wenn wir das tun wollen wäre da noch etwas zu tun.
- [ ] Die [Dokumentation](https://commonsbooking.org/dokumentation/) hat zum Verhalten bei Überschneidungen mit den Time-Frames keinen Eintrag, den könnte man ggf. dort nachtragen.

**Comment by hansmorb** [comment]
Ja, was schlägst du da an Dokumentation vor? 
Und könnte man nicht einfach die TimeRange mit dem höchsten Enddate nehmen, wenn sie sich überschneiden? Und ansonsten einfach zwei ranges. Also dann sowas wie:

Bis 01.03.2023
Ab 20.03.2023

**Comment by datengraben** [comment]
Auf der Seite https://commonsbooking.org/docs/erste-schritte/buchungszeitraeume-verwalten/ einen Abschnitt `Überlappende Zeiträume` in dem genau steht wann Überlappungen existieren können und wann nicht. Also ungefähr das was fachlich im Code umgesetzt ist.

> Und könnte man nicht einfach die TimeRange mit dem höchsten Enddate nehmen, wenn sie sich überschneiden?
Ok das war mein Fehler. Die Implementierung verhält sich natürlich genauso wie du in der letzten Nachricht geschrieben.
