### ISSUE TITLE
Timestamps in Buchungen und Zeitrahmen falsch

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1023]
Die timestamps "repetition-start" und "repetition-end" die bei einer Buchung oder einem Zeitrahmen sind keine normalen Epoch timestamps sondern lokalisierte Timestamps (dh. die Zeitzonen sind da schon mit draufgerechnet). 

Das führt dann dazu, dass Funktionen wie Timeframe->getEndDateDateTime falsche DateTime Objekte zurückgeben. Die Timestamps sollten eigentlich immer UTC sein, mit setTimezone kann dann an das DateTime Objekt eine Zeitzone angehängt werden um am Ende im Frontend wieder das richtige Datum auszugeben.

**Comment by chriwen** [comment]
@hansmorb Danke für den Hinweis.
@markus-mw : Können wir das global anpassen und überall UTC machen? Fände das auch stringenter. Bei der cancelltion-Time machen wir das ja glaub ich bereits. Kannst du mal schauen, was wir da alles anpassen  müssen, damit auch diese ganzen zeitbasierten Berechnungen weiter stimmen?

**Comment by markus-mw** [comment]
@chriwen : Wir können das machen, müssen dabei aber höllisch aufpassen, dass wir alles Stellen erwischen. Außerdem brauchen wir dann noch eine weitere Migration für Bestandsdaten.

**Comment by markus-mw** [comment]
@hansmorb: Hast du eine Stelle an der du fest machst, dass die Buchungs Timestamps lokalisiert sind? Ich hab da nichts gesehen. Nur in den API Aufrufen wird da mit der Zeitzone hantiert. Soweit ich es sehen konnte, werden bereits alle Buchungszeiten in UTC/GMT gespeichert.
Was ich herausgefunden habe ist genau das Gegenteil: Die in UTC/GMT gespeicherten Timestamps werden in der Ausgabe falsch dargestellt und von der Wordpress Einstellung umgerechnet. Stellt man in WP UTC als Timezon ein, sieht die Ausgabe der Zeiten beim Kalender als auch den Buchungen ok aus. Wir müssten also bei allen Ausgaben die Zeitausgabe auf UTC formatieren, dann sollte es passen.

**Comment by hansmorb** [comment]
Die Funktion getEndDateDateTime z.B..:
Sie nimmt die repetition_end und erstellt daraus ein DateTime Objekt. Die repetition-end ist aber eine Timestamp, die bei der Umwandlung exact der Rückgabeuhrzeit in UTC entspricht.

![image](https://user-images.githubusercontent.com/6433480/177046628-36dae74e-24a7-4e1e-8cec-d621e4744c92.png)
![image](https://user-images.githubusercontent.com/6433480/177046694-229f9f68-407f-48f4-968a-99a3af56d08c.png)

Meinem Verständnis nach, sollte ein Timestamp immer in UTC sein um dann für die Anzeige der Nutzer*innen in local time konvertiert zu werden. Genauso dachte ich wird ein Datetime Objekt auch aus einem Timestamp erstellt und kann dann anschließend mit einer Zeitzone ergänzt werden, um für die Zeitzone die richtige Uhrzeit anzuzeigen.

**Comment by markus-mw** [comment]
@chriwen , @hansmorb: Ich bin die Sache Schritt für Schritt nochmal durchgelaufen und konnte nachvollziehen, dass die Timestamps bei Buchungen lokalisiert gespeichert werden.
Das was du dir vorstellst ist jedoch nicht so einfach wie es sich anhört.
Wenn wir die Timestamps in UTC speichern, also das lokale Offset vom Timestamp abziehen und die Zeitzone wird verstellt, sind alle Ausgaben im Anschluss falsch. Warum? Weil wir im Zweifel einen anderen Offset auf den jetzt normalisierten UTC draufrechnen.
Wenn wir die Zeit (wie bisher) als "UTC-lokalisierten" Timestamp speichern und bei der Formatierung als Zeitzone UTC (unabhängig von der WP Einstellung) verwenden, also immer die gleiche, kann an der Zeitzone herumgestellt werden ohne, dass was kaputt geht. Das ist logisch zwar nicht sauber, aber es sichert eine korrekte Ausgabe der Zeiten...

**Comment by markus-mw** [comment]
@chriwen , @hansmorb : Ich hab den Ansatz, überall mit der UTC zu arbeiten und die lokale Zeit zu ignorieren mal im Branch feature/issue-1023 umgesetzt. Testet das doch bitte mal.
