### ISSUE TITLE
Fehler: Buchung über bereits gebuchten Zeitraum bei stundenweisem Zeitrahmen möglich

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1034]
Grundlage:
Zeitrahmen, stundenweiser Slot, 08:00 - 18:00 Uhr, wöchentlich, jeder Tag

1. Buchung
Eintägige Buchung an Tag 15.05. Abholung 13:00 - 14:00 Uhr, Rückgabe 16:00 - 17:00 Uhr

2. Buchung
Mehrtägige Buchung: Abholung 15.05, 09:00 - 10:00 Uhr, Rückgabe 17.05., 15:00 - 16:00 Uhr

Der Kalender erlaubt das Überbuchen der bereits getätigten eintägigen Buchung.

Gewünschtes Verhalten:
Jede Buchung im Kalender soll als Blocker gelten, über den keine weitere Buchung hinweg durchgeführt werden kann.

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das kurzfristi priorisiert anschauen? Merci

**Comment by markus-mw** [comment]
@chriwen : Ich bekomme es mal wieder nicht reproduziert:

https://user-images.githubusercontent.com/22905753/167138810-1eb786b0-2113-438f-bfe4-537c9f8c3f2d.mp4

**Comment by chriwen** [comment]
@markus-mw probier mal auf stage3 mit dem artikel der die letzte Buchung bekommen hat. Das war mein Test. Bin grad Nicht am Rechner

**Comment by markus-mw** [comment]
@chriwen : Auch da bekomm ich es nicht hin. Mach am besten ein kleines Video, wenn du später Zeit hast.

**Comment by chriwen** [comment]
@markus-mw Hier kannst du das sehen
https://stage3.commons-booking.org/rundedinge/e-lastenrad-buergerzentrum-vingst/?location=3619

16.05. - da ist bereits nachmittags eine Buchung. Du kannst aber nun von 16.05 morgens bis 17.05 auswählen. Die Buchung am 16.05 nachmittags kannst du dabei im Kalender überbuchen.

**Comment by chriwen** [comment]
@markus-mw Hier nochmal Video, wobei du da den spannenden Teil (nämlich den ausgegrauten Buchungsbereich am 16.05. ja nicht sehen kannst) probier es einfach mal selbst. Evtl. hängt es damit zusammen, dass für diesen Zeitraum generell 2 Timeframes buchbar sind (einer Mo-Do, einer Fr.)?

**Comment by markus-mw** [comment]
@chriwen : Jetzt hab ich es verstanden. Da muss ich auf JS Ebene und sicherheitshalber auch im Backend ran.

**Comment by markus-mw** [comment]
Jetzt ist auch der Backend-Part angepasst, sodass keine überlappenden Buchungen mehr erstellt werden können.

**Comment by chriwen** [comment]
@markus-mw Super, schaut gut aus.
