### ISSUE TITLE
Fehler: Ticket 563 (Fatal Error wg. fehlendem Property in CustomPost)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1035]
Fehler tauchte bei einer Instanz auf. Nach erneutenm Speichern des Vorschaubildes und des Artikels war er verschwunden.

Todo: Fehler besser abfangen, um Fatal Error bei fehlendem Property zu vermeiden.
Fehler tritt erst ab PHP 8 auf

**Comment by datengraben** [comment]
@chriwen @hansmorb Hat sich das hier erledigt, wir haben seit dem doch einige transients eingeführt, die das ggf. abfangen.

Wenn nein: Konnte das seit dem nochmal jemand nachstellen? Bzw. welche Property hat denn gefehlt?

Oder vielleicht kann jemand einen Unit-Testfall schreiben, der das beschriebene Szenario nachstellt, den Fehler erwirkt und das erwartete Verhalten nachbildet.

**Comment by hansmorb** [comment]
Das wurde meiner Meinung nach schon mit Commit 4a8a627b3e1c31bc8c56f66a8e0643b84526046f gefixt.
Leider finde ich nicht mehr raus zu welchem PR das gehört.
