### ISSUE TITLE
cb_items Shortcode zeigt maximal 10 Artikel an

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1050]
Das ist leider nirgendwo dokumentiert, scheint aber ein Bug zu sein.

Kann mich vage daran erinnern, dass die WP_Query Klasse standardmäßig max. 10 posts zurückgibt, vielleicht liegt es daran

**Comment by chriwen** [comment]
@hansmorb manchmal ist das auch in den Themes definiert. Hatte den Fall auch desöfteren. Oder in den globalen Wordpress-Einstellungen gibt es auch eine Option, die die maximal Anzahl Posts definiert. Vielleicht da nochmal nachprüfen?
