### ISSUE TITLE
Karte auf Positionierungsseite lädt oft nicht richtig

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1060]
![image](https://user-images.githubusercontent.com/6433480/170090862-49ca620f-b3d5-487f-92f9-e70d59283e75.png)

Da hattest du @chriwen doch mal einen ähnlichen Bug behoben ,oder?

**Comment by datengraben** [comment]
Was ist denn das erwartete Verhalten? Das die Tiles angezeigt werden? Für mich sieht das eher danach aus als wäre eine Quota für die Website/IP erreicht und es werden daher keine Tiles für die Website/IP ausgeliefert. Steht irgendwas in der Dev-Console?

**Comment by datengraben** [comment]
@hansmorb Also ich habe dieses Problem in meiner Wordpress-Installation noch nie gesehen, aber schon beim surfen auf OpenStreetMap oder embedded Versionen einer OSM-karte. Da diese Tiles immer von demselben Server ausgeliefert werden und dieser Quotas auf IP/Cookie-Basis für einen gewissen Zeitraum hat, liegt es in der Natur der Sache, das es zu Problemen kommt, wenn du als IP zu oft Tiles anforderst. 

Ich würde daher dieses Ticket als won't fix schließen, man könnte wenn dann nur anbieten andere Tile-Server konfigurieren zu können.

**Comment by chriwen** [comment]
Ich würde das gerne offen lassen. Hab das Problem auch auf unserer Produktiv Instanz. Da werden gar keine Karten mehr im backend angezeigt. Da muss es ne andere Lösung geben. Das war früher nicht so.

**Comment by datengraben** [comment]
@chriswen Wenn das Problem bei dir Auftritt schau mal in den Network-Tab der Dev-Tools, da solltest du bei jeder Scroll- oder Zoom-Bewegung 500-er Status-Codes o.Ä. für Anfragen an den Tileserver bekommen. Das würde meine Vermutung bestätigen.

Wenn das nicht auftritt, ist es vermutlich ein anderes Problem.

**Comment by chriswen** [comment]
😄 You tagged the wrong username. I was wondering why I was receiving German.

@chriwen

**Comment by datengraben** [comment]
@chriwen Es ist gefixed, wenn [`Map.invalidateSize`](https://leafletjs.com/reference.html#map-invalidatesize) nach dem Rendern der Karte aufgerufen wird. Aktuell werden die Tiles zwar geladen, aber außerhalb des sichtbaren Bereiches der Karte. Das resize bewegt den sichtbaren Bereich wieder ins Zentrum. Ich pushe den Fix gleich.

**Comment by datengraben** [comment]
@chriwen jetzt auch auf Standort-Karte gefixed.
