### ISSUE TITLE
Überbuchung von Holiday immer möglich

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1062]
Egal welche Einstellung beim Standort vorgenommen wird, Holiday ist immer überbuchbar.

**Comment by hansmorb** [comment]
Das hatte etwas mit dem Bug in 2.7.2 zu tun, bei dem nur ein Tag ausgewählt werden konnte. Deshalb geändert zu Überbuchung von Holiday immer möglich.

**Comment by datengraben** [comment]
Wahrscheinlich im Litepicker Modul
