### ISSUE TITLE
Inkompatibilität Theme Rex Addons

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1065]
Die lokale Standorkarte (die auf der Artikelseite angezeigt wird) verschwindet,
wenn das "ThemeREX Addons" Plugin (ein Premium Plugin) verwendet wird. Dann werden die GPS Daten nicht mehr richtig übertragen und die Karte zeigt die Standardwerte (in Berlin) an.

Hab die Issue nur zur Dokumentation erstellt, ich glaube nicht, dass wir das von unserer Seite aus beheben können. Hat wohl eher was mit denen zu tun. Wir verwenden brav die wp_enqueue_script und wp_add_inline_script Funktionen, irgendwo dazwischen geht was verloren.

**Comment by datengraben** [comment]
Dann würde ich es als wont fix schließen.
