### ISSUE TITLE
Legende anpassen. Orange müsste schraffiert sein.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#1077]
![grafik](https://user-images.githubusercontent.com/28141760/174275060-6f0e6d43-d256-4b67-acf9-effd4f7209ae.png)

**Comment by hansmorb** [comment]
Wurde bereits umgesetzt und ist im master.

**Comment by hansmorb** [comment]
c51420d4b064d996625141ac1121b667313772f8
