### ISSUE TITLE
Nutzungseinschränkung: Falscher Buchungslink in E-Mail

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1083]
Der Parameter {{booking:BookingLink}} generiert bei der Aufhebung einer Nutzungseinschränkung nicht den richtigen Buchungslink, sondern verweist auf Buchungen anderer Nutzer:innen.

**Comment by chriwen** [comment]
@hansmorb Ich denke das hat damit zu tun, dass wir ja doppelte Mails vermeiden wollten. Ich prüfe das mal und ggf. senden wir dann doch wieder doppelte Mails. Ist ja auch eher die Ausnahme.

**Comment by chriwen** [comment]
@markus-mw Hast du da evtl. ne Idee, wo das entsteht?

**Comment by chriwen** [comment]
@hansmorb ich bastel gerade an einer Lösung

**Comment by markus-mw** [comment]
@chriwen : Mit Sicherheit kann ich dir das nicht sagen, aber die Funktion bookingLinkUrl würde ich auf folgenden Code umstellen, vielleicht hilfts ja (ungetestet):
```
public function bookingLinkUrl() {
	return get_post_permalink($this->post->id);
}
```
