### ISSUE TITLE
Cronjobs werden nicht sofort deaktiviert

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1088]
Das ist vermutlich die Ursache für #1012 .
Wenn der Haken für die Export Jobs oder die Erinnerungsmails entfernt wird, bleibt der Cronjob bestehen. Cronjobs müssten mit der https://developer.wordpress.org/reference/functions/wp_clear_scheduled_hook/ Funktion wieder entfernt werden.

**Comment by markus-mw** [comment]
@hansmorb : Eigentlich dürfte der Cronjob nur noch maximal einmal laufen, weil er danach nicht neu "gescheduled" wird. Du hast aber vollkommen recht, dass wir um das zu verhindern, den geplanten Lauf löschen müssen.
Die Holzhammer-Methode, für den Fall, dass das Modul deaktiviert wird, existiert bereits und müsste nur feinfühliger gemacht werden: \CommonsBooking\Service\Scheduler::unscheduleEvents

Machst du das oder soll ich?

**Comment by hansmorb** [comment]
Ich kann mich gerne Mal probieren!
