### ISSUE TITLE
Übersetzungsmacke Litepicker

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1093]
![image](https://user-images.githubusercontent.com/6433480/178466331-7bacd6ba-f886-4835-bc4d-3c5bb7b969da.png)

**Comment by datengraben** [comment]
Das sollte es sein. Jetzt fehlt nur noch die Stelle in Lite-Picker: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

**Comment by hansmorb** [comment]
Ich hab schon einen etwas nicht so sauberen PR in dem Litepicker Repo von Markus gestellt:

github.com/markus-mw/litepicker
