### ISSUE TITLE
Validierung auf Artikel an verschiedenen Standorten liefert falsches Ergebnis

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1095]
Bei direkt aneinander anschließenden Zeitrahmen eines Artikels an unterschiedlichen Standorten wirft die isValid im Timeframe-Model einen Validierungsfehler, obwohl der Artikel sich nicht überschneidet.

**Comment by hansmorb** [comment]
Genau das ist vermutlich der Grund, warum die Stornierung oft fehlgeschlagen ist, das ist auch erst bei angrenzenden Zeitrahmen aufgetreten. Wenn das behoben ist, kann bestimmt auch hier die Ausnahme für canceled raus:

https://github.com/wielebenwir/commonsbooking/blob/6be9677141e8111708e315fe15345730cc6fd033/src/Wordpress/CustomPostType/Booking.php#L93-L95

**Comment by hansmorb** [comment]
Zusätzlich: Die Validierung schlägt auch fehl, wenn der Artikel an dem gleichen Standort mit direkt angrenzendem Datum verfügbar ist.

**Comment by hansmorb** [comment]
Ups, mir ist gerade aufgefallen, dass ich den Fehler woanders hatte und zwar war bei mir aus Versehen das Enddatum vor dem Startdatum. Deshalb habe ich auf diesem Branch mal Unit Tests für deinen Fall hinzugefügt und zusätzlich wird jetzt auch der von dir angesprochene Fall getestet. Vielleicht kannst du mal schauen ob du diese Situation irgendwie noch reproduziert kriegst @chriwen
