### ISSUE TITLE
TimeframeExport - Uncaught error

### ISSUE THREAD

**Issue by Splines** [wielebenwir/commonsbooking#1104]
**Describe the bug**
Appeared when trying to use the [Commons Booking export](https://commonsbooking.org/docs/einstellungen-2/export/) over a too big span of months. Originally, only got this error:

```
Maximum execution time of 360 seconds exceeded
```

but now, we got this stacktrace a few days later when trying to export again (paths trimmed):

```
Ein Fehler vom Typ E_ERROR wurde in der Zeile 256 der Datei /wp-content/plugins/commonsbooking/src/View/TimeframeExport.php verursacht.
Fehlermeldung: Uncaught Error: Call to a member function getPost() on null in /wp-content/plugins/commonsbooking/src/View/TimeframeExport.php:256
Stack trace:
#0 /wp-content/plugins/commonsbooking/src/View/TimeframeExport.php(68): CommonsBooking\View\TimeframeExport::getTimeframeData()
#1 /wp-content/plugins/commonsbooking/src/Wordpress/Options/OptionsTab.php(126): CommonsBooking\View\TimeframeExport::exportCsv()
#2 /wp-includes/class-wp-hook.php(309): CommonsBooking\Wordpress\Options\OptionsTab::savePostOptions()
#3 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2.php(880): do_action()
#6 /wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2.php(764): CMB2->after_save()
#7 /wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2_Options_Hookup.php(306): CMB2->save_fields()
#8 /wp-includes/class-wp-hook.php(307): CMB2_Options_Hookup->save_options()
#9 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /wp-includes/plugin.php(476): WP_Hook->do_action()
#11 /wp-admin/admin-post.php(85): do_action()
#12 {main}
  thrown

```

## System details
- WordPress-Version 6.0.1
- Aktives Theme: Neve Child (Version 1.0.0)
- Aktuelles Plugin: Commons Booking (Version 2.7.2) PHP-Version 8.0.18

**Comment by Splines** [comment]
Investigated a bit further: this issue only occurs when I try to export two specific months (September or October 2021). For all other months, it works fine (but still takes way to long in my opinion ;-)...

**Comment by Splines** [comment]
Error still occurs with these PHP settings:

- version: 8.0.18
- memory_limit: 1024M
- max_execution_time: 600 seconds

**Comment by hansmorb** [comment]
Danke für den Hinweis. Das hat etwas damit zu tun, dass bei euch Buchungen existieren zu denen aber entweder der zugehörige Standort oder der zugehörige Artikel fehlen. Das ist natürlich ein Bug. Der Fix ist fertig und muss noch getestet werden, kommt hoffentlich mit dem nächsten Release.

**Comment by Splines** [comment]
@hansmorb Super, vielen lieben Dank euch.
