### ISSUE TITLE
Fehler: Buchungscodes werden nicht zufällig vergeben

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1110]
Beim Generieren von Buchungscodes werden diese nicht zufällig vergeben. 
Der erste Code wird zufällig ausgewählt, aber danach wird einfach die Liste in der Reihenfolge vergeben.

**Comment by printpagestopdf** [comment]
Ist das nicht ein Konflikt zu der Möglichkeit zukünftige Buchungscodes zu versenden? Falls Buchungscodes bereits versendet wurden und dann die Liste noch einmal generiert wird (und dies dann wirklich zufällig geschieht) hätten die Stationen doch falsche Buchungscodes?

**Comment by chriwen** [comment]
@printpagestopdf vielen dank für den Hinweis. Jedoch werden bereits generierte Codes bei erneutem generieren nicht überschrieben. Nur wenn vorher die bestehenden Codes gelöscht wurden.

**Comment by nelarsen** [comment]
Hmm, da ist noch ein Bug drin: Wenn bereits Codes generiert wurden, ich dann unter Einstellungen weitere Codes zur Codeliste hinzufüge, und schließlich den vorhandenen Zeitrahmen aktualisiere, dann werden neue Codes für die Tage generiert, die bereits Codes hatten. Die alten Codes werden nicht gelöscht, sondern es existieren zwei Codes pro Tag. 
![grafik](https://github.com/wielebenwir/commonsbooking/assets/2667894/28393299-8943-4368-bcdf-f6f01a8351dc)

Ich würde erwarten, dass die schon vorhandenen Codes bleiben und keine neuen Codes generiert werden.

**Comment by hansmorb** [comment]
Ui, das ist gar nicht Mal so gut. Hat der Zeitrahmen ein Enddatum?

**Comment by nelarsen** [comment]
`Ui, das ist gar nicht Mal so gut. Hat der Zeitrahmen ein Enddatum?`

Ja, 31.01.2025.

**Comment by nelarsen** [comment]
Die Bookingcodes werden komplett deterministisch vergeben. Ist das gewollt? Wenn ja ist diese Issue kein Bug, sondern ein Feature Request. 

Die Index für bookingCodesArray hängt nur vom Tag des Jahres, Timeframe-ID, Location-ID und Artikel-ID ab. Die Codes werden in Reihenfolge des bookingCodesArrays ausgegeben. Da bei mir eine alphabetisch sortierte Liste von Städten als bookingCodesArray gegeben ist, erkennt jeder halbwegs aufmerksame Laie mit Blick auf die Codeliste, dass man den nächsten Code einfach erraten kann. Ich weiß, dass die Codes niemals als echtes Sicherheitsmerkmal vorgesehen waren oder sind, sondern eher da sind, um Irrtümer zu vermeiden. Aber soll es SO offensichtlich sein? Man könnte die Codes zusätzlich neu mischen (deterministisch, wenn gewollt, aber nicht so offensichtlich), hier ein Vorschlag für einen Ansatz in BookingCodes.php:

	```
		$bookingCodesRandomizer = intval( $timeframe->ID );
		$bookingCodesRandomizer += $item->ID;
		$bookingCodesRandomizer += $location->ID;

		foreach ( $period as $dt ) {
			$day = new Day( $dt->format( 'Y-m-d' ) );

			$codeIndex = ( (int) $dt->format( 'z' ) + $bookingCodesRandomizer ) % count( $bookingCodesArray );
			$shuffledCodeIndex = ($codeIndex * 9301 + 49297) % count( $bookingCodesArray );

			if ( $day->isInTimeframe( $timeframe ) ) {
				$bookingCode = new BookingCode(
					$dt->format( 'Y-m-d' ),
					$item->ID,
					$location->ID,
					$timeframe->ID,
					$bookingCodesArray[ $shuffledCodeIndex ]
				);
				self::persist( $bookingCode );
			}
		}
```

Es gibt aber den von mir erwähnten Bug, ich schreibe später etwas dazu. Mir kommt die Implementierung der BookingCodes unnötig komplex vor. Wieso nicht so einfach wie im alten CB mit einer Code-Tabelle mit Lastenrad-ID, Datum und Code? Meines Erachtens sind die Felder timeframe und location weder nötig noch sinnvoll.

**Comment by hansmorb** [comment]
> Die Bookingcodes werden komplett deterministisch vergeben. Ist das gewollt? Wenn ja ist diese Issue kein Bug, sondern ein Feature Request.
> 
> Die Index für bookingCodesArray hängt nur vom Tag des Jahres, Timeframe-ID, Location-ID und Artikel-ID ab. Die Codes werden in Reihenfolge des bookingCodesArrays ausgegeben. Da bei mir eine alphabetisch sortierte Liste von Städten als bookingCodesArray gegeben ist, erkennt jeder halbwegs aufmerksame Laie mit Blick auf die Codeliste, dass man den nächsten Code einfach erraten kann. Ich weiß, dass die Codes niemals als echtes Sicherheitsmerkmal vorgesehen waren oder sind, sondern eher da sind, um Irrtümer zu vermeiden. Aber soll es SO offensichtlich sein? Man könnte die Codes zusätzlich neu mischen (deterministisch, wenn gewollt, aber nicht so offensichtlich), hier ein Vorschlag für einen Ansatz in BookingCodes.php:
> 
> ```
> 		$bookingCodesRandomizer = intval( $timeframe->ID );
> 		$bookingCodesRandomizer += $item->ID;
> 		$bookingCodesRandomizer += $location->ID;
> 
> 		foreach ( $period as $dt ) {
> 			$day = new Day( $dt->format( 'Y-m-d' ) );
> 
> 			$codeIndex = ( (int) $dt->format( 'z' ) + $bookingCodesRandomizer ) % count( $bookingCodesArray );
> 			$shuffledCodeIndex = ($codeIndex * 9301 + 49297) % count( $bookingCodesArray );
> 
> 			if ( $day->isInTimeframe( $timeframe ) ) {
> 				$bookingCode = new BookingCode(
> 					$dt->format( 'Y-m-d' ),
> 					$item->ID,
> 					$location->ID,
> 					$timeframe->ID,
> 					$bookingCodesArray[ $shuffledCodeIndex ]
> 				);
> 				self::persist( $bookingCode );
> 			}
> 		}
> ```
> 
> Es gibt aber den von mir erwähnten Bug, ich schreibe später etwas dazu. Mir kommt die Implementierung der BookingCodes unnötig komplex vor. Wieso nicht so einfach wie im alten CB mit einer Code-Tabelle mit Lastenrad-ID, Datum und Code? Meines Erachtens sind die Felder timeframe und location weder nötig noch sinnvoll.

Wenn du Zeit hättest wäre das als separater PR auch bestimmt ne gute Sache!

**Comment by nelarsen** [comment]
> Wenn du Zeit hättest wäre das als separater PR auch bestimmt ne gute Sache!

Sehr gern, aber ich habe erst nach dem 5.3. Zeit. Vielleicht brauche ich eine Erinnerung.

**Comment by hansmorb** [comment]
@nelarsen Wenn du Lust hast dich dem anzunehmen wäre glaube ich jetzt ein guter Zeitpunkt. Vielen Dank :)

**Comment by hansmorb** [comment]
Mit #1604 behoben
