### ISSUE TITLE
Workaround für Wochenenden: 1 überbuchbaren Tag abziehen statt 2

### ISSUE THREAD

**Issue by genevievecory** [wielebenwir/commonsbooking#1113]
Eine Station wollte nicht, dass die Nutzer von **Freitag bis Dienstag** buchen konnten, wo die maximale Nutzungsdauer doch auf **3 Tage** steht. Das ging, weil das komplette Wochenende überbuchbar war, und es wird (wie in der Dokumentation steht) pauschal nur ein Tag von der Buchungsdauer abgezogen.
https://github.com/wielebenwir/commonsbooking/issues/799
https://commonsbooking.org/docs/erste-schritte/stationen-anlegen/
>>Pro Überbuchung wird immer pauschal 1 Tag von der maximalen Buchungsdauer abgezogen.

Ich habe jetzt einen Zeitrahmen "Urlaub" gemacht für jeden Sonntag, unendlich wiederholend. Dieser Tag zählt jetzt als ein Tag, das heißt, dass jetzt nur Freitag-Montag gebucht werden kann.  Oder sonst 3 Tage unter der Woche.  Siehe bitte: https://www.freie-lastenradl.de/cb_item/brucker-e-dreirad/ 

![image](https://user-images.githubusercontent.com/50321664/188264678-e0f2a092-671b-40f2-b836-95652495adbf.png)

In 16 Monaten seit unserem Livegang hat nur eine Station dieses Verhalten bemerkt, wir können das aber für jede Station implementieren.  Wenn die Logik des Systems eines Tages umgestellt werden sollte könnten wir diese zusätzlichen Zeitrahmen alle löschen, aber bis dahin scheint das zu funktionieren.  

Was meint Ihr?

**Comment by datengraben** [comment]
FYI @nelarsen  der verlinkte Merge-Request wandert bald in den Release-Branch zum Testen.
