### ISSUE TITLE
Effizienterer Umgang mit full-day Zeitrahmen

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#1114]
Beim Einsatz von full-day Zeitrahmen, werden im Code und in der Datenbank relativ viele unnötige Raster- / grid-Informationen verarbeitet / gespeichert. Aus Verständnis- und Effiziengründen kann der zugehörige Code aus meiner Sicht etwas aufgeräumt werden.

Einen entsprechenden Pull-Request werde ich gerne vorbereiten.

**Comment by datengraben** [comment]
TODO: Merge into 2.8.1 bzw. master zurück in 2.8.1

**Comment by hansmorb** [comment]
@datengraben Würdest du das also erst schließen, wenn der Release da ist?
