### ISSUE TITLE
Bug: Mehr als zwei Timeframes pro Item an einer Location führen zu Fehler

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#112]
zwei Timeframes sind für ein Item an einer Location gesetzt. Bei Absenden des Buchen-Buttons kommt folgender Fehler:

https://dev.commonsbooking.org/?cb_timeframe-custom-fields_wpnonce=df0e41ab0c&location-id=67&item-id=71&type=6&post_type=cb_timeframe&post_status=unconfirmed&start-date=1594983600&end-date=1595019599

Warning: date() expects parameter 2 to be integer, string given in /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Model/Booking.php on line 75

Fatal error: Uncaught Exception: more than one timeframes found in /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Model/Booking.php:81 Stack trace: #0 /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Model/Booking.php(43): CommonsBooking\Model\Booking->getBookableTimeFrame() #1 /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(124): CommonsBooking\Model\Booking->assignBookableTimeframeFields() #2 /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(62): CommonsBooking\Wordpress\CustomPostType\Timeframe->handleFormRequest() #3 /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Plugin.php(28): CommonsBooking\Wordpress\CustomPostType\Timeframe->__construct() #4 /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Plugin.php(159): CommonsBo in /var/www/clients/client4066/web11045/web/cb-dev/wp-content/plugins/commonsbooking/src/Model/Booking.php on line 81

Es gab einen kritischen Fehler auf deiner Website.

Erfahre mehr über die Fehlerbehebung in WordPress.

**Comment by markus-mw** [comment]
@farbschein : Ich habe die Limitierung die den Fehler wirft entfernt. Das was an dem Fall problematisch ist, ist die Übernahme der Timeframe Daten für die Buchung. Wir müssten uns ja bei dem Fall, dass die Buchung sich über mehrere Timeframes erstreckt für einen entscheiden und Infos wie "Slottyp" usw. übernehmen.

**Comment by farbschein** [comment]
@markus-mw : Wichtiger Aspekt ;-)  Gut wäre es allerdings, wenn wir bei der Buchung evtl. garnicht auf die zugrunde liegenden Timeframes zurückgreifen müssten, sondern einfach bei Start- und Endzeit den auf Basis des jeweiligen Buchungs-Timeframes relevanten Zeitraum übergeben. Also z.B. zusätzlich zur Startzeit den errechneten Abhol- und Rückgabezeitraum, z.B. in der Form (pickup-time_from -> pickup-time_to / return_time_from -> return_time_to)?
