### ISSUE TITLE
PHP 8 Kompatibilität nicht mit CMB2 custom fields? Deprecated: required parameter follows optional parameter

### ISSUE THREAD

**Issue by genevievecory** [wielebenwir/commonsbooking#1132]
Alle CB-Seiten mit Custom Fields funktionieren nicht mit meiner live-Instanz mit PHP 8. (Lokal mit Local hat's alles funktioniert! Ich verstehe das nicht! Grrrr!)

Betroffen: Filter auf der Karte der Artikel, Verfügbarkeits-Tabelle, Buchungen-Seite, wie auch Konto-Seite.

Fehlermeldung:

`[28-Oct-2022 11:24:35 UTC] PHP Deprecated:  Required parameter $field_type_object follows optional parameter $field_escaped_value in /usr/www/users/lastens/freie-lastenradl/wp-content/plugins/commonsbooking/vendor/mustardBees/cmb-field-select2/cmb-field-select2.php on line 83`

MustardBees hat das hier wohl behoben: https://github.com/CMB2/CMB2/pull/1417 

Problem kann man hier auf meiner Karte sehen: https://www.freie-lastenradl.de/lastenrad-leihen-muenchen/ wie auch https://www.freie-lastenradl.de/alle-verfuegbarkeiten-der-lastenradl-muenchens-auf-einem-blick/ 

![image](https://user-images.githubusercontent.com/50321664/198609647-67dc8531-cc7f-4f8e-a838-db47415b18e1.png)

![image](https://user-images.githubusercontent.com/50321664/198610243-ed1f0dcc-2eef-4ca1-bfe2-417f4264a01e.png)

**Comment by genevievecory** [comment]
(Ich habe die Site jetzt auf PHP 7.4 zurückgesetzt damit sie wieder funktioniert...)

**Comment by chriwen** [comment]
@genevievecory  Ich hab das bei mir jetzt nicht getestet, glaube aber auf den ersten Blick, dass dir von dir verlinkte Bugfix das Problem nicht lösen dürfte.

Die Ursache liegt in der Funktion:
	public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object ) {
In Zeile 83 in /commonsbooking/vendor/mustardBees/cmb-field-select2/cmb-field-select2.php 

Du könntest versuchen das mit folgender Anpassung zu lösen:
	public function get_pw_multiselect_options( $field_escaped_value, $field_type_object ) {

Siehe auch:
https://www.php.net/manual/de/migration80.deprecated.php

Wenn das für dich funktioniert, könnten wir die Anpassung bei uns übernehmen.
der Code für mustardBees/cmb-field-select2 wurde seit 6 Jahren von dem Entwickler nicht mehr aktualisiert, sodass wir davon ausgehen können, dass hier auch keine Anpassungen mehr erfolgen.

**Comment by hansmorb** [comment]
Ich würde eher zu dieser Variante tendieren:

https://github.com/wpcodefactory/cmb-field-select2

Damit wäre das Problem dann auch gelöst, weil beide Parameter optional sind.

**Comment by hansmorb** [comment]
Hab gerade nochmal nachgeguckt, PHP Deprecated: Required parameter $field_type_object follows optional parameter $field_escaped_value darf nicht zu einem fatal error führen, das muss was anderes sein.

**Comment by hansmorb** [comment]
Ja, scheint kein PHP8 Fehler gewesen zu sein!
