### ISSUE TITLE
Telefonnummer und Adresse sichtbar für cb_manager|s

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1136]
Hallo zusammen, in CB 0.x.x wurde standardmäßig Telefonnummer und Adresse bei der Registrierung erfasst (war vom alten Plugin so vorgesehen). Für CB2 wurde die (vernünftige) Entscheidung getroffen, die Gestaltung der Registrierungsseite jedem Webseitenbetreiber selbst zu überlassen. Damit gab es aber auch keine "vorgegebene" Art und Weise, Adresse und Telefonnummer zu erfassen und z.B. auf der Buchungsübersichtsseite (booking-single.php) anzeigen zu lassen. Zwar wurde da "irgendwie" mit
`<?php echo commonsbooking_sanitizeHTML( CB::get( 'user', 'address' ) ); ?>`
reingeschoben, dass eine vorhandene Adresse (wenn im Meta-Feld "address" gespeichert ist) unter "Dein Benutzername" (!) angezeigt wird. Die Telefonnummer (bei CB 0.x.x als Meta-Feld 'phone') wird nirgendwo angezeigt.

Unter Einstellugen->Migration findet sich zu meiner Verwunderung ein Hinweis darauf, dass diese Angaben (phone, address) als "veraltet" betrachtet werden

> Aktiviere die folgenden veralteten Nutzer-Profilfelder aus Commons Booking Version 0.X:
> first_name, last_name, phone, address, terms_accepted 

Bestimmt übersehe ich etwas, denn ich verstehe nicht, wie es gedacht ist. Sollen die Lastenradinitiativen und insbesondere Lastenradpaten (cb_manager) gar nicht die Kontaktdaten (insbesondere Telefonnummer) erfahren? Bei uns (Frieda&Friedrich in Dresden) war und ist es uns wichtig, dass wir Nutzer kurzfristig telefonisch kontaktieren können, um Probleme einfach zu klären.

Für unseren geplanten Umstieg auf CB2 habe ich ein neues, angepasstes Registrierungsformular (mit first_name, last_name, address und phone) erstellt. Das gewünschte Feature besteht darin, dass unsere Paten (cb_manager) diese Angaben auch sehen können, z.B. wenn sie die Buchungsbestätigungsseiten "ihrer" Nutzer aufrufen.

**Comment by chriwen** [comment]
@nelarsen Vielen Dank für deinen Hinweis. Ich werde mal schauen, ob ich die die Ausgabe im Template konfigurierbar machen kann.

**Comment by chriwen** [comment]
@nelarsen Ich habe die Erweiterung gerade in einem neuen Branch umgesetzt. Wir werden das im nächsten Update dann ausspielen. Viele Grüße

**Comment by nelarsen** [comment]
Hallo @chriwen, wow, vielen Dank! Ich probiere deinen Feature-Brauch in den nächsten Tagen aus und gebe eine Rückmeldung!

**Comment by nelarsen** [comment]
Ich habe es getestet und bei mir tut die Ergänzung, was ich erwarte :thumbsup:! Ich freue mich sehr über die schnelle Unterstützung. Ich war (und bin) noch etwas unsicher, was CB2 schon leisten kann bzw. wie bestimmte Prozesse vorgesehen sind. Ich dachte, dass ich vielleicht etwas übersehen habe. Ich habe gleich eine neue Frage bzw. ein Featurerequest zu einem verwandten Thema geöffnet.
