### ISSUE TITLE
Datenschutz: Beschränkung des Zugriffs auf Nutzerdaten für cb_managers

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1138]
Bei Frieda&Friedrich in Dresden haben wir ca. 30 Lastenrad-Paten, die Zugriff auf die Nutzerdaten von "aktuellen" Nutzern des Lastenrades des Paten haben. "Aktuell" heißt, dass die Buchung in den letzten 10 Tagen oder in den nächsten 10 Tagen stattfindet. Alle andere Nutzerdaten, z.B. für Nutzungen, die länger zurückliegen, sind für die Arbeit der Paten i.d.R. gar nicht relevant. Irrlevante Personendaten sollen im Sinne von Datenschutz und Datensparsamkeit gar nicht abgerufen werden können. Wir gewähren den Zugriff auf unserem CB 0.x.x-System mit dem Plugin von @gundelfisch custom-shortcodes-cb-bookings-overviews.php (https://github.com/flotte-berlin/cb-shortcodes).

Unsere 30 Lastenrad-Paten sollen nach dem Umstieg auf CB2 vermutlich cb_managers sein (bisher hatten sie die WP-Rolle Mitarbeiter/Contributor). Kann man aktuell den Zugriff für cb_managers zeitlich einschränken wie oben geschildert? Oder ist eine andere Art und Weise des Zugriffs auf Nutzerdaten durch Lastenradpaten vorgesehen? Ansonsten wäre das ein Featurewunsch von mir.

**Comment by gundelfisch** [comment]
Guter Vorschlag, @nelarsen! Entweder den Starttermin-Filter beschränken oder in den älteren Buchungsdetails die Nutzer-Kontaktdaten weglassen. Dort wird übrigens  - anders als beim fLotten bookings-overview-Shortcode - leider statt der Nutzer-Telefonnr dessen (unverifizierbare) Anschrift angezeigt. Das erschwert schnelle Kontaktaufnahme, falls ein Rad beschädigt oder nicht rechtzeitig zurückgebracht wird.
Zum CB-Manager: sobald dieser einem Rad und/oder Standort zugeordnet ist, kann er/sie nicht nur alle Buchungen zum Rad/Standort ansehen, sondern selbige auch stornieren und außerdem Artikeldaten, Standort u. Zeitrahmen ändern! Unsere fLotten StandortpartnerInnen und RadpatInnen können/sollen/brauchen das alles nicht, sondern sie erhalten zu "ihren" Rädern ausschließlich Infos wie akt. Buchungsliste, monatl. Codelisten, Ausleihformular etc. Falls das evtl. bei anderen CB-Projekten auch so ist, plädiere ich für eine weitere Rolle wie CB-Partner, mit genau diesen Frontend-Leserechten ohne Dashboard-Zugriff.

**Comment by nelarsen** [comment]
@gundelfisch Danke für deine Rückmeldung! Für uns kommt natürlich es auch in Frage, stattdessen eine Weiterentwicklung deines Flotte-Berlin-Plugins zu nutzen, falls die cb2-Entwickler meinen, dass unsere Anforderungen für Radpaten/Partner das CB2-Plugin "überladen" würde. Dafür hätte ich viel Verständnis. (Ich habe mich noch nicht hinreichend mit der Struktur der CB2-Buchungen in der Datenbank auseinandergesetzt, so dass ich gerade nicht einschätzen kann, ob so eine Weiterentwicklung leicht oder komplex sein wird)
Plant ihr bei fLotte eigentlich auch einen Umstieg auf cb2?

**Comment by gundelfisch** [comment]
@nelarsen Wir haben kürzlich mit @hansmorb vom cb-Entwicklerteam direkten Kontakt aufgenommen wie wir diesen Umzug absehbar, d.h. hoffentlich bis Ende nächsten Jahres, hinbekommen, der auch für die fLotte Brandenburg erforderlich ist. 
EinTeil unserer fLotten Ergänzungen ist bereits oder wird Bestandteil von cb2 werden, aber sicher nicht jedes Detail.

**Comment by chriwen** [comment]
@nelarsen Christian hier, vom CB-Team. Deine Anforderungen können wir gerne in den Core übernehmen. Es wäre sinnvoll hier die konkreten Anforderungen (also, welche Rolle soll in welchem Kontext was sehen können) einmal strukturiert aufzuschreiben, sodass wir dann schauen können, wie wir das am besten umsetzen. 
PS: Wir favorisieren den Ansatz, lieber mehr in CB direkt zu integrieren, als später eine Reihe von separaten Plugins mit all den damit zusammenhängenden Kompatibilitäts-Fragen etc. bei Updates zu haben ;-)
Viele Grüße. Christian

**Comment by nelarsen** [comment]
Wir brauchen diese Enhancement nicht mehr bzw. wir haben für unsere Prozesse eigene Lösungen gebastelt. Wir haben einen "Paten/Partnerzugriff", der eine Frontend-Seite ist, nur lesend ist und so einfach, dass unsere Paten keine Schlung dafür benötigen. Sie müssen nur unterschreiben, dass sie den Datenschutz einhalten. Die Paten/Partner können Nutzerdaten einsehen, aber nur die aktuellen +/- 10 Tage. Das reicht in 95% der Fälle.
CB Manager müssen eh umfangreich geschult werden und diese Rolle können nur sehr wenige Leute bekommen. Das ist keine Rolle für die Paten, wie ich ursprünglich gedachte habe. Daher schließe ich.
