### ISSUE TITLE
cb_items_table zeigt falschen Monat an (November statt Dezember)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1145]
User-Feedback:

cb_items_table zeigte in einer Instanz statt den aktuellen Monat Dezember im Monats-Titel "November" an. 
Fehler lag in der View/Calendar.php
Dort wird aus dem übergeben Wert (Z.B. 2022-12) mit strotime ein Timestamp erzeugt.
Wenn dieser Timestamp umgerechnet wird, ergibt das den 30.11.2022 23:00 Uhr.

Ich habe das nun gelöst, in dem ich dem ich den Timestamp per wieder von UTC in GMT umrechne.

`$print .= date_i18n( 'F', strtotime( get_date_from_gmt( $month ) ) ) . "</th>";`

**Comment by hansmorb** [comment]
Das ist interessant, ich dachte wir hätten die UTC timestamps noch gar nicht im release. Haben die zufällig den Master genutzt?
