### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1155]
Vor allem wegen dieser issue in wp-env.

https://github.com/WordPress/gutenberg/issues/46635

**Comment by hansmorb** [comment]
Am besten gemeinsam mit #1247

**Comment by datengraben** [comment]
@hansmorb ich habe mal den Bug entfernt.

**Comment by datengraben** [comment]
@hansmorb Mh welche Deps meinst du eigentlich? Die Story ist so allgemein formuliert, aber sind ja bis auf contrib-nodeunit nur minor versionen oder dev-packages. Wobei Shufflejs glaube auch im Frontend genutzt wird.


```
❯ npm outdated 
Package                 Current   Wanted   Latest  Location                             Depended by
@babel/preset-env        7.22.5  7.22.20  7.22.20  node_modules/@babel/preset-env       commonsbooking
@wordpress/env           5.16.0   5.16.0    8.8.0  node_modules/@wordpress/env          commonsbooking
cypress                 12.17.4   13.3.0   13.3.0  node_modules/cypress                 commonsbooking
editorconfig             0.15.3   0.15.3    2.0.0  node_modules/editorconfig            commonsbooking
grunt-contrib-compass     1.1.1    0.8.0    1.1.1  node_modules/grunt-contrib-compass   commonsbooking
grunt-contrib-nodeunit    4.0.0    5.0.0    5.0.0  node_modules/grunt-contrib-nodeunit  commonsbooking
shufflejs                 5.4.1    5.4.1    6.1.0  node_modules/shufflejs               commonsbooking
```

**Comment by hansmorb** [comment]
@datengraben Als ich das geschrieben habe kannte ich mich noch nicht so gut mit npm aus (tue ich immer noch nicht) aber ich habe immer nur die Warnungen für outdated packages bzw. Sicherheitslücken gesehen. Deshalb dachte ich das wäre ein To-Do. Kann aber auch gerne geschlossen werden wenn sich das deiner Meinung nach erledigt hat.

**Comment by datengraben** [comment]
Ok, dann würde ich das mal schließen, da aktuell unkritisch. Außerdem haben wir ja den dependabot aktiv, welcher kritische veraltete oder verwundbare Abhängigkeiten recht früh erkennt.

**Comment by hansmorb** [comment]
Ich hab das mal wieder eröffnet um es als Referenz für einen PR zu nutzen.
