### ISSUE TITLE
Backend/Timeframe-Editor: Bei "keine Wiederholung" kein Start/End-Datum

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#117]
**Describe the bug**
- Anlegen eines neuen timeframes
- Auswahl von "Keine Wiederholung"
- Es wird kein Start / End-Datum mehr angezeigt.

**Expected behavior**
- Grundsätzlich sollen alle Timeframes bei Auswahl von "keine Wiederholung" eine Start- und Enddatum (inkl. Start-Zeit und Endzeit) haben.
- Das jeweilige Zeitfenster erstreckt sich dann durchgehen von Start-Datum/Uhrzeit bis End-Datum/Uhrzeit.

Beispiel: Reparatur geht von 15.07 10:00 - 23.07 19:00 Uhr => dann soll genau dieser timeframe als vollständig geblockt angezeigt werden.

Ebenso 

**Screenshots**

**Comment by markus-mw** [comment]
@farbschein : Ist erledigt.
