### ISSUE TITLE
Frontend/Buchungskalender: Bei full-day Slots Fehlermeldung nach Buchungs-Button

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#118]
**Describe the bug**
-Zeitfenster full-day ist angelegt (in diesem Fall parallel zu einem anderem Zeitfenster mit der gleichen Item/Location-Kombination, das jedoch ein anderes Start-Datum hat)
- Im Buchungskalender können die Tage ausgewählt werden
- Nach Klick auf Buchen, kommt folgende Fehlermeldung:

Fatal error: Uncaught Exception: more than one timeframes found in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Model/Booking.php:81 Stack trace: #0 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Model/Booking.php(43): CommonsBooking\Model\Booking->getBookableTimeFrame() #1 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(131): CommonsBooking\Model\Booking->assignBookableTimeframeFields() #2 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php(62): CommonsBooking\Wordpress\CustomPostType\Timeframe->handleFormRequest() #3 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Plugin.php(28): CommonsBooking\Wordpress\CustomPostType\Timeframe->__construct() #4 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Plugin.php(159): CommonsBooking\Plugin::getCustomPostTypes() #5 /Applications/MAMP/htdocs/cb01/wp-includes/class-wp-hook.php(287 in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Model/Booking.php on line 81

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by markus-mw** [comment]
@farbschein : Das Problem hat sich über issue-112 bereits gelöst. Aber wie du schon geschrieben hast, müsste man da ein paar Regeln beim Anlegen vorsehen, damit keine ungültigen Konstellationen angelegt werden können.
