### ISSUE TITLE
Offset für Buchungen (Mindest-Buchungsvorlauf) einstellbar machen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1185]

**Comment by Brixxor** [comment]
Ein Offset für Buchungen wäre wirklich für kleine Verleiher ein essentielles Feature, was einiges an Arbeitszeit freigeben würde, wenn klar ist, dass eine Buchung min. 1 Tag vorher sein muss. Eine Tagesaktuelle Buchung ist  teils sehr schwer umsetzbar und eine andere alternative Möglichkeit ist mir noch nicht über den Weg gelaufen. Ich würde mich freuen, wenn dieses Feature in die ToDo laufen könnte :) LG und DANKE für die tolle Arbeit hier!
