### ISSUE TITLE
Frontend/Kalender: Mobile Optimierung

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#119]
Der Kalender soll für eine mobile Buchung optimiert werden:

- [ ] Anzeige eines Monats
- [x] vor/zurück-Option um im nächsten Monat zu wechseln 
- [ ] Anzeige des Abhol- und Rückgabedatums und Dropdown sollen mobil nutzbar sein

Derzeit werden alle Elemente nur abgeschnitten und somit ist keine mobile Buchung möglich.

**Comment by markus-mw** [comment]
@farbschein : Ich habe das vor-zurück-Thema mal in #133 überführt. Ist sinnvoller als alleinstehendes Thema.

**Comment by markus-mw** [comment]
@farbschein : Was heißt der erste Punkt "Anzeige eines Monats"?

**Comment by markus-mw** [comment]
@farbschein : Der Kalender wird jetzt je nach viewport mit einem oder 2 Monaten dargestellt. Die Darstellung der Auswahlfelder sollte auch passen.
