### ISSUE TITLE
Frage: Öffentliche Buchungskommentare nicht vorgesehen?

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1207]
++ Kein Bug report oder Feature request ++
In CB 0 wurden von Nutzer*innen eingegebenen Buchungskommentare als Tooltip im öffentlichen Buchungskalender angezeigt, wenn man mit der Maus über den Kalender gefahren ist.
**In CB2 ist das nicht mehr der Fall, richtig?** Ich nehme an, dass es eine bewusste Entscheidung ist. Ich denke, wir können damit gut leben, fanden die öffentlichen Buchungskommentare aber eigentlich ganz nett. Bei uns lautete die Aufforderung

> "Du kannst freiwillig andere Frieda & Friedrich-Fans inspirieren, indem du den geplanten Nutzungszweck im Buchungskalender als Kommentar öffentlich teilst. Beispiele: Transport von Zimmerpflanzen, Kindergeburtstag, Umzug. Nur der eingegebene Text (bitte keine persönliche Angaben) wird veröffentlicht."

**Comment by chriwen** [comment]
Hallo @nelarsen . Das war tatsächlich ein bewusste Entscheidung. Teilweise wurden in den Kommentaren dann doch persönliche Infos an die Station gesendet, da wohl nicht immer klar war, dass das auch öffentlich ist. 
Vielleicht könnte als zusätzliches Feature eine separate Frage nach "Wofür benötigst du das Rad/Artikel" einbauen. Ist aber derzeit nicht in Planung.

**Comment by nelarsen** [comment]
Ok! Ich fand das ursprüngliche Feature zwar nett, weil es den Commons-Charakter von Freien Lastenrädern unterstreichte (weniger anonym, mehr gemeinsam, einander inspirieren). Aber wir haben auch die Erfahrung gemacht, dass die Funktion selten auch falsch verstanden wurde und persönliche Daten eingegeben wurden, obwohl wir den Standardtext geändert haben (siehe oben), um zu betonen, dass keine persönliche Nachrichten hinterlassen werden sollen. Wir können erst mal auf die Funktion verzichten.
Es wäre eigentlich hilfreich, eine Liste von Unterschieden zwischen CB0 und CB2 zu haben. Dann müsste das nämlich auf die Liste.
