### ISSUE TITLE
Bessere Formulierungen / Darstellungen finden für Timeframe Einstellungen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1214]
![image](https://user-images.githubusercontent.com/6433480/231302848-90937c72-87c4-44db-95a1-9f1006e358a4.png)

Diese drei Parameter könnten besser verständlich beschrieben werden oder ein Bild zur Klarifizierung enthalten.

**Comment by flegfleg** [comment]
Hallo zusammen, hier mein Vorschlag. 

1. Gruppieren unter Headline (hier nicht "-einschränkung" gewählt, da es ja unter dem Namen noch einen anderen Menüpunkt gibt). Analog zu "Configure Timeframe" drunter. 
2. "Vorlauf" war im Screenshot nicht drin, ich hoffe ich hab das Feature richtig getroffen (hab auch keinen 2.8er Branch gefunden) 


![CleanShot 2023-04-17 at 14 58 24@2x](https://user-images.githubusercontent.com/4009931/232491326-826633ea-f8de-4639-8f43-39d5a7ab8534.jpg)

**Comment by hansmorb** [comment]
Der Buchungsvorlauf ist in diesem Screenshot die "Mindestbuchungsdauer", was natürlich maximal missverständlich ausgedrückt ist ;) Eine Buchungen für mindestens x Tage Funktion existiert (noch) nicht. 

Finde aber den Vorschlag ansonsten richtig gut. @genevievecory Hast du vielleicht ne Idee für englische Übersetzungen? Dann kann ich das direkt übernehmen.

**Comment by flegfleg** [comment]
> Der Buchungsvorlauf ist in diesem Screenshot die "Mindestbuchungsdauer", was natürlich maximal missverständlich ausgedrückt ist ;) Eine Buchungen für mindestens x Tage Funktion existiert (noch) nicht.
Hihi, OK!

> Der Branch für 2.8 ist release/2.8
Ah, irgendwie komplett übersehen

**Comment by hansmorb** [comment]
> Hallo zusammen, hier mein Vorschlag.
> 
>     1. Gruppieren unter Headline (hier nicht "-einschränkung" gewählt, da es ja unter dem Namen noch einen anderen Menüpunkt gibt). Analog zu "Configure Timeframe" drunter.
> 
>     2. "Vorlauf" war im Screenshot nicht drin, ich hoffe ich hab das Feature richtig getroffen (hab auch keinen 2.8er Branch gefunden)
> 
> 
> ![CleanShot 2023-04-17 at 14 58 24@2x](https://user-images.githubusercontent.com/4009931/232491326-826633ea-f8de-4639-8f43-39d5a7ab8534.jpg)

Vielleicht hier noch für Buchungen unter Maximal "Der Artikel kann maximal X Tage lang gebucht werden".

Und sollen wir uns die Mühe machen das X mit dem aktuellen Wert aus dem Feld zu ersetzen? Oder verwirrt das nur?

**Comment by flegfleg** [comment]
> Und sollen wir uns die Mühe machen das X mit dem aktuellen Wert aus dem Feld zu ersetzen? Oder verwirrt das nur?

würde ich eher keine Zeit drauf verwenden, lieber den *ganzen* Screen noch mal überdenken.  

Mein Gefühl war, dass diese ellenlangen erklär-Texte das Ganze nicht besser bedienbar (einfacher zu „parsen“)  machen. 

Hätte die Überschrift gerne „Buchungsbeschränkungen“ genannt, aber das verwirrt dann weil es ja eine andere Funktion/Menüpunkt mit dem gleichen Namen gibt. 

Würde vielleicht noch 
„Tage am Stück“ ergänzen

**Comment by genevievecory** [comment]
Ich finde das X ok.

Kein Eintrag erlaubt das Buchen für alle.
-->
Leer lassen um das Buchen für alle zu erlauben.

**Comment by hansmorb** [comment]
Vielen Dank für eure Mühe. So sieht das jetzt umgesetzt auf Deutsch aus:

![image](https://user-images.githubusercontent.com/6433480/232796301-d972c0ad-1025-493c-9ac9-0b3e7339dd6b.png)


Und so auf Englisch: 

![image](https://user-images.githubusercontent.com/6433480/232796527-ea66c9ce-6a1e-4644-b382-dafcb13ad37d.png)

Passt das so?

**Comment by genevievecory** [comment]
**Lead time!** Of course! Yes, looks great!
