### ISSUE TITLE
Github Actions nicht für alle Änderungen laufen lassen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1220]
Gerade laufen die Checks durch selbst wenn nur die README aktualisiert wurde. Das ist meiner Meinung nach etwas unnötig. Da wir sowieso nur Tests für PHP in place haben wäre es vielleicht ganz cool, wenn nur Änderungen im src Ordner die Github Actions auslösen würden. Geht das?

**Comment by datengraben** [comment]
Finde ich gut @hansmorb habe es jetzt für php,json,js,xml,dist Endungen eingebaut

* json wegen den SCHEMA files (werden aktuell aber glaube nicht per phpunit getestet)
* xml und dist wegen den configs files im Rootverzeichnis
* js ist eigentlich unnötig fällt mir gerade auf

**Comment by datengraben** [comment]
Es fehlt noch `yaml`, wenn wir die worklfows ändern wollen wir die ja auch testen.

**Comment by datengraben** [comment]
Ok jetzt habe ich es nach den nicht-Code Files gemacht, glaube das ist einfacher.

Wenn sich z.B. die load-wp-tests.sh ändert wollen wir das ja auch mitbekommen, die Liste der Whitelist-Patterns wurde dann immer längern.
