### ISSUE TITLE
Timezone configuration is missing in docs

### ISSUE THREAD

**Issue by datengraben** [wielebenwir/commonsbooking#1234]
**Describe the bug**
~Event description includes two different start and end times. Maybe thats a problem of my setup.~

Correctly configured timezone is critical for booking and ical features, though it's not mentioned in the installation instructions.

**To Reproduce**
~Steps to reproduce the behavior:~
* ~Add item to an hourly timeframe~
* ~Enable Icalender feed~
* ~Create a booking for the item and retrieve the ical feed~

**Expected behavior**
~Start and end times of the ical event are the same as the start or end time of the pickup intervals.~

**Screenshots**
![image](https://user-images.githubusercontent.com/105302830/234120682-e23c53d9-b405-4932-b6c0-a08e16ffc29b.png)

**Comment by hansmorb** [comment]
Und das wird nicht mit #1225 bei dir behoben? Weil das ist genau die Timezone Issue die ich in #1224 beschreibe. Die Beschreibung enthält auch bei mir da das richtige Datum. Manchmal braucht der Feed auch ne Sekunde um aktualisiert zu werden. Am besten lädst du die Datei über die URL direkt runter und prüfst dann, ob die Uhrzeiten jetzt stimmen. Ansonsten müssen wir da nochmal dran.

**Comment by datengraben** [comment]
Ich habe es auf dem Hotfix branch getestet. Aber ich hatte die Timezone in den Wordpress Settings nicht auf UTC+2 gesetzt sondern auf UTC. War also leider mein Setup.

**Comment by datengraben** [comment]
Oder ich eröffne es wieder, da es an der Stelle mehrere Möglichkeiten gibt.

Diese Stellen in der Doku wären geeignet für einen klärenden Satz wie 
```
Buchungs- und Termin-Funktionalitäten in CommonsBooking gehen von der Zeitzone aus, 
welche in Wordpress konfiguriert wurde. Wenn du das noch nicht getan hast hole unter 
"Einstellungen / Allgemein / Zeitzone" nach.
```
https://commonsbooking.org/docs/installation/installieren/
https://commonsbooking.org/docs/einstellungen-2/spracheinstellung-datumsformat/

Um wirklch allen Problemen vorzubeugen könnte man einmal die in den Wordpress-Einstellungen hinterlegte Zeitzone auch beim Anlegen von Timeframes und den Einstellungen für den I-Cal-Feed anzeigen.

Oder die im Browser eingestellte Timzone mit der Wordpress-Timezone bei eingeloggten Admin-Rollen vergleichen und nachfragen.

**Comment by chriwen** [comment]
@datengraben Danke für deine Hinweise. Ich habe die Doku gerade entsprechend angepasst.
