### ISSUE TITLE
Better default for booking "Calendar shows" setting

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#1236]
Currently, it's "**365** days", which i don't think people actually want? 
→ proposal: **31**

**Comment by chriwen** [comment]
@flegfleg Die Idee hier war, dass wir vorher keinen Wert hatten und deshalb hier für Bestands-Installationen nach der Installation nicht ungefragt einen Wert von 31 Tagen definieren wollten, da bestimmte Installationen ja ggf. andere Vorstellungen haben. Deshalb der lange Zeitraum der genug Spielraum lässt. Zukünftig könnten wir das aber per default auf 31 setzen, da ja in der Zwischenzeit alle Bestands-Installationen ein Update haben sollten.

**Comment by flegfleg** [comment]
Ah OK! Wunderte mich
