### ISSUE TITLE
Admin Backend wird sehr langsam mit vielen Nutzenden in Datenbank

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1237]
Auf jeder Seite im Backend werden mehrere Funktionen ausgeführt, die bei hoher Nutzendenzahl im Backend zu langen Wartezeiten führt. Zu prüfen wäre, ob diese Funktionen wirklich bei jeder Backendseite aufgerufen werden müssen oder ob man das nicht verfeinern sollte.

Das wäre laut Query Monitor vor allem diese hier:
![image](https://user-images.githubusercontent.com/6433480/234247050-ad36a209-2a2e-4a9d-95c5-13152fbe2615.png)

**Comment by chriwen** [comment]
@hansmorb Hat dein Ansatz die Geschwindigkeit erhöht? Mich wundert ein wenig, woher die langen Ladezeiten kommen, da die Nutzerverwaltung ja eigentlich ne WP-Sache ist, auf die wir nur rudimentär zugreifen oder?

**Comment by hansmorb** [comment]
@chriwen Ja, hat etwas gebracht, schau Mal in den PR. Leider werden die CMB2 Metaboxen für jeden CPT auf jeder Admin Seite geladen und damit über die OptionsArray auch die Abfrage nach CB Admins.

**Comment by chriwen** [comment]
@hansmorb Ok. Vielleicht können wir das ja auch lösen, in dem wir die 
add_action( 'cmb2_admin_init', array( $this, 'registerMetabox' ) ) in den jeweiligen Post-Type-Seiten
mit einer Abfrage nach dem aktuellen Screen verbinden bzw. den post-type per GET auslesen und die Action nur triggern, wenn wir im jeweiligen Post-Type auf der Edit-Page sind?
wp-admin/edit.php?post_type=cb_location

**Comment by hansmorb** [comment]
@chriwen 
 So wie es mir scheint ist das aber nicht die übliche Art CMB2 zu benutzen, auch in der offiziellen Doku https://github.com/CMB2/CMB2/wiki/Basic-Usage#create-a-metabox werden die Metaboxes mit dem init der Admin Seite geladen.
Weiss nicht, ob das nicht uns weitere Problem bringen würde.

**Comment by chriwen** [comment]
@hansmorb @poilu Hab mal eine Ajax user search Erweiterung für CMB2 integriert. Damit entfällt schonmal das Laden aller User in einer Buchung. Im ersten Test funktioniert das auch. Ob das für 28.000 User noch performant ist, weiß ich allerdings nicht ...
