### ISSUE TITLE
Cache Warmup auch für cb_items_table Shortcode

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1243]
Aktuell wird nur nach cb_items, cb_location(!) und cb_map gesucht für den warmup. 

https://github.com/wielebenwir/commonsbooking/blob/76f5d70f4ec047c998351f800457cd5e18499be6/src/Service/Cache.php#L214-L217

cb_bookings und cb_items_table sollten da auch mit rein, damit auch diese Calls gecachet werden.

**Comment by datengraben** [comment]
@hansmorb Was bedeutet denn Warm-Up? Wir cache bis Mitternacht oder? Sind die cb_bookings und cb_item_table nicht angewiesen auf aktuelle Booking-Daten, also sollte man doch explizit nicht tagsüber cachen.

**Comment by hansmorb** [comment]
@datengraben Ich bin mir ziemlich sicher, dass nach jeder Buchung / Änderung der Cache neu aufgebaut wird. Also auch die Cache Validierung funktioniert. Letzlich passiert bei dem Warmup meinem Verständnis nach nichts anderes als, dass im Hintergrund schonmal alle Shortcodes ausgeführt werden die eine Person, die die Webseite besucht, auch angezeigt bekommen könnte.
