### ISSUE TITLE
Buchungsvalidierung optimieren / Bug: unbestätigte Buchungen führen zu Fehlermeldungen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1248]
Folgende Validierungen optimieren:
- Buchung angelegt, aber nicht bestätigt -> mit Abbrechen zurück -> neue Buchung über gleichen Zeitraum bzw. mit Überschneidung -> Fatal Error: Uncaught Exception: There is already a booking in this timerange.
Todo:

- [x] Fatal Error vermeiden und durch User-Notice optimieren
- [x] Bei abbrechen einer unconfirmed Buchung soll diese direkt gelöscht werden, um einen nachfolgenden Buchungskonflikt zu vermeiden
- [x] Zusätzlich die Validierung überlappender Buchungen mit setzen eines transient prüfen - das funktioniert in bestimmten Fällen nicht zuverlässig @chriwen

**Comment by hansmorb** [comment]
Ich hatte da schonmal was gebaut, wo es eine Buchungsexception gibt die einfach nur gefangen werden muss. Damit wird der Fehler auch richtig und übersetzbar im Frontend angezeigt. Das liegt aktuell zusammen mit dem ganzen Gedöns von den Buchungsregeln in der feature/issue-697-2 .

Ich versuche das mal da herauszuziehen und das könnten wir dann in die 2.8.1 reinbringen.

**Comment by cosi255** [comment]
Hallo, ich habe hier das Problem, dass 'unconfirmed' Buchungen in der Datenbank stehen bleiben. (Plugin Version 2.8.0)
Wie sollten die denn normalerweise gelöscht werden, wenn ein Nutzer die Buchung abbricht? Dass Nutzer eine Buchungsprüfung machen, dann aber doch nicht buchen ist ja eigentlich mehr Regel als Ausnahme.

**Comment by chriwen** [comment]
@cosi255 Die unconfirmed Buchungen werden über einen Cronjob ca. alle 10 Minuten automatisch gelöscht. Dann kann auch wieder in dem entsprechenden Zeitraum gebucht werden.
