### ISSUE TITLE
zipdist anpassen für Distribution von Releases

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#125]
Zipdist so anpassen, dass nur genutzte Bibliotheken enthalten sind.

Ziel ist: Nach ausführen der zipdist.sh soll eine ZIP-Datei erstellt werden, die wir Nutzern zum Download bereitstellen können und die keine unnötigen Order/Dateien enthalten.

**Comment by markus-mw** [comment]
@farbschein , @flegfleg : Ich habe die Ordner etwas umstrukturiert und das archive command von git verwendet. So bekommt man ein Archiv, das das gitignore-File berücksichtigt. Was zu beachten ist, dass nach dem auspacken die Schritte aus der Readme durchgeführt werden müssen. Das wird auch bei der Entwicklung benötigt. So vermeiden wir aber ebenfalls die dauernden Konflikte beim erzeugen der komprimierten CSS-Dateien.

**Comment by flegfleg** [comment]
Huhu @markus-mw, das ziel der zipdist ist eigentlich, schnell ein ZIP für End-Anwender*innen zum Testen zu erstellen… das direkt in Plugins hochgeladen werden kann. Entwickler*innen können sich das ja von GitHub ziehen.

**Comment by farbschein** [comment]
@markus-mw : Ja, bitte zipdist.sh so anpassen, wie Flo beschrieb bzw. wie oben in der Story steht. Das soll quasi ne schnelle Möglichkeit sein, ein installierbares Plugin an Testende zu schicken.

**Comment by flegfleg** [comment]
Hallo zusammen, 
wie ist das denn jetzt gelöst, haben wir überhaupt noch (**nicht**-dev) dependencies @markus-mw?
