### ISSUE TITLE
Übersetzung für iCalendar Titel kaputt

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1251]
Leider hat sich ein blöder Fehler in der Übersetzung eingeschlichen, mit nervigen Konsequenzen:

![image](https://user-images.githubusercontent.com/6433480/235235834-7b9aa2db-a25c-460c-beae-314c20dec664.png)

Wurde so übersetzt. Das führt dazu, dass jetzt nicht der post_title sondern der post_name im Kalender angezeigt wird. Das sieht blöd aus:

![image](https://user-images.githubusercontent.com/6433480/235235953-abd9cc2f-7d81-4a4a-83ee-b7efba5e1572.png)

Der post_name ist der Slug.

Vorschlag: Update nachschieben, in dem das Feld nochmal geleert wird?

Das betrifft übrigens sowohl den Feed als auch den Buchungsmailanhang

**Comment by hansmorb** [comment]
Das funktioniert leider nicht ganz. Wenn in dem Optionsfeld noch keine Werte sind, dann wird der default Wert gesetzt. Danach wird der Wert nicht mehr geändert. Wenn jetzt also Menschen aktualisieren, dann wird ein falscher Default Wert gespeichert, der nicht so leicht geändert werden kann, außer das Feld wird wieder geleert.

**Comment by datengraben** [comment]
Wahrscheinlich ist deins aber einfacher und klarer.

**Comment by chriwen** [comment]
ich verstehe glaube ich die Ansätze hier nicht ganz. Nach meinem Verständnis müssen wir doch einfach nur im nächsten Update das Feld richtig übersetzen und ab dann werden alle neuen Buchungen richtig übersetzt. Die Kalender-Feed Datei aktualisiert sich doch eh regelmäßig oder? Dann würden einfach beim nächsten Sync die neuen Werte übertragen. Oder sehe ich da was falsch?

**Comment by chriwen** [comment]
Es geht doch nur um die deutsche Übersetzung oder? Die Original-Werte sind doch korrekt? @hansmorb

**Comment by hansmorb** [comment]
> ich verstehe glaube ich die Ansätze hier nicht ganz. Nach meinem Verständnis müssen wir doch einfach nur im nächsten Update das Feld richtig übersetzen und ab dann werden alle neuen Buchungen richtig übersetzt. Die Kalender-Feed Datei aktualisiert sich doch eh regelmäßig oder? Dann würden einfach beim nächsten Sync die neuen Werte übertragen. Oder sehe ich da was falsch?

Das Problem ist, dass der Optionswert schon gesetzt ist, wenn das Plugin aktualisiert wurde. Und ein schon gesetzter Wert wird auch von uns nicht überschrieben.

Das gleiche passiert auch, wenn du CommonsBooking auf English installierst und dann auf Deutsch switcht. Weil die Felder schon befüllt sind, werden die nicht nochmal mit der deutschen Übersetzung überschrieben

**Comment by chriwen** [comment]
@hansmorb ah, sorry. Hatte übersehen, dass das ein Options-Feld ist. Dann lass uns einfach schnell ein Update nachschieben, Optionsfeld löschen und neu anlegen. Soviel Anpassungen werden da in der Zwischenzeit nicht stattgefunden haben. 
Wir haben ja schon eine Funktion, die eine Update-Info (gelbes Infofeld) in der Plugin-Liste anzeigt, da könnten wir nen Hinweis einblenden. Die mit Auto-Update erreichen wir damit aber auch nicht.

**Comment by hansmorb** [comment]
@chriwen Meinst du es wäre vieleicht einfach okay in diesem Fall nicht nochmal ein Benachrichtigungsfeld zu erstellen sondern das in der Update Notiz nur kurz zu vermerken? Sollte ja auch nicht so viele Menschen betreffen.
