### ISSUE TITLE
Suche über Artikel nicht möglich

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#1255]
WordPress-Suche über Artikel nicht möglich, da
`'exclude_from_search' => true,` in https://github.com/wielebenwir/commonsbooking/blob/ac7cdaaba6bc09fa2806a5fba8c46601ceca0bc4/src/Wordpress/CustomPostType/Item.php#LL145C34-L145C34

Für Leih-Läden wäre es super, wenn wir über die Artikel suchen könnte. 
Kann das per default an sein, oder zumindest ein Setting? 

Danke!

Nachtrag: Wahrscheinlich, weil Artikel in den Archiven nicht die CB-Infos drin/dran haben? Im ersten Zug wäre das aber OK.

**Comment by flegfleg** [comment]
Huhu @chriwen, soll ich da einen PR machen oder siehst du das nicht als Feature?

**Comment by chriwen** [comment]
@flegfleg ja, gerne PR. Ich denke das ist kein Problem wenn das an ist. Können dann ja mal schauen was es noch an Änderungen braucht damit es gut funktioniert.

**Comment by flegfleg** [comment]
Hallo zusammen, ich häng hier schon ein paar Stunden an einem blöden Problem: 
Inhalte+Titel der Items+Locations lassen sich durchsuchen, aber die **taxonomy** nicht, also der Term/Custom Kategorie (in meinem Falle entweder "_Zweirad_" oder "_Dreirad_") wird in den Suchergebnissen nicht angezeigt. 
Hab in der WP-Doku überprüft, sollte eigentlich funktionieren, aber vielleicht ist da im Aufruf noch irgendwas speziell im CB?

→ Branch mit den Änderungen: https://github.com/wielebenwir/commonsbooking/tree/1255-search-items-locations-taxonomies

# Isoliert (Test-System mit eigenem Custom Post Type/Taxonomy) wird der Term gefunden: 

1. Test-Plugin installieren (oder in functions.php kopieren): https://gist.github.com/flegfleg/4ea742b69469ecae72b3474dcacd09b2
2. WordPress-Plugin [Ivory Search installieren](https://wordpress.org/plugins/add-search-to-menu/) → erlaubt das durchsuchen von (Custom) Kategorien/Terms
3. Ivory Search konfigurieren: 

![CleanShot 2023-05-31 at 12 47 37@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/9c408be3-2098-4bf3-aa0c-ef5f2debeaa0)

Sorry für die lange Beschreibung, konnte nicht klarer. 

Jemand ne Idee? 
Danke!

**Comment by chriwen** [comment]
@flegfleg Ich habs mir mal angeschaut und evtl. ne Lösung.
