### ISSUE TITLE
Klassen mit PHPDocs kommentieren

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1257]
Ziel ist es, dass mit PHPDocs nicht nur Methoden sondern auch Klassen kommentiert werden.

**Comment by datengraben** [comment]
Mit PHPCS haben wir auch ein Tool um das in den Prozess (Build/PullRequest) zu integrieren, von selber schreiben sich die Kommentare aber natürlich nicht :D

Siehe #1230
