### ISSUE TITLE
maximal buchbare Slots einstellbar machen

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#126]
Nutzer mit den Rechten einen Standort zu bearbeiten, sollen im Timeframe-Editor die Möglichkeit haben bei timeframes vom Typ "bookable" die maximale Buchungsdauer in Tagen pro Buchung festzulegen.

AK:
- Zusätzliches Feld "maximale Buchungsdauer in Tagen" (Dropdown mit Werten von 1-10, default-Wert = 3)

**Comment by markus-mw** [comment]
@farbschein : Könntest du noch ergänzen wo die max. Slots einstellbar sein sollen?

**Comment by markus-mw** [comment]
@farbschein : Die Auswahl ist im Master umgesetzt.
