### ISSUE TITLE
Fix translation "CustomPostType/Booking"

### ISSUE THREAD

**Issue by datengraben** [wielebenwir/commonsbooking#1260]
Typo `If the booking was was made`

https://github.com/wielebenwir/commonsbooking/blob/ac7cdaaba6bc09fa2806a5fba8c46601ceca0bc4/src/Wordpress/CustomPostType/Booking.php#L802

**Comment by datengraben** [comment]
![image](https://user-images.githubusercontent.com/105302830/236176117-95a2513b-ca0f-4f42-92d2-715b1beafe0b.png)

Im gleichen Textbaustein noch zwei Typos

`IWenn` <- Typo
`Hinweis:Der` <- Leerzeichen fehlt.

**Comment by hansmorb** [comment]
Ist im neuen Release drin
