### ISSUE TITLE
Calendar: Javascript error on date select

### ISSUE THREAD

**Issue by datengraben** [wielebenwir/commonsbooking#1263]
**Describe the bug**
In the two following cases, calendar behaviour is inconsistent and leads to further errors:

(1) JS Error when selecting more than 4 Days, though 10 days are allowed.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'bookedDay')
    at public.min.js?ver=2.8:1:32860
    at Array.forEach (<anonymous>)
    at h.onMouseEnter (public.min.js?ver=2.8:1:32710)
    at HTMLDivElement.<anonymous> (public.min.js?ver=2.8:1:21376)
```
(2) JS Error after successful selection and clicking on any available day to reset selection and start a new one, rather than clicking on `reset selection` button.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'slots')
    at p (public.min.js?ver=2.8:1:81120)
    at h.onDaySelect (public.min.js?ver=2.8:1:84528)
    at h.onClick (public.min.js?ver=2.8:1:29072)
    at HTMLDocument.<anonymous> (public.min.js?ver=2.8:1:21187)

Uncaught TypeError: Cannot read properties of undefined (reading 'bookedDay')
    at public.min.js?ver=2.8:1:32860
    at Array.forEach (<anonymous>)
    at h.onMouseEnter (public.min.js?ver=2.8:1:32710)
    at HTMLDivElement.<anonymous> (public.min.js?ver=2.8:1:21376)
```

**To Reproduce**
Bug (1)
1. Click on any available day 
2. Hover over a calendar day that would span number of selected days > 4
3. JS Error will appear and hover animation will freeze on days > 4

Bug (2)
1. Click on any available day and a days within range of 4 days.
2. Click on any day more than 4 days away from the first available day.
3. JS Error will appear

**Expected behavior**
(1) I can select a date range that is configured in backend settings.

(2) I can reset the date selection when clicking on any available day. Or at least the calendar won't break from the click.

**Comment by chriwen** [comment]
@hansmorb @datengraben Hat jemand von euch da eine Idee bzw. die Skills, um sich des Problems anzunehmen? Ansonsten müssen wir nochmal Markus involvieren. Ich bin da leider überfragt, aber das Problem sollten wir möglichst zügig beheben, da es ja essenziell für die Buchungen ist.

**Comment by hansmorb** [comment]
@chriwen Ich weiß leider noch nicht Mal wie der litepicker zu kompilieren ist.

**Comment by chriwen** [comment]
seltsamerweise wird mir lokal der JS-Error nicht mehr angezeigt. Das Verhalten bleibt aber das gleiche.

**Comment by markus-mw** [comment]
@datengraben , @chriwen , @hansmorb : Ich habe mir gerade den aktuellen master-Stand gezogen und versucht die Fehler zu reproduzieren. Allerdings ohne Erfolg. Auf welchem Branch habt ihr die Probleme?
@hansmorb, @chriwen : Das JS vom Litepicker findet ihr hier https://github.com/markus-mw/Litepicker . Ich habe euch mal als Collaborators eingeladen. @Wenn du mir die passenden Rechte gibst @chriwen kann ich das auch mal in die Wielebenwir Company übertragen.

**Comment by hansmorb** [comment]
Danke @markus-mw . Ich kann leider in der Litepicker repo keine Issues erstellen aber könntest du noch build instructions zur Verfügung stellen? Ich habe leider keine Ahnung wie ich den Litepicker für CommonsBooking kompilieren soll. Und könnte man das vielleicht auch über ein NPM Paket lösen, ähnlich wie bei dem CB Frontend?

**Comment by markus-mw** [comment]
@hansmorb : Ja das ist ein minimal Repo, ohne Projekt usw.. Wie der Build funktioniert findest du hier in sehr abgespeckter Form:
https://github.com/markus-mw/Litepicker/blob/master/build.md

Da kann man bestimmt ein NPM Paket draus bauen, ist halt nur nicht in 5 Minuten gemacht. :)

**Comment by hansmorb** [comment]
Ah cool, danke ja das reicht mir auch erstmal :)

**Comment by chriwen** [comment]
@datengraben @hansmorb  Könnt ihr das Problem noch irgendwo reproduzieren. Ich konnte das vor einiger Zeit hier lokal auch nochmal nachstellen, jetzt bekomme ich das aber in verschiedenen Instanzen nicht mehr dargestellt.

**Comment by datengraben** [comment]
Nein bekomme es auch nicht mehr reproduziert.

**Comment by chriwen** [comment]
> u mir die passenden Rechte gibst @chriwen kann ich das auch mal in die Wielebenwir Company übertragen.

@markus-mw erledigt
