### ISSUE TITLE
PR triggern oft keine Actions mehr

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1268]
Zum Beispiel hier:

https://github.com/wielebenwir/commonsbooking/pull/1250
https://github.com/wielebenwir/commonsbooking/pull/1183

Wird nicht nochmal eine Action getriggert, obwohl der PR auf den Master zeigt, kein Entwurf ist und der Commit gerade erst stattgefunden hat.

Magst du dir das mal ansehen @datengraben ?

**Comment by hansmorb** [comment]
Ich habe hier einen Draft erstellt #1275 der ja eigentlich keine Actions triggern soll, macht er aber leider trotzdem.

**Comment by hansmorb** [comment]
Nö, finde das mit den drafts auch passt, ich habe nur aktuell das Gefühl, dass bei jedem PR aktuell (unnötigerweise) zweimal die Actions aufgeführt werden aber vielleicht hat das ja auch n'en Sinn.

**Comment by datengraben** [comment]
Das Problem ist, das ich den Branch in meinem Repo gehostet habe.
Sobald ich auf Branches im main-repo push geht es.

> Nö, finde das mit den drafts auch passt, ich habe nur aktuell das Gefühl, dass bei jedem PR aktuell (unnötigerweise) zweimal die Actions aufgeführt werden aber vielleicht hat das ja auch n'en Sinn.

Verstehe nicht ganz. Zu welchem Zeitpunkt wäre eine Ausführung denn deiner Meinung nach optimal?

**Comment by datengraben** [comment]
@hansmorb Habe es verstanden, du meinst wenn ein PR erstellt wird, wird der workflow 2 mal ausgeführt. Ja das kann ich wieder ändern.
