### ISSUE TITLE
auf Item-Detailseite sollen Kalender integriert werden.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#127]
Analog zu Location:

- Wenn mehr als 1 Location, dann zunächst Liste, ansonsten direkt Kalender der Location

**Comment by markus-mw** [comment]
@farbschein : Ich nehme an, dass wir hier analog zu den Item Seiten die Locations anzeigen. Korrekt?

**Comment by markus-mw** [comment]
@farbschein : Ist erledigt.
