### ISSUE TITLE
Erstellung von Feiertagen verbessern.

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#1270]
Moin,

ein Feiertag betrifft in der Regel alle Stationen (bis auf Ausnahmen). Will man einen Feiertag (1. Mai) eintragen, muss man aktuell einen Zeitrahmen für jede Station erstellen. Schön wäre es, wenn man diejenigen (alle/einige) Stationen auswählen könnte, auf die der Feiertag-Zeitrahmen anzuwenden ist.

**Comment by hansmorb** [comment]
Dopplung mit #1140
