### ISSUE TITLE
Admin Buchung bei vielen Accounts führt zu Memory Size Exhaustion

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#1279]
Auf Installationen mit einer großen Anzahl von Accounts wird sehr viel RAM gebraucht, um Userdaten zu laden und zu cachen. Bei 28.000 User-Datensätzen kann dies mehr als 1GB sein.

Dies führt zu Fehlermeldungen, wie "Fatal error: Allowed memory size of 1073741824 bytes exhausted", welche schon beim Aktivieren des Plugins auftreten können. In der Regel wird Wordpress-Instanzen nicht so viel Arbeitsspeicher zugebilligt. Bei In-Memory Caching wird außerdem dauerhaft viel RAM belegt.

Das Problem wird in v2.8.0 durch das Laden aller User beim Aufruf von get_users() ohne Filter verursacht.
https://github.com/wielebenwir/commonsbooking/blob/e5f52dcf686a0e9c04ae332df596a6695d971efa/src/Wordpress/CustomPostType/Booking.php#L705

Bei der Erstellung von Admin-Buchungen wirkt sich das Laden von mehreren Tausend Usern in eine Select-Box auch negativ auf die Performance im Browser aus.
Eine Lösung könnte die Implementierung einer User-Suche sein, die nach Eingabe von ein paar Buchstaben entsprechend gefilterte Vorschläge macht.

**Comment by poilu** [comment]
Es gibt noch einen Bug, wenn man die wp-admin Seite öffnet und nicht eingeloggt ist. Dies verhindert einen Redirect zur Login-Seite.
![wp-admin-error](https://github.com/wielebenwir/commonsbooking/assets/3170770/972a4634-90a9-498c-840b-b1dd4d01d8b4)

**Comment by hansmorb** [comment]
> Es gibt noch einen Bug, wenn man die wp-admin Seite öffnet und nicht eingeloggt ist. Dies verhindert einen Redirect zur Login-Seite. ![wp-admin-error](https://user-images.githubusercontent.com/3170770/242915308-972a4634-90a9-498c-840b-b1dd4d01d8b4.png)

Das ist mir auch gerade aufgefallen, etwas kurios! Bitte lass das Ticket gerne offen, bis der entsprechende PR gemergt ist. Die Diskussion über die Umsetzung ist auch noch nicht ganz abgeschlossen.
