### ISSUE TITLE
Fehlermeldung Überlappung taucht falsch auf

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#1283]
Huhu, 
hab gerade auf dieser Seite einen Fehler bekommen:
https://www.kasimir-lastenrad.de/cb-items/leila/?cb-location=9443

* Kalendertage gewählt
* Weiter geklickt
* Fehlermeldung (s.u.) 
* Konnte trotzdem die Buchung bestätigen

Ach so, ich war mit einem Admin-Account unterwegs!

![CleanShot 2023-06-03 at 12 39 56@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/b7463412-8c5c-445a-b6c2-bb81118d41a7)

![CleanShot 2023-06-03 at 12 40 23@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/fdd46143-3255-4f69-9b9f-6853c245f2c3)

![CleanShot 2023-06-03 at 12 39 27@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/ec926558-39b0-4dbc-9b37-a25fe0c4364d)

… ich konnte die aber trotzdem bestätigen:
![CleanShot 2023-06-03 at 12 40 42@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/69f1b51c-785d-4d84-9f55-25255d874b67)

**Comment by hansmorb** [comment]
@flegfleg Hast du Backend Zugriff? Gibt es denn wirklich ne Überschneidung? Das einzige was ich mir vorstellen könnte ist, dass eine unbestätigte Buchung drin war die vielleicht genau in diesem Moment gelöscht wurde. Aber das ist vielleicht etwas unwahrscheinlich.

**Comment by flegfleg** [comment]
War auch mehrfach der Fall, ich hab genau dasselbe mehrfach probiert (immer Fehlermeldung) Am 03.06.2023 um 14:38 schrieb Hans Morbach ***@***.***>:﻿
@flegfleg Hast du Backend Zugriff? Gibt es denn wirklich ne Überschneidung? Das einzige was ich mir vorstellen könnte ist, dass eine unbestätigte Buchung drin war die vielleicht genau in diesem Moment gelöscht wurde. Aber das ist vielleicht etwas unwahrscheinlich.

**Comment by chriwen** [comment]
@flegfleg @hansmorb  Ich hab da eine Erklärung. Das Problem ist mir auch bekannt. Das hat mit den Transient zu tun, der an dieser Stelle nicht richtig gesetzt bzw. nicht korrekt gelöscht wird.. Taucht wahrscheinlich primär in dem von dir beschriebenen Fall auf @hansmorb -> unconfirmed Buchung steht noch herum, und User versucht gleichen Zeitraum zu buchen. 
In der nächsten Version wirds dafür ein Update geben, da bist du ja dran @hansmorb und ich würde diese nicht korrekte Transient-Geschichte wieder herausnehmen.
