### ISSUE TITLE
Javascript Bug im Fall: Abholung+Rückgabe nur einen Tag/Woche möglich

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#1289]
Selektion wird mit dem 2. Klick aufgehoben, sieht nach einem Javascript-Bug aus

Video: https://github.com/wielebenwir/commonsbooking/assets/4009931/b405f25a-586f-4b00-a6f3-49282579dedf
Online: https://commonsbooking.bluepingu.de/cb_item/akku-winkelschleifer-flex/

Zeitrahmen-Einstellungen: 
![CleanShot 2023-06-12 at 23 29 39@2x](https://github.com/wielebenwir/commonsbooking/assets/4009931/2b3fa57a-3b5f-488b-843b-c7d05b5184f1)

CB V. 2.8

Ebenfalls für Leihläden, siehe auch: #1255, #1256

**Comment by hansmorb** [comment]
Was sind die Standorteinstellungen? 
Ist 
![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/138c1e5f-4dc3-4077-a327-225aaba8f17f)
aktiviert?

Konnte das nämlich auf der Webseite sehen aber beim Testen nicht nachstellen.

**Comment by hansmorb** [comment]
Das stimmt, danke!
