### ISSUE TITLE
Speicherbedarf ab 2.8

### ISSUE THREAD

**Issue by printpagestopdf** [wielebenwir/commonsbooking#1321]
Auf der von uns betriebenen Wordpress Instanz, die bisher mit CB Version 2.7.3 betrieben wurde versuchten wir ein update auf 2.8. Das update selbst lief augenscheinlich ok, aber nach dem update war es nicht mehr möglich das Wordpress Backend aufzurufen (WP Fehlermeldung "Es ist ein schwerwie.."

Grund hierfür war wohl, dass unsere Instanz bisher mit eine max memory Konfiguration betrieben wurde:
define('WP_MEMORY_LIMIT', '256M');
define('WP_MAX_MEMORY_LIMIT', '256M');

Dies war für den Betrieb von 2.7.3 nochausreichend, führte dann aber nach dem 2.8 update zu dem oben genannten Fehler. Die Installation läuft dann z.B. korrekt mit:
define('WP_MEMORY_LIMIT', '512M');
define('WP_MAX_MEMORY_LIMIT', '512M');

Es ist natürlich klar, dass die Überschreitung des Speicherlimits grundsätzlich nicht nur von einem Plugin verursacht werden muß, sondern auch von Gesamtentviornment abhänig ist, aber zumindest in diesem Fall ließ es sich eindeutig dem Versionsupdat zuordnen.

Falls diese Beobachtung auch auf anderen Systemen reproduzierbar ist wäre es sinnvoll zumindest einen Hinweis in die Release und/oder Installations/Update Anleitung einzufügen?

**Comment by hansmorb** [comment]
War das nur bei dem Zugriff auf das Backend der Fall oder auch bei den Shortcodes?

**Comment by printpagestopdf** [comment]
Soweit ich das sehe nur beim Zugriff auf das Backend (wir hatten es wieder rückgängig gemacht, deshalb aus dem Gedächtnis). Der Shortcode dürfte funktioniert haben, da das Frontend wohl noch funktional war.

**Comment by hansmorb** [comment]
Ich Stelle einfach Mal die Vermutung in den Raum, dass das was mit der #1237 zu tun hat. Würde passen, weil ihr ja auch ein größeres Projekt seid.

**Comment by printpagestopdf** [comment]
Halte ich auch für möglich, aber ich denke es geht in diesem Issue ja nicht darum ein mögliches Speicherproblem zu lösen, sondern einen entsprechenden Hinweis in die Installations- und Releasenotes aufzunehmen. Wenn der Fehler auftritt ist er nämlich nicht so einfach zu finden.

**Comment by hansmorb** [comment]
Okay! Ich habe jetzt zwar die Änderungen mit dem entsprechenden Fix in die 2.8.1 eingebaut aber eine Warnung könnten wir trotzdem machen. Das kann aber glaube ich nur @chriwen

**Comment by hansmorb** [comment]
@printpagestopdf Magst du mal schauen, ob das jetzt mit der 2.8.2 für euch behoben ist?

**Comment by hansmorb** [comment]
Supi, freut mich zu hören.
