### ISSUE TITLE
Kartensicht auf Standortseite fehlt (evtl. ab 2.8.x)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1326]
**Describe the bug**
Kartenansicht wird nicht angezeigt, nur der leere Container
<img width="781" alt="image" src="https://github.com/wielebenwir/commonsbooking/assets/12683634/72e48bb2-86dc-4478-9bf1-f179e188a585">

**To Reproduce**
Kartenansicht im Standort aktivieren
Standordseite oder Artikeldetailseite aufrufen

**Comment by chriwen** [comment]
@hansmorb @datengraben Habt ihr da ne Idee für nen Fix? Konnte den Fehler auf mehreren Produktivseiten beobachten. Wohl alle die, die auf die aktuellste Version umgestellt haben.

**Comment by hansmorb** [comment]
Kann es auch bei anderen Seiten nicht nachstellen (z.B. dasallrad.org ).  Hast du vielleicht genauere Infos dazu wo es auftritt und ob dann ein Fehler in der JS Konsole ist?

**Comment by chriwen** [comment]
Konsole sagt:
error
: 
{code: 400, message: "Nothing to search for."}
code
: 
400
message
: 
"Nothing to search for."

Hier auch noch ein Beispiel: https://www.duisbock.de/cb_item/waldorf-fuer-mitglieder-des-bauverein-friemersheim/

**Comment by chriwen** [comment]
Kann die Ursache hier liegen:
`        var url = 'https://nominatim.openstreetmap.org/search';
        var params = {
            street: jQuery('#_cb_location_street').val(),
            city: jQuery('#_cb_location_city').val(),
            postalcode: jQuery('#_cb_location_postcode').val(),
            format: 'json',
            limit: 1
        }`

Das versucht ja die Adressdaten aus HTML-Elementen zu extrahieren. Aber die gibts in der Form im Frontend ja nicht, oder?

**Comment by hansmorb** [comment]
> Konsole sagt: error {code: 400, message: "Nothing to search for."} <img alt="image" width="611" src="https://user-images.githubusercontent.com/12683634/259861846-d141d177-bb21-41e2-bcc7-d490d534f054.png">
> 
> Hier auch noch ein Beispiel: https://www.duisbock.de/cb_item/waldorf-fuer-mitglieder-des-bauverein-friemersheim/ Auch hier: https://dasallrad.org/cb_item/rote-zora/?cb-location=1151

Beide Beispiele funktionieren bei mir auf Firefox unter Linux, welchen Browser nutzt du?

**Comment by chriwen** [comment]
Bei mir funktionieren die Beispiele auch in Firefox nicht.

**Comment by hansmorb** [comment]
> Das ist seltsam. Nutze Chrome. Und soweit ich den Code verstehe, können an dieser Stelle die Geo-Daten garnicht übergeben werden, da das Script ja auf die HTML-Objekte zugreift, die aber garnicht existieren. Hab in dem Branch mal einen Fix angelegt, der die HTML-Objekte bereitstellt. Das hat bei mir funktioniert. Sauberere Lösung wäre aber, die Geo-Paramater über wp_add_inline_script zur Verfügung zu stellen. Das hab ich aber nicht hinbekommen.
> 
> Frage: Bei dieser Ausgabe brauchen wir eigentlich ja auch nicht die Nomination-Abfrage auf Basis der Adresse. Wenn die Location mit entsprechenden Adressdaten angelegt ist, werden die Geo-Daten ja erzeugt, sodass hier im Frontend die Geo-Koordinaten zur Verfügung stehen sollten.

Hmm, das ist möglich. Ich habe damals einfach nur den Code von dem Location CPT kopiert. Aber in Zeile 171 werden doch mit wp_add_inline_script die Dinger übergeben.

**Comment by hansmorb** [comment]
Auch hier in dem emulierten Browser geht es:
https://www.browserling.com/browse/win10/firefox116/https://www.duisbock.de/cb_item/waldorf-fuer-mitglieder-des-bauverein-friemersheim/

Aber ich probier auch mal den PR aus, solange der nix kaputt macht und es dann bei dir funktioniert ist ja gut :)

**Comment by chriwen** [comment]
das ist sehr seltsam. Auf allen meinen Geräten und Browsern geht es nicht. auch anderer Internet-Provide (LTE) liefert gleiches Ergebnis. Versteh ich nicht.

**Comment by chriwen** [comment]
fixed in 3.2.8
