### ISSUE TITLE
Übersetzungen nicht aktualisiert bei CB 2.8.1

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1331]
Uns ist nach dem Update auf 2.8.2 via Wordpress.org aufgefallen, dass manche Texte plötzlich auf Englisch statt auf Deutsch erscheinen. Beispiel: "Hier verfügbar **_until_** ..." und "Hier verfügbar **_from_** ..."

![grafik](https://github.com/wielebenwir/commonsbooking/assets/2667894/512ba1fb-5115-4a3c-ba6e-85494ac643cf)

Scheinbar liegt es in diesem Fall daran, dass in Timeframe.php ein Leerzeichen entfernt geändert wurde
`commonsbooking_sanitizeHTML( __( 'from %1$s until %2$s', 'commonsbooking' ) ),`
aber commonsbooking.pot bzw. commonsbooking-de_DE.po weiterhin das vorgestellte Leerzeichen enthält
```
#. translators: %1$s = startdate, second %2$s = enddate in WordPress defined format
#: src/Model/Timeframe.php:149
msgid " from %1$s until %2$s"
msgstr ""
```
Kann es sein, dass ihr vergessen habt, die Übersetzungen zu aktualisieren?

Außerdem ist mir aufgefallen, dass der Litepicker 1 day bzw. 2 days als Tooltip anzeigt, obwohl Deutsch als Sprache eingestellt ist. Das war aber auch schon vor dem Update auf 2.8.1 der Fall.

**Comment by chriwen** [comment]
@nelarsen  Danke für den Hinweis. Der erste Punkt wird im nächsten Update behoben bzw. wir haben es in der online-Übersetzung in Wordpress schon angepasst. Versuche mal die Sprachdateien zu aktualisieren, das könnte das Problem schon beheben.
Ansonsten kommt bald ein Update mit der Fehlerbehebung raus.
Punkt 2 ist auch bekannt und steht in der langen Todoliste ;-)

**Comment by hansmorb** [comment]
Den Fehler habe ich im Litepicker schon behoben, wenn das nächste Mal der Litepicker aktualisiert wird können wir das gerne mit reinnehmen. Oder ich stell mal so einen PR aber für das bisschen lohnt sich das vielleicht nicht.
