### ISSUE TITLE
GBFS: Availability wird nicht berücksichtigt

### ISSUE THREAD

**Issue by futuretap** [wielebenwir/commonsbooking#1332]
Der `station_status` Endpunkt (`/wp-json/commonsbooking/v1/station_status.json`) soll laut GBFS-Spec die aktuelle Verfügbarkeit von Fahrzeugen (Items) in allen Stationen (Locations) wiedergeben. Derzeit werden jedoch einfach alle Fahrzeuge berücksichtigt, egal ob sie verfügbar sind oder nicht.

Konkret sollte `num_bikes_available` pro Station der Zahl der aktuell frei verfügbaren Fahrzeuge entsprechen.

Leider sind meine PHP-Kenntnisse etwas eingerostet und das Projekt ist schon einigermaßen komplex. Könnte sich jemand von Euch des Problems annehmen?

**Comment by hansmorb** [comment]
$preparedItem->num_bikes_available = count( Item::getByLocation( $item->ID ) ); zählt stumpf die Artikel am Standort, da sollte geschaut werden, ob die Artikel HEUTE verfügbar sind.
