### ISSUE TITLE
Inkorrekter Buchungszeitraum in Buchungsprüfung

### ISSUE THREAD

**Issue by kidhab** [wielebenwir/commonsbooking#1342]
**Describe the bug**
Auf der Übersichtsseite "Buchungsprüfung" werden andere und nicht die im Kalender ausgewählten Buchungszeiträume (Abholung, Rückgabe) angezeigt.

Selbes Verhalten mit CB 2.8.2 und 2.8.3

**To Reproduce**
- Erstellen eines Zeitraumes mit verschiedenen Buchungsfestern pro Tag, bspw.  10- 15 Uhr und 15 - 18 Uhr
- Buchen eines Artikels, bspw. Abholung Tag 1 im Zeitfenster 10 - 15 Uhr, Rückgabe Tag 2 im Zeitfenster 15 - 18 Uhr
- In der Buchungsprüfung werden die gewählten Zeitfenster nicht korrekt dargestellt.
- Die anschließend per Mail verschickte Buchungsbestätigung enthält ebenfalls die falschen Zeiträume

**Expected behavior**
Die Buchungszeiträume sollen in der Buchungsprüfung und in der Buchungsbestätigung per Mail korrekt angezeigt werden.

![Bildschirmfoto vom 2023-08-27 13-30-35](https://github.com/wielebenwir/commonsbooking/assets/32387157/b7a9005f-2468-4061-9ec0-7d121db77e8e)

![Bildschirmfoto vom 2023-08-27 13-31-00](https://github.com/wielebenwir/commonsbooking/assets/32387157/bcf0e058-fdb8-449b-9f28-aff731afcdfa)

**Comment by hansmorb** [comment]
Danke für die Fehlermeldung, ich konnte den Fehler reproduzieren und habe auch schon einen Pull Request erstellt. Falls du eine Testumgebung hast würde es mich freuen, wenn du es mal ausprobieren könntest. Ansonsten würden wir das mit dem nächsten Update (2.8.4) wahrscheinlich in den nächsten Wochen ausspielen.

**Comment by kidhab** [comment]
Ich habe es auf der Live-Instanz getestet. Dein Fix löst das Problem. Dankeschön!
