### ISSUE TITLE
Überlappung nicht erkannt für zwei Slot TFs mit gleichem Zeitraum

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1344]
**To Reproduce**
Zwei Zeitrahmen mit Rep Daily und Slots einstellen, bei beiden die gleiche Uhrzeit einstellen (zB. 10:00 - 15:00). Beide sind speicherbar und es wird kein Fehler erzeugt. Wenn die Uhrzeit leicht geändert wird (ie. einer 10:00 - 15:00 und der andere 10:00 - 16:00 wird der Zeitrahmen korrekt abgelehnt)

**Expected behavior**
Einer von beiden Zeitrahmen sollte nicht gespeichert werden.

**Comment by datengraben** [comment]
Wartest du noch auf Input von mir oder jemand anderem? Sonst wäre ich dafür einen PR erstellen und es reinzumergen.

**Comment by hansmorb** [comment]
Ich muss noch die Unit Tests beheben, irgendwas ist da auf dem Weg kaputtgegangen, dann erstelle ich den PR und dann kannst du gerne nochmal rüberschauen :)

**Comment by chriwen** [comment]
@hansmorb : Ich hab jetzt nicht alles im Detail durchgesehen, aber wird die Prüfung immer nur auf gleiche Timeframe-Typen (z.B. buchbar, geblockt etc.) durchgeführt? Weil grundsätzlich wäre es ja u.U. schon möglich gerade Blocker oder Urlaub / Feiertage auch übereinander zu legen. Aber ich glaube, in dem Fall haben wir keine Prüfung, oder?

**Comment by hansmorb** [comment]
Die Prüfung Model/Timeframe::isValid() wird nur für Zeitrahmen vom Typ Bookable durchgeführt.
