### ISSUE TITLE
filterTimeframesByMaxBookingDays filtert zu viel -> Feiertage funktionieren manchmal nicht

### ISSUE THREAD

**Issue by genevievecory** [wielebenwir/commonsbooking#1357]
Habe gerade einen Feiertag für ein Rad angelegt und es taucht nicht in der Benutzeroberfläche auf. Buchung des Tages läuft normal, trotz Feiertag.  Dasselbe ist letzte Woche passiert beim gleichen Rad (ein neues, aber an einer bestehenden Station).

V 2.8.2 auf unserem Live-System. 

https://www.freie-lastenradl.de/cb_item/zeus/?cb-location=319 - Allerheiligen ist nicht angezeigt. 

https://www.freie-lastenradl.de/wp-admin/post.php?post=15683&action=edit&classic-editor ist der Feiertag-Zeitrahmen. 

Verwandt mit https://github.com/wielebenwir/commonsbooking/issues/1252 ?

(Auch dort sichtbar ist ein Hinweis, den ich nicht wegbekomme - ich schätze ein CB Manager hat einen bestehenden Hinweis angepasst und alle Artikel und alle Stationen ausgewählt, dann gespeichert, und dann hat ein Admin das korrigiert, aber es wird trotzdem überall angezeigt - das mit "nicht verfügar" 29. 9 - 1. 10. Wir haben keinen Cache-Lösch-Plugin installiert.)

**Comment by hansmorb** [comment]
Danke für den Hinweis! Ich habe leider keinen Backend- Zugriff aber könntest du mir vielleicht noch sagen was die genauen Einstellungen von dem Zeitrahmen sind? Also Wiederholung und ob "Ganzer Tag" angewählt ist oder nicht?

**Comment by hansmorb** [comment]
Okay, konnte das Problem nachstellen. Es tritt nur auf wenn der Zeitrahmen für den Urlaub weit genug hinten liegt (bei mir meistens so, dass ich den Kalender weiterklicken muss) UND der Cache aktiviert ist. Witzig dabei ist, dass es egal ist ob der Cache geleert wurde oder nicht. Anscheinend wird immer ein falscher Cachewert aufgebaut. Wenn der Cache komplett deaktiviert ist tritt das Problem nicht auf.

**Comment by hansmorb** [comment]
Konnte den Fehler reproduzieren und die Ursache liegt darin, dass die Funktion filterTimeframesByMaxBookingDays auch die Holiday Timeframes rausfiltert. Eigentlich sollte diese Funktion nur die Timeframes rausfiltern, die aufgrund der Einstellung 'maxBookingDays' nicht mehr in unserem Radius liegen. Jedoch wird der Metawert 'maxBookingDays' auch still und heimlich für Holidays gesetzt. Seit unserem neusten Update ist dieser Wert bei Standardmäßig 30 Tagen. Das heißt also, dass jeder Feiertag  der mehr als 30 Tage in der Zukunft liegt automatisch nicht mitgezählt wird.
