### ISSUE TITLE
Kartenansicht implementieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#138]
Nutzer sollen die Möglichkeit haben über eine Kartenansicht:
 - alle Standorte mit Lastenrädern zu sehen
- ihre eigene Adresse anzugeben, um so Lastenräder in der näheren Umgebung zu finden.
 - zusätzlich über Filterfunktion verfügbare Lastenräder zu einem definierten Zeitraum auf der Karte zu filtern.

Implementierung könnte analog zur bereits sehr gut gelösten Integration bei Flotte erfolgen:
https://flotte-berlin.de/lastenrad-ausleihen/standorte/

**Comment by farbschein** [comment]
@markus-mw Habe Kontakt mit Flotte aufgenommen, um ggf. Codesnippets zu übernehmen.

**Comment by farbschein** [comment]
@markus-mw : Es gibt von Flotte Berlin ein karten-Plugin, welches mit CommonsBooking 1 funktioniert. Mein Vorschlag wäre, das zu nutzen und seitens CB2 die Daten passend an das Plugin zu übergeben.
https://github.com/flotte-berlin/commons-booking-map

Todo: Prüfen, in welchem Datenformat das Plugin die Daten erwartet. Bei Rückfragen kann ich Kontakt zum Entwickler herstellen.

**Comment by markus-mw** [comment]
@farbschein : Ich weiß nicht ob das wirklich so eine gute Idee ist. Ich habe es mal überflogen und bin mir nicht sicher wie sich das Pluging die benötigten Daten holt. Wahrscheinlich sind wir flexibler/schneller, wenn ich einfach nur das Leaflet Plugin verwende.
Wenn du mir den Kontakt zu dem Entwickler geben könntest, würde ich mich aber vorher nochmal mit ihm abstimmen wollen.

**Comment by markus-mw** [comment]
Wird nicht mehr benötigt, nehme ich an.
