### ISSUE TITLE
GBFS Funktionalität wird nicht dokumentiert

### ISSUE THREAD

**Issue by datengraben** [wielebenwir/commonsbooking#1381]
In der Anwender-Dokumentation unter https://commonsbooking.org gibt es noch keinen Abschnitt für die GBFS Routen.
Wo sie zu erreichen sind un welche aktuelle Version des GBFS Schemas bzw. welche Attribute CommonsBooking aktuell unterstützen.

Ich würde mir vorstellen:
* Liste der Endpunkte
    * `wp-json/v1/station_information.json`
    * `wp-json/v1/station_status.json`
    * `wp-json/v1/system_information.json`
* Unterstützten Attribute und Version des allgemeinen GBFS-Schema
* Kommentar zur Exponierung von personenbezogenen Daten (Namen, Adressen, ...)
* Ggf. Einrichtung, Beispiel-Aufrufe oder Rückgaben
* Ggf. noch wichtige offene Punkte der Implementierung die bei der Nutzung zu beachten sind

Da die Dokumentation ja außerhalb von Git-Gepflegt wird eher ein Merker für uns.

**Comment by chriwen** [comment]
@datengraben Wenn du da eine Doku erstellen möchtest, kannst du diese gerne anlegen. Bisher gab es keinen wirklichen Bedarf an der GBFS-API. Mir sind nur 1-2 Anwendungsfälle bekannt, die meines Wissens auch noch nicht mal produktiv umgesetzt wurden.
