### ISSUE TITLE
Hooks für Custom Metaboxen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1385]
Wenn wir einen Filter Hook für die CMB2 Metaboxen hätten, könnten CB2 Erweiterungen, Child Themes oder Codesnippets Metadaten hinzufügen ohne diese im WordPress Backend definieren zu müssen.
Ich brauche das, da ich gerade an einem Plugin arbeite welches spezifische Metaboxen für Artikel erstellt. (Damit die Erstellung von Rädern / Anhängern automatisiert werden kann).  Wenn Nutzende diese erst in das entsprechende Backend Feld kopieren müssten wäre das nicht sehr Nutzer*innenfreundlich.

**Comment by chriwen** [comment]
@hansmorb Um welchen Anwendungsfall geht es denn hier? Also, wo muss die Erstellung von Rädern etc. automatisiert werden und wie läuft das ab?

**Comment by hansmorb** [comment]
Ich wollte ein Plugin für CB2 erstellen mit dem es möglich ist einen Fahrradverleih mithilfe von Metaboxen zu konfigurieren. Dann könntest du, statt für jedes Rad eine eigene Beschreibung zu schreiben, dir automatisch die technischen Daten aus Metadaten heraus generieren lassen. So was ähnliches haben wir schon bei freie Lasten im Einsatz, unser System baut nur auf Advanced custom fields auf und ich wollte das etwas universeller mit CMB2 machen.
