### ISSUE TITLE
Slotweise Buchungen nicht für wöchentliche Zeitrahmenwiederholungen möglich?

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1404]
**Describe the bug**
Angenommen, eine Verleihstation hat Mo-Fr von 10 bis 18 Uhr auf. Die Verleihstation möchte gern die Auslastung des Lastenrades verbessern und schlägt vor, dass es zwei Slots pro Tag gibt (10-14 Uhr und 14-18 Uhr). Wenn ich diesen nicht exotischen Fall mit CB2 abbilden möchte, erhalte ich die Fehlermeldung "Overlapping bookable timeframes are not allowed to have the same weekdays". 

**To Reproduce**
Einen Zeitrahmen mit Wiederholung wöchentlich vom 1.1.2024 bis 1.6.2024 angelegen. Ganzen Tag abgewählen. Startzeit 10 Uhr, Endezeit 14 Uhr. Dann einen zweiten Zeitrahmen genau so anlegen, aber Startzeit 14 Uhr und Endezeit 18 Uhr.  Der Fehler erscheint beim Speichern.

**Expected behavior**
Da die zwei Zeitrahmen im Grunde genommen **nicht** überlappen, würde ich erwarten, dass ich den zweiten Zeitrahmen anlegen kann. Wenn ich bei den Zeitrahmen die Wiederholung "täglich" nehme, dann klappt es. Jedoch sind Stationen mit täglicher Öffnung extrem selten.

**Comment by hansmorb** [comment]
@nelarsen Vielen Dank für den Bug Report, ich konnte das Problem identifizieren und habe gerade einen PR für einen Bugfix gestellt.

**Comment by hansmorb** [comment]
@nelarsen Kann es sein, dass du auf dem aktuellen Master Branch bist? Das würde auch die nicht übersetzte Fehlermeldung erklären. Weil auf dem aktuellen Release konnte ich das Problem nicht nachstellen.

**Comment by nelarsen** [comment]
Argh, ich habe gerade festgestellt, dass ich auf dem Branch experimental/flotte-merge war )-;
Entschuldigung.

**Comment by hansmorb** [comment]
@nelarsen Dachte ich es mir doch, die Fehlermeldung war noch gar nicht "veröffentlicht" :) Aber danke für den Hinweis, das ist auf jeden Fall was für den Master!

**Comment by hansmorb** [comment]
@nelarsen Der Branch experiment/flotte-merge ist jetzt auch mit dem Bugfix bespielt, achtung, ich habe die changes re-based, unter Umständen musst du den Branch zurücksetzen um die Änderungen zu ziehen.
