### ISSUE TITLE
WP_DEBUG: REST API LocationsRoute und ProjectsRoute Schema Validation

### ISSUE THREAD

**Issue by printpagestopdf** [wielebenwir/commonsbooking#1408]
CB Version: 2.8.5
WP Version 6.4
PHP 8.1

**Describe the bug**
Sowohl die LocationsRoute als auch die ProjectsRoute der REST API rufen die schemaValidation Methode im WP Debug Modus auf. Die zugehörenden Schema Dateien sind aber nicht Bestandteil des Plugins, sodass die Aufrufe mit Fehler beendet werden.

**To Reproduce**
WP_DEBUG einschalten und z.B. http....../wp-json/commonsbooking/v1/location aufrufen

**Expected behavior**
Ausgabe einer Json Datei

**Screenshots**

**Comment by datengraben** [comment]
@printpagestopdf Hat das in früheren Versionen bei dir schon mal funktioniert? Oder ist dir das einfach das erste mal aufgefallen, weil du WP_DEBUG eingeschaltet hast. Meine Vermutung ist gerade das sich ggf. das Build-Verhalten via npm geändert hat. Dort sollten die Schema-Dateien aus dem node_modules in das bin-zip verschoben werden.

**Comment by printpagestopdf** [comment]
Soweit ich mich erinnere hat es in 2.7.3 noch funktioniert. Hier waren auch die Schema Dateien unter COMMONSBOOKING_PLUGIN_DIR . "node_modules/commons-api/commons-api.locations.schema.json" vorhanden. 
Diese scheinen bei der 2.8.5, installiert von der Wordpress Plugin Page zu fehlen.
P.S.: bin-zip sagt mir dabei nichts, soweit ich das sehe wird auch in der 2.8.5 die Schema Datei in COMMONSBOOKING_PLUGIN_DIR . "node_modules/commons-api gesucht.

**Comment by hansmorb** [comment]
Gibt es denn einen Grund WP_DEBUG in einer "Production" Umgebung einzuschalten? Weil um das zu beheben kannst du ja den Weg über git clone gehen, dann hast du nach einem npm install die entsprechenden Routen.

**Comment by printpagestopdf** [comment]
Sorry, es ging mir nich darum einen Workaround für mich zu finden, da würde ich diverse kennen (und nutze die auch). 
Nur kann es aus verschiedenen Gründen vorkommen, dass bei Realinstallationen z.B. zur Fehlersuche auch für ganz andere Zwecke als CB einmal WP_DEBUG einschalten muß. Falls dann die  REST API genutzt wird funktionieren die Locations nicht mehr (übrigens die Items, die ja viel aufwändiger sind funktionieren, weil da auf die Validierung verzichtet wird).
Alles in allem aber nicht wirklich wichtig, da ich vermute, dass die Rest API kaum genutzt wird, wollte nur auf den "Fehler" aufmerksam machen, hat mit Sicherheit niedrigste Priorität

**Comment by hansmorb** [comment]
> Alles in allem aber nicht wirklich wichtig, da ich vermute, dass die Rest API kaum genutzt wird, wollte nur auf den "Fehler" aufmerksam machen, hat mit Sicherheit niedrigste Priorität

Magst du mal den Bugfix im verlinkten Branch testen? Du kannst mit den bin/build-zip.sh eine Plugin zip aus dem ausgecheckten Branch erstellen

**Comment by printpagestopdf** [comment]
Beim ausführen von  bin/build-zip.sh bekomme ich:

Generating build directory...
Installing PHP and JS dependencies...
npm ERR! Cannot read property '@commonsbooking/frontend' of undefined

**Comment by hansmorb** [comment]
Ah, du musst erst
`npm run start` in dem Verzeichnis ausführen, dann werden die ganzen Abhängigkeiten installiert :)

**Comment by printpagestopdf** [comment]
Irgednwie sieht es so aus, als bräuchte ich da noch diverse prerequisits (grunt und composer hatte ich bereits zusätzlich installiert) aber jetzt:

> grunt dist

Loading "dart-sass.js" tasks...ERROR
>> ReferenceError: globalThis is not defined
Warning: Task "dart-sass:admin" not found. Use --force to continue.

**Comment by hansmorb** [comment]
Lösch mal deinen node_modules Ordner, ich habe das gerade mal manuell auf einem leeren Docker Container ausprobiert und eigentlich braucht das Bauen von dem Plugin nur composer, npm und rsync. Der Rest sollte von selber installiert werden.

**Comment by printpagestopdf** [comment]
Auch nach Löschen des node_modules Ordners der Fehler (bei mir übrigens nicht Docker sonder WSL2 mit Ubuntu 20.04):

Loading "dart-sass.js" tasks...ERROR
>> ReferenceError: globalThis is not defined
Warning: Task "dart-sass:admin" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! commonsbooking@2.8.5 dist: `grunt dist`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the commonsbooking@2.8.5 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hansmorb** [comment]
Ah, deine Node Version ist zu alt, gib mal node --version ein, die ist wahrscheinlich unter Node 12. Versuch mal  `sudo apt update && sudo apt upgrade` auf deinem System. Vielleicht sollten wir doch mal ein makefile zur Verfügung stellen :)

**Comment by printpagestopdf** [comment]
Sowohl die locations als auch die projects REST route lassen sich auch bei eingeschaltetem WP_DEBUG ohne Fehler aufrufen und geben ein entsprechendes JSON Result.

Sieht für mich also gefixt aus!
