### ISSUE TITLE
Buchungskalender bei "nicht überbuchbar" für Feiertag und locked Tag

### ISSUE THREAD

**Issue by printpagestopdf** [wielebenwir/commonsbooking#1424]
**Describe the bug**
Der Buchungskalender zeigt ein nicht eindeutiges Verhalten Station "nicht überbuchbar"
- Ein Feiertag kann trotz alledem überbucht werden, wird aber scheinbar als Tag zu gezählt
- Ein "locked" Tag wird im Buchungskalender zunächst so angezeigt als wäre er überbuchbar (z.B. aktivieren des Tags davor), wenn dann aber das zweite Datum (mit dem locked dazwischen) gewählt wird, ist es nicht  mehr auswählbar.

**To Reproduce**
- Station anlegen mit allen drei Überbuchbar Parameter (global benutzen, überbuchbar, überbucht Tage zählen) NICHT aktiviert
- Einen Artikel für die Station anlegen und einen zugehörenden buchbar Zeitrahmen (wöchentlich, außer Sonntag) mit z.B. 3 Tagen max buchbar
- Einen Feiertag anlegen für Station/Rad

Der Feiertag ist in dem Fall überbuchbar und wird wohl als ein Tag gezählt. 
Im Buchungskalender einen Samstag aktivieren zeigt auch den Montag als auswählbar, wird dieser gewählt, wird der ausgwählte Zeitraum zurückgesetzt.

**Expected behavior**
Der Feiertag sollte nicht überbuchbar sein
Der Buchungskalender sollte den Sonntag nicht als überbuchbar anzeigen

**Screenshots**
Eine Testinstallation ist noch 6 Tage im Zugriff (Achtung: danach autom. deaktiviert):
https://average-albatross-ctc7e.instawp.xyz/
Abonnent => Name: test, Passwort: test
Admin => Name: admin, Passwort: test

**Comment by hansmorb** [comment]
Danke, hab mir das mal angeschaut und konnte es bestätigen. Das Verhalten bei Locked Days ist schon in #1087 dokumentiert, das Verhalten für die Holidays muss auf jeden Fall angepasst werden.
