### ISSUE TITLE
Positionierungskarte geht nicht mehr

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1428]
**Describe the bug**
Die Karte auf der Positionierungsseite beim Erstellen eines neuen Standorts ist nicht verfügbar. Die Response von OSM ist: 400 - Nothing to search for. Bei existierenden Standorten wird die Karte richtig angezeigt. Der Fehler existiert sowohl mit dem neuen Frontend als auch in 2.8.5

EDIT: Die Positionierungskarte scheint seit dem Frontend Merge auch für existierende Standorte kaputt zu sein.

**To Reproduce**
Standort erstellen->Positionierunskarte ist weiss

**Comment by chriwen** [comment]
hab das gerade getestet. Die Karte wird jetzt wieder angezeigt.
 
Davor hatte ich folgenden Fehler:
Uncaught ReferenceError: L is not defined
    at Object.init_map (cb-map-positioning.js?ver=6.0.6:8:9)
    at HTMLDocument.<anonymous> (cb-map-positioning.js?ver=6.0.6:113:28)
    at e (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.0.6:2:30038)
    at t (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.0.6:2:30340)

Das ist im Script dann hier:
`init_map: function (latitude, longitude, add_marker) {
        // set up the map
        map = new L.Map('cb_positioning_map');

        const self = this;
        `

Irgendwie erinnere mich dunkel, dass wir das Problem schonmal hatten. Hat es eventuell etwas mit der Art, wie die Leaflet-Map in WP eingebunden wird zu tun? Hat sich da evtl. seit den Aktualisierungen durch die neue Frontend-Map was geändert?
ChatGTP sagt dazu folgendes:
Fehlendes oder fehlerhaftes Einbinden der Leaflet-Bibliothek: Stellen Sie sicher, dass die Leaflet-JavaScript-Bibliothek vor dem Ausführen Ihres eigenen Skripts korrekt eingebunden ist. Dies kann durch einen <script>-Tag im HTML-Code oder durch das korrekte Enqueueing der Skripte in WordPress erfolgen.

Reihenfolge der Skriptladung: Möglicherweise wird Ihr eigenes Skript (cb-map-positioning.js), das das 'L' Objekt verwendet, vor dem Leaflet-Skript geladen. Überprüfen Sie die Reihenfolge, in der die Skripte geladen werden, und stellen Sie sicher, dass Leaflet zuerst geladen wird.

@hansmorb : Hast du vielleicht nen Ansatz?

Beim Testen deines Fix wird zwar die Karte, dafür bekomme ich folgenden Fehler im admin-ajax-Request:

Fatal error: Uncaught Error: Non-static method CommonsBooking\Map\BaseShortcode::execute() cannot be called statically
in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Service/Cache.php on line 349

Aufrufstapel

CommonsBooking\Plugin::runShortcodeCalls()
wp-content/plugins/commonsbooking/src/Service/Cache.php:261
CommonsBooking\Plugin::warmupCache()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-admin/admin-ajax.php:187
Query Monitor
Es gab einen kritischen Fehler auf deiner Website.

**Comment by hansmorb** [comment]
@kmohrf Kannst du mir vielleicht Feedback geben ob ich den Fix von diesem commit besser lösen könnte?

https://github.com/wielebenwir/commonsbooking/pull/1431/commits/a75e60bbfc93a4e34920091e4ea31533b50e78ce

**Comment by hansmorb** [comment]
Der Hook betrifft nur das Frontend (siehe https://developer.wordpress.org/reference/hooks/wp_enqueue_scripts/ )
Bei init wird er immer ausgeführt, falls da nichts dagegen spricht wäre das vielleicht nützlicher. Ich hatte nur etwas Bedenken ob wir damit dann nicht unnötig viele Daten übertragen (wenn die Map im Backend ja nur in diesem einen Fall gebraucht wird)
