### ISSUE TITLE
E-Mail-Absender Sonderzeichen falsch dargestellt

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1433]
Von @nelarsen
wenn ein Absender-Name mit Sonderzeichen gewählt ist, in meinem Fall so:
![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/83644518-e29b-4769-9992-6b6c35ef4e7e)

Dann werden beim Senden die Sonderzeichen in HTML Entities in Settings::getOption mit commonsbooking_sanitizeHTML() umgewandelt. Leider sind HTML Entities wie & in E-Mail-Headers nicht zulässig. Das Ergebnis:

![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/3440b29a-6be2-4d94-945d-5c4d363e287b)

**Comment by nelarsen** [comment]
Mir ist aufgefallen, dass man sowohl für Buchungsemails (unter Vorlagen) als für Erinnerungen eine Absender-E-Mail-Adresse und einen Namen einstellen kann. Ich kann mir gerade nicht vorstellen, warum man dafür _unterschiedliche_ Absender angeben sollte. Ja, eigentlich könnte man auf die Default-Einstellungen für die ganze WP-Installation zurückgreifen, und in CB2 komplett darauf verzichten, eine Einstellung für Absenderadresse zu haben. Leider kann man die From-Einstellung nicht im nativen WP-Backend einstellen, sondern man braucht ein Plugin dafür, sonst kommt die Mail vom "wordpress@domain.de". Vorteil: Dieser Issue wäre erledigt, weil die Funktionalität aus CB2 fliegen würde.

```
add_filter( 'wp_mail_from', 'custom_wp_mail_from' );
function custom_wp_mail_from( $original_email_address ) {
	return 'lastenraeder@beispiel.de';
}
add_filter( 'wp_mail_from_name', 'custom_wp_mail_from_name' );
function custom_wp_mail_from_name( $original_email_from ) {
	return 'CB2 Buchungssystem';
}
```

**Comment by hansmorb** [comment]
Eine Frage noch: In deinem Screenshot scheint das gleiche Problem auch mit der Betreffzeile aufzutreten, ich konnte das in meinem Testsystem auch nachstellen. Aber dein PR bearbeitet nur die "From" Zeile, oder?

**Comment by nelarsen** [comment]
Du hast Recht, das Problem besteht ebenfalls für die Betreffzeile. Das hat mich nicht betroffen, weil ich für die Praxis keine &<> Zeichen in der Betreffszeile brauche (anders als beim Absender: Frieda & Friedrich). Sag Bescheid, wenn ich eine Lösung auch für die Betreffszeile vorschlagen soll.

**Comment by hansmorb** [comment]
Lass uns das Problem doch gerne gleich im Ganzen angehen!

**Comment by hansmorb** [comment]
Lass uns das Problem doch gerne gleich im Ganzen angehen!

**Comment by nelarsen** [comment]
OK. Auch für die Betreffszeile könnten wir sanitize_text_field statt commonsbooking_sanitizeHTML verwenden. Dann würde **&** wie erwartet funktionieren. Aber < und > würden weiterhin nicht funktionieren (d.h. sie würden in &lt; &gt; umgewandelt werden). Dafür müsste ich eine eigene Sanitize-Funktion schreiben. Soll ich einfach 'sanitize_text_field' nutzen?

**Comment by hansmorb** [comment]
Ein kurzer Test der sanitize_text_field hat bei mir gerade ergeben, dass es einfach die < > Zeichen komplett entfernt, ich glaube das ist okay für unseren use case.

**Comment by nelarsen** [comment]
Ja, sie werden von sanitize_text_field() entfernt, wenn sie paarweise auftreten wie in HTML-Tags. Sonst werden sie kodiert. Aber ich glaube es ist wirklich in Ordnung, der Welt zuzumuten, dass cb2 keine <> in Betreffszeile unterstützt (-;
Ich ergänze den PR, damit cb2 immerhin & in der Betreffszeile unterstützt (vermutlich auch ein seltener Fall).

**Comment by nelarsen** [comment]
`&` wird weiterhin (falsch) als `&amp;` in der Betreffszeile dargestellt. Das ist mir aufgefallen, weil wir einen Anhänger mit dem Namen "Henry & Wilde Hilde" haben (-;

Es liegt daran, dass der Betreff mit commonsbooking_parse_template() bearbeitet wird (das passiert nicht für den Absender). commonsbooking_parse_template() ruft gleich an zwei Stellen commonsbooking_sanitizeHTML() auf. Das ist in Ordnung, wenn die Ausgabe HTML ist, aber die Betreffzeile ist nicht HTML.

Ich werde eine Lösung vorschlagen. 

Die zwei Stellen mit commonsbooking_sanitizeHTML() sind:

- CB::**lookUp**() called by CB::get() called by commonsbooking_parse_template_callback() called by commonsbooking_parse_template() called by Message::prepareMail()
- **commonsbooking_parse_template_callback**() called by commonsbooking_parse_template() called by Message::prepareMail()

**Comment by hansmorb** [comment]
Wenn du magst, dann stell gerne einen PR!

**Comment by nelarsen** [comment]
Ich habe **zwei** Lösungvorschläge für Zeichen wie & im Email-Betreff als draft-PR erstellt. Ich finde Variante 1 (#1479 ) leicht besser als  (#1480). Was denkt ihr?

**Comment by datengraben** [comment]
Already merged for 2.9

**Comment by hansmorb** [comment]
Da fehlt noch die #1480
