### ISSUE TITLE
Frontend/Calendar: Zufällig buchbare Tage beim Blättern durch Kalender

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#144]
**Describe the bug**
- Beim Vorwärtsblättern (per Pfeilsymbol) im Kalender, erscheinen in manchen Monaten plötzlich ein bis mehrere grün hinterlegte Tage. Diese sind in den Timeframes jedoch nicht definiert.

siehe auch: https://drive.google.com/file/d/17bRT8yGkTfAAs1Dx_t41JKmtQoE6PhXY/view

Erwartet:
- Es werden nur Tage als buchbar angezeigt, die in einem Timeframe entsprechend definiert sind.

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben. Es lag an einem Fehler in der Funktion zur Rückgabe der Wochen die zu einem Kalender gehören.
