### ISSUE TITLE
Geohelper wirft Fatal Error bei fehlendem CURL

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1442]
Wenn curl auf dem Server nicht installiert ist, wird folgender Fehler geworfen:
` Fatal error: Uncaught Error: Undefined constant "CommonsBooking\Helper\CURLOPT_SSL_VERIFYHOST" in /wordpress/wp-content/plugins/commonsbooking/src/Helper/GeoHelper.php:28 Stack trace: #0 /wordpress/wp-content/plugins/commonsbooking/src/Model/Location.php(196): CommonsBooking\Helper\GeoHelper::getAddressData(', , ') #1 /wordpress/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Location.php(39): CommonsBooking\Model\Location->updateGeoLocation() #2 /wordpress/wp-includes/class-wp-hook.php(2): CommonsBooking\Wordpress\CustomPostType\Location->savePost(32, Object(WP_Post)) #3 /wordpress/wp-includes/class-wp-hook.php(2): WP_Hook->apply_filters(NULL, Array) #4 /wordpress/wp-includes/plugin.php(2): WP_Hook->do_action(Array) #5 /wordpress/wp-includes/post.php(2): do_action('save_post', 32, Object(WP_Post), false) #6 /wordpress/wp-content/plugins/wordpress-importer/src/class-wp-import.php(746): wp_insert_post(Array, true) #7 /wordpress/wp-content/plugins/wordpress-importer/src/class-wp-import.php(89): WP_Import->process_posts() #8 /wordpress/wp-content/plugins/wordpress-importer/src/class-wp-import.php(65): WP_Import->import('/wordpress/wp-c...') #9 /wordpress/wp-admin/admin.php(2): WP_Import->dispatch() #10 {main} thrown in /wordpress/wp-content/plugins/commonsbooking/src/Helper/GeoHelper.php on line 28 `

Das betrifft einen sehr spezifischen Use-Case und zwar den Wordpress Playground ( https://playground.wordpress.net/ ). Wenn dieser Bug nicht wäre, könnten wir mit wenig Mühe die #1221 umsetzen. Aktuell hindert uns aber der Bug am Erstellen von neuen Standorten. Hier muss meiner Meinung nach keine große Usermeldung oder ähnliches hin, der Fatal Error muss einfach nur abgefangen werden und dann können wir weitermachen.

**Comment by datengraben** [comment]
@hansmorb Freut mich wenn das mit einer Demo-Umgebung klappt!

Nach der aktuellen Umsetzung in [8983f14](https://github.com/wielebenwir/commonsbooking/commit/8983f14d745338f038f31b8368151e2f3fcbbc6e) ist das Verhalten aber nicht ganz nachvollziehbar. Wenn ich kein `curl` installiert habe, bekomme ich bei den folgenden Verwendungen von `GeoHelper::getAdressData` eine Exception `Location address missing. (ID: mit post id)`, was ja in unserem Fall nicht stimmt. Die Verarbeitung eines items wird dann übersprungen und taucht bei eingeschaltetem WP_DEBUG auf.

* `src/API/LocationsRoute::prepare_item_for_response`
* `src/API/GBFS/StationInformation::prepare_item_for_response`

Bei der folgenden Verwendung, wird aber ohne Beanstandung weitergemacht.
* `src/Model/Location::updateGeoLocation`

Ich glaube, dann würde ich anstatt null zurückzugeben liebe eine Exception mit sowas wie `Curl extension missing`.
In allen drei Fällen oben werden die Items mit einer Exception einfach ausgelassen, das wäre ja zu verkraften.
Falls WP_DEBUG gesetzt ist, fällt dieser Fehler dann auch auf.

Langfristig wäre es aber schon nötig, das irgendwie transparent zu haben. Jemand der sich darauf verlässt die Koordinaten für eine Location zu haben (CB-API, GBFS), sollte ja aktiv werden können, sobald es ausgeführt wird. Schwierig das Problem (curl fehlt) zu verstehen, wenn diese Items in der Rückgabe der APIs einfach fehlen.
