### ISSUE TITLE
Mobile Optimierung: Kalender für ipad optimieren

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#146]
![grafik](https://user-images.githubusercontent.com/28141760/90766898-9351eb00-e2ec-11ea-9760-c17c08df13e2.png)

**Comment by flegfleg** [comment]
Huhu, ich hab die Kalenderanzeige gefixt (brechen jetzt um wenn zu wenig Platz) in diesem Branch:
 **bugfix/calendar-on-mobile**


<img width="1340" alt="Bildschirmfoto 2020-09-29 um 19 06 20" src="https://user-images.githubusercontent.com/4009931/94590380-dfe2fb80-0286-11eb-922e-48d8950ae26c.png">
