### ISSUE TITLE
JSON REST "locations" route does not work when WP_DEBUG=1

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1466]
CB 2.8.6 installiert von WP Plugins Directory.

Wenn WP_DEBUG gesetzt ist, gibt /wp-json/commonsbooking/v1/locations ein leeres/ungültiges Ergebnis zurück und ein Stack Trace wird in der WP-Logdatei ausgegeben. Offenbar liegt es daran, dass die "locations"-Route validateData() aufruft wenn und nur wenn WP_DEBUG=1. validateData() ist jedoch nicht erfolgreich, weil ein schemaValidation() ausgefüht wird. schemaUrl ist definiert als

`protected $schemaUrl = COMMONSBOOKING_PLUGIN_DIR . "node_modules/commons-api/commons-api.locations.schema.json";`

und diese Datei ist nicht vorhanden.

Wenn WP_DEBUG nicht gesetzt ist, funktioniert die locations-Route. Bei 'availability' besteht das o.g. Problem nicht, weil schemaValidation() nicht aufgerufen wird.

**Comment by hansmorb** [comment]
Dopplung mit #1408. 
Warum wollt ihr denn CB2 mit WP_DEBUG aktiviert nutzen?

**Comment by nelarsen** [comment]
Oh, sorry wegen der Doppelung. Wir sind noch in der Testphase und testen projektspezifische Plugins. Dafür ist WP_DEBUG hilfreich oder notwendig. Der beschriebene Bug verhindert das, weil ein Plugin von ebendieser locations-Route abhängig ist.. Später wollen wir WP_DEBUG nicht aktiviert lassen.

**Comment by chriwen** [comment]
ich nehme mal an an, dass das commons-api Verzeichnis in den node-modules im Zuge der aktuelleren build-Prozess-Anpassungen mal irgendwann rausgeflogen ist. Das müssten wir wieder implementieren.

**Comment by hansmorb** [comment]
Ah, ich habe gar nicht daran gedacht: @nelarsen Probier doch mal statt einer Plugin Zip mit git clone das Pluginverzeichnis zu nehmen und dann auf den release/2.8.6 Branch zu wechseln. Wenn du jetzt `npm run start` ausführst, sollte das Problem behoben sein.

**Comment by hansmorb** [comment]
> ich nehme mal an an, dass das commons-api Verzeichnis in den node-modules im Zuge der aktuelleren build-Prozess-Anpassungen mal irgendwann rausgeflogen ist. Das müssten wir wieder implementieren.

Na ja, ich würde eigentlich den node_modules Ordner im besten Fall gar nicht mit dem Plugin mitliefern. Wenn dann würde ich eher den Check deaktivieren, wenn er die Schema Datei nicht findet oder wenn der node_modules Ordner nicht existiert

**Comment by hansmorb** [comment]
> CB 2.8.6 installiert von WP Plugins Directory.
> 
> Wenn WP_DEBUG gesetzt ist, gibt /wp-json/commonsbooking/v1/locations ein leeres/ungültiges Ergebnis zurück und ein Stack Trace wird in der WP-Logdatei ausgegeben. Offenbar liegt es daran, dass die "locations"-Route validateData() aufruft wenn und nur wenn WP_DEBUG=1. validateData() ist jedoch nicht erfolgreich, weil ein schemaValidation() ausgefüht wird. schemaUrl ist definiert als
> 
> `protected $schemaUrl = COMMONSBOOKING_PLUGIN_DIR . "node_modules/commons-api/commons-api.locations.schema.json";`
> 
> und diese Datei ist nicht vorhanden.
> 
> Wenn WP_DEBUG nicht gesetzt ist, funktioniert die locations-Route. Bei 'availability' besteht das o.g. Problem nicht, weil schemaValidation() nicht aufgerufen wird.

Magst du mal den Bugfix im verlinkten Branch testen? Du kannst mit den bin/build-zip.sh eine Plugin zip aus dem ausgecheckten Branch erstellen

**Comment by nelarsen** [comment]
> Magst du mal den Bugfix im verlinkten Branch testen? Du kannst mit den bin/build-zip.sh eine Plugin zip aus dem ausgecheckten Branch erstellen
Ich habe ein Workaround für mich für jetzt, aber ich teste natürlich sehr gern deine Lösung. Leider schaffe ich es nicht (mehr) die Dependencies mit `composer install --no-dev` oder `build/bin-zip.sh` zu installieren (gerade Fehler wegen "Cypress cannot write to the cache directory due to file permissions"). Könntest du mir die ZIP-Datei schicken?

**Comment by hansmorb** [comment]
Hui, das ist ja ungünstig! Ja, hier ist die zip:
[commonsbooking.zip](https://github.com/wielebenwir/commonsbooking/files/13708886/commonsbooking.zip)

**Comment by nelarsen** [comment]
Ich kann bestätigen, dass der bugfix/issue-1408-Branch das Problem löst. Vielen Dank!

**Comment by chriwen** [comment]
@hansmorb  mir ist noch nicht ganz klar warum du die Abfrage nach dem Schema im produktivbetrieb abschaltest. Braucht es das nicht? Wir hatten das Schema damals absichtlich lokal hinterlegt da ein Zugriff auf ein externes repo nicht den WP Sicherheitsrichtlinien entsprach. Wie bekommen wir das wieder eingebunden? Oder kann das generell weg? Bin da nicht so firm aber hätte vermutet dass es schon einen Sinn macht dass wir das vorhalten?

**Comment by chriwen** [comment]
Evtl. müssen wir das Schema dann woanders hinlege wenn es nicht ins node_modules soll.

**Comment by datengraben** [comment]
@nelarsen @hansmorb @chriwen 
Mit https://github.com/wielebenwir/commonsbooking/commit/72ead46f904715fa1bbaa7788eaad68c2f910ae1 sind jetzt die Schema-Dateien an einem Ort wo auch eine nicht-DEV-Installation sie lesen können.

Trotzdem verhält sich der Validator aber seltsam.

Diese Route (lokal) "http://localhost:1000/index.php?rest_route=/commonsbooking/v1/projects" hat ein Problem mit  dem `#/definitions/project` Pointer und ergibt folgenden Fehler:

```
Opis\\JsonSchema\\Exceptions\\UnresolvedReferenceException: Unresolved reference: /definitions/project in /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/PointerRefKeyword.php:49
Stack trace:
#0 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/AbstractRefKeyword.php(58): Opis\\JsonSchema\\Keywords\\PointerRefKeyword->doValidate(Object(Opis\\JsonSchema\\ValidationContext), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema))
#1 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(113): Opis\\JsonSchema\\Keywords\\AbstractRefKeyword->validate(Object(Opis\\JsonSchema\\ValidationContext), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema))
#2 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(98): Opis\\JsonSchema\\Schemas\\ObjectSchema->applyKeywords(Array, Object(Opis\\JsonSchema\\ValidationContext))
#3 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(67): Opis\\JsonSchema\\Schemas\\ObjectSchema->doValidate(Object(Opis\\JsonSchema\\ValidationContext))
#4 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/IterableDataValidationTrait.php(55): Opis\\JsonSchema\\Schemas\\ObjectSchema->validate(Object(Opis\\JsonSchema\\ValidationContext))
#5 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/IterableDataValidationTrait.php(102): Opis\\JsonSchema\\Keywords\\ItemsKeyword->iterateAndValidate(Object(Opis\\JsonSchema\\Schemas\\ObjectSchema), Object(Opis\\JsonSchema\\ValidationContext), Object(Generator), Object(ArrayObject))\n#6 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/ItemsKeyword.php(141): Opis\\JsonSchema\\Keywords\\ItemsKeyword->validateIterableData(Object(Opis\\JsonSchema\\Schemas\\ObjectSchema), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema), Object(Opis\\JsonSchema\\ValidationContext), Object(Generator), 'items', 'All array items...', Array, Object(ArrayObject))\n#7 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(113): Opis\\JsonSchema\\Keywords\\ItemsKeyword->validate(Object(Opis\\JsonSchema\\ValidationContext), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema))
#8 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(85): Opis\\JsonSchema\\Schemas\\ObjectSchema->applyKeywords(Array, Object(Opis\\JsonSchema\\ValidationContext))
#9 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(67): Opis\\JsonSchema\\Schemas\\ObjectSchema->doValidate(Object(Opis\\JsonSchema\\ValidationContext))\n#10 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Keywords/PropertiesKeyword.php(83): Opis\\JsonSchema\\Schemas\\ObjectSchema->validate(Object(Opis\\JsonSchema\\ValidationContext))
#11 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(113): Opis\\JsonSchema\\Keywords\\PropertiesKeyword->validate(Object(Opis\\JsonSchema\\ValidationContext), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema))\n#12 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(85): Opis\\JsonSchema\\Schemas\\ObjectSchema->applyKeywords(Array, Object(Opis\\JsonSchema\\ValidationContext))\n#13 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Schemas/ObjectSchema.php(67): Opis\\JsonSchema\\Schemas\\ObjectSchema->doValidate(Object(Opis\\JsonSchema\\ValidationContext))
#14 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Validator.php(158): Opis\\JsonSchema\\Schemas\\ObjectSchema->validate(Object(Opis\\JsonSchema\\ValidationContext))\n#15 /var/www/html/wp-content/plugins/commonsbooking/vendor/opis/json-schema/src/Validator.php(64): Opis\\JsonSchema\\Validator->schemaValidation(Object(stdClass), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema), NULL, NULL)\n#16 /var/www/html/wp-content/plugins/commonsbooking/src/API/BaseRoute.php(95): Opis\\JsonSchema\\Validator->validate(Object(stdClass), Object(Opis\\JsonSchema\\Schemas\\ObjectSchema))\n#17 /var/www/html/wp-content/plugins/commonsbooking/src/API/ProjectsRoute.php(47): CommonsBooking\\API\\BaseRoute->validateData(Object(stdClass))\n#18 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1193): CommonsBooking\\API\\ProjectsRoute->get_items(Object(WP_REST_Request))\n#19 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/commonsbooking...', Array, NULL)\n#20 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch(Object(WP_REST_Request))\n#21 /var/www/html/wp-includes/rest-api.php(424): WP_REST_Server->serve_request('/commonsbooking...')
#22 /var/www/html/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#23 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#24 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#25 /var/www/html/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#26 /var/www/html/wp-includes/class-wp.php(813): WP->parse_request('')
#27 /var/www/html/wp-includes/functions.php(1336): WP->main('')
#28 /var/www/html/wp-blog-header.php(16): wp()
#29 /var/www/html/index.php(17): require('/var/www/html/w...')
#30 {main}
```

Diese Route (lokal) "http://localhost:1000/index.php?rest_route=/commonsbooking/v1/locations" ergibt zwar keinen Fehler, wenn ich das Schema verändere, z.B. den o.g. JSON-Pointer `#/definitions/` in eine Version die auch eine `UnresolvedReferenceException` erzeugen sollte, passiert nichts und OPIS wertete es als "valide" aus.

Kann das jemand von euch bestätigen?

**Comment by hansmorb** [comment]
Danke dir, die Locations Route funktioniert jetzt wieder!
Leider kriege ich jetzt bei der Locations Route einen Validation Fehler (auch nur bei aktiviertem WP_DEBUG):
![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/287468c6-d127-4d00-a7ce-f794ce44ebf5)

Das ist die gesamte Antwort aus unserem Produktivsystem bei freie Lasten: 
[items.json](https://github.com/wielebenwir/commonsbooking/files/14595059/items.json)

**Comment by hansmorb** [comment]
Ich glaube das Problem ist, dass ownerID für die items Route ein required Parameter ist, dieser aber nur gesetzt ist, wenn auch wirklich item Admins definiert sind:

![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/c26537c5-950c-4aee-be79-2d748cc43155)

FÜr mich die sauberste Lösung wäre das Schema entsprechend anzupassen, das müsste dann aber im Repo für das Schema passieren. Für die Locations ist das auch kein required Parameter.

**Comment by hansmorb** [comment]
Ich schließe das jetzt hier, da das eine separate Issue ist!
