### ISSUE TITLE
Backend: Buchungsliste bauen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#147]
Bitte folgende Spalten einfügen
- [ ] Titel (verlinkt zur Detailansicht)
- [ ] Artikel-Name
- [ ] Buchungs-Start
- [ ] Buchungs-Ende
- [ ] Buchungs-Code
- [ ] Nutzer*in, die gebucht hat (verlinkt zur Backend-Profilseite)
- [ ] Standort-Name
- [ ] Buchungszeitpunkt
- [ ] Buchungs-Status (pending, confirmed, canceled)

Bitte Filter für:
- [ ] Artikel-Name
- [ ] Standort-Name
- [ ] Buchungs-Status

**Comment by farbschein** [comment]
identish mit #87 -> Anforderungen übernommen. Schließe dieses Ticket.
