### ISSUE TITLE
Autor von Seiten, Artikel, Standorte, ... in Autor mit Rolle cb_manager ändern geht nicht

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1471]
CB 2.8.6.
Bei mir kann ich als Admin oder als cb_manager den Autor von Posts (normale Posts, Artikel, Standorte, ...) im Backend ändern. So weit prima. Allerdings stehen grundsätzlich nur Admins oder Mitarbeiter in der Dropdown zur Verfügung, keine cb_manager. Ich habe versucht, die Ursache zu finden, aber habe es noch nicht geschafft. Ist das bekannt? 
Ich kann gerne weiter Fehlersuche machen und ggf. eine Lösung vorschlagen. Vielleicht ist es aber auch ein Problem mit meiner Installation.
![grafik](https://github.com/wielebenwir/commonsbooking/assets/2667894/b0ac62ea-efc5-437e-bb1a-2df6b69603cb)

**Comment by hansmorb** [comment]
Nein, ich kann das auch reproduzieren. Da CB-Manager auch items erstellen können sollten diese auch eigentlich als Autor zuweisbar sein, wenn du magst dann stell gerne mal Nachforschungen an!

**Comment by nelarsen** [comment]
Ok, hier ist die Lösung: In Plugin.php, Funktion getRoleCapMapping(), bitte **level_0** und **level_1** einfügen, um dem cb_manager die capabilites level_0 und level_1 zu erteilen (wie ein Mitarbeiter/contributor):

```
self::$CB_MANAGER_ID => [
	'read'                                 => true,
        'level_0'                              => true,
        'level_1'                              => true,
	'manage_' . COMMONSBOOKING_PLUGIN_SLUG => true,
],
```

Danach muss CB deaktiviert und aktiviert werden. Und danach muss jeder bestehender cb_manager im Backend->Benutzer zu einem Abonnent (beispielsweise) und dann wieder zu einem cb_manager gemacht werden. Im Ergebnis wird wp_user_level in der usermeta-Tabelle gleich 1 gesetzt (der administrator hat level 10; hauptsache der Wert ist ungleich 0). 
![grafik](https://github.com/wielebenwir/commonsbooking/assets/2667894/06971458-77ce-4e67-a838-b1ea1f6940d9)

User_level ist eigentlich seit vielen Jahren deprecated. Aber der Gutenberg-Editor nutzt dennoch ebendiesen Wert, um festzustellen, wer "author" ist. Der Gutenberg-Editor fragt das über diese REST-API-Anfrage ab, wie man leicht mit Mozilla-Netzwerkanalyse feststellen kann.
/wp-json/wp/v2/users?context=view&who=authors&per_page=50&_fields=id,name&_locale=user

Zum Thema gibt es [hier ](https://www.role-editor.com/wordpress-user-levels-deprecated-just-partially/ )einen schon alten Blog-Artikel. Der Nachtrag vom Jahr 2022 mag für den alten WP-Editor (gibt es den noch?) zutreffen, aber nicht für Gutenberg.

**Comment by nelarsen** [comment]
In 2.9 ist das Problem gelöst. Ich weiß nicht wodurch, aber ich kann den Autor von Posts nun auch auf cb_manager ändern. Schließen @hansmorb?
PS: Vielen Dank für das Release 2.9. Es ging problemlos, umzustellen!

**Comment by nelarsen** [comment]
Ich habe noch mal mit der aktuellen Version 2.9.3 geschaut. Das von mir gemeldete Problem (cb 2.8.6) besteht offenbar nicht mehr. Ich schließe.
