### ISSUE TITLE
Sortierung in [cb_items_table] ist nicht alphabetisch, sondern nach Datum

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#1478]
Der [cb_items_table] gibt die Lastenräder sortiert nach Datum, nicht alphabetisch aus. Das liegt daran, dass der get_posts()-Aufruf keinen 'orderby' => 'title' hat. Für 'orderby' gibt es in WP ein Default: date.

commonsbooking/src/View/Calender.php:
```
$items = get_posts(
          array(
		'post_type'      => 'cb_item',
		'post_status'    => 'publish',
		'order'          => 'ASC',
		'posts_per_page' => - 1,
          )
      );
```

(Die Ergänzung von `'orderby' => 'title'` habe ich lokal getestet. `'orderby' => 'post_title'` funktioniert ebenfalls)

**Comment by hansmorb** [comment]
Danke dafür, aber hat der Shirtcode nicht auch ein Order und orderby Parameter? Also eigentlich sollte das ja von den Nutzenden konfigurierbar sein.

**Comment by nelarsen** [comment]
Hallo Hans,
das trifft nur bei [cb_items] und bei [cb_locations] zu, nicht bei [cb_items_table].

Man kann das problemlos auf cb_items_table analog implementieren (ich unterstütze gern: wenn gewollt, erstelle ich einen PR).

ABER eigentlich halte ich das für unnötig. Es ist schon sehr eingeschränkt, welche Werte orderby annehmen kann. Wer sollte schon die Lastenräder nach Autor, Post-ID oder Kommentar-Anzahl sortieren? Am ehesten (auch ziemlich hypothetisch) könnte ich mir vorstellen, dass jemand nach einem Lastenradparameter wie Tragfähigkeit (kg) oder Akku-Reichweite (km) sortieren möchte. Dafür müsste man orderby=meta_value setzen, aber dann wäre gleich ein weitereren Parameter meta_key=my_custom_cargobike_parameter nötig, der aktuell nicht zugelassen ist.
99% wollen doch einfach nur alphabetisch sortieren? Ich rege daher an, die 1 Zeile wie oben vorgeschlagen einzufügen und damit dieser Issue schließen.

**Comment by nelarsen** [comment]
Spricht etwas dagegen, diesen Bug sofort zu lösen? Einfach **'orderby' => 'title'** einfügen . Der Bug ist auch in 2.9 vorhanden.

**Comment by chriwen** [comment]
@nelarsen : ich passe das gerne an. Können wir evtl. im nächsten Update noch einfügen.
