### ISSUE TITLE
Profildaten

### ISSUE THREAD

**Issue by mega-stoffel** [wielebenwir/commonsbooking#1482]
Hej!
Könnte man bei der Buchungsbestätigung unter "Deine Profildaten" statt "Nutzenden-Daten" vielleicht einfach "Deine Daten" schreiben, analog zu "Deine E-Mail" darüber?
![grafik](https://github.com/wielebenwir/commonsbooking/assets/25298441/f68e7744-7e01-4aaa-a175-063f6361fdc7)

**Comment by chriwen** [comment]
@mega-stoffel Ja, das können wir gerne umsetzen. Nehme ich auf die Todoliste.
