### ISSUE TITLE
cb_map : Manche Kartenpräsentationen funktionieren nicht

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1496]
Tiles werden bei zwei Kartentypen nicht gefunden. 
OSM - Wanderung und Fahrrad: Server nicht gefunden
OSM - Lokaler: SSL Error

Beide Tileserver nicht mehr verfügbar, deshalb müssen beide Optionen entfernt werden.

Am besten gemeinsam mit #1412

**Comment by datengraben** [comment]
Ja das stimmt, find ich auch gut. Glaube der Fahrrad-Stil könnte bald auch wieder aktiv werden.

Aber unabhängig davon, @hansmorb das Ermöglichen von Hinzufügen / Ändern der Kartenstile in der Ausleihkarten könnten wir auch mal als "good first issue" erstellen. Genauso wie man die Icons in der Leaflet-Karte anpassen kann könnten User dann auch eigene Karten-Stile verwenden (z.B. über Eintrag im Settings-Bereich oder einen Filter-Hook). Oder auf Dienste wechseln dessen TOS nicht bei zu großer Nutzung ein Limit vorsehen.
