### ISSUE TITLE
Frontend: Monatsnamen einheitlich auf Deutsch anzeigen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#150]
![grafik](https://user-images.githubusercontent.com/28141760/90775528-3f99ce80-e2f9-11ea-804e-54baf44af48d.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Wo wird das so dargestellt? Ich konnte die Stelle nicht finden.

**Comment by hanneskasimir** [comment]
hm, das war auf der Artikel-Liste. In der Zwischenzeit sieht die Seite komplett anders aus.
