### ISSUE TITLE
Fatal Error bei Adminprüfung (leeres Array)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1501]
Auf unserer Instanz kam es zu einem fatal error in 
/commonsbooking/src/Model/Timeframe.php : 960 
da in einem Fall eines users itemAdminIds leer war und somit die array_merge den Fehler geworfen hat.

Tritt wohl auf, wenn ein CB Manager zwar einer Location aber keinem Item zugewiesen ist.

Lösungsansatz: die beiden Variablen als Array initializieren:
        $locationAdminIds = array();
        $itemAdminIds = array();

**Comment by hansmorb** [comment]
Dopplung mit #1472
