### ISSUE TITLE
New map does not work after update to version 2.9

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#1522]
**Describe the bug**
I added the shortcode `[cb_search id="24282"]` to the page https://fjordbeweger.de/neue-karte/ but its not shown and the DevTools throws some errors.

**Screenshots**

<img width="1675" alt="2024-02-24_15-11-55" src="https://github.com/wielebenwir/commonsbooking/assets/363363/17b0d264-fa4f-45a1-b6e9-e67108be06a1">

**Comment by hansmorb** [comment]
Die neue Version vom Frontend wurde veröffentlicht aber irgendwie erstellt dependabot keinen PR für das Update, müssen wir wohl manuell machen wenn Zeit dafür ist. Dann können wir auch eine js Datei statt cjs ausliefern.

**Comment by hansmorb** [comment]
Der spezifische Fehler wurde damit behoben, fehlende Tiles sind in #1496 , das mit den Fonts muss nochmal geprüft werden und wäre dann eine eigene Issue.
