### ISSUE TITLE
Feiertage-Import: JS funktioniert nicht in Edge

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#1533]
Meldung über Ticketsystem:
- Der Button zum importieren der Feiertage funktioniert anscheinend in Edge nicht.

**Comment by datengraben** [comment]
@chriwen Zur Sicherheit wäre die Version von Edge interessant und die Fehlermeldung in der Dev-Console ["How to open Dev-Tools in Edge"](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview#open-devtools)

**Comment by hansmorb** [comment]
Konnte das unter 122.0.2365.52 (Official build) (64-bit) unter Linux nicht reproduzieren und auch nicht über browserling.com mit Windows und Edge 118. Meine Vermutung ist, dass der JS Cache nicht geleert ist.

**Comment by hansmorb** [comment]
Würde das schließen, da es vermutlich eher was mit gecachten Werten zu tun hatte
