### ISSUE TITLE
Nutzer-Rollen: Kombination location/item_admin

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#154]
Die beiden Rollen location_admin und item_admin sollen zu einer Rolle "cb_admin" zusammengeführt werden.
Diese neue Rolle dient dann für die Auswahl entsprechender Nutzer an Locations und Items.
Diese Story ist eine Anpassung von #101 

Anpassung der Rechte für die Rolle cb_manager:
a) Ein Nutzer kann nur die mit ihm verknüpften Items bearbeiten.

b) Ein Nutzer kann die mit ihm verknüpften Locations bearbeiten. 

c) Jeder Nutzer kann neue Timeframes anlegen. Bei der Bearbeitung der Timeframes ist die Auswahl der Locations auf die mit dem Nutzer verknüpften Locations beschränkt **und ein Pflichtfeld**.
Ist keine Location mit dem Nutzer verknüpft, bleibt die Auswahl leer. Das Feld wird so validiert, dass mindestens eine Auswahl getroffen werden muss. Der Nutzer kann aus allen Items mit Status publish auswählen.

**Comment by markus-mw** [comment]
@farbschein : Also die Sache, dass der manager Timeframes anlegen kann, aber keine Locations/Items ist leider nicht so ganz trivial. Super schnell gemacht wäre, dass er gar nichts oder alles anlegen kann. Ebenso einfach wäre es Teile einfach auszublenden. Was sagst du?

**Comment by farbschein** [comment]
@markus-mw Dann erstmal alles anlegen, also keine Beschränkung. Frage wäre aber, ob man die Abfrage zur Location-Auswahl nicht einfach über ne Query lösen kann, die eben prüft, ob der Nutzer in den Meta-Daten enthalten ist oder nicht? Also als Filter auf die Select-Liste?

**Comment by markus-mw** [comment]
@farbschein : Die Auswahl der Locations einzuschränken ist kein Thema. Lediglich das mit den anlegen der Posts lässt sich nicht so ohne weiteres gezielt für bestimmt Custom Post Types einschränken.

**Comment by markus-mw** [comment]
@farbschein : Die Änderungen sind jetzt im Master.

**Comment by farbschein** [comment]
@markus-mw .. Super, schaut alles fein aus. Gut gelöst ;-)
