### ISSUE TITLE
Frontend/Buchungskalender: Anpassung Datumsauswahl

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#155]
Es sollen folgende Änderungen im Buchungskalender vorgenommen werden:

- Die Infobox (mit Zeit-Select) soll immer sichtbar sein
- Start und Endzeit in der Box sollen sich dynamisch je nach Auswahl im Kalender anpassen
- Wenn kein Datum gewählt ist, soll in der Infobox ein Hinweis-Text (Bitte Abhol-Datum wählen / Bitte Rückgabe-Datum wählen) eingeblendet werden.

**Comment by markus-mw** [comment]
@farbschein : Die Infobox wird doch bereits immer angezeigt, wenn ein Datum gewählt ist. Der zweite Punkt verhält sich auchschon so wie beschrieben. Ich habe jetzt lediglich den dritten Punkt ergänzt. Den Text hab ich auf englisch eingetragen. Da könntest du noch die Übersetzungen ergänzen. (wieder im master)

**Comment by farbschein** [comment]
@markus-mw Die Box wird derzeit erst angezeigt, wenn das zweite Datum (Return-Date) gewählt wurde. Erste Usability-Tests haben gezeigt, dass das bezüglich der Uhrzeitauswahl nicht so leicht verständlich ist.
Deshalb sollte die Box am besten schon ohne Datumauswahl sichtbar sein. Sobald man das erste Datum gewählt halt, soll in der Box dann das Datum sichtbar sein und das Dropdown zur Abholzeit eingeblendet werden.
Sobald das Return-Datum gewählt wurde, soll dann auch dieses Datumsfeld mit der Auswahl gefüllt und das Zeit-Dropdown angezeigt werden.
Ist das ungefähr verständlich?

**Comment by markus-mw** [comment]
@farbschein: Bin mir nicht 100%-ig sicher, ob es jetzt so ist, wie du es dir vorstellst, aber teste bitte mal den Branch feature/issue-155.

**Comment by farbschein** [comment]
@markus-mw : Kann leider in dieser Hinsicht gar keine Veränderung sehen. Ich glaub ich muss dir das mal live zeigen ;-)

**Comment by markus-mw** [comment]
@farbschein : Achso, wahrscheinlich müsstest du nochmal den grunt laufen lassen, nachdem du den branch feature/issue-155 ausgecheckt hast. Hilft das?

**Comment by farbschein** [comment]
@markus-mw hab npm install und dann grunt laufen lassen. Leider keine Änderung.
Also, Ziel wäre, das dieser untere Block (mit Abhol- und Bringdatum) schon im initialen Zustand des Kalenders sichtbar ist, also ohne das Nutzer irgendwas geklickt hat. 
Zunächst nur mit den Platzhaltern
Abholung: (Bitte wählen)
Rückabe: (Bitte wählen)
Wenn Nutzer dann erstes Datumsfeld wählt, soll dieses Datum dynamisch in dieser Textbox aktualisiert werden.

![image](https://user-images.githubusercontent.com/12683634/98871352-0e9ee500-2475-11eb-9542-ed3ee1405d7a.png)

**Comment by markus-mw** [comment]
@farbschein : Ich glaub jetzt haben wirs...

**Comment by farbschein** [comment]
@markus-mw : yes, yes!! das issses :-)
