### ISSUE TITLE
Stundenweise Buchung: Bestätigungsseite lädt nicht

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#156]
Buchungsbestätigungs-Seite wird nicht geladen, Buchung bleibt unconfirmed: https://lastenrad.asta.ms/?cb_timeframe-custom-fields_wpnonce=5f41abf782&location-id=17&item-id=14&type=6&post_type=cb_timeframe&post_status=unconfirmed&repetition-start=1600678800&repetition-end=1600682399

**Comment by markus-mw** [comment]
@hanneskasimir : Mit welchem Nutzertypen hast du versucht die Buchung zu bestätigen? Kannst du es mit bitte dem aktuellen master-Stand nochmal versuchen?
