### ISSUE TITLE
Stundenweise Buchung: Mehrere Fehler, ggf. in Zusammenhang mit #156:

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#158]
- Unvollständige Buchungen aus #156 mit Status "unconfirmed" sind im Frontend teilweise weiter buchbar im Dropdown, Kalender zeigt aber teilweise die halbrot markierte Fläche
- Teilweise sind eigentlich freie Buchungsfenster am selben Tag nicht buchbar, d.h. nicht im Dropdown
- Wann welche Variante auftritt, konnte ich nicht nachstellen, ggf. erstmal #156 abwarten?

**Comment by markus-mw** [comment]
@hanneskasimir : Lösch bitte die "defekten" Buchungen noch einmal und versuche es noch einmal mit dem aktuellen Master-Stand. Danke!
