### ISSUE TITLE
Buchungscodes nicht für Vergangenheit generieren

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1602]
Bei der Erstellung von Buchungscodes für Zeitrahmen, die vorher keine hatten aber buchbar waren werden noch rückwirkend Buchungscodes erstellt. In Zukunft sollen Buchungscodes immer nur vom ausgehenden Datum aus erstellt werden.

**Comment by nelarsen** [comment]
Ich bin dran, fast fertig. Ich habe ein bisschen mit den Tests gekämpft, aber nun laufen sie. Ich muss noch "aufräumen". Wenn ich es nicht morgen schaffe mache ich einen PR nächste woche.

**Comment by hansmorb** [comment]
@nelarsen Tausend Dank und kein Stress. Ich muss mich auch nochmal mit Christian absprechen was einige Features von 2.10 angeht.
