### ISSUE TITLE
Workflows die beim ersten Mal fehlschlagen erneut versuchen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#1643]
Wir haben einige Schritte in den Workflows die "moody" sind. Das heißt oft muss der Workflow manuell neu-gestartet werden, beim zweiten Mal klappt es dann. Deshalb sollte ein zusätzlicher Workflow die Workflows überwachen und bei Bedarf max 3x neu starten. Erst danach wird der Workflow als "fehlgeschlagen" angesehen.

**Comment by hansmorb** [comment]
Im Master eingebracht & getestet

**Comment by datengraben** [comment]
@hansmorb hatten wir nicht mal das Problem, dass wir ein Limit des Github-Free-Tiers überschritten haben. Ich glaube sowas wie CPU-Sekunden unserer Github-Workflows ... Fällt mir gerade nur ein, auch wenn es aktuell nicht akut ist (glaube ich).

**Comment by hansmorb** [comment]
Ne, ich glaube das war mit Travis das Problem. GitHub actions hat soweit ich weiß für Public repos kein Limit.
