### ISSUE TITLE
Fehlermeldung auf Zeitrahmen-Liste (eingeloggt als cb_manager

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#166]

**Comment by hanneskasimir** [comment]
![grafik](https://user-images.githubusercontent.com/28141760/93216698-569cd680-f768-11ea-8581-4baa16fe7c12.png)

**Comment by markus-mw** [comment]
@hanneskasimir , @farbschein : Der Fehler resultierte aus falsch erzeugten Bookings aus #166. Ich habe eine ergänzende Prüfung eingebaut. (in master)
