### ISSUE TITLE
Fehler bei Buchung wenn nicht Admin

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#167]
gilt für Nutzerrolle cb_manager und abonnent, nicht für Admins

**Comment by hanneskasimir** [comment]
![grafik](https://user-images.githubusercontent.com/28141760/93217473-679a1780-f769-11ea-9b99-13737f44518a.png)

**Comment by farbschein** [comment]
konnte ich bei mir auch nachvollziehen. @markus-mw  hast du ne Idee?

**Comment by markus-mw** [comment]
@farbschein : Ist im Master-Branch behoben.
