### ISSUE TITLE
Backend: Validierung bookable timframes

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#174]
Beim speichern eines Timeframes vom Typ "bookable" sollen folgende Prüfungen erfolgen, um fehlerhafte Kombinationen von sich überlagernden bookable Timeframes abzufangen.

1. Prüfen, ob in dem gewählten Zeitraum ein weiterer bookable Timeframe für die Kombination Location/Item existiert.

2. wenn ja, Prüfen, ob die bereites existierenden bookable Timemframes das gleiche Buchungsraster haben. Wenn nein, dann Fehlermeldung ausgeben mit Hinweis, dass sich überlagernde Bookable Timeframes nur das gleiche Raster haben dürfen + timeframe nicht speichern bzw. nur als Entwurf anlegen und ein Publizieren verhinden.

3. wenn 1 = ja, prüfen, ob sich überlagernde Timeframes an einem Tag überlagernde Zeiträume haben. Falls ja, Fehlermeldung mit Hinweis, dass Zeiträume sich nicht überlagern dürfen. Speichern bzw. Publizieren verhindern.

**Comment by markus-mw** [comment]
@farbschein : Ist im master-Branch umgesetzt und kann getestet werden. (die Übersetzungen müssen noch gepflegt werden, hab erstmal nur die deutschen Texte eingebaut)

**Comment by farbschein** [comment]
Tests:
1. fullday / gleicher Zeitraum => fehlermeldung Korrekt (nicht überlappende Zeiträume)
2. stundenweise / gleicher Zeitraum / überlappende Zeiten: Fehlermeldung korrekt (nicht überlappende Zeiten am gleichen Tag)
3. stundenweise / gleicher Zeitraum / nicht überlappende Zeiten: FALSCHE Fehlermeldung (gleiche wie bei Nr. 2)

Ergebnis:
Die Prüfung bei sich überlappenden Zeiträumen, die nicht vom Typ fullday sind, soll nicht zu einer Fehlermeldung führen, wenn die Zeiten sich nicht überlappen. Im Test war T1 = 09:00 - 14:00 Uhr, T2 = 18:00 - 20:00 Uhr.

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben.
