### ISSUE TITLE
Backend:timeframe-editor: administrator sieht nicht alle locations/items

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#191]
Wenn einem Item oder Location mindestens ein Admin zugeordnet wurde, können nur noch diese Nutzer die jeweiligen Elemente im Timeframe-Editor auswählen.
Nutzer mit der wordpress-Rolle administrator können nur noch Items oder Locations wählen, die keinem cb_manager zugeordnet wurden.

Erwartet:
Nutzer mit der Rolle administrator sollen ungeachtet der Zuweisung alle Locations und Items bearbeiten und auswählen dürfen.

**Comment by farbschein** [comment]
hotfix in bugfix/issue-#191 / bitte nochmal prüfen und optimieren.

**Comment by markus-mw** [comment]
@farbschein : Das kann ich nicht reproduzieren. Bei dir sieht der Admin locations/items nicht mehr, wenn z.B. ein cb-manager zugewiesen ist?

**Comment by farbschein** [comment]
@markus-mw Ja, der Admin konnte die Items/Locations im timeframe-Editor nicht mehr auswählen. Hast du mit aktualisiertem Master inklusive meines Hotfixes getestet? siehe branch bugfix/issue-#191

**Comment by markus-mw** [comment]
Ja, wenn ich irgendwas teste, dann immer mit dem aktuellen master.
