### ISSUE TITLE
als cb-Manager: Widerspruch von Anzahl alle Artikel (7) und keine Artikel gefunden.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#196]
Ziel müsste sein: Alle ARtikel werden angezeigt. Wo keine Rechte: kein Bearbeiten und Löschen möglich.
![signal-2020-10-02-200828](https://user-images.githubusercontent.com/28141760/94957084-79abe200-04ed-11eb-84fb-2b7aed6c0d10.png)

**Comment by farbschein** [comment]
kann ich reproduzieren.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Ich habe ehrlich gesagt keinen Schimmer, warum das nicht funktioniert.
@chriwen : Du hast gesagt, dass es bei dir auch lokal nicht geht. Welche Plugins hast du installiert und welche davon finden sich auch auf Stage?

**Comment by chriwen** [comment]
@markus-mw Ich hab das hier gerade im Log gefunden. Vielleicht ein Ansatz:
Uncaught Error: Call to a member function add_cap() on null
cb-dev/stage1/wp-content/plugins/commonsbooking/src/Plugin.php Zeile 178
Backtrace
#0 cb-dev/stage1/wp-content/plugins/commonsbooking/src/Plugin.php(104): CommonsBooking\Plugin::addRoleCaps('cb_item')
#1 cb-dev/stage1/wp-includes/class-wp-hook.php(292): CommonsBooking\Plugin::activation(false)
#2 cb-dev/stage1/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 cb-dev/stage1/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 cb-dev/stage1/wp-admin/includes/plugin.php(701): do_action('activate_common...', false)
#5 cb-dev/stage1/wp-admin/plugins.php(58): activate_plugin('commonsbooking/...', 'https://stage1....', false)
#6 {main}

**Comment by markus-mw** [comment]
@chriwen : Das war nur von meinem Missgeschick wegen der Rollen. Ich hab jetzt das Problem gefunden: Das Ultimate User Plugin verhindert, dass der Adminbereich gesehen werden kann...

**Comment by chriwen** [comment]
@markus-mw aargh. Und ich hatte die Tage dazu sogar nochn FAQ-Eintrag geschrieben, weil mich ein Nutzer darauf aufmerksam gemacht hat. https://support.commonsbooking.org/knowledgebase.php?article=5
Leider in dem Moment die Dinge nicht zusammenkombiniert...
Danke fürs Rausfinden!
