### ISSUE TITLE
Performance Kalender-Rendering optimieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#198]
Rendern des Kalenders dauert teilweise recht lange (3-4 Sekunden):

![image](https://user-images.githubusercontent.com/12683634/94994154-280b6200-0596-11eb-8dcc-292efa15b10e.png)

Wenn möglich bitte beschleunigen.

**Comment by markus-mw** [comment]
Probier mal obs jetzt schneller läuft (zumindest ab dem zweiten Aufruf). Hab ein Caching in die Repos gebaut. Abfragen werden solange gespeichert, bis was an den Posts geändert wird.

**Comment by farbschein** [comment]
@markus-mw Habs auch mal aufm Dev-Webserver getestet. Minimal besser, aber auch nach mehrmaligen Aufruf immer noch sichtbare Verzögerung. Siehe hier: https://drive.google.com/file/d/1qqDdOahHaesLFgpwcPjExfJxVBMinlYv/view
Hast du noch ne andere Idee zur Optimierung? Kann man noch was an den Abfragen optimieren? Vielleicht nur einen begrenzten Zeitraum vorausladen. Wir brauchen ja immer nur 2 Monate im Voraus. Vielleicht kann man da noch was machen?

**Comment by markus-mw** [comment]
@farbschein : Jetzt müsste es besser laufen. Da war noch ein Bug, der dazu geführt hat, dass die Timeframe-Suchen nicht gecached wurden.

**Comment by farbschein** [comment]
@markus-mw Danke. Ist jetzt besser. Komme hier lokal auf ca. 1 Sekunden TTFB. Lassen wir jetzt erstmal so, ich würd  aber nochmal ein Ticket ins Backlog stellen, da man das rendern des Kalenders schon auch optisch noch wahrnimmt.
