### ISSUE TITLE
Booking Menüpunkt

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#200]
im Backend soll ein Menüpunkt "Buchungen" hinzugefügt werden.
Dieser soll dann alle Timeframes vom Typ "Booking" und "Booking closed" enthalten.

Die Liste soll folgende Spalten enthalten:
itte folgende Spalten einfügen

 Titel (verlinkt zur Detailansicht)
 Artikel-Name
 Buchungs-Start
 Buchungs-Ende
 Buchungs-Code
 Nutzer*in, die gebucht hat (verlinkt zur Backend-Profilseite)
 Standort-Name
 Buchungszeitpunkt
 Buchungs-Status (pending, confirmed, canceled)
Bitte Filter für:

 Artikel-Name
 Standort-Name
 Buchungs-Status

**Comment by danielappelt** [comment]
@chriwen, der kann meiner Ansicht nach geschlossen werden. Fehlende Felder lassen sich im Backend ggf. über existierende Standard-WP-Hooks ergänzen.
