### ISSUE TITLE
Unconfirmed bookings nach 10 Minuten löschen

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#201]
unbestätigte Buchungen sollen 10 Minuten nach der Erstellzeit gelöscht werden.

**Comment by markus-mw** [comment]
@farbschein : Ist umgesetzt. Die Wordpress Cronjobs sind aber keine genaue Wissenschaft. Das kann auch mal ein paar Minuten mehr dauern.

**Comment by hanneskasimir** [comment]
klappt bei mir noch nicht.
![Bildschirmfoto 2020-12-04 um 13 59 46](https://user-images.githubusercontent.com/28141760/101166857-4266c800-3639-11eb-86c4-a130510be6b7.png)

**Comment by hanneskasimir** [comment]
Läuft, allerdings dauert es deutlich mehr als 10 Minuten. Nach 1h war noch nix passiert bei 2 Tests auf 2 Systemen. Nach 3 Stunden waren die Buchungen weg.

**Comment by markus-mw** [comment]
@hanneskasimir : Ja, das verhält sich eigenartig, aber ich habe aktuell keine Idee woran das liegt. Ich würde aber Mal behaupten, dass das am Ende nicht kriegsentscheidend ist, solange die zumindest täglich gesäubert werden, oder?

**Comment by farbschein** [comment]
@markus-mw @hanneskasimir : Ja, da erstmal bitte keine weitere Energie reinstecken. Solange das nicht unkontrolliert volläuft ist es erstmal ok.

**Comment by farbschein** [comment]
@hanneskasimir Danke fürs ausführliche Testen!!
