### ISSUE TITLE
Migrationskonzept CB1 -> CB2 entwickeln

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#203]
Migrationskonzept und Datenmapping siehe:
https://miro.com/app/board/o9J_kxXD9Fk=/?moveToWidget=3074457350733903047&cot=12

- [x] Items
- [x] Locations
- [x] Bookings
- [x] Timeframes

**Comment by farbschein** [comment]
@markus-mw Migrationskonzept skizziert. Bitte mal prüfen und bei Fragen besprechen wir uns kurz.

**Comment by markus-mw** [comment]
@farbschein : Funktional hab ich das fertig. Die Frage ist, wie soll das getriggert werden?

**Comment by farbschein** [comment]
Super. Ich schau’s mir heute Abend an. Gut wäre, wenn das als Tab in den Einstellungen verortet wäre. Dort ein Button ‚Migration von CB1 ausführen‘ und dann ne Rückmeldung über Erfolg oder Fehlermeldungen. Ginge das?

**Comment by markus-mw** [comment]
Ich habe die Migration jetzt bei den Einstellungen in einem Tab verortet. (Branch feature/issue-203)

Eine Anmerkung bzgl. des Ablaufs:
Damit beide Plugins parallel aktiv sein können, muss zuerst das CB1 Modul aktiviert werden, weil dort eine Prüfung auf die Existenz einer Funktion fehlt, was ansonsten zu einem Fehler führt.

**Comment by farbschein** [comment]
@markus-mw : Perfekt. Kannst du mir sagen, welche Prüfung da fehlt? Vielleicht kann Flo die noch als Update in die CB1 implementieren. Das Problem hatte ich hier beim testen auch schon festgestellt. Das wär natürlich super, wenn sich das lösen ließe.

**Comment by markus-mw** [comment]
Du hast es schon in Ticket #216 beschrieben. Wenn die Funktion umbenannt werden würde, wäre das in der Tat am sichersten.
