### ISSUE TITLE
backend: timeframe list -> location filter falsch

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#209]
Backen-Timemframe-Liste:
- Dropdown des "Location-Filters" zeigt items statt locations an.

Vielleicht irgendwie im Zusammenhang mit BookablePost, Zeile 170 ->  Plugin::setCacheItem($posts)?

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben. Ich hatte außerdem noch eine Eingebung bzgl. der Performance des Kalenders. Schau da auch bitte nochmal nach. Danke!
