### ISSUE TITLE
Buchungscodes implementieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#212]
Grundsätzliches Buchungscodes-Konzept:
Es sollen zwei Arten von Buchungscodes generiert werden:
1. Vorgenerierte Buchungscodes
2. Buchungscodes, die erst bei der Buchung automatisch generiert werden 

In dieser Story wird nur Variante 1 beschrieben. Variante 2 soll in einem späteren Release implementiert werden - und folgt einer anderen Logik.

Szenario aus Anwendendensicht:

- Wenn im Timeframe-Editor ein timframe mit den Werten Typ = Bookable, fullday = on, Start- UND Enddatum sind gesetzt angelegt ist, soll ein zusätzlicher Button (oder Checkbox) "Buchungscodes generieren" angezeigt werden. Idealerweise sollte der Button dynamisch erscheinen, sobald die oben genanten Bedingungen erfüllt sind. Sollte das zu aufwändig sein, könnte ein Workaround sein, zuerst den Datensatz speichern zu lassen und anschließen den Button "Buchungscodes generieren" einzublenden.

- Nach Klick auf den Button wird für jeden Tag des Buchungsfensters ein Code generiert und mit Item / Location verknüpft.
- Die generierten Codes speisen sich aus einem Code-Vorrat der als einzelnes Textarea-Feld in den Plugin-Einstellungen durch kommaseparierte Werte befüllt werden kann. (-> neuer Options-Tab "Buchungscodes")
- Die generierten Codes werden als Liste im Timeframe-Editor angezeigt mit den Spalten: Item / Startdatum / Code
- Die Liste kann über einen Button/Link als Excel-Datei/CSV heruntergeladen werden. 

- Bei einer Buchung wird geprüft, ob der Start-Tag der Buchung aus einem Timeframe mit den o.g. Bedingungen erzeugt wurde. In diesem Fall wird der Buchungscodes dieses Tages dem Buchenden auf der Buchungsbestätigungs-Seite angezeigt und in der E-Mail angezeigt. Der Buchungscode sollte dazu als postmeta-Feld (_cb_bookingcode) dem Timeframe der Buchung hinzugefügt werden, sodass er auch später noch eindeutig einer Buchung zugewiesen werden kann.

Technische Ansätze / Ausnahmefälle:
-----------------------------
- Die Buchungscodes sollen in einer separaten Tabelle gespeichert (cb_bookingcodes) werden und enthalten eine Referenz auf die Timeframe-ID, Location, Item, Tag
- Werden an einem Timeframe mit bereits generierten Codes Änderungen an einem der o.g. Werte (Typ, Fullday, Start/End-Datum) vorgenommen, sollen die bereits generierten Codes grundsätzlich nicht gelöscht werden. 
- Bei einer Erweiterung des Datumsbereich sollen lediglich die zusätzlichen Tage mit neuen Codes ergänzt werden. 
- Wenn ein Timeframe gelöscht wird, sollen auch die damit verbundenen Codes gelöscht werden.
- Wenn der Code-Vorrat für die Generierung eines Zeitrahmens nicht ausreichend, sollen Codes mehrfach zugewiesen werden.

**Comment by markus-mw** [comment]
@farbschein : Ich habe die Generierung sowie die Ausgabe im Timeframe umgesetzt. Der CSV Download und die Ausgabe im Frontend kommt noch. Der Zwischenstand ist in feature/issue-212. Kannst ja schonmal testen.

**Comment by farbschein** [comment]
@markus-mw : Hey, super. Das ging ja flott :-). Vielen Dank. Schaut gut aus beim ersten Durchtesten.

**Comment by farbschein** [comment]
@markus-mw : Könnten wir für die Ausgabe eine Methode im Model oder View erstellen, auf die man dann per Parameter (Datum, Location, Item) den passenden Code abrufen kann? Dann könnte ich das z.B. auch für die Ausgabe in den Mail-Templates verwenden.

**Comment by markus-mw** [comment]
@farbschein : Klar kein, Problem.

**Comment by farbschein** [comment]
@farbschein : Kleine Anpassung. Da du die Codes ja in einer separaten Tabelle speicherst, sollte im timeframe die Referenz ja besser auf die ID des booking codes verweisen, oder? also in den postmeta cb_bookingcode dann die ID stehen. Dazu vielleicht das Feld auch umbenennen in _cb_bookingcode_id?
-> und wenn du eh dabei bist, gibt es noch folgendes issue im Zusammenhang mit den Codes: #221

**Comment by markus-mw** [comment]
@farbschein : Jetzt ist bis auf die Sache mit der Mail alles umgesetzt. Bitte füge du das ein, wo du es benötigst. Die nötige Funktion getBookingCode ist am Booking vorhanden.

**Comment by farbschein** [comment]
@markus-mw : Erhalte beim Speichern mit aktiviertem "create codes" folgenden Fehler:
Notice: Undefined offset: 316 in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Repository/BookingCodes.php on line 156

![image](https://user-images.githubusercontent.com/12683634/97810425-00cab200-1c74-11eb-91b3-af144ac3abfb.png)

**Comment by markus-mw** [comment]
@farbschein : Ahhh ja, da hatte ich noch eine zusätzliche Varianz reinbringen wollen, die aber was zerschießt. Bringe ich in Ordnung...

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben. Ich habe gerade nur noch festgestellt, dass die Codeerzeugung noch nicht die Wochentage berücksichtigt und ich aktuell stumpf vom Start- bis zum Endtag Codes erzeuge. Das bringe ich noch in Ordnung.

**Comment by markus-mw** [comment]
@farbschein : Das Problem mit den Wochentagen ist behoben. Wenn man jedoch die Tage ändert, werden aber nach wie vor vorhandene Codes nicht gelöscht!
