### ISSUE TITLE
Timeframe-Editor: Zeitauswahl verschwindet bei einmaligen Ereignissen

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#213]
Timeframe-Editor:
Zeitrahmen Typ: Bookable
Zeitrahmenwiederholung: keine Wiederholung

Wechsel der Checkbox "Ganztägig" lässt die Felder für Uhrzeit verschwinden.
Felder erscheinen erst wieder, wenn Zeitrahmenwiederholung auf einen der anderen Werte gesetzt wurde.

Siehe Screencast:
https://drive.google.com/file/d/1YoODaRjdbDgLLciToT5huPkT2fcb0d6L/view

**Comment by markus-mw** [comment]
Ist korrigiert. (master-Branch)

**Comment by farbschein** [comment]
@markus-mw : In einer bestimmten Konstellation geht es, aber leider nicht immer. Siehe hier: https://drive.google.com/file/d/1_urBd7QA1DDaCWNoUl7i1dt6y3CvZa9Y/view

**Comment by markus-mw** [comment]
@farbschein : Ich bekomme das nicht reproduziert. @hanneskasimir : Hast du das gleiche Problem?
