### ISSUE TITLE
Frontend/Kalender: Buchungszeitraum in Vergangenheit möglich

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#214]
Es ist möglich den Buchungszeitraum vor dem aktuellen Datum auszuwählen. 

Gewünscht: 
Alle Tage vor dem aktuellen Tag sollen als nicht Buchbar markiert und nicht auswählbar sein.

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben.
