### ISSUE TITLE
Fehlermeldung bei Zeitrahmen-Überlappung obwohl gar keine Überlappung da ist.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#219]
Keine Überlappung. Trotzdem kommt die Fehlermeldung
![grafik](https://user-images.githubusercontent.com/28141760/97689722-4b91d180-1a9c-11eb-9716-df34bd9625c2.png)
![grafik](https://user-images.githubusercontent.com/28141760/97689757-59475700-1a9c-11eb-9d1e-14b3e60debda.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Kannst du das bitte noch einmal testen? Jetzt sollte es funktionieren.
