### ISSUE TITLE
Migration: Booking-Codes migrieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#221]
Bei der Migration von CB1 sollen zu Buchungen die dort verknüpften Buchungscodes mit übernommen werden und die ID des Booking-Codes (Referenz zum Code in der cb_bookingcodes) als postmeta-Feld 'cb_bookingcode_id" an den Bookings-Timeframe geschrieben werden. 

- [x] Codes übernehmen
- [x] IDs an Bookings schreiben

**Comment by markus-mw** [comment]
@farbschein , @hanneskasimir : Hilfreicher wäre doch wahrscheinlich der eigentliche Buchungscode, oder? Den könnte ich dann in das gleiche Feld schreiben, wie auch die CB2 Codes.

**Comment by farbschein** [comment]
@markus-mw ja, völlig korrekt. Bitte den Code direkt reinschreiben

**Comment by markus-mw** [comment]
@farbschein : Ist umgesetzt. Ich habe auch das passende Ausgabefeld in den den Buchungsposts ergänzt, damit man sehen kann, was für ein Buchungscode verwendet wird/wurde. Das Feld ist nicht anpassbar, damit da nichts durcheinander gebracht werden kann.
