### ISSUE TITLE
Frontend: Karte auf Artikelseite einfügen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#222]
![grafik](https://user-images.githubusercontent.com/28141760/97719495-6ded1480-1ac7-11eb-9bbd-86549c9e59a2.png)

**Comment by farbschein** [comment]
@hanneskasimir : Nicht lieber nen Link zu Google Maps oder OSM wie auf der alten Seite? Zerhaut uns sonst bestimmt wieder das Layout.

**Comment by hanneskasimir** [comment]
@farbschein: hm, keine Ahnung, das Frontend-Thema bleibt für mich nicht einschätzbar. Lass uns das mal grundsätzlich im Januar angehen.

**Comment by hanneskasimir** [comment]
@chriwen : Heute hab ich auf der Artikelseite kein Indizi, wo die Station sich befindet außer der PLZ und wer kennt schon Postleitzahlen?
Ich nehme gerne deinen Vorschlag auf, lass uns "Auf Karte anzeigen" ergänzen und diesen Text sowie den Stationsnamen mit der Stationsseite verlinken und dort die Karte einbinden! vom Ausschnitt genauso wie im Stationsseiten-Backend. OK?

**Comment by markus-mw** [comment]
@chriwen : Das ist in release/2.5-RC drin
