### ISSUE TITLE
Migration: Kategorien mitmigrieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#224]
Bei der Migration sollen auch die Kategorien, die mit den jeweiligen Artikeln und Standorten verknüpft sind migriert und die Verknüpfung erhalten bleiben.

Hinweis:
- Ich hatte im neuen CB einen Kategorie-Baum für den CPT items angelegt, sodass diese Kategorien dann nur für die items zur Verfügung stehen.

Definition der CPT-Kategorien fürs Item ist in Plugin.php, Zeile: 288

Müsste dann noch um location erweitert werden.

**Comment by markus-mw** [comment]
@farbschein : In CB1 gabs die Kategorien aber nur für Items, oder? Für die Locations konnte ich da soweit nichts sehen.

**Comment by hanneskasimir** [comment]
Hat bei mir (ASTA)  leider nicht funktioniert.
![Bildschirmfoto 2020-11-13 um 13 50 37](https://user-images.githubusercontent.com/28141760/99074011-48780480-25b7-11eb-9409-63cec6a59508.png)
![Bildschirmfoto 2020-11-13 um 13 50 30](https://user-images.githubusercontent.com/28141760/99074013-4b72f500-25b7-11eb-996e-c2a24600f6cd.png)

**Comment by farbschein** [comment]
@hanneskasimir : Das war wohl noch nicht umgesetzt, wie ich Markus letztem Kommentar entnehme.

**Comment by farbschein** [comment]
@markus-mw : Das geht in Ordnung. Die taxonomies werden derzeit in Plugin, Zeile 307 für Items und Locations definiert. Du kannst das gerne anpassen.

**Comment by markus-mw** [comment]
@farbschein : Die Migration für die Taxonomies ist jetzt auch drin. Bitte beachtet, dass die Kategorien nicht korrekt dargestellt werden, wenn beide Plugins gleichzeitig aktiviert sind. In diesem Fall überschreiben sich die Taxonomies. Wenn dann nur ein Plugin aktiv ist, passt es.

**Comment by farbschein** [comment]
@markus-mw Erhalte beim Migrieren folgenden Fehler:
Fatal error: Uncaught Error: Call to undefined method CommonsBooking\Repository\CB1::getCB2PostIdByCB1Id() in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Migration/Migration.php:370 Stack trace: #0 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Migration/Migration.php(70): CommonsBooking\Migration\Migration::migrateTaxonomy(Object(stdClass)) #1 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/View/Migration.php(30): CommonsBooking\Migration\Migration::migrateAll() #2 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2_Base.php(315): CommonsBooking\View\Migration::renderMigrationForm(Array, Object(CMB2_Field), NULL) #3 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2_Base.php(273): CMB2_Base->do_callback(Array) #4 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/cmb2/cmb2/includes/CMB2_Base.php(249): CMB2_Base->get_param_callback_result('render_ in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Migration/Migration.php on line 370

**Comment by markus-mw** [comment]
@farbschein : Ist behoben, da ist beim mergen was rausgefallen.
