### ISSUE TITLE
Frontend: Item-Liste

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#226]
Doppelte Anzeige sich überschneidender Timeframes + Abgelaufene Timeframes nicht mehr anzeigen.

- [x] Abgelaufene Timeframes nicht anzeigen
- [x] Überschneidende Timeframes zusammenfassen

**Comment by markus-mw** [comment]
@farbschein: Abgelaufene Timeframes werden nicht mehr angezeigt und die Dopplung von Items/Locations im Listing ist raus. Stattdessen wird jedes Element nur einmal angezeigt und das Start/Enddatum global für alle vorhandenen Timeframes ausgegeben.
