### ISSUE TITLE
REST-API: Availability - Buchung eines Items beeinflusst Verfügbarkeit eines anderen Items an einem anderen Standort

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#227]
**Beschreibung**
betrifft API-Endpunkt: /commonsbooking/v1/items
Buchung von Item B and Standort Y führt zu Nicht-Verfügbarkeit (fehlende availability) von Item A an Standort X im Zeitraum der Buchung.

**Reproduzierbarkeit**
1. Erstelle einen Zeitrahmen vom Typ "buchbar" für Item A and Standort X.
2. Erstelle eine Buchung für Item B an Standort Y, die innerhalb des in 1. erstellten Zeitrahmens liegt.
3. Verifiziere "availability" für Item A an Standort X -> Verfügbarkeit innerhalb des Buchungszeitraums von Item B ist nicht gegeben.

**erwartetes Verhalten**
Buchung von Item B an Standort Y hat keinen Einfluss auf Verfügbarkeit von Item A an Standort X.

**Ergänzung**
Der API-Endpunkt /commonsbooking/v1/availability/[itemId von A] gibt die Verfügbarkeit korrekt aus.

**getestete Version**
https://github.com/wielebenwir/commonsbooking/commit/7f2d216ff9f3176ab36227caf070dcbeb99acf92

**Comment by markus-mw** [comment]
@poilu : Das Problem ist behoben und in den master gemerged. Schau mal bitte, obs jetzt passt.

**Comment by poilu** [comment]
@markus-mw : Ja, sieht gut aus für mich. :+1:
