### ISSUE TITLE
Frontend/timeframe-calendar.php: Javascript Bug

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#244]

**Comment by farbschein** [comment]
In der Listenansicht von Items wird folgender Javascript-Fehler ausgegeben:
 
![image](https://user-images.githubusercontent.com/12683634/98363309-0c7cf680-202f-11eb-8726-a30b75722c57.png)

In der timeframe-template.php ab Zeile 6 scheint da was nicht korrekt zu sein.
<? -> Php fehlt
und "let data" -> ist das korrekt so?

**Comment by markus-mw** [comment]
@farbschein: Hast du den aktuellen master ausgecheckt? Bei mir ist die Stelle mit php, der Rest ist so in Ordnung.

**Comment by markus-mw** [comment]
Seh grad, dass du es selbst ergänzt hast ;)

**Comment by farbschein** [comment]
@markus-mw : Ja, hatte den PHP-Teil ergänzt, war mir aber mit dem "let data" nicht so klar, ob das nicht template_data oder so heißen sollte? Wenn das aber so korrekt ist, dann ist ja alles ok.
