### ISSUE TITLE
Migration: Geschlossene Tage migrieren

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#246]
Neues Vorgehen:
- in Timeframe-Editor zwei neue Optionen: 
- [x]  nicht ausgewählt Tage an denen kein anderer Timeframe definiert wird, können überbucht werden. (Checkbox)

weitere Anpassungen:
- [x]  zu überbuchende nicht definierten Tage zählen als 1 gebuchter Tag.
- [x]  Anpassungen an litepicker, um Tage korrekt zu zählen. 
- [x]  beim Import müssen diese Konfigurationsfelder aus CB1 ausgelesen und entsprechend gesetzt werden (for="commons-booking_bookingsettings_allowclosed")

**Comment by markus-mw** [comment]
@hanneskasimir : Das ließe sich auch einfacher lösen, wenn wir sagen, dass man generell über nicht gebuchte (auch nicht teilweise) Tage hinweg buchen kann. Dann müssten nur die passenden Tage migriert werden und wir hätten nicht mehrere Timeframes.

Sowas wäre dann möglich:
![image](https://user-images.githubusercontent.com/22905753/98987546-9d1f6f00-2526-11eb-92c2-832f9726ddff.png)

**Comment by farbschein** [comment]
@markus-mw Nach Abwägung verschiedener Möglichkeiten, sind wir zum Schluss gekommen, dass wir es doch so wie oben beschrieben umsetzen müssen. Ich hab oben die Spezifikation ergänzt, um die Umsetzung hoffentlich zu vereinfachen.

**Comment by markus-mw** [comment]
@farbschein: Hilf mir bitte mal kurz. Was ist die zweite Einstellung, neben der Definition dass undefinierte Tage überbucht werden können?
Sollen die nicht-definierten Tage nur "im Verbund", wenn Sie direkt aufeinander folgen als einer gelten?
Ein Beispiel:
5 Tage sind am Stück wählbar, Di + Do nicht definiert -> wir wählen als Startdatum Montag.

Sollen wir bis Freitag oder Samstag buchen können? Oder soll das nur so sein, wenn die nicht definierten Tage aufeinander folgend sind?

**Comment by markus-mw** [comment]
@farbschein: Wäre es außerdem geschickter die Einstellung der Überbuchbarkeit an der Location/dem Item zu hinterlegen? Ansonsten können wir in das Problem laufen, dass aufeinander folgende Timeframes einmal die Einstellung an und einmal aus haben. Das würde ein ganz schönes Gefrickel werden.

**Comment by farbschein** [comment]
@markus-mw 
- die zweite Einstellung war, dass alle überbuchbaren Tage als 1 Tag gelten (oder Alternativ als 0). Wir hatten uns entschieden das per default auf 1 zu setzen und erstmal nicht vom Nutzer konfigurierbar zu machen. 
- Ja, überbuchbare Tage sollen nur im im Verbund gezählt werden.

**Comment by markus-mw** [comment]
@farbschein: Perfekt, dann ist der Rest schnell erledigt.

**Comment by markus-mw** [comment]
@farbschein : Ist erledigt

**Comment by farbschein** [comment]
@markus-mw : Was noch fehlte war, das die in CB2 definierten Closeddays in den CB2-timeframe auch übernommen werden (also die Wochentage gesetzt und die repitition auf weekly gesetzt) - oder hattest du das in einem anderen Branch gemacht?
Ich hab das mal auf Master in der migrateTimeframe eingefügt. Vielleicht kannst du nochmal nen Blick drauf werden, ob das so ok ist.
