### ISSUE TITLE
Model/CustomPostType: getMeta static or non static?

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#249]
in Model/Booking.php wird die getMeta() über teilweise über self::getMeta und teilweise über $this->getMeta instanziert. 

Siehe z.B.
     * @return Item
     * @throws \Exception
     */
    public function getItem() {
        $itemId = self::getMeta('item-id');

        if($post = get_post($itemId)) {
            return new Item($post);
        }
        return $post;
    }

    /**
     * Returns the booking code.
     * @return mixed
     */
    public function getBookingCode() {
        return self::getMeta(CB_METABOX_PREFIX . 'bookingcode');
    }

Die Funktion ist wohl aber als nicht statisch angelegt?
Seltsamerweise gibt aber   getBookingCode() trotzdem einen Wert zurück. 
Wie geht das? Und was stimmt da evtl. nicht?
Würde das gerne verstehen, da ich eine formatierte Booking-Code ausgabe für die E-Mail-Templates basteln möchte.

**Comment by markus-mw** [comment]
Man sollte sich immer für einen Weg entscheiden. Wenn die Funktion sinnvoll statisch umgesetzt werden und in anderen Klassen verwendet werden kann, sollte man das tun. Macht sie nur im Model-Kontext Sinn, kann man sie auch als statisch deklarieren, aber in beiden fällen muss sich auch statisch aufgerufen werden. Zu einem gewissen Grad "verzeiht" PHP an der Stelle Pfusch, aber wir sollten das aufräumen. Sowas passiert, wenn mehrere an einem Projekt arbeiten und im Zweifel nicht projektweit Änderungen vorgenommen werden.

**Comment by farbschein** [comment]
@mw: Ok, was empfiehlst du hier? Ich hatte weder die getMeta noch die betroffenen Referenzen bearbeitet. Du kannst gerne aufräumen oder mir sagen, welcher Weg der richtige ist.

**Comment by markus-mw** [comment]
@farbschein : Ich räume das auf...

**Comment by markus-mw** [comment]
@farbschein : Ist korrigiert.
