### ISSUE TITLE
Frontend/Kalender: CSS-Anpassungen Litepicker

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#253]
Bitte folgende Anpassungen am Litepicker vornehmen:

1. IsinRange soll gleiche Farbe haben wie Start und Endpunkt:
--litepickerDayIsInRange: #2096f3;

2. Tage sollen einen weißen dünnen Rand bekommen-

**Comment by markus-mw** [comment]
@farbschein : Ist erledigt
