### ISSUE TITLE
Zeitrahmen wurde nicht migriert. Meldung war aber positiv.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#263]
Bei der Migration wurden mehrere Buchungen migriert, nicht aber ein bookable-Timeframe.

![Bildschirmfoto 2020-11-13 um 12 37 18](https://user-images.githubusercontent.com/28141760/99068812-81ab7700-25ad-11eb-8373-0717c2e61ca8.png)
![Bildschirmfoto 2020-11-13 um 12 36 50](https://user-images.githubusercontent.com/28141760/99068819-83753a80-25ad-11eb-92e2-c26294fe11d4.png)
![Bildschirmfoto 2020-11-13 um 12 34 45](https://user-images.githubusercontent.com/28141760/99068825-840dd100-25ad-11eb-8d1e-287ba5d5862c.png)
![Bildschirmfoto 2020-11-13 um 12 34 35](https://user-images.githubusercontent.com/28141760/99068828-84a66780-25ad-11eb-9466-781c6c5ee47c.png)
![Bildschirmfoto 2020-11-13 um 12 42 00](https://user-images.githubusercontent.com/28141760/99068931-a9024400-25ad-11eb-8867-d3c454295626.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Kannst du mir noch einen Screenshot von dem nicht migrierten Timeframe erstellen? Kann das nicht reproduzieren.

**Comment by hanneskasimir** [comment]
Eine Idee: Auf der Instanz hatte ich vor ein paar wochen schonmal die neue Version installiert.Dann dort das Plugin gelöscht, cb1 installiert und dann migriert. hoffentlich hat es damit zu tun?
hier der Screenshot:
![grafik](https://user-images.githubusercontent.com/28141760/99793848-8e8a1680-2b29-11eb-8394-663e93af0ea4.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Hat sich das Problem mit der letzten Anpassung vom Freitag erledigt?
