### ISSUE TITLE
Zeitrahmen-Liste: Bei Sortierung nach Buchungszeitpunkt ist Liste leer.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#264]
![Bildschirmfoto 2020-11-13 um 12 45 19](https://user-images.githubusercontent.com/28141760/99069165-24fc8c00-25ae-11eb-8151-c1725fe8fef2.png)

gilt auch für Buchungsstatus

**Comment by markus-mw** [comment]
@hanneskasimir : Das Problem ist behoben. Bitte testen.
