### ISSUE TITLE
Buchung soll nicht ohne Rückgabe-Datum möglich sein. Das aktuelle Datum wird genommen, wenn keines ausgewählt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#269]
Buchung soll nicht ohne Rückgabe-Datum möglich sein. 
Momentan wird das aktuelle Datum wird genommen, wenn keines ausgewählt.

Gewünschtes Verhalten:
- Button für weiter soll solange inaktiv / hellgrün sein, bis Abhol und Rückgabedaten gewählt wurden.

![Bildschirmfoto 2020-11-13 um 14 06 19](https://user-images.githubusercontent.com/28141760/99075576-fe445280-25b9-11eb-8692-0a1df8d7f426.png)
![Bildschirmfoto 2020-11-13 um 14 05 54](https://user-images.githubusercontent.com/28141760/99075582-000e1600-25ba-11eb-8947-c9ab17aa365e.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Das Problem ist behoben. Bitte teste es noch einmal.
