### ISSUE TITLE
Frontend/Kalender: Linie um Day-Box führt zu 6 Tage pro Woche in der Ansicht.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#270]

**Comment by farbschein** [comment]
Die 1-px Linie um die Tage führt dazu, dass die Kästchen nach 6 Tagen umbrechen und dadurch der Kalender nicht mehr stimmt. Bitte so anpassen, dass die Linie bleibt aber korrekter Umbruch erfolgt.

![image](https://user-images.githubusercontent.com/12683634/99080617-d3f69300-25c1-11eb-8114-96b13321e92f.png)

**Comment by markus-mw** [comment]
@farbschein : Ist korrigiert.

**Comment by farbschein** [comment]
@markus-mw Im Kasimir-Theme sieht das jetzt so aus:
![image](https://user-images.githubusercontent.com/12683634/99689451-4dd9c100-2a87-11eb-8f5c-63b40e1391e8.png)

Im Standard twenty-nineteen so:
![image](https://user-images.githubusercontent.com/12683634/99689558-6c3fbc80-2a87-11eb-828a-e1522cbc298b.png)

auch nach grunt keine Änderung und in anderen Browsern ebenso.
Irgendwie ist alles zu groß geraten. Hast du nen Ansatz?

**Comment by markus-mw** [comment]
So siehts bei mir mit twenty-twenty aus:
![image](https://user-images.githubusercontent.com/22905753/99723300-48de3700-2ab2-11eb-8be9-9a762485d1a7.png)

Ich versuch mal das Kasimir und twenty-nineteen

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben.
