### ISSUE TITLE
Backend/Timeframe-Editor: Fehler bei Validierung der Zeitangaben

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#271]
Prüfung ob Startzeit und Endzeit ausgefüllt sind, soll bei aktiver Checkbox "Ganzer Tag" nicht stattfinden. Alternativ sollen alle Einträge bei Start- und Endzeit gelöscht werden, wenn "Ganzer Tag" ausgewählt ist.

**Comment by farbschein** [comment]
@hanneskasimir : Ich kann das bei mir lokal gerade nicht nachstellen. Wo hattest du das beobachtet? Kannst du nochmal die Schritte beschreiben, wie es zu der Meldung kam?

**Comment by markus-mw** [comment]
@markus-mw : Erst mit Zeit anlegen, dann ändern, dann Problem

**Comment by markus-mw** [comment]
@farbschein : Ich kriegs nicht reproduziert. ;(

**Comment by farbschein** [comment]
@hanneskasimir : ich schließ das mal, kann es auch nicht mehr reproduzieren.
