### ISSUE TITLE
Timeframe-Liste: Timeframes, die aus dem Papierkorb wiederhergestellt werden sind leer.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#272]
Timeframe in Papier legen.
Aus Papierkorb wieder herstellen
Alle Daten bis auf den Titel sind weg.

**Comment by markus-mw** [comment]
@farbschein : Das sollte jetzt funktionieren.

**Comment by farbschein** [comment]
@markus-mw Funktionierte zwischendrin, jetzt mit aktuellem Master nicht mehr. Test auf kasimir.commonsbooking

**Comment by markus-mw** [comment]
@farbschein : Ok, das wiederherstellen löscht offensichtlich auch metadata. Das ist jetzt korrigiert.
