### ISSUE TITLE
Booking.php: Fehler in assignBookableTimeframeFields beim Anlegen einer Buchung

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#273]
Schritte:
- Timeframe bookable mit fullday = on
- Buchung im Frontend. Auf der Buchungsbestätigungsseite wird neben dem Datum auch die Uhrzeit (0:00 - 23:59) angezeigt (bzw. möglicherweise auch jeder andere Zeitwert, der ggf. vorher in diesem Feld gespeichert war)
- Erst nach der Bestätigung der Buchung wird nur noch (wie gewünscht) das Datum angezeigt. Bei ganztägiggen Buchungen sollen keine Uhrzeiten ausgegeben werden.
![screenshot-localhost-8888-cb01-1605390172357](https://user-images.githubusercontent.com/12683634/99157644-135cd680-26cb-11eb-82f8-11b441bb71dd.png)

Auf der Buchungsüberprüfungsseite schlägt die Funktion Booking->pickupDatetime fehl, da für $fullday kein Wert übergeben wurde. 

In der Timeframe.php in Zeile 281 soll ja über die Funktion assignBookableTimeframeFields die fehlenden Metafelder hinzugefügt werden (u.a. auch fullday, grid etc.). Diese Funktion nutzt wiederum $timeframe = $this->getBookableTimeFrame(); was aber in diesem Kontext keinen Wert zurück gibt. Irgendwie müsste an dieser Stelle der korrekte Timeframe gefunden werden, auf dem die Buchung basiert auf Basis der in der URL übergebenen Paramater:

http://localhost:8888/cb01/cb2_item23/cb1-artikel-2/?cb_timeframe-custom-fields_wpnonce=5e7f5b6e08&location-id=1121&item-id=1123&type=6&post_type=cb_timeframe&post_status=unconfirmed&repetition-start=1608422400&repetition-end=1608595199

Hoffe, das hilft, das Problemchen schnell einzugrenzen.

**Comment by markus-mw** [comment]
Bei mir schlägt nix fehl und ich kann das auch nicht reproduzieren. Könnt ihr mal ein "grunt" probieren?
![image](https://user-images.githubusercontent.com/22905753/99313262-8303ca80-285f-11eb-833c-a6d7705f6c74.png)

**Comment by farbschein** [comment]
@markus-mw Das Phänomen scheint tatsächlich nur aufzutreten bei aus CB1 importierten bookable timeframes. Konnte das zumindest so reproduzieren. Hast du nen Ansatz dafür?
In der DB scheinen sich die Timeframes von CB2 gegenüber den von CB1 importierten nur darin zu unterscheiden, dass bei denen von CB1 importen noch die start-time und end-time übergeben werden.

**Comment by markus-mw** [comment]
Ich bekomm das nicht nachgestellt. Die start-time und end-time werden auch bei CB2 Buchungen geschrieben.

![image](https://user-images.githubusercontent.com/22905753/99726454-d02da980-2ab6-11eb-8155-62b51f3bd044.png)
![image](https://user-images.githubusercontent.com/22905753/99726508-d91e7b00-2ab6-11eb-96e1-ad539ae33e9c.png)

**Comment by markus-mw** [comment]
@farbschein : Hab rausgefunden woran es liegt... Der Timeframe hat nicht den post_status publish, wird aber dennoch dargestellt. Bei der Buchungserzeugung klappt das dann aber nicht. Ich korrigiere das.

**Comment by markus-mw** [comment]
@farbschein : Das Problem hatte ich am Freitag behoben. Sollte jetzt funktionieren.

**Comment by farbschein** [comment]
@markus-mw Ja, ist behoben. Danke.

**Comment by farbschein** [comment]
@markus-mw : auf dem kasimir dev tritt der fehler im aktuellen master wieder auf.

**Comment by markus-mw** [comment]
@farbschein : Probiers bitte nochmal. Ich vermute das hing mit dem SQL Bug zusammen.
