### ISSUE TITLE
REST-API: zusätzliche Item-Eigenschaften für Kartendarstellung

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#274]
Folgende zusätzliche Item-Eigenschaften werden für CommonsBooking-Maps benötigt:
- Auszug des Posts (als excerpt, short_description o.ä.)
- Veröffentlichungsstatus des Posts
- URL des Vorschaubildes (v. Artikelbild)

**Comment by christianvoigt** [comment]
Zu Punkt 1 und Punkt 3: Items in der Commons-Api enthalten bereits Felder für description und image, die genau für diesen Zweck vorgesehen sind.

Der Veröffentlichungsstatus ist etwas sehr Wordpress-Spezifisches. Der Gedanke hinter der Commons-Api ist ja, dass beliebige Datenquellen ihre Daten per Api anbieten können. Es wäre also gut, entweder ein Feld zu definieren, was auch für andere Systeme sinnvoll nutzbar ist oder diese Funktionalität mit Wordpress-internen Mitteln zu implementieren. 

Außerdem sollte doch in der Commons Api eigentlich nur das erscheinen, was schon veröffentlicht ist, oder? Ansonsten müßte der Commons Hub ja das Ganze nochmal filtern, was wiederum Wissen darüber voraussetzen würde, aus welchem System die Daten eigentlich stammen (was wir ja gerade vermeiden wollen).

Warum nutzen wir dafür eigentlich nicht die normale Wordpress Rest-Api, die doch alle solche Informationen bereits liefert? Dann hätten wir diesen Konflikt zwischen den verschiedenen Anwendungszwecken der Api nicht.

**Comment by poilu** [comment]
> Zu Punkt 1 und Punkt 3: Items in der Commons-Api enthalten bereits Felder für description und image, die genau für diesen Zweck vorgesehen sind.

Grundsätzlich hab ich nichts dagegen, sich an das Schema der Commons-API zu halten und wir können gern nach Wegen suchen, das umzusetzen, ohne damit zu brechen. Daher hatte ich das auch erstmal als Bedarf formuliert.
Bisher wird unter 'description' der ausführliche Inhalt des Artikel-Posts gerendert. Das ist für die Darstellung im Marker-Popup nicht zielführend, mitunter sehr umfangreich, zumal es einen Artikel-Auszug gibt, der sich dafür eignet.
Die image URL von Items wird bisher gar nicht ausgegeben, erfüllt also in der Hinsicht nicht die [Commons-API](https://github.com/wielebenwir/commons-api/blob/master/commons-api.items.schema.json).

Der Veröffentlichungstatus könnte durchaus über die Wordpress-API kommen. Ein zweiter Request dafür durch das Maps-Plugin wäre sicher verschmerzbar. Die Items müssten dafür vermutlich nur freigegeben werden, wie in diesem [Blog-Artikel](https://scottbolinger.com/custom-post-types-wp-api-v2/) beschrieben. Damit wäre wohl auch auch #276 erledigt.

**Comment by markus-mw** [comment]
@poilu , @christianvoigt : Wärt ihr so nett für mich die Anforderungsessenz abzustimmen? Ich bin grundsätzlich leidenschaftslos.

**Comment by chriwen** [comment]
Wir schließen das Ticket wegen längerer Inaktivität. Ggf. nehmen wir das Thema überarbeitung der Map nochmal separat auf und stimmen uns dann nochmal ab
