### ISSUE TITLE
REST-API: Priorisiere in postmeta gespeicherte Geo-Koordinaten für Locations

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#275]
Wenn die post meta-Felder geo_latitude und geo_longitude für einen Standort hinterlegt sind, priorisiere diese gegenüber den durch den Geo-Provider ermittelten Koordinaten in der Eigenschaft geometry.coordinates für locations.

**Comment by markus-mw** [comment]
@poilu : Das ist jetzt umgesetzt. Probier es doch bitte einmal.

**Comment by poilu** [comment]
@markus-mw: Ja, verhält sich wie erwartet.
