### ISSUE TITLE
REST-API: Kategorien der Items für Kartendarstellung

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#276]
Um in Filter für NutzerInnen zu Verfügung stellen zu können, werden die IDs der den Items zugeordneten Artikel-Kategorien benötigt. Die Ausgabe kann als eindimensionales Array erfolgen.

**Comment by christianvoigt** [comment]
Wenn das als Extra-Api-Route implementiert wird, ist das einfach eine Extra-Route neben den Commons-Api-Routen, so dass sich an den Schemata der Commons Api nichts ändern muss, oder?

Auch hier könnte man aber auch einfach die Wordpress Rest-Api nutzen, oder? (https://developer.wordpress.org/rest-api/reference/categories/)

**Comment by poilu** [comment]
> Auch hier könnte man aber auch einfach die Wordpress Rest-Api nutzen, oder?

Ja über ein posts list wäre das zu machen, wenn die items dafür freigegeben sind, siehe: https://github.com/wielebenwir/commonsbooking/issues/274#issuecomment-733168835

**Comment by markus-mw** [comment]
@poilu , @christianvoigt : Wärt ihr so nett für mich die Anforderungsessenz abzustimmen? Ich bin grundsätzlich leidenschaftslos.

**Comment by chriwen** [comment]
@markus-mw Wenn ich mich einschalten darf ;-) : Bitte gerne so nah wie möglich an der Wordpress-Welt. Wenn das über Wordpress-API geht, würde ich das zumindest konzeptionell befürworten :-)!
