### ISSUE TITLE
Frontend: Nicht veröffentlichte Artikel werden auf der Standort-Liste bei den Stationen angezeigt. Auf der Artikel-Liste werden sich nicht geführt.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#277]
siehe Erläuterung im Kommentar

**Comment by markus-mw** [comment]
@farbschein: Was meinst du mit der Standort-List? Geht's dabei um den shortcode? Welcher Filter wird im Backend nicht korrekt dargestellt?

**Comment by farbschein** [comment]
@markus-mw Das hatte Hannes formuliert .. Ich versuche zu klären:

- Wenn Item Status Entwurf hat, wird dieses Item trotzdem in der Liste der Stationen im Frontend (Shortcode cb_locations) ausgegeben. Items die nicht auf published stehen sollten aber nie im Frontend angezeigt werden.

- Das im Backend ist ein anderes Thema. Da mache ich ein neues Issue draus.

**Comment by farbschein** [comment]
@markus-mw Hab BRanch 277 nochmal gecheckt. Damit ist dieses Issue behoben.

**Comment by markus-mw** [comment]
@farbschein : Habs gemerged.
