### ISSUE TITLE
Date/Timepicker auf deutsch

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#278]

**Comment by markus-mw** [comment]
Welchen meinst du?
![image](https://user-images.githubusercontent.com/22905753/100018641-10559a80-2ddd-11eb-9b36-0fe4519d2b26.png)

**Comment by farbschein** [comment]
@markus-mw Wie hast du das hinbekommen? Bei mir sieht das so aus:
![image](https://user-images.githubusercontent.com/12683634/102548912-9f439300-40bb-11eb-84fc-68d30846e1c5.png)

**Comment by markus-mw** [comment]
@chriwen : Allgemeine Einstellungen -> 
![image](https://user-images.githubusercontent.com/22905753/102999453-4cd5fc80-4529-11eb-8619-1970c4a90a78.png)
