### ISSUE TITLE
REST-API: neuer Endpunkt für Adress-Rückwärtssuche über Geo-Provider (Prio: low)

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#279]
Um in der Kartendarstellung eine Umkreissuche anbieten zu können, wird eine Adress-Auflösung in Geo-Koordinaten benötigt. Um dies über den im Backend verwendeten Geo-Provider ausführen zu können, wird eine API-Endpunkt benötigt, der einen Adress-String entgegennimmt und die entsprechenden Geo-Koordinaten (latitude, longitude) zurück liefert.

**Comment by chriwen** [comment]
Wir schließen das erstmal und nehmen die Themen bei einer Überarbeitung der Karte separat nochmal auf
