### ISSUE TITLE
REST-API: Filtermöglichkeit für Items-Endpunkt

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commonsbooking#280]
Um in der CommonsBooking-Maps-Administration die Funktion zur Verfügung zu stellen, die Items vorzufiltern, die auf einer Karte dargestellt werden, wird eine Möglichkeit benötigt, die durch den API-Endpunkt /commonsbooking/v1/items zurückgegebenen Items durch einen Kategorie-Filter einzuschränken.
Ist kein Filter gesetzt, werden, wie bisher alle Items gerendert. Sind Kategorie-IDs für den Filter (GET-Parameter) angegeben, werden nur die Items ausgegeben, denen mindestens eine dieser Kategorien innerhalb der übergeordneten Kategorien-Gruppe (parent term) zugeordnet ist (UND-Verknüpfung zwischen Kategorien-Gruppen).

**Comment by chriwen** [comment]
Wir schließen das erstmal und nehmen es bei Überareitung der Karte nochmal auf.
