### ISSUE TITLE
REST Api: Small Commons API compatibility issues

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commonsbooking#281]
currently the REST Api data does not validate against the Commons Api Json scheme because of the following reasons:

- missing timezone in availability timestamps (has to be in date-time format: https://docs.opis.io/json-schema/1.x/formats.html)
- locations should implement GeoJSON FeatureCollection (https://blog.codecentric.de/2018/03/geojson-tutorial/)
- remove items/locations arrays in owners object
- convert owner ids to strings (currently are numbers)
- projectId in items data is currently project name instead of id (e.g. "Velogistics" instead of "1")

**Comment by markus-mw** [comment]
@christianvoigt : Timzone isn't essential to have a valid date-time, but if you like I can add one by default.

![image](https://user-images.githubusercontent.com/22905753/100021192-63c9e780-2de1-11eb-84f1-50dc522a032d.png)

**Comment by markus-mw** [comment]
_locations should implement GeoJSON FeatureCollection (https://blog.codecentric.de/2018/03/geojson-tutorial/)_
Done, hopefully how you need it ;)

_remove items/locations arrays in owners object_
Done. I hope this makes no problems in map plugin...

_convert owner ids to strings (currently are numbers)_
Done.

_projectId in items data is currently project name instead of id (e.g. "Velogistics" instead of "1")_
Done. But please note, that there is no logic behind the ID. Its always "1" because there's no unique identifier available (at least I don't know what to take).

**Comment by markus-mw** [comment]
@christianvoigt : Außerdem müsstest du bitte mal die Schemas prüfen. Bei den Locations haben wir mit den Anpassungen jetzt eine Differenz zu https://raw.githubusercontent.com/wielebenwir/commons-api/master/commons-api.locations.schema.json.
Ich hab eine Validierung drin, die gegen die Schemata validiert und aktuell hinfällt.

**Comment by christianvoigt** [comment]
Super, danke! 

**Zur date-time:** Meine Liste bestand ja einfach aus den Fehlermeldungen, die die Validierung im Commons Hub ergeben hat. Der Commons Hub verwendet [ajv](https://github.com/ajv-validator/ajv). Die bisherigen date-times wurden einfach nicht akzeptiert. Nachdem ich die Timezone manuell ergänzt habe, wurden sie akzeptiert. 

Ist natürlich doof, wenn unterschiedliche Validators voneinander abweichen. Das kann aber auch daran liegen, dass wir unterschiedliche Versionen der JSON-Schema Drafts verwenden (ich habe [draft 06](https://json-schema.org/draft-06/json-schema-release-notes.html) verwendet). 

**Zu der Fehlermeldung:** Bist Du sicher, dass das erst jetzt nicht mehr akzeptiert wird? Ich habe ja wie gesagt Euern Testserver ausprobiert und da scheiterte die Validierung auch schon vorher. Hast Du den Testserver geupdated? Momentan zeigt der [hier](https://dev.commonsbooking.org/wp-json/commonsbooking/v1/items) dieselbe Fehlermeldung wie vorher.

Ich glaube eigentlich nicht, dass dieser Fehler an den Schemata selbst liegt. Ich verwende die ja schon länger ohne Probleme im Commons-Hub. Es scheint mir eher, dass der Valditor das Schema nicht findet (oder ein verlinktes Schema, die einzelnen Dateien verweisen ja mit Links aufeinander). Ohne eine aussagekräftigere Fehlermeldung, kann ich dazu aber wenig sagen (gut wäre eine Zeilenangabe an welcher Stelle der JSON-Datei die Validierung gescheitert ist).

In AJV konnte ich die einzelnen Schemata übrigens vom lokalen npm-package vorladen, so dass er die nicht jedesmal wieder von Github abrufen musste. Es könnte sein, dass dadurch ein fehlerhafter Link bei mir keine Auswirkung hatte. Ich denke es wäre aber grundsätzlich gut, wenn CommonsBooking die Schemata auch lokal laden würde.

**Comment by christianvoigt** [comment]
**Zur fake-projectId:** Das ist kein Problem. Das ist nur relevant für Datenquellen, in denen es mehrere Projekte gibt. Bei Commonsbooking-Instanzen wird das nie der Fall sein. In anderen System könnte das aber durchaus der Fall sein. Wenn z.B. der Commons Hub seine Daten selbst wieder über die Commons Api weiterverteilen würde, müßte er zwischen unterschiedlichen Projekten unterscheiden und selbst unterschiedliche projectIds generieren.

**Comment by christianvoigt** [comment]
Hab gerade nochmal die Fehlermeldung angeschaut: Das Problem scheint zu sein, dass die JSON-Datei von Github nicht korrekt in PHP geladen wird (`file_get_contents(https://raw.githubusercontent.com/wielebenwir/commons-api/master/commons-api.items.schema.json): failed to open stream: no suitable wrapper could be found`). Als Folge davon wird dann das Schema auch nicht gefunden.

Ich würde sowieso empfehlen die Schemata per npm zu installieren und dann lokal zu laden (`npm install https://github.com/wielebenwir/commons-api`, habe noch kein package bei npm veröffentlicht).

(Bezieht sich auf die gegenwärtige Version vom Testserver, weiß nicht, ob das noch aktuell ist)

**Comment by markus-mw** [comment]
Das Problem ist ein anderes. Der Server lässt den file_get_contens Befehl einfach nicht zu. Ich schau mal wie ich das anders aufsetze.

**Comment by markus-mw** [comment]
@christianvoigt : Ich habe jetzt den dev aktualisiert und so wie es aussieht tut das ganze jetzt. Kannst du mir sagen, was im Rahmen dieses issues noch gemacht werden müsste?

**Comment by christianvoigt** [comment]
Bei mir scheitert die Validierung in ajv nach wie vor an der fehlenden timezone der availability date-times. Könntest Du die einfach  noch hinzufügen?

**Comment by christianvoigt** [comment]
Ansonsten sind die Locations noch in einem Array, statt in einer GeoJson FeatureCollection.

Bei meinem Test der Daten des dev-Servers scheiterte außerdem der JSON Parser an den item descriptions, weil die strings noch nicht vollständig escaped sind (gilt für `\n`, `\r` und `\t`):

```
"description":"Details about your items:\r\n<ul>\r\n \t<li>information 1<\/li>\r\n \t<li>information 2<\/li>\r\n \t<li>information 3<\/li>\r\n<\/ul>\r\n&nbsp;"
```

sollte so ausschauen:

```
"description":"Details about your items:\\r\\n<ul>\\r\\n \\t<li>information 1<\/li>\\r\\n \\t<li>information 2<\/li>\\r\\n \\t<li>information 3<\/li>\\r\\n<\/ul>\\r\\n&nbsp;"
```

**Comment by markus-mw** [comment]
@christianvoigt: Die Sache mit der Timezone hab ich angepasst, auch das Escaping ist ergänzt. 

Was du bei der GeoJson FeatureCollection erwartest versteh ich nicht. Kannst du mir ein Beispiel geben? Ich habs exakt so wie [hier](https://blog.codecentric.de/2018/03/geojson-tutorial/) beschrieben umgesetzt und die Jungs wissen eigentlich was sie tun...

**Comment by christianvoigt** [comment]
Ok, hab die [Daten](https://dev.commonsbooking.org/wp-json/commonsbooking/v1/items) vom dev server mit ajv validiert. AJV beschwert sich, dass manche location features keine "geometry"-Eigenschaft besitzen. Die haben wahrscheinlich noch keine Koordinaten.

Macht aber Sinn, dass die Commons Api die geometry property mit Koordinaten der location verlangt, denke ich. Wenn es in CB die Möglichkeit gibt, locations ohne Geocoding anzulegen, müssen wir überlegen wie wir in der Commons Api damit umgehen wollen.

Ich denke es gibt drei Möglichkeiten:

- Locations ohne Koordinaten bekommen Fake-Koordinaten. Nicht sehr sauber, aber einfach. Im Commons Hub, würden diese locations dann allerdings in der Karte an falscher Stelle erscheinen (z.B. in der Antarktis).
- In CB werden nur Locations (und items an diesen Locations) in der Rest API veröffentlicht, die Koordinaten haben.
- Änderung der Commons API: es gibt locations ohne geometry property. Dann müßten Apps, die die Daten auf einer Karte visualisieren (Commons Hub) solche Daten rausfiltern.

Was meint Du? Ich bin unentschlossen, Lösung 3 gefällt mir aber ein bisschen weniger (ich denke locations sollten eigentlich schon Koordinaten haben).

**Comment by markus-mw** [comment]
@christianvoigt: Ich wäre für den zweiten Ansatz. Dann ist es sauber. In der Theorie dürfte es auch keine Locations ohne Koordination geben, weil die Adressfelder verpflichtend sind. Das kann nur bei migrierten bzw. älteren Datensätzen passieren.

**Comment by markus-mw** [comment]
@christianvoigt : Der zweite Ansatz ist jetzt so im Master umgesetzt. Locations ohne Adresse bzw. mit einer Adresse für die keine Geokordination gefunden werden können, werden nicht mehr ausgegeben.

**Comment by christianvoigt** [comment]
Hi @chriwen, ich habe vor zwei Wochen einen neuen Test gemacht, der zeigte, dass die Commons-Api-Implementierung noch nicht robust genug ist (die Kasimir-Daten sind derzeit nicht valide). Habt Ihr das auch schon gefixt? Ansonsten sollte dieses Issue wohl wieder geöffnet werden und auf die Todo-Liste oder wir sollten ein neues Issue für die aktuelle Inkompatibilität erstellen.

**Comment by chriwen** [comment]
@markus-mw Kannst du das bitte nochmal prüfen?

**Comment by christianvoigt** [comment]
Hi @chriwen und @markus-mw,
Christian und ich hatten bei unserem letzten Telefonat über die Owner-Geschichte nochmal geredet und waren auf folgende Lösung gekommen:

CB-Admins sollten in den Einstellungen die Option haben zu wählen, welche Daten für die Item-Owner verwendet werden:

- Der CB-Manager wird als Owner verwendet (d.h. Name und Wordpress-Link zu User-Seite tauchen in der Commons Api auf)
- Es kann ein Owner-Name frei gewählt werden (Textfeld) und die URL verweist einfach auf die Homepage (oder man kann in einem weiteren Textfeld eine URL eingeben)

So decken wir alle Use-Cases ab und wer nicht mit Klarnamen in der API auftauchen will, kann das einfach abstellen (bzw. wir können das per default ausstellen).

Soll ich dafür nochmal ein neues Issue erstellen und dafür dieses Issue schließen?

**Comment by chriwen** [comment]
@christianvoigt Wenn das der einzige offene Punkt in dieser Story hier war (du schriebst in deinem letzten Kommentar "die Kasimir-Daten sind derzeit nicht valide"), dann übernehme ich das in eine separate Story. Oder was hattest du mit nicht valide gemeint?

**Comment by christianvoigt** [comment]
Hatte ich am 21.April geschrieben: Es gab einen Owner ohne Namen und URL. Wenn wir die Owner-Geschichte sowieso nochmal neu implementieren, dann können wir das Issue hier erstmal schließen. Soll ich das neue Issue erstellen oder machst Du das?
