### ISSUE TITLE
Stundenweise Buchung / Kalender Frontend: Auswahl Rückgabe nach Uhrzeitauswahl ermöglichen.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#292]
Wenn nach Wahl des Abholtages die Uhrzeit ausgewählt wird, ist es nicht mehr möglich, den Rückgabetag auszuwählen. Änderungen im Uhrzeit-Dropdown sollten keine Auswirkung auf die Auswahlmöglichkeiten im Kalender haben. 

siehe: https://drive.google.com/file/d/1QUJsHxqGKZniY4RO3LB7KZjg-NP3TOnO/view

**Comment by markus-mw** [comment]
@hanneskasimir : Das ist das Standard-Verhalten vom Litepicker. Ich habs jetzt geändert, sodass die Datumsauswahl nicht mehr verschwindet.
