### ISSUE TITLE
frontend/kalender: kalender rendering performance optimieren

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#295]
nach migration von ca. 1600 timeframes und jeweils > 60 locations / items, dauert der initiale renderprozess beim aufruf einer location-detailseite ca. 40 sekunden.

nachdem kalender geladen ist, und die nächsten monate gewählt sind, dauert auch hier das rendern ewig.

vielleicht ein ansatz?
es müssen bei der berechnung des kalenders nur timeframes bookings nur mit einem end-datum größer dem aktuellen datum überhaupt berücksichtigt werden.
evtl. kann die abfrage auch noch weiter optimiert werden (z.B. maximales renderlimit für monate in der zukunft (z.B. maximal 30 tage in die zukunft)

Beispiel hier:
https://kasimir.commonsbooking.org/cb_item/leila/?location=3579
(Zugangsdaten per Slack)

**Comment by markus-mw** [comment]
@farbschein : Vermutlich muss ich die Queries auf reines MySQL umstellen. Die Wordpress queries sind einfach zu schlecht. Ich schau aber mal ob's auch mit Bordmitteln geht.

**Comment by farbschein** [comment]
@mw: ok, konntest du es reproduzieren?

**Comment by markus-mw** [comment]
@farbschein : Ich kanns sehen ja, lokal halt nur nicht. Da müsste ich mir erst diese Menge an timeframes usw. erstellen. Ich schau wie grad besprochen mal direkt auf dem Dev-System nach.

**Comment by markus-mw** [comment]
@farbschein : Ich habe den Timeframe Query jetzt anders umgesetzt, sodass der Seitenaufruf beim ersten mal ca. 1,5s dauert und danach unter einer Sekunde. Das ist mit der Performance der "normalen" Content-Seiten vergleichbar (teils sogar besser) und daher nicht steigerbar außer durch einen besseren Server.
Das ganze ließe sich nur noch steigern, wenn ich eine eigene Tabelle für die Relationen der Timeframes, Orte und Items anlege, aber davon würde ich erstmal absehen.

**Comment by farbschein** [comment]
@markus-mw : Super, das schaut sehr gut aus. Ich denke, so kann es erstmal bleiben. git pull auf dem kasimir dev-server  warf einen fehler (siehe slack) wie kann ich denn da den aktuellen branch pullen?
