### ISSUE TITLE
Frontend/Buchungsbestätigung:  Datenbank-Fehler

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#301]
Abfrage	Abruffunktion	Komponente	Fehlermeldung	Fehlercode
SELECT wp_posts.* from wp_posts
INNER JOIN wp_postmeta pm4
ON pm4.post_id = pm1.post_id
AND pm4.meta_key = 'repetition-start' pm4.meta_value BETWEEN 0
AND 1606262340
INNER JOIN wp_postmeta pm5
ON pm5.post_id = pm1.post_id
AND pm5.meta_key = 'repetition-end'
AND pm5.meta_value BETWEEN 1606176000
AND 3000000000
WHERE wp_posts.id in (7328)
AND wp_posts.post_type = 'cb_timeframe'
AND wp_posts.post_status IN ('confirmed','unconfirmed','publish','inherit')	

-
CommonsBooking\R\Timeframe::get()
wp-content/plugins/commonsbooking/src/Repository/Timeframe.php:94
CommonsBooking\M\Booking->getBookableTimeFrame()
wp-content/plugins/commonsbooking/src/Model/Booking.php:146
load_template('wp-content/plugins/commonsbooking/templates/booking-single.php')
wp-includes/template.php:732
cb_get_template_part()
wp-content/plugins/commonsbooking/includes/Template.php:78
CommonsBooking\W\C\Timeframe->getTemplate()
wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php:228
apply_filters('the_content')
wp-includes/plugin.php:206
the_content()
wp-includes/post-template.php:253
load_template('wp-content/themes/kasimir-theme/template-parts/content.php')
wp-includes/template.php:732
locate_template()
wp-includes/template.php:676
get_template_part('template-parts/content','')
wp-includes/general-template.php:204

Plugin: commonsbooking	You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'pm4.meta_value BETWEEN 0 AND 1606262340 INNER JOIN wp_postm' at line 6

**Comment by farbschein** [comment]
@markus-mw Die Meldung steht irgendwie auch im Zusammenhang mit #273 . Vielleicht hilft dir das.

**Comment by markus-mw** [comment]
@farbschein : Problem ist behoben.
