### ISSUE TITLE
Migration: Falsche Zuordnungen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#311]
Ich hab mal beispielsweise die beiden ältesten Buchung untersucht:

- [x] Buchungsstatus wurde nicht richtig übernommen (Confirmed anstatt canceled)

- [x] Falsche Zuordnung bei der Station. (Ferdinandstraße Stegerwaldsiedlung anstatt Asta Büro). In der Liste steht jedoch gar keine Station drin. Asta Büro ist jedoch mitmigriert worden.

![Screenshot_2020-11-24 Zeitrahmen bearbeiten ‹ KASIMIR - Dein Lastenrad - Lastenrad-Verleih in Köln — WordPress](https://user-images.githubusercontent.com/28141760/100088419-5a2b9880-2e50-11eb-93d8-33abbaebab10.png)
![Screenshot_2020-11-24 Standort bearbeiten ‹ KASIMIR - Dein Lastenrad - Lastenrad-Verleih in Köln — WordPress](https://user-images.githubusercontent.com/28141760/100088412-59930200-2e50-11eb-8e25-ecd460ab33ea.png)
![Migrationsfehler](https://user-images.githubusercontent.com/28141760/100088400-5730a800-2e50-11eb-8a45-a723e558d14e.png)

**Comment by farbschein** [comment]
@markus-mw  Kannst du das bitte nochmal priorisiert bearbeiten. Das wäre momentan wichtiger als API-Themen. Vielen Dank.

**Comment by markus-mw** [comment]
@farbschein , @hanneskasimir : Die Probleme sind behoben. Zum einen kam uns die Standard-Limitierung von WP Datenbankabfragen von 30 in die Quere und zum anderen ein Typo 'cancelled' statt 'canceled', daher wurden die Status nicht gesetzt.

**Comment by farbschein** [comment]
@markus-mw super. Vielen Dank fürs schnelle lösen. Ich teste das heute Abend gleich mal.
