### ISSUE TITLE
Frontend/Buchung: Leere Buchung auf Buchungsbestätigungsseite

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#316]
Nach Klick auf Buchungbestätigung erscheint eine leere Buchungsbestätigungsseite.
Siehe: https://drive.google.com/file/d/18iI-ihFTJZQrNV4KESbr00ECQx9BQqV6/view

**Comment by markus-mw** [comment]
@farbschein : Ich weiß das Problem ist, nur noch nicht wie ichs elegant löse. Das häng mit dem Problem zusammen, dass Meta-Felder beim legen in den Papierkorb gelöscht werden. Die Funktion die das verhindert, verhindert aktuell die korrekte Speicherung der Buchung.

**Comment by markus-mw** [comment]
@farbschein : Ging einfacher als Gedacht. Das Problem ist behoben. Es kann sein, dass ich dir ein paar Buchungen und Timeframes beim Testen kaputt gemacht hab. Bitte nicht wundern!
