### ISSUE TITLE
Frontend:/timeframe-withlocation -> Bei mehreren bookable timeframes wird nicht das Enddatum des längsten Timeframes verwendet.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#318]
Es sind zwei Timeframes bookable für gleiche item/location-Kombi angelegt.
T1: stündlich, 09:00 - 12:00 Uhr von 27.11. - 30.12.2020
T2: stündlich, 14:00 - 17:00 Uhr von 27.11. - 31.12.2020

im Frontend in der items/locations-Liste wird in timeframe-withlocation.php angezeigt: "item verfügbar bis 30.12.2020".
Da hier ja eine gültige Kombination von zwei sich überlappenden bookable timeframes existiert, sollte in diesem Fall der Zeitraum des längsten Timeframes angezeigt.
Zudem ist der 31.12. im Kalender als nicht buchbar gekennzeichnet.

Hatten wir das so definiert? Wenn ja, warum? ;-)
Oder ist das ein Bug?

![image](https://user-images.githubusercontent.com/12683634/100380848-f6ec6280-3017-11eb-8b43-3b86c74e5986.png)

![image](https://user-images.githubusercontent.com/12683634/100380898-14b9c780-3018-11eb-9cfb-f37fddc5a573.png)

**Comment by markus-mw** [comment]
@farbschein : Bitte probiers noch einmal. Das sollte jetzt (wieder) passen.

**Comment by farbschein** [comment]
geht. danke.
