### ISSUE TITLE
Booking: Tage verschoben?

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#323]
Folgendes Phänomen, evtl. auch Ursache für #318 

Es scheint, als sei die Ausgabe eine Timeframes im Frontend-Buchungskalender um einen Tag zurück verschoben.

Beispiel siehe Screens:
Buchbarer Zeitraum von 30.11 - 30.12.2020
![image](https://user-images.githubusercontent.com/12683634/100382219-218bea80-301b-11eb-9c15-9ec7b7d0952d.png)

im Frontend-Kalender:
29.11 - 29.12
![image](https://user-images.githubusercontent.com/12683634/100382298-51d38900-301b-11eb-9ae5-6783092427c1.png)

Das gleiche ist auch bei Buchungen etc. zu beobachten.

**Comment by markus-mw** [comment]
@farbschein : Bitte probiers noch einmal. Das sollte jetzt (wieder) passen.

**Comment by farbschein** [comment]
passt jetzt.
