### ISSUE TITLE
cb_items Shortcode auf einer Instanz ohne Ausgabe

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#325]
Testinstanz: https://lastenrad.asta.ms/?page_id=23
Zugangsdaten per Slack

Auf der Seite ist Shortcode cb_locations eingebunden.
Erzeugt keine Ausgabe. Auch cb_items nicht.

Die Installation erfolgte über ein zip, welches ich aus meinem lokalen Master (ohne den node_modules) erzeugt habe.

Hast du ne Idee?

**Comment by farbschein** [comment]
@markus-mw auf einer lokalen Testinstanz konnte ich das nicht reproduzieren. Gibt es irgendwelche Einstellungen/Versionen (PHP etc.) die die Ausgabe verhindern könnten?

**Comment by markus-mw** [comment]
@farbschein : Das Problem war, dass die Shortcodes nur für Timeframes funktioniert haben, die aktuell buchbar sind. Ich hatte zwischendurch das Timeframe-Repo nachgeschärft, das war vorher an der Stelle ungenau, weshalb die Shortcodes zu diesem Stand noch funktioniert hatten.
