### ISSUE TITLE
Booking-Mail ohne Subject und Body

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#327]
auf kasimir.commonsbooking wird bei einer Buchung eine Mail ohne Subjekt und Body gesendet.

Siehe Wordpress -> Werkzeuge -> Log Emails (das Plugin fängt alle Mails ab und loggt sie)

**Comment by markus-mw** [comment]
@farbschein : Das scheint sich durch eine der letzten Anpassungen selbst behoben zu haben:
![image](https://user-images.githubusercontent.com/22905753/100386141-dd054c80-3024-11eb-8eb4-11d62c363405.png)

**Comment by farbschein** [comment]
@markus-mw : scheint bei Buchungsbestätigung zu gehen. Stornierungsmail ist jedoch weiterhin leer.

**Comment by markus-mw** [comment]
@farbschein : Auch die Stornierungsmails funktionieren jetzt wieder. Das Problem war die geänderte schreibweise von "cancelled". Diese hatte ich in einem früheren Ticket bzgl. der Migration geändert, damit Buchungen korrekt übernommen werden konnten (In CB1 _canceled_, in CB2 vorher _cancelled_).

**Comment by farbschein** [comment]
@markus-mw Moin. Danke Dir Es fehlte noch die Änderung am emailtemplates_mail-booking-cancelled-subject, das hab ich noch fix angepasst und push es gleich.
