### ISSUE TITLE
Frontend/Liste: Es werden alle bookable timeframes angezeigt - auch vergangene

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#330]
In der Locations-Liste werden items auch angezeigt, deren bookable timeframe in der Vergangenheit endete. 

Wunsch:

- [x] Es sollen in der Locations-Liste nur Items angezeigt werden, bei denen mindestens 1 bookable timeframe gleich oder größer dem heutigen Tag ist und die den Status publish haben.

Ergänzung:
- [x] In der Items-Liste sollen alle Items angezeigt werden, die den Status publish haben - auch wenn diese nicht mit einem timeframe verknüpft sind. Dann mit dem Hinweis "item derzeit nicht verfügbar" --> ich glaube, das funktioniert bereits
- [x] In der Locations-Liste sollen ebenfalls alle published Locations angezeigt werden.

**Comment by markus-mw** [comment]
@farbschein : "Wunsch" ist erledigt.

**Comment by markus-mw** [comment]
@farbschein : Der Rest ist auch erledigt. Bitte prüfen.
