### ISSUE TITLE
Check compatibility with WP 5.6

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#332]
> The biggest things you need to look out for with WordPress 5.6 is our continuing jQuery updates. In the last version, 5.5, we disabled jQuery Migrate but did not update jQuery and jQuery UI. Now for WordPress 5.6, we have upgraded jQuery and jQuery UI to the latest version of those libraries and added the correct version of jQuery Migrate to go along with it. If your plugin uses jQuery, we encourage you to test as soon as possible.

[will be released december 8](https://make.wordpress.org/core/2020/11/20/wordpress-5-6-field-guide/)

**Comment by markus-mw** [comment]
@flegfleg , @chriwen : Ich bin nur auf eine Notice bzgl. der API-Routen gestoßen. Das Problem hab ich aber behoben. Ansonsten hatte alles was mit dem Kalender und der Buchung zu tun hatte geklappt. Hab die Änderungen im Branch feature/issue-332

**Comment by chriwen** [comment]
@markus-mw Da ich die API nicht testen kann, gehe ich mal davon aus, dass alles so stimmt. Dann gerne in den Master ;-)
