### ISSUE TITLE
Mehrere Zeitrahmen mit der selben Kombination aus Artikel und Standort in der Liste kombinieren

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#333]
immer letztes Datum der Verfügbarkeite aus allen Zeitrahmen anzeigen.
aktuell:
![grafik](https://user-images.githubusercontent.com/28141760/100443861-c4d81080-30aa-11eb-85db-5013b962b01e.png)
![grafik](https://user-images.githubusercontent.com/28141760/100443877-ca355b00-30aa-11eb-9dd0-5f1789042de5.png)

**Comment by farbschein** [comment]
@markus-mw : Es wird irgendwie nur der eine Timeframe (bis 05.01) ausgegeben. Der zweite fehlt. 
@hanneskasimir : In diesem Beispiel überlappen sie sich ja aber nicht, d.h. hier wäre es korrekt, die beiden Timeframes auch getrennt auszugeben, oder?
Der erste endet ja am 05.01 - der 2. beginnt erst am 13.01 . Sowas würde ich glaube ich nicht verbinden, da wir dann auch prüfen müssten wie lange der undefinierte Zeitraum dazwischen ist. Wenn das mehr als 1-2 Wochen sind sieht es im Kalender seltsam aus.

**Comment by markus-mw** [comment]
@farbschein @hanneskasimir : Wollt ihr das eventuell noch ausdiskutieren bevor ich daran herumdokter?

**Comment by hanneskasimir** [comment]
@farbschein : Ja, sehr gut. 
D.h. ist unserem Fall oben würde beides da stehen:

Hier verfügbar bis 5. Januar und vom 13.  bis 22. Januar 

oder der Einfachheit erstmal:

Hier verfügbar bis 5. Januar
Hier verfügbar vom 13. Januar bis 22. Januar

**Comment by markus-mw** [comment]
@chriwen : Wie soll die Logik hierfür jetzt aussehen? Sollen die Zeiträume nur dann zusammengezogen weden, wenn sie sich überlappen oder auch wenn ein Zeitraum x dazwischen ist (falls ja, wie groß ist x?)?

**Comment by chriwen** [comment]
@markus-mw : Versuchen wirs mal mit folgender Regel:
- Wenn sich bei mehreren Zeiträume in mindestens zwei davon in einem Tag (Datum ohne berücksichtung der Uhrzeit) überlappen dann sollen diese kombiniert dargestellt werden. Es gilt dann: Anfangsdatum ist das in der Schnittmenge der beiden früheste Datum, Enddatum ist das späteste Datum.
- Wenn es keine Überlappung in mindestens einem Tag gibt, werden die Zeiträume separat aufgelistet, wobei die Sortierung mit Anfangsdatum aufsteigend erfolgen soll.

Soweit nachvollziehbar? Und, danke fürs mitdenken :-)

**Comment by markus-mw** [comment]
@chriwen : Ist nachvollziehbar. Ich kümmer mich drum.

**Comment by markus-mw** [comment]
@chriwen : Ich habe das mal in feature/issue-333 umgesetzt. Eine Sache habe ich aber anders gemacht:
Die Zeiträume müssen nicht zwangsweise überlappen, es reicht, wenn z.B. Timerange 1 von 01.01.-15.01. und Timerange 2 vom 16.01.-30.01. läuft. Wenn die Zeiträume also direkt aneinander anschließen.
Ansonsten würden diese Fälle getrennt voneinander dargestellt werden. Das hielte ich für falsch.

**Comment by chriwen** [comment]
@hanneskasimir : Bitte das nochmal im Detail testen in der aktuellen Version.

**Comment by hanneskasimir** [comment]
getestet auf Stage1: Funktioniert bei Stundenweise Buchung!
![Bildschirmfoto 2021-01-22 um 15 11 42](https://user-images.githubusercontent.com/28141760/105501174-2e982380-5cc4-11eb-85f3-022b504f934c.png)
![Bildschirmfoto 2021-01-22 um 15 11 16](https://user-images.githubusercontent.com/28141760/105501184-31931400-5cc4-11eb-858a-c49ffe843f52.png)

Funktioniert aber leider nicht bei tageweise Buchung:
![Bildschirmfoto 2021-01-22 um 15 09 08](https://user-images.githubusercontent.com/28141760/105500920-df51f300-5cc3-11eb-989d-c187390d54bf.png)
![Bildschirmfoto 2021-01-22 um 15 08 46](https://user-images.githubusercontent.com/28141760/105500950-e416a700-5cc3-11eb-88a4-6ad2e1a3824a.png)

**Comment by chriwen** [comment]
@hanneskasimir :  Die Fehlermeldung bei der Überlappung der tageweisen Zeitrahmen ist eigentlich korrekt. Wir wollen verhindern, dass sich tageweise Buchungszeiträume überlagern, da das keinen Sinn macht. 

Das einzige, was ich hier sehen würde ist die kombinierte Ausgabe auf der Artikel-Liste. Hier sollen die direkt aufeinanderfolgenden Zeiträume als ein von / bis-Zeitraum ausgegeben werden.

**Comment by hanneskasimir** [comment]
ok!

**Comment by chriwen** [comment]
@markus-mw Kannst du diese Darstellung auf der Artikel-Liste (siehe letzter Screen im Verlauf hier) noch anpassen? Also, wenn sich Zeiträume einander anschließen, dass dann der kombinierte Zeitraum angezeigt wird.
