### ISSUE TITLE
Frontend-Artikel-Liste: Sortierung nach neuestem Datum bei mehreren Stationen je Artikel

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#334]
ist hier nur zufällig richtig:
![grafik](https://user-images.githubusercontent.com/28141760/100444706-28167280-30ac-11eb-9d2b-4737fc27a015.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Ist erledigt.
