### ISSUE TITLE
Migration: _cb_allow_lockdays_in_range ist nach Migration selected, ist aber nicht aktiv.

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#336]
Erst nach erneutem Speichern der Location scheint die Einstellung gespeichert zu sein.

Ziel:
- Einstellung sollte direkt bei Migration aktiviert werden.

**Comment by markus-mw** [comment]
@farbschein : Das Problem ist behoben.

**Comment by hanneskasimir** [comment]
klappt bei mir noch nicht.
![grafik](https://user-images.githubusercontent.com/28141760/101166810-2e22cb00-3639-11eb-87d7-a6c42a2670fa.png)
