### ISSUE TITLE
Link zur Doku ist falsch / Deutsche Begriffe im Quelltext

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#339]
![grafik](https://user-images.githubusercontent.com/28141760/100464378-c830c380-30cd-11eb-994a-b56d2f6ab4f7.png)

**Comment by flegfleg** [comment]
![CleanShot 2020-12-01 at 14 36 51@2x](https://user-images.githubusercontent.com/4009931/100750529-75654d80-33e6-11eb-87e9-b6aaa841158a.png)
Detail: Wenn ihr mit PoEdit übersetzungen eingebt, auf jeden Fall das hier abschalten. 
Sonst auto-korrigiert der `" "` in die deutsche Variante ( `„ “ `).
