### ISSUE TITLE
CB-Manager Berechtigungen korrigieren

### ISSUE THREAD

**Issue by markus-mw** [wielebenwir/commonsbooking#341]
@markus-mw 

Hier eine detaillierte Beschreibung. Hoffe, das passt so?
https://docs.google.com/document/d/1WFfU_lnbE15tv7daiGx-cka3LPyCcja4ztP5xY0scDo/edit?usp=sharing

# Artikel & Standorte
### Bearbeiten
eigene (Autor) oder zugewiesene Artikel & Standorte:
- [x] in Liste sehen, öffnen
- [x] bearbeiten
- [x] publizieren / depublizieren
Andere Artikel & Standorte werden nicht angezeigt.

### Erstellen:
- [x] ohne Einschränkung

# Zeitrahmen
### Bearbeiten:
für alle Zeitrahmen, die
- [x] selbst erstellt sind (Autor)
- [x] mit einer eigenen Station (Autor) verknüpft sind
- [x] mit einer Station verknüpft sind, wo Nutzer als cb_manager eingetragen ist

gelten folgende Rechte:
- [x] in Timeframe-Liste sehen, öffnen
- [x] bearbeiten (wenn mögliche Konflikte technisch verhindert werden, z.B. bei Buchungsverlängerungen)
- [x] publizieren / depublizieren
- [x] Status ändern (Buchung canceln, confirm, unconfirm)

Andere Zeitrahmen werden nicht angezeigt.

### Erstellen:
- [x] Es werden nur die Artikel & Stationen im Dropdown zur Auswahl angezeigt, die auch bearbeitet werden können, siehe bei “Artikel & Standorte” -> #Bearbeiten

**Comment by farbschein** [comment]
@markus-mw : Wenn du dazu fragen hast, dann kannst du morgen auch gerne @hanneskasimir wenden.

**Comment by markus-mw** [comment]
@farbschein : Darf der Manager selbst erstellte Artikel/Standorte/Timeframes löschen?

Was genau ist mit dem Satz "bearbeiten (wenn mögliche Konflikte technisch verhindert werden, z.B. bei Buchungsverlängerungen)" gemeint?

**Comment by markus-mw** [comment]
@farbschein : Das ist soweit in feature/issue-347 erledigt.
Bezüglich meiner Frage habe ich es wie folgt gemacht: Der Manager kann eigene Posts (Author) löschen.

**Comment by hanneskasimir** [comment]
Danke! Leider wird das Beitragsbild nicht geladen als cb_manager:
![grafik](https://user-images.githubusercontent.com/28141760/101160535-7f2dc180-362f-11eb-93cb-95a4fffa226b.png)

**Comment by hanneskasimir** [comment]
Die Buchungsverlängerungen klären wir mal in Ruhe in einem anderen Ticket.

**Comment by hanneskasimir** [comment]
Update: Beitragsbild-Problem tritt nur beim Gutenberg-Editor auf, den wollen wir eh nicht https://github.com/wielebenwir/commonsbooking/issues/354

**Comment by markus-mw** [comment]
@hanneskasimir : Also gibt's hier erstmal nichts mehr für mich zu tun?
