### ISSUE TITLE
Frontend Buchung. Fatal error bei Abbruch

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#342]
**Describe the bug**
Wenn man Auf der Buchungsbestätigungaseite auf abbrechen klickt kommt ein fatal error. 
Test auf kasimir-lastenrad.de

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by markus-mw** [comment]
@farbschein : Ich bekomm das lokal und auf https://kasimir.commonsbooking.org/ nicht reproduziert. Kannst du mir einen Tipp geben?

**Comment by farbschein** [comment]
@markus-mw Seltsam, jetzt konnte ich es gerade auch auf kasimir-lastenrad.de auch nicht reproduzieren. Das hier war aber die Meldung:


Fatal error: Uncaught Error: Call to a member function booking_timeframe_date() on null in /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/src/CB/CB.php:166 Stack trace: #0 /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/src/CB/CB.php(42): CommonsBooking\CB\CB::lookUp(NULL) #1 /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/includes/TemplateParser.php(21): CommonsBooking\CB\CB::get('booking', 'booking_timefra...') #2 [internal function]: cb_parse_template_callback('booking:booking...') #3 /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/includes/TemplateParser.php(6): preg_replace_callback('/\\{{.*?\\}}/', 'cb_parse_templa...', ' ...') #4 /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/src/Messages/Messages.php(61): cb_parse_template(' ...') #5 /var/www/client in /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/src/CB/CB.php on line 166
Es gab einen kritischen Fehler auf deiner Website.

Erfahre mehr über die Fehlerbehebung in WordPress.


![image](https://user-images.githubusercontent.com/12683634/100781804-ce93a800-340b-11eb-86f7-f8f472b54c85.png)

**Comment by markus-mw** [comment]
@farbschein : Wenn ich mir den Backtrace so ansehe, scheint da der Body-Text für eine Mail nicht gefunden worden zu sein.
