### ISSUE TITLE
Rollen item_admin und location_admin löschen

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#347]
Diese Rollen benötigen wir nicht mehr. Bitte löschen.

**Comment by markus-mw** [comment]
@farbschein , @hanneskasimir : Ist in feature/issue-347 erledigt. Wird mit #341 gemerged.

**Comment by hanneskasimir** [comment]
ist bei mir immer noch da, auch die Rolle Stationsmanager, für die gilt ja das gleiche.
![grafik](https://user-images.githubusercontent.com/28141760/101166178-2878b580-3638-11eb-9e71-d8c817165167.png)
