### ISSUE TITLE
Mobile: Auf iphone7 kein Buchungskalender in auf Item-Detailseite.

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#349]
Auf iphone7 wird auf kasimir-lastenrad.de der Buchungskalender nicht angezeigt.

**Comment by markus-mw** [comment]
@farbschein: Ob du es mir glaubst oder nicht, ich hab grad kein iPhone 7 zur Hand. XD In der simulierten Ansicht vom Chrome wird der Kalender angezeigt... Was vielleicht zunächst gemacht werden sollte, wäre den JS Fehler zu beheben. Eventuell tut sich das native iPhone damit schwer.

**Comment by farbschein** [comment]
@markus-mw du solltest auf jeden fall an deinem Testpark arbeiten :-) Kannst du den JS-Fehler beheben? Wo kommt der her?

**Comment by markus-mw** [comment]
@farbschein: Soweit ich es sehen kann aus der project.min.js aus dem Kasimier Theme. Ist aber nicht sicher.

**Comment by farbschein** [comment]
@flegfleg Kannst du dir das mal anschauen?

**Comment by flegfleg** [comment]
Huhu, 
fies weil es tatsächlich nur auf Handys (iPhones? Hab kein anderes hier zum Testen) auftaucht. Theme wirft einen Fehler, daran liegt es aber nicht. 

Die "`screen.orientation.angle`" scheint (nicht) mehr definiert zu sein.

`TypeError: undefined is not an object (evaluating 'screen.orientation.angle')`
<img width="1120" alt="CleanShot 2020-12-07 at 09 33 21@2x" src="https://user-images.githubusercontent.com/4009931/101327964-b5598400-386f-11eb-8eea-59212a2899c4.png">

* Nutzen wir die Orientation change überhaupt? Sollte alles per CSS gelayoutet sein. 
* Können wir die Bibliothek einfach aktualisieren?

**Comment by flegfleg** [comment]
Hab in dem Branch  bugfix/issue-349  die Bibliothek aktualisiert, Fehler besteht leider noch. @markus-mw kannst du dir das JS angucken?

**Comment by flegfleg** [comment]
Ups, war ein Cache-Thema. Funktioniert jetzt. Ist aktiv auf kasimir, noch nicht gemergt.

**Comment by markus-mw** [comment]
@chriwen , @flegfleg : Bitte versuchts nochmal mit dem Branch bugfix/issue-349. Es sieht so aus, als ob das iPhone die Orientation Variable einfach nicht unterstützt. Ich habs jetzt anders gelöst.
