### ISSUE TITLE
cb_manager: Buchungen fremder Artikel oder Stationen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#353]
Buchungen, die als cb_manager im Frontend bei fremden Artikeln oder/und Stationen gemacht werden, erscheinen im Backend des cb_managers. Im Bearbeitungsmodus der Buchung sind im Dropdown keine bzw. die falschen Artikel/Stationen angezeigt, d.h. die Buchung wird falsch geändert bzw. es kommt zu Verwirrungen.

**Comment by chriwen** [comment]
@hanneskasimir ist das noch aktuell?
