### ISSUE TITLE
Classic-Editor soll immer aktiv sein bei cb

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#354]
Classic Editor für unsere Post-Types als Standard definieren

**Comment by chriwen** [comment]
@hanneskasimir Setzen wir erstmal nicht um, da Classic-Editor nicht Wordpress-Standard ist. Es gibt ein Plugin, mit den Nutzende selbst einstellen können, welchen Editor sie nutzen wollen. im Prinzip gibts mit dem Gutenberg auch keine Probleme in Zusammenhang mit CB.
