### ISSUE TITLE
Backend/Timeframeliste: Nutzer in Zeitrahmen-Liste mit Benutzerprofil-seite verlinken

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#358]
![Bildschirmfoto 2020-12-04 um 15 31 13](https://user-images.githubusercontent.com/28141760/101175995-2ae20c00-3646-11eb-87a5-4edabcfd8cc7.png)

Hierfür muss cb_managern die Rechte gegeben werden, auf die Benutzerprofile zuzugreifen.

Eine Bearbeitung eines Benutzers soll für cb_manager nicht möglich sein. Ausnahme ist natürlich ihr eigenes Profil
![grafik](https://user-images.githubusercontent.com/28141760/101176060-41886300-3646-11eb-971a-5b01482997d4.png)

**Comment by farbschein** [comment]
@markus-mw : Die Verlinkung der Userspalte mit dem Userprofil hab ich mal umgesetzt: https://github.com/wielebenwir/commonsbooking/tree/feature/issue-358 
Irgendwie konnte ich auch so schon als cb-manager die Userprofile sehen. Evtl. muss da nichts weiter angepasst werden.

**Comment by hanneskasimir** [comment]
Funktioniert schon auf KASIMIR Live-System für Admins.
Leider noch nicht für cb_manager.

**Comment by markus-mw** [comment]
@farbschein , @hanneskasimir : Damit das der CB-Manager über den Link sehen kann, muss er Profile anpassen dürfen. Ich kann mir nicht vorstellen, dass das so gewollt ist.
@farbschein : Den Link den du da eingebaut hast, ist der zum editieren des Users im Backend. Ist es das was du wolltest?

**Comment by farbschein** [comment]
@markus-mw : Ja, der Link soll zum Userprofil führen. Ideal wäre die Möglichkeit, dass der cb_manager zwar das Userprofil sehen, es aber nicht bearbeiten kann. Grundsätzlicher Use Case ist, dass der cb_manager die Nutzerdaten zu einer Buchung einsehen können soll, um ggf. die Person kontaktieren und dessen Daten überprüfen kann.
Fällt dir da sonst ne andere Lösung ein?
Weitere Herausforderung: Die Nutzerverwaltung liegt ja nicht in commonsbooking, d.h. je nach Wordpress-Instanz können die Admins auch weitere Plugins für die Userverwaltung nutzen (und z.B. zusätzliche Nutzerdaten erfassen). D.h. wir können nicht die Nutzerdaten in unser Backend übernehmen.

**Comment by markus-mw** [comment]
@farbschein : Ehrlich gesagt, fällt mir keine einfache Lösung für das Problem ein, weil Wordpress da einfach nichts für mitbringt.

**Comment by farbschein** [comment]
@markus-mw OK, dann vertagen wir das.
