### ISSUE TITLE
Mobile (Safari iOS, u.U. andere): Startdatum wird nicht übernommen 

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#361]
**Describe the bug**
Startdatum wird nicht in die Box übernommen.

**To Reproduce**
Auf iOS, mobile Safari (hier: iPhone X): Nach Tap auf dem Kalender (https://www.kasimir-lastenrad.de/cb-items/buergerrad-nippes/?location=3594 ) wird das Anfangsdatum nicht in die Box übernommen.

**Expected behavior**
Anfangsdatum wird übernommen

**Notes**
* Es werden keine JS-Fehler geworfen
* Theme "kasimir" wirft einen Fehler, Problem ist aber mit Standard-Theme reproduzierbar
* Auf Desktop funktioniert es.
* Ich habe die Bibliothek aktualisiert:  #349

![IMG_4F93510293B2-1](https://user-images.githubusercontent.com/4009931/101343949-09229800-3885-11eb-82ae-ac57d5473ec8.jpeg)

**Comment by markus-mw** [comment]
@flegfleg : Ich habe keine Apfelgeräte um das zu testen ;/ Wie gehen wir damit um?
