### ISSUE TITLE
cb_manager: Alle Artikel und Stationen anzeigen.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#364]
Für cb_manager werden im Backend nur die 20 aktuellsten (Publikationsdatum) Artikel und Stationen angezeigt.
Das liegt wohl an der Listen-Erstellung (Paginierung), dort werden vermutlich zuerst die 20 (Standardeinstellung) aktuellsten Einträge gefiltert und dann danach erst nach den für den cb_manager zugeordneten Einträgen.
Stellt Mensch die Paginierung auf z.B. 50 tritt das Problem nicht mehr auf.
Der Filter für den cb_manager könnte als Lösungsvorschlag also vor der Anzahl der angezeigten Einträge erfolgen.

**Comment by markus-mw** [comment]
@hanneskasimir : Das ist etwas knifflig, weil die Paginierung selbst bei den "normalen" Filtern nicht richtig funktioniert. Ich hab noch nicht den Punkt gefunden, an dem ich mich am besten einhaken kann, denke aber, dass ich da eine Lösung finde.

**Comment by markus-mw** [comment]
@hanneskasimir , @farbschein : Bitte probiert es einmal mit dem Branch bugfix/issue-364. Da müsste die Paginierung funktionieren. 
Die Anzeige der Post-Anzahl(en) bleibt weiterhin falsch. Das ist recht aufwändig das gerade zu ziehen und drückt auf die Performance. Lasst mich wissen, wenn das ein wichtiger Punkt ist.

**Comment by farbschein** [comment]
@markus-mw : Jetzt ist es leider so, dass die Einträge sich auf mehrere Seiten verteilen. So hat man z.B. bei 5 Einträgen trotzdem eine Paginierung über 3 Seiten, auf die sich dann die Einträge verteilen. Das gleiche gilt auch für die Timeframe-Liste.

Kannst du hier mal prüfen, ob das ggf. schnell zu lösen wäre? Wenn das was Größeres ist, lass uns nochmal kurz sprechen, dann würden wir noch ein paar Alternativlösungen in Betracht ziehen.

**Comment by markus-mw** [comment]
@farbschein 
Ich Dussel hatte meine letzten Änderungen nicht gepusht. Jetzt sind die Änderungen drin und kasimir.commonsbooking.org auf dem neuesten Stand. Check das bitte mal, für mich sieht es gut aus.
