### ISSUE TITLE
Nicht verfügbare Räder aus Liste entfernen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#372]
nicht verfügbare Räder sind plötzlich wieder in der Liste aufgetaucht: https://www.kasimir-lastenrad.de/bikes/

**Comment by markus-mw** [comment]
@hanneskasimir : Solange die Räder publiziert sind, soll das so sein. Siehe hier: https://github.com/wielebenwir/commonsbooking/issues/330

**Comment by hanneskasimir** [comment]
@farbschein , Markus hat völlig recht, das hatten wir schonmal anders gebrieft. 
vielleicht ist es irgendwie doch Geschmackssache, vielleicht im Backend auswählbar machen?
