### ISSUE TITLE
Buchung in der ferneren Zukunft nicht möglich

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#377]
Buchungen in der fernen Zukunft, d.h. etwa in 2 Monaten funktioniert nicht. Der Rückgabetag ist nicht auswählbar.
hier kannst du testen: https://kasimir.commonsbooking.org/cb_item/elsa/?location=30208
![grafik](https://user-images.githubusercontent.com/28141760/101912140-a3eedf80-3bc1-11eb-9055-2cddb536bd74.png)
![grafik](https://user-images.githubusercontent.com/28141760/101912200-b6691900-3bc1-11eb-9a1f-1437301b533d.png)

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Das Problem ist behoben. Bitte testet mal.

**Comment by chriwen** [comment]
@hanneskasimir : hab getestet. Bitte nochmal retesten, wenn veröffentlicht.
