### ISSUE TITLE
Save plugin options on activation to prevent mail not sent error

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#394]
**Problem**: Emails are not sent. 

**Reason:** Plugin options defaults are not available to WordPress (get_option) on a new install if they are not saved first. 

In CB1, a solution is implemented: 

https://github.com/wielebenwir/commons-booking/blob/58c8c296d84d30f6e919c8588ba202b57f32dd9a/admin/cb-settings/cb-admin-settings.php#L160

* on activation, add a hook (`register_activation_hook`)
* loop through settings array and 
* if empty -> save default value for key

**Comment by farbschein** [comment]
implement function that sets every field that has a default value to its default value whenever the field is not set. this allows us to add new fields in the future without having the user activate the plugin again to set these fields to their default value

**Comment by flegfleg** [comment]
> implement function that sets every field that has a default value to its default value whenever the field is not set. this allows us to add new fields in the future without having the user activate the plugin again to set these fields to their default value

on plugin update the plugin activation hook should fire again. 
i think activation is the right hook, or what would you hook into?
