### ISSUE TITLE
BookingCodes: Leere und doppelte Bookingcodes, wenn kein Vorrat vorhanden.

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#396]
Wenn ein Zeitrahmen mit Buchungscodes erstellt wird, zu diesem Zeitpunkt aber keine Buchungscodes in den Optionen hinterlegt waren, werden leere Buchungscodes erzeugt.

Fügt man nun nachträglich Buchungscodes in den Optionen hinzu und generiert erneut Buchungscodes für den gleichen Timeframe, werden doppelte Buchungscodes (einmal leer, einmal mit Code) erzeugt.

![image](https://user-images.githubusercontent.com/12683634/102668888-6378fe00-418d-11eb-9d2b-3c4ef35ad95e.png)

Gewünschtes Verhalten:
- Wenn keine Buchungscodes vorhanden sind, soll beim Generieren eine Fehlermeldung erscheinen "Es konnten keine Buchungscodes angelegt werden, da keine Buchungscodes zur Auswahl standen. Bitte hinterlege Buchungscodes in den CommonsBooking-Einstellungen."

**Comment by markus-mw** [comment]
@chriwen : Ist umgesetzt. Müsstest nur noch die Sprachvariablen pflegen.
