### ISSUE TITLE
Timeframe-Editor: Buchungscodes deaktivieren pro Timeframe

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#404]
Nutzerfeedback: Buchungscodes können derzeit nicht deaktiviert werden. 

Ziel:
- [ ] Checkbox im Timeframe-Editor: "Buchungscodes aktivieren"
-> Nur bei aktivierter Checkbox werden Buchungscodes im 
- [ ] Frontend und der 
- [ ] E-Mail
angezeigt.

Hinweis: im System können die Buchungscodes trotzdem weiterhin gespeichert werden. Sie sollten jedoch nicht im Frontend/Templates ausgegeben werden.

**Comment by markus-mw** [comment]
@chriwen : An welcher Position soll die Checkbox angezeigt werden. Ist ihre Darstellung von irgendwelchen Bedingungen abhängig?

**Comment by markus-mw** [comment]
@chriwen : Das ist soweit ich es ohne die Antworten auf die Fragen bearbeiten konnte in feature/issue-404 umgesetzt. Schau doch bitte mal, ob das so für dich funktioniert.
