### ISSUE TITLE
Timeframe-Editor: Buchungscodes nur generieren wenn Checkbox Buchungscodes generieren aktiv

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#405]
Momentan werden die Buchungscodes beim Speichern eines ganztägigen Timeframes generiert, unabhängig ob die Checkbox "Buchungscodes generieren" gewählt ist oder nicht.

Codes sollen nur generiert werden, wenn Checkbox gewählt.

**Comment by markus-mw** [comment]
@chriwen : Ist umgesetzt.

**Comment by chriwen** [comment]
@markus-mw : funktioniert bei mir leider nicht. Hab im master getestet. Branch 405 gibt es nicht, oder? 
Was hab ich gemacht:
- timeframe angelegt, fullday, checkbox codes generieren an, speichern. keine Codes erzeugt. Vorrat an Codes in Optionen vorhanden.

**Comment by markus-mw** [comment]
@chriwen : Ich habe dev auf den neuesten master-Stand gebraucht und kein Problem feststellen können: https://dev.commonsbooking.org/wp-admin/post.php?post=453&action=edit

P.S.: Kannst du auf dem Server mal php-cli installieren lassen, damit wir composer benutzen können?
