### ISSUE TITLE
Inkompatibilität mit Wordpress-Installationen mit Datenbank-Tabellen-Prefix ($wpdb->prefix)

### ISSUE THREAD

**Issue by nelarsen** [wielebenwir/commonsbooking#406]
Ich habe von CB 0.9.x migriert.
Beim Anlegen eines Zeitraumes erscheint dieser Fehler:

![grafik](https://user-images.githubusercontent.com/2667894/102986774-a03c5080-4511-11eb-8875-18c4fac0addc.png)

Das liegt wohl daran, dass unsere WP-Installation mit einer Prefix af34pSW_ arbeitet (alle Tabellennamen fangen damit an). Das wird aber von Timeframe.php nicht berücksichtigt 
SELECT DISTINCT pm1.post_id from wp_postmeta pm1

An anderen Stellen wird das schon berücksichtigt, z.B. BookingCodes.php:
$table_name = $wpdb->prefix . self::$tablename;
SELECT * FROM $table_name

**Comment by nelarsen** [comment]
Ich arbeite gerade an einem PR für das Problem.

**Comment by nelarsen** [comment]
Hier ist eine Änderung, die m.M.n. das Problem lösen sollte. (Damit habe ich leider CB2 noch nicht zum Laufen bekommen; scheint doch etwas komplizierter zu werden...)

https://github.com/nelarsen/commonsbooking/tree/bugfix/issue-406

Soll ich ein Pull Request öffnen? Für welchen Branch?

**Comment by chriwen** [comment]
Hallo. Vielen Dank für die Fehlermeldung und den Input. 
Wir legen für jedes issue einen Branch in der Form bugfix/issue-000 (nr. Des issues) an. 

Du kannst gerne einen entsprechenden branch anlegen und dann einen pull request stellen. Wir schauen regelmäßig drauf. 

Vielen Dank und schöne Grüße 
Christian

**Comment by chriwen** [comment]
Alternativ können wir das Thema aber auch intern lösen. Sollte mit dem nächsten Release behoben sein

**Comment by chriwen** [comment]
@markus-mw : Frohe Weihnachten :-) 
Kannst du dir das bei Gelegenheit bitte priorisiert anschauen? Das scheint leider bei mehreren Nutzern Probleme bei der Migration zu verursachen.

**Comment by nelarsen** [comment]
> Hallo. Vielen Dank für die Fehlermeldung und den Input.
> Wir legen für jedes issue einen Branch in der Form bugfix/issue-000 (nr. Des issues) an.

Das habe ich bereits gemacht, siehe Link. Allerdings in einem Projektfork. Ich habe hier keine Schribrechte, denke ich.

> Du kannst gerne einen entsprechenden branch anlegen und dann einen pull request stellen. Wir schauen regelmäßig drauf.
> Achso und den pr immer auf den Master.

Ich habe das noch nicht so häufig gemacht. Ich frage daher lieber einmal "zu viel". Soll ich den pr stellen?

Viele Grüße!

**Comment by chriwen** [comment]
@nelarsen : wir werden den Bugfix intern bearbeiten. Das geht wahrscheinlich etwas schneller für uns zum testen und ausrollen.

**Comment by chriwen** [comment]
@markus-mw : Hab Pullrequest gestellt #410

**Comment by chriwen** [comment]
@nelarsen : Hab den Bugfix in der aktuellen Version 2.2.14 integriert. Kannst du mal mal über die Wordpress-Funktion aktualisieren und dann eine kurze Rückmeldung geben, ob es nun funktioniert? Danke.
