### ISSUE TITLE
Migration: BookingCodes nicht übernommen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#414]
Im aktuellen Master bzw. release/2.2.14 werden bei der Migration die Buchungscodes der bookable-Timframes nicht importiert.  Kannst du das bitte nochmal prüfen. Ich konnte auf die schnelle nichts finden.
UPDATE:
@markus-mw : Konnte das Problem eingrenzen. Es tritt auf, wenn der Timeframe bereits schon einmal importiert worden war, dann in CB2 gelöscht wurde (in Papierkorb) und dann die Migration erneut ausgeführt wurde.
Wenn man den Papierkorb leert, funktioniert es wieder.
Irgendwo fehlt da wohl ne Abfrage, dass Posts/Timeframes im Papierkorb nicht in den Queries berücksichtigt werden sollen.

**Comment by chriwen** [comment]
@markus-mw : Konnte das Problem eingrenzen. Es tritt auf, wenn der Timeframe bereits schon einmal importiert worden war, dann in CB2 gelöscht wurde (in Papierkorb) und dann die Migration erneut ausgeführt wurde.
Wenn man den Papierkorb leert, funktioniert es wieder. 
Irgendwo fehlt da wohl ne Abfrage, dass Posts/Timeframes im Papierkorb nicht in den Queries berücksichtigt werden sollen.

**Comment by markus-mw** [comment]
@chriwen : Verstehe. Dann passe ich den query so an, dass nur die aktiven Posts berücksichtigt werden.

**Comment by markus-mw** [comment]
@chriwen : Wenn ich den Query entsprechend anpasse bedeutet das, dass auch die Timeframes, zu den die Booking Codes gehören, immer wieder neu angelegt werden müssen. Ist das so gewollt?
Was ist die Erwartungshaltung an die Migration im Zusammenhang der restlichen Elemente? Soll es da auch so laufen, dass gelöschte Elemente ignoriert werden und stumpf alles frisch angelegt wird? Ich versteh den Sinn nicht so recht (Ich migriere, lösche ein Element und migriere dann neu, damit es wieder neu angelegt wird?)

**Comment by chriwen** [comment]
Ok. Dann lassen wir das erstmal und ich schreib dazu was in der Doku. Der Fall tritt ja nur auf wenn man während der Migration nochmal neu startet und alles löschen will um nochmal neu zu testen. Dann müssen Nutzer darauf achten auch den Papierkorb zu leeren.

**Comment by chriwen** [comment]
@markus-mw : Nochmal zu deiner generellen Frage: Nein, es soll nicht alles wieder gelöscht und stumpf neu angelegt werden. Gewünscht ist, dass ggf. geänderte Daten die bereits bestehenden importierten Datensätze aktualisieren. ein typisches Szenario ist z.B., dass während der Migrations-Testphase z.B. noch neue Buchungen über das alte Plugin erzeugt werden. Diese sollen dann importiert werden, wobei aber bereits importierte Optionen oder Buchungscodes nicht nochmal neu erzeugt werden sollen.
