### ISSUE TITLE
Timeframe-Validierung: Berücksichtigung von ausgewählten Tagen bei Validierung

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#415]
Nutzerrrückmeldung:

Schritte:
- Lege 2 Timeframes an mit stundenweise und weekly Wiederholung. 
- T1 = Tage von Montag bis Freitag, Uhrzeit von 09:00 - 13:00
- T2 = Samstag, Uhrzeit von 09:00 - 16:00

T1 + T1 gehen über den gleichen Zeitraum. Für T2 sollen aber andere Öffnungszeiten als für T1 gelten.

Momentan führt das Szenario zu einem Fehler "Zeiträume dürfen sich nicht überschneiden.Überprüfe, den Zeitrahmen, um überlappende Zeiträume an einem bestimmten Tag zu vermeiden."

Dies liegt daran, dass die aktivierten Tage bei der Prüfung nicht berücksichtigt werden, oder?

Ziel:
- Prüfen, ob sich überlappende Timeframes in den aktivierten Tagen unterscheiden (prüfe auf weekly bzw. daily Wiederholung). Fehlermeldung dann nur, wenn die Überschneidung der Zeiten bei sich überschneidenden Tagen innerhalb der Wochentage befindet.

**Comment by markus-mw** [comment]
@chriwen : Ich schau mir das an. Bin mir grad nicht ganz sicher ob die Tage schon berücksichtigt werden.

**Comment by markus-mw** [comment]
@chriwen : Das müsste jetzt klappen. Bitte testen. Danke!

**Comment by chriwen** [comment]
@markus-mw : Klappt. Vielen Dank.
