### ISSUE TITLE
Booking-Tabelle Frontend: MVP / Basiskonzept

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#416]
Ich würde gerne prüfen, ob und wie wir das ganze Thema Buchungstabelle im Frontend darstellen können. 
Hier schonmal die Basis-Anforderungen:

- [x] neuer Shortcode cb_bookings für die Auflistung von Buchungen
- [x] tabellarische Liste von Buchungen mit folgenden Spalten: 
 Startdatum
 Enddatum
 Item
 Location
 BookindDate
 User
 Status
 Aktion (Button bzw. Dropdown mit Funktionen wie "Bearbeiten", Stornieren", "Buchungsdetails ansehen")

- [ ] Falls möglich pro Buchungszeile so eine Art Expand-Funktion einbauen (per Klick auf einen Pfeilbutton oder so), der dann in der Liste Detailinfos zur Buchung einblendet (z.B. Nutzerdaten, Buchungscode, Bemerkungen etc.)
- [x] List nach allen Spalten sortierbar und filterbar/suchbar (im besten Fall per Ajax und Fancy-Funktion über den Spalten-Namen ähnlich wie z.B. hier http://tablefilter.free.fr/selection-grid.php
- [x] Berücksichtung der bereits definierten Zugriffsrechte (cb_manager, Admin, Author etc.)

Bemerkung zu den Filtern:
- ideal wäre, wenn man perspektivisch bestimmte Filter speichern könnte wie  "zeige mir nur Buchungen von Item X" oder "zeige mir nur heutige Buchungen an Station  Z"

Reponsivitität:
- Die Liste sollte auch mobil nutzbar optimal funktionieren, ggf. mit anderen Daten. Szenario wäre hier z.B., dass Stationen auf Mobilgeräten einfach eine Übersicht der heutigen bzw. z.B. der nächsten Buchung anzeigen können und dann z.B. über einen Klick die relevanten Daten wie Buchungscode, Nutzerdaten (Adresse, Telefonnnummer) aufrufen können. 

Fürs Editieren (Button in Spalte Aktion) würden wir dann zunächst ins Wordpress-Backend auf den Timeframe-Editor wechseln. (ggf. prüfen wir späte, ob einzelne Änderungen auch direkt sinnvoll im Frontend erfolgen können)

Könntest du hierzu mal prüfen, wie das umzusetzen ist oder falls relativ einfach möglich, gleich nen MVP ausetzen?

**Comment by markus-mw** [comment]
@chriwen : Das darstellen in Tabellenform sowie das listen, sortieren und filtern stellt keine große Herausforderung dar. Stornieren und Details darstellen ist kein großes Thema. Was ich als eher problematisch sehe ist die bearbeiten Funktion. Wie soll das aussehen? Soll das ähnlich wie im Backend funktionieren oder ist das eher eine abgespeckte Variante bei der ein paar bestimmte Felder editiert werden können sollen?

**Comment by chriwen** [comment]
Ok. Dann lassen wir bearbeiten weg und springen dazu ins backend. Wenn die anderen Sachen funktionieren wäre schon mal super.

**Comment by chriwen** [comment]
Achso und die Seite am besten per shortcode cb_bookings einfügbar machen.

**Comment by markus-mw** [comment]
@chriwen : Ich gehe jetzt mal davon aus, dass Nutzer ihre eigenen Buchungen einsehen können sollen, oder ist das mehr zur Verwaltung gedacht?

**Comment by chriwen** [comment]
Ja, für beides. Nutzer ihre eigenen und rollen mit entsprechenden Rechten mehr.

**Comment by chriwen** [comment]
Also nochmal zur Ergänzung: soll zwei szenarien abbilden: 
- Nutzer ihre eigenen Buchungen ansehen und per Link auf die Buchungsdetailseite (also die bereits existierende booking-single) 

- Admins und cb-Manager sollen darüber Buchungen suchen und ansehen können. Für weitere Bearbeitungen kann dann ins Backend gesprungen werden. 

Wenn möglich wären folgende einfache Anpassungen an der Buchung direkt übers Frontend super: 
- Stornieren
- Status setzen auf "Rückgabe ist erfolgt" (Buchung also beendet - bisher noch nicht implementier)

**Comment by markus-mw** [comment]
@chriwen : Ich hab jetzt mal den ersten Wurf gepusht (feature/issue-416). Damit solltest du schonmal die Buchungen in Listenform mit Paginierung bekommen. Sortierung (+ Speicherung) und Suche gehe ich als nächstes an.

**Comment by chriwen** [comment]
@markus-mw Supi, läuft erstmal. Vielen Dank. Daten sind da. 
Erstes Feedback: Ich konnte trotz Admin-Account keine anderen Buchungen sehen.
Nächstes Ziel wäre:
- [ ] Filter / Suche (nach Spaltenwerten)
- [ ] Interface-Optimierungen (ich liefere dazu noch ein Scribble)
Speichern erstmal nicht höchste Priorität.

**Comment by markus-mw** [comment]
@chriwen : Ich habe jetzt noch die Sortierung, Suche und Speicherung der letzten Einstellung ergänzt. Leider ist die Spaltensuche nicht sonderlich schlau, sodass immer nur nach dem zuletzt eingegebenen Begriff gesucht wird.
Warum du keine Buchungen siehst, müssten wir uns mal zusammen ansehen. Das kann ich noch nicht nachvollziehen.

**Comment by markus-mw** [comment]
@chriwen : Ich habe den aktuellen Stand auf Stage ausgerollt. Was noch fehlt:
* Paginierung bei vielen Seiten per ... kürzen
* Sortierung
* Filterauswahl abhängig von anderen Filtern aktualisieren (falls das benötigt wird), ansonsten kann es zu leeren Ergebnissen kommen.

**Comment by markus-mw** [comment]
@chriwen : Ich habe den aktuellen Stand jetzt auf Stage ausgecheckt. Folgende Sachen sind jetzt mit drin:

- Sortierung
- Paginierung (überarbeitet)
- Anpassung der Filter -> Wenn Auswahl getroffen wurde, werden andere Auswahlmöglichkeiten an die Ergebnismenge angepasst
- Filter zurücksetzen,
- Titel verlinkt
- Überschrift raus
- Button auf Buchungsdetailseite

Ich glaub das wars im Wesentlichen. Schau es dir mal an und lass mich wissen, was noch zu tun ist.
