### ISSUE TITLE
Timeframe-Editor: Maximal Buchungsdauer erhöhen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#417]
Nutzeranfrage:
- Kann die maximale Buchungsdauer auf unendlich gestellt werden oder führt das dann zu größeren Problemen?
- Szenario: Werkzeugverleih, bei dem Werkzeuge auch mehrere Monate ausgeliehen werden können. 

Könnte man das alternativ durch eine max. Buchungsdauer von sagen wir mal 200 Tage lösen und das einfach erstmal als weitere Option in das Dropdown aufnehmen. Quasi als unbegrenzt-Option mit halt dem 200 Tage-Anschlag?

**Comment by markus-mw** [comment]
@chriwen : Das können wir machen. Bei so langen zeiträumen müssen wir aber nochmal alle Sonderlocke durchprüfen. Ich denke dann an das überbuchen von Tagen zum Beispiel. Grundsätzlich funktioniert das aber. Ich habe es lokal schon getestet. Auch das Blättern durch die Monate macht keine Probleme.

**Comment by danielappelt** [comment]
Ich habe einen Vorschlag hierfür eingereicht (#576). Mit einem numerischen Textfeld ohne Obergrenze hat man als User alle Möglichkeiten ohne irgendwo noch eine weitere Option dafür vorsehen zu müssen. Man erhält Spinner-Buttons für die Maus-Eingabe und Eingaben werden vom Browser validiert (ab IE 10).

Testen mit beliebig großen Werten steht nun noch aus, denke ich.
