### ISSUE TITLE
[WP 5.5+] Nutzerfeedback: Fehlermeldungen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#420]
Hallo Hannes oder andere,
 
leider funktioniert es auch dann nicht.
Es kommt die Meldung unter der Artikelseite, wenn man buchen möchte: Notice: Undefined index: location in /Pfad/zur/WP-Installation/wp-content/plugins/commonsbooking/src/View/Item.php on line 51
Dieser Artikel ist derzeit nicht verfügbar.
Ich habe allerdings einen Zeitrahmen hinzugefügt.

Noch etwas, es kommt immer diese Fehlermeldung beim erstellen eines Artikel, Standorts oder einer Normalen Seite,…:

Notice: register_rest_route wurde fehlerhaft aufgerufen. Der Definition der REST-API-Route für commonsbooking/v1/availability fehlt das erforderliche Argument permission_callback. Für REST-API-Routen, die für öffentlichen Zugriff gedacht sind, benutze __return_true als Berechtigungs-Callback. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 5.5.0 hinzugefügt.) in /Pfad/zur/WP-Installation/httpdocs/wp-includes/functions.php on line 5311
 
Notice: register_rest_route wurde fehlerhaft aufgerufen. Der Definition der REST-API-Route für commonsbooking/v1/availability/(?P[\d]+) fehlt das erforderliche Argument permission_callback. Für REST-API-Routen, die für öffentlichen Zugriff gedacht sind, benutze __return_true als Berechtigungs-Callback. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 5.5.0 hinzugefügt.) in /Pfad/zur/WP-Installation/httpdocs/wp-includes/functions.php on line 5311
 
Notice: register_rest_route wurde fehlerhaft aufgerufen. Der Definition der REST-API-Route für commonsbooking/v1/availability/schema fehlt das erforderliche Argument permission_callback. Für REST-API-Routen, die für öffentlichen Zugriff gedacht sind, benutze __return_true als Berechtigungs-Callback. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 5.5.0 hinzugefügt.) in /Pfad/zur/WP-Installation/httpdocs/wp-includes/functions.php on line 5311

**Comment by markus-mw** [comment]
@chriwen : Die erste Notice ist entfernt. Die API-Themen sind erst in WP 5.5 dazugekommen. Aktuell entwickeln/testen wir noch mit 5.4.
