### ISSUE TITLE
Doku zu Template Tags für Mail-Templates fehlt.

### ISSUE THREAD

**Issue by RalphBike** [wielebenwir/commonsbooking#421]
Hi, 

die in der V. 0.9.4 verlinkte Wikiseite zu "Template Tags" enthält keinen Inhalt, die Weiterleitung liefert ebenfalls eine leere Seite. Daher fehlt hier die Doku zu einem recht essentiellen Feature. 

Verlinkt ist https://dein-lastenrad.de/index.php?title=Settings:Template_Tags.
Übrigens ungelogen 10x auf der Seite zum bearbeiten der Mail-Templates.
Die Suchfunktion im Wiki hat mir ebenfalls nicht weitergeholfen.

Falls mir jemand sagen kann, wo ich die Infos finde, gerne! Alternativ suche ich nach dem Tag für die Kontakt-Infos der Location.

**To Reproduce**
Auf Links "Template Tag" im wp-admin/options-general.php?page=commons-booking klicken.

**Expected behavior**
Der Link führt zu einer Seite mit den Infos.

PS: Falls unsere penibel aktuell gehaltene 0.9.4.14 zu alt ist, bitte ich das zu entschuldigen, aber mir wird von WP noch kein Update angeboten :-/
PPS: Ja, technisch betrachtet ist dies nicht zwingend ein Fehler im Code, sondern eventuell ein Fehler im Wiki.

**Comment by RalphBike** [comment]
Ah... `{{LOCATION_CONTACT}}` isses. Der Bug ist trotzdem weiterhin relevant.

**Comment by chriwen** [comment]
@RalphBike : Vielen Dank für dein Feedback. 

Es gibt mittlerweile das neue CommonsBooking. Dieses ist ein separates Plugin, das es von Grund auf neu entwickelt wurde. Vielleicht magst du es dir mal installieren und testen. Das Plugin funktioniert grundsätzlich schon stabil und wird in den nächsten Monaten noch intensiv weiterentickelt. Wir würden uns freuen, wenn du es mal testest und uns ggf. Rückmeldung gibst, wenn noch etwas fehlt oder nicht wie gewünscht funktioniert.
Ansonsten empfehlen wir grundsätzlich eine Migration auf die neue Version. Mehr Informationen findest unter https://commonsbooking.org/
Trage dich dort am besten in den Newsletter ein, dann erfährst du immer alle News rund um das neue CommonsBooking.

Die Doku von CB 0.9.x ist auch auf die neue Seite umgezogen. Wir schauen uns ma die falschen Verlinkungen auf dein.lastenrad.de an.
https://commonsbooking.org/docs/informationen-zur-alten-version-0-9/bookings-template-tags-verson-0-9/


Viele Grüße,
Christian

**Comment by chriwen** [comment]
@RalphBike : Noch ein Hinweis bezüglich des Updates. Das neue CommonsBooking wird nicht als Update zu 0.9.x angeboten, sondern ist ein neues, separates Plugin: https://de.wordpress.org/plugins/commonsbooking/
Da die Änderungen im Code so umfangreich waren, können wir das nicht über die normale Update-Funktion anbieten.
Bitte schau mal in unserer Doku, wie du von der alten auf die neue Version migrieren kannst: https://commonsbooking.org/docs/installation/migration-von-cb1/

Bei Fragen schreib uns gerne über die Kontaktmöglichkeiten auf der Webseite https://commonsbooking.org/kontakt/

**Comment by chriwen** [comment]
@RalphBike : Da ich keine Rückmeldung mehr erhalten habe, schließe ich das Thema und gehe davon aus, dass damit deine Frage beantwortet wurde. Viele Grüße, Christian
