### ISSUE TITLE
Warning: Artikel-Detailseite/Kalendar: DateTime::setTimestamp()

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#427]
z.B. derzeit hier:
https://www.kasimir-lastenrad.de/cb-items/e-lastenrad-buergerzentrum-vingst/

Warning: DateTime::setTimestamp() expects parameter 1 to be int, string given in /var/www/clients/client4066/web11636/web/kasimir-lastenrad.de/wp-content/plugins/commonsbooking/src/Model/Day.php on line 251

**Comment by chriwen** [comment]
@markus-mw Timeframe scheint in Ordnung:

== Table structure for table wp_postmeta

|------
|Column|Type|Null|Default
|------
|//**meta_id**//|bigint(20)|No|
|post_id|bigint(20)|No|0
|meta_key|varchar(255)|Yes|NULL
|meta_value|longtext|Yes|NULL
== Dumping data for table wp_postmeta

|61654|7454|_edit_lock|1610058523:4
|61655|7454|_edit_last|2966
|61657|7454|type|2
|61658|7454|timeframe-max-days|3
|61659|7454|location-id|3591
|61660|7454|item-id|3634
|61661|7454|timeframe-repetition|w
|61662|7454|full-day|on
|61663|7454|start-time|00:00
|61664|7454|end-time|00:00
|61665|7454|grid|0
|61666|7454|repetition-start|1611532800
|61667|7454|weekdays|a:5:{i:0;s:1:&quot;1&quot;;i:1;s:1:&quot;2&quot;;i:2;s:1:&quot;3&quot;;i:3;s:1:&quot;4&quot;;i:4;s:1:&quot;5&quot;;}
|61668|7454|repetition-end|1614297600
|61669|7454|prevent_delete_meta_movetotrash|3869906276

**Comment by chriwen** [comment]
Evtl. Besonderheit: Timframe wurde durch einen Nutzer mit der Rolle cb_manager angelegt.

**Comment by chriwen** [comment]
@markus-mw Ich hab was gefunden: es gibt eine Buchung ohne Startdatum. Wie die entstanden sein kann, hab ich keine Ahnung. Können wir serverseitig nochmal ne Validierung einbauen, dass auch Buchungen nicht gespeichert werden, wenn ihnen zumindest folgende Daten fehlen: Item, Location, Start-Datum, End-Datum?

**Comment by markus-mw** [comment]
@chriwen : Item und Location wurden bereits geprüft. Ich habe das jetzt für das Start- und End-Datum für Buchungen ergänzt.

**Comment by chriwen** [comment]
ok. Ist schon im Master, oder?

**Comment by markus-mw** [comment]
@chriwen : Ja, war aus meiner Sicht nichts kritisches dabei.
