### ISSUE TITLE
Karte in den Core implementieren

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#429]
Karte in Core implementieren

**Comment by markus-mw** [comment]
@chriwen : Du kannst feature/issue-429 mal probieren. Das funktioniert schon recht gut. Ich habe noch nicht alle Features überarbeitet, aber die Karte wird mit Locations, Verfügbarkeiten und sonstigen Infos versorgt.

**Comment by chriwen** [comment]
@markus-mw : ja, cool. Bin beeindruckt. Das schaut schon ziemlich gut aus. 
Was mir bei schnellem Blick aufgefallen ist: Die Verfügbarkeiten auf der Map stimmen nicht mit denen im Kalender überein.
Beispiel siehe hier:
https://stage1.commons-booking.org/karte-2/
z.b: Leila
![image](https://user-images.githubusercontent.com/12683634/104124114-357f7780-534f-11eb-9317-576a95e49f00.png)


Im Kalender:
![image](https://user-images.githubusercontent.com/12683634/104124124-4334fd00-534f-11eb-83ef-29ea21f52589.png)

Die Filter scheinen ja auch schon grundsätzlich zu tun. Hier müsste ich aber nochmal intensiver prüfen. Momentan werden jeweils keine Ergebnisse angezeigt. 

Toll, dass das so schnell geklappt hat 👍

**Comment by chriwen** [comment]
@markus-mw Der Branch ist gerade auf stage1 aktiviert. Kannst das gerne auch mal testen.

**Comment by markus-mw** [comment]
@chriwen : Die Darstellung der gebuchten/geschlossenen Tage funktioniert jetzt auch. (Branch ist aktualisiert)

**Comment by chriwen** [comment]
@markus-mw : Super. läuft. Bei mir hat die Karte noch ein Dauer Lade-Icon, das quasi nicht weggeht. Ist das bekannt?
![image](https://user-images.githubusercontent.com/12683634/104240365-3e11a400-545c-11eb-8c9b-364e01c00ddf.png)

**Comment by markus-mw** [comment]
@chriwen: Das Problem dass der Spinner nicht verschwindet, ist "behoben". Da kommt es zu irgendeinem Fehler, wenn die max_cluster_size Einstellung = 0 ist. Ich wollte da jetzt nicht groß Aufwand für verschwenden und hab das mal auf mind. 10 gesetzt.

Kannst du bitte nochmal testen und mich wissen lassen, was noch getan werden sollte?
