### ISSUE TITLE
Codes: csv-Export Umbrüche

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#431]
- [ ] Bei Hannes, KASIMIR-Live-Plattform (Echtes Excel auf Mac): Zwischen dem Komma nach dem Artikel und dem Code soll kein Zeilenumbruch sein.
![grafik](https://user-images.githubusercontent.com/28141760/104041022-ad776180-51d8-11eb-91ad-641c5e467433.png)

**Comment by chriwen** [comment]
@hanneskasimir : Bei mir tritt das nicht auf. Kannst du mir sagen, von welcher Installation das ist?

**Comment by hanneskasimir** [comment]
Hm. Ist von kasi live.
