### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#432]
* Willkommens-Box
* Links-Box
   * Dokumentation
   * Newsletter
   * Donate?

Um direkt ein wenig Mehrwert zu haben, könnten wir Admins die möglichkeit geben, einen eigenen Text auf die Seite zu setzen. 
Also: Setting "[ ] Dashboard anpassen" und "Textfeld Dashboard Text", dort können Admins einen  eigenen Text für Stationsbetreibende schreiben, der Ihnen dann statt der technischen Doku angezeigt wird

**Comment by flegfleg** [comment]
<img width="800" alt="CleanShot 2021-01-15 at 11 07 09@2x" src="https://user-images.githubusercontent.com/4009931/104711639-e906b400-5721-11eb-83b5-014c87521c2c.png">

gepusht

**Comment by chriwen** [comment]
@flegfleg : sehr schick. Vielen Dank. Geht direkt ins Release heute :-)
