### ISSUE TITLE
Backend-Zeitrahmen: Buchungscodes konfigurieren

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#436]
- [x] "Buchungscodes anzeigen" bei Stundenweise Ausleihen nicht anzeigen
- [x] Checkbox "Buchungscodes generieren" soll eingeblendet sein, sobald Checkbox "Ganzer Tag" aktiv und nicht erst, wenn Start- und Enddatum ausgefüllt ist
- [x] Checkbox "Buchungscodes anzeigen" erst eingeblendet werden, wenn Checkbox "Buchungscodes generieren" aktiviert wird.
- [x] Buchungscodes generieren soll über Buchungscodes anzeigen sein

![grafik](https://user-images.githubusercontent.com/28141760/104750947-09039b00-5755-11eb-84a7-d8f5c4ed803e.png)

**Comment by chriwen** [comment]
@markus-mw Da stimme ich dir zu. Bitte wieder so ändern, wie von dir beschrieben. Ich beschreibe das in der Doku nochmal. 
@hanneskasimir zur Info.

**Comment by markus-mw** [comment]
@chriwen : Die Buchungscode Einstellungen sind jetzt erst dann auswählbar, wenn ein Start- und Enddatum gewählt wurde.

**Comment by hanneskasimir** [comment]
fein, jetzt muss @chriwen nur noch texten.
