### ISSUE TITLE
Geo-Koordinaten für Standorte anlegen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#441]
Problem bei aktueller Implementierung:
- keine Geo-Koordinaten vorhanden, deshalb keine Locations in der Karte angezeigt

Todo:

- [x] Map Admin-Funktion implementieren  (aus dem ursprünglichen Plugin) und so anpassen, dass die Metabox-Teile im CPT Location enthalten sind. Erster Entwurf im Branch 441
- [x] Automatische Geo-Kodierung beim Speichern einer Location implementieren (Funktion in der API ja bereits enthalten)
- [x] Script schreiben, welches für alle Standorte prüft, ob Geo-Koordinaten vorhanden sind und diese, wenn leer, anlegt. Dieses Script soll z.b. nach der Migration oder bei der initialen Installation / Update des Plugins ausgeführt werden (kann in die Plugin::runTasksAfterUpdate integriert werden)
- [x] Globale Anpassung der geo-Koordinaten-Felder in post_meta. Die Felder sollen  geo_latitude und geo_longitude (ohne prefix) heißen, um sich am Standard zu orientieren https://codex.wordpress.org/Geodata

**Comment by markus-mw** [comment]
@chriwen : Die Änderungen sind jetzt in deinem Branch umgesetzt. Teste doch bitte mal.
