### ISSUE TITLE
Standorte in Zeitrahmen-Dropdown bitte alphabetisch ordnen.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#446]
![grafik](https://user-images.githubusercontent.com/28141760/104818079-91517100-5825-11eb-9a66-8b11c2d447fd.png)

**Comment by chriwen** [comment]
@hanneskasimir ist bereits in neuer Version umgesetzt

**Comment by hanneskasimir** [comment]
teilweise ist sortiert, leider nicht komplett.
![grafik](https://user-images.githubusercontent.com/28141760/144611540-a93343d6-ffb7-4f93-8b59-f9f4bff01c0d.png)

**Comment by chriwen** [comment]
@markus-mw Kannst du mal prüfen, warum das nicht sortiert? Danke

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Ist der Fehler noch da? Ich habs gerade auf Stage getestet und aktuell passt die Sortierung dort.

**Comment by hanneskasimir** [comment]
ja, leider noch da. gilt für Artikel und Stationen!
ganz frische Screenshots ;-)
![grafik](https://user-images.githubusercontent.com/28141760/144708804-c9578821-05f1-483b-ac62-61dd85a04f7e.png)
![grafik](https://user-images.githubusercontent.com/28141760/144708813-d1954741-c0a9-4b15-8a22-27b8ab0dd2d7.png)

**Comment by markus-mw** [comment]
![image](https://user-images.githubusercontent.com/22905753/144708871-27951515-6740-4aab-b99d-8c85268cea34.png)
![image](https://user-images.githubusercontent.com/22905753/144708916-b5eb4e42-170f-4bdf-a97d-7bfd22451c8c.png)

Bei mir ganz frisch... oO

**Comment by hanneskasimir** [comment]
ah! es scheinen bei mir zwei sortierte Liste zu sein.

**Comment by hanneskasimir** [comment]
vielleicht hat es irgendwas mit mir als Autor zu tun?

**Comment by hanneskasimir** [comment]
ja, das ist es! die obere Liste hat nur Einträge, die ich angelegt habe!

**Comment by markus-mw** [comment]
@hanneskasimir : Das war ein guter Tipp. Jetzt sollte es passen.

**Comment by hanneskasimir** [comment]
Passt, DANKE!

**Comment by chriwen** [comment]
@hanneskasimir Danke für dein Top-Testing. Du bist echt ein Fuchs im Aufspüren dieser versteckten Fälle !! 👍 
@markus-mw Danke fürs Lösen :-)
