### ISSUE TITLE
Verlinkungen für cb_manager entfernen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#447]
- [x] Navipunkt "Karte" für cb_manager ausblenden.
- [x] Link zu "Einstellungen" für cb_manager aus Dashboard entfernen

**Comment by markus-mw** [comment]
@hanneskasimir : Meinst du mit Navipunkt "Karte" den Menüpunkt unter dem "Commons Booking" Bereich?

**Comment by hanneskasimir** [comment]
Ja!

**Comment by markus-mw** [comment]
@hanneskasimir : Ist erledigt. Ich habe die Maps/Karten auch vom Dashboard für den CB Manager entfernt. Macht dann ja auch keinen Sinn.
