### ISSUE TITLE
Fatal Error wenn "Vorschau" im "Zeitrahmen bearbeiten" bearbeiten wird 

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#451]
**Describe the bug**

<img width="763" alt="CleanShot 2021-01-18 at 13 07 32@2x" src="https://user-images.githubusercontent.com/4009931/104913615-27081000-598e-11eb-906e-5fcde87c08b4.png">
<img width="317" alt="CleanShot 2021-01-18 at 13 07 25@2x" src="https://user-images.githubusercontent.com/4009931/104913628-2d968780-598e-11eb-8412-f0271d367724.png">

**To Reproduce**
Neuer Zeitrahmen -> Speichern -> Veröffentlichen -> Vorschau

**Comment by chriwen** [comment]
@flegfleg Das direkte Aufrufen eines Timeframes ist nicht vorgesehen, außer es handelt sich um eine Buchung. Ich schau mal, ob wir da eine bessere Fehlermeldung anzeigen könnnen.

**Comment by chriwen** [comment]
@flegfleg : Welcher Typ Timeframe war das denn? Ich krieg das garnicht reproduziert. Bei mir kommt nur ein Notice-Error

**Comment by chriwen** [comment]
Lösung:
- CustomPosttype->Timeframe->getTemplate: Abfrage nach timeframe_typ integrieren und wenn nicht booking oder booking canceled dann single-not-allowed anzeigen.
