### ISSUE TITLE
Fehler "A pickup time but no return time has been set. Please set the return time." -> auch bei ganztägiger Buchung

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#452]
**Describe the bug**

* Fehler "A pickup time but no return time has been set. Please set the return time."
* Artikel konnte nicht gebucht werden
* Musste Zeitrahmen löschen, neu anlegen

**To Reproduce**

* cb_manager hat neuen Zeitrahmen angelegt, Fehler trat auf. 
* Ganztägig war eingestellt

https://www.kasimir-lastenrad.de/wp-admin/post.php?post=7600&action=edit
(liegt im Papierkorb)

**Screenshots**
<img width="1149" alt="CleanShot 2021-01-18 at 13 25 21@2x" src="https://user-images.githubusercontent.com/4009931/104915237-a7c80b80-5990-11eb-8595-ee55d62daebc.png">

**Comment by chriwen** [comment]
@flegfleg Sollte behoben sein.

**Comment by hanneskasimir** [comment]
ich versteh die Fehlerbeschreibung leider nicht. selbes Problem wie #548 ?

**Comment by chriwen** [comment]
@hanneskasimir Ist behoben.
