### ISSUE TITLE
"Profile" Spalte im Backend sollte nicht da sein?

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#453]
![CleanShot 2021-01-18 at 13 30 03@2x](https://user-images.githubusercontent.com/4009931/104916117-ed390880-5991-11eb-84e2-31ca08b9f49c.png)

**Comment by chriwen** [comment]
@flegfleg Die kommt von dem Übersetzungstool auf unserer Instanz. Ich schließe das Ticket deshalb hier.
