### ISSUE TITLE
(Möglicherweise) wp_options werden durch upgrade überschrieben

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#454]
**Describe the bug**

* wp_options werden möglicherweise überschrieben
In commonsbooking/src/Wordpress/Options/AdminOptions.php, https://github.com/wielebenwir/commonsbooking/blob/b2caa62b6a70aa9bd87f581bc7c495aba95d2c43/src/Wordpress/Options/AdminOptions.php#L39

**Mögliche Lösung**

      if ( empty ( $field_value ) ) {

ersetzen durch

     if (option_exists("option_name"){

wir müssen nicht nach der value checken, sondern nur ob der option key bereits exisitiert. 
Wert kann auch leer sein bei Checkboxen z.B.

**Comment by chriwen** [comment]
@flegfleg an sich gute Idee. Wir wollen aber bei bestimmten Feldern, die leer sind, den Wert wieder auf den default-Wert setzen, wenn diese z.B. einen Wert brauchen (wie E-Mail-Templates etc.). Es werden in der Funktion ja auch nur die Werte angepasst, für die ein default-Wet definiert war. Das trifft z.B. auf die Checkbox-Felder (derzeit) nicht zu. Wir könnten aber eine Prüfung einbauen, die Checkbox-Felder von diesem Restore ausnimmt.

**Comment by flegfleg** [comment]
> Wir wollen aber bei bestimmten Feldern, die leer sind, den Wert wieder auf den default-Wert setzen

Beim Upgrade/Aktiviereung? Find ich super problematisch, haben wir gerade bei kasimir gesehen (bzw. ich nur durch Zufall).  

Wenn jemand E-Mail-Templates löscht/es neue Tags gibt, gibt es eben einen Link zur Doku wo Mensch das default-Template noch mal reinkopieren kann.

**Comment by chriwen** [comment]
Bei Kasimir kann es daran  nicht gelegen haben; da die zurücksetzen–Funktion die checkbox ja garnicht neu setzt.; sondern nur die Felder für die ein default wert überhaupt definiert war. Evtl. war das bei Kasimir einfach garnicht aktiviert gewesen.?

**Comment by chriwen** [comment]
@flegfleg Check implementiert, um Checkboxen vom default zurücksetzen auszuschließen.
