### ISSUE TITLE
Map-Error: Values not in Options

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#455]
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 112 der Datei /var/www/vhosts/.......de/..............de/wp-content/plugins/commonsbooking/src/Map/MapShortcode.php verursacht. Fehlermeldung: Uncaught Exception: DateTime::__construct(): Failed to parse time string (2021-01-18 + days) at position 11 (+): Unexpected character in /var/www/vhosts/.......de/..............de/wp-content/plugins/commonsbooking/src/Map/MapShortcode.php:112
Stack trace:
#0 /var/www/vhosts/.......de/..............de/wp-content/plugins/commonsbooking/src/Map/MapShortcode.php(112): DateTime->__construct()
#1 /var/www/vhosts/.......de/..............de/wp-content/plugins/commonsbooking/src/Map/MapShortcode.php(78): CommonsBooking\Map\MapShortcode::get_settings()
#2 /var/www/vhosts/.......de/..............de/wp-includes/shortcodes.php(343): CommonsBooking\Map\MapShortcode::execute()
#3 [internal function]: do_shortcode_tag()
#4 /var/www/vhosts/.......de/..............de/wp-includes/shortcodes.php(218): preg_replace_callback()
#5 /var/www/vhosts/.......de/..............de/wp-includes/class-wp-hook.php(287): do_sh

Ursache:
Es wird auf eine in der alten Map (altes CB) verwendeten Option $commons_booking_settings['commons-booking_bookingsettings_daystoshow']; gesucht. Die gibt es aber im neuen CB nicht.
Ebenso wie eine weitere $commons_booking_settings['commons-booking_bookingsettings_maxdays']; (weiter unten im Script)

Gewünschtes Verhalten:
- Bitte in der Map-Bearbeitungsmaske (nicht in den allgemeinen CB-Options) zwei weitere Optionen hinzufügen unterhalb des Punkts "Availability":
- availability_max_days_to_show (default = 11)
- availability_max__day_count (default = 20)

Bitte für die Werte default Werte anlegen.

**Comment by chriwen** [comment]
@markus-mw : Könntest du das evtl. kuzfristig beheben. Der Fehler verhindert leider, dass die Leute ohne altes CB (wo der Wert ja schon der DB vorhanden war) Karten anzeigen lassen können. Dankesehr.

**Comment by markus-mw** [comment]
@chriwen : Bin dran.

**Comment by chriwen** [comment]
@markus-mw ach cool. dann kann ich mir meinen hotfix ja sparen .. ignoriere ihn ;-)

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben. Ich habs in den master gemerged.

**Comment by chriwen** [comment]
@markus-mw Bei mir werden im Popup nun keine dieser Optionen mehr angezeigt, also Verfügbarkeit, Öffnungszeiten, Kontaktinfos.

**Comment by markus-mw** [comment]
@chriwen : Komisch. Ich kann das nicht nachstellen. Hier eine komplett neu erstellte Karte mit aktiven Optionen:
![image](https://user-images.githubusercontent.com/22905753/104948290-5aae5e80-59bd-11eb-80d7-d9dbf774b7a0.png)
