### ISSUE TITLE
Kalender mit dem ersten Monat beginnen, in dem ein Artikel erstmalig verfügbar ist.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#458]
Ziel: Leer Kalender vermeiden.
![grafik](https://user-images.githubusercontent.com/28141760/105043966-76217400-5a66-11eb-8b30-fe9a8b2dce7c.png)

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Die Anpassung ist jetzt im master. Bitte testet es mal. Danke!

**Comment by chriwen** [comment]
@hanneskasimir Kannst du mal testen und dann schließen? auf stage1.commons-booking.org
