### ISSUE TITLE
Vereinfachung Zeitrahmen anlegen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#460]
https://miro.com/app/board/o9J_kxXD9Fk=/?moveToWidget=3074457351365206348&cot=12

Todo:

- [ ]  Übernehme full-day als Option in grid-Optionen (inkl. Anpassung  aller damit zusammenhängen Funktionen). Es gibt ja u.a. bereits die public function isFullDay - die wird aber nicht überall konsequent genutzt. 

- [ ]  Erstelle Migration-Skript, um bei einem Upgrade die bestehenden Timeframes und Buchungen entsprechend zu konvertieren

- [x]  Passe die Reihenfolge und Abhängigkeiten entsprechend dem Miro-Scribble im Editor-Screen an

**Comment by chriwen** [comment]
@markus-mw Hab im 2.5-RC Branch die Reihenfolge sowie das Ausblenden der Advanced-Days eingebaut. So kann es erstmal im nächsten Update bleiben. Die weiteren Anpassungen bitte in neuem Branch, damit wir das in einem separaten Update ausspielen können.

**Comment by hansmorb** [comment]
Das hat sich mittlerweile alles erledigt.
