### ISSUE TITLE
Kalender: Wird nicht angezeigt in Edge / Explorer (userfeedback)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#461]
Kalender in Edge / Explorer nicht angezeigt. In Firefox schon.

**Comment by danielappelt** [comment]
Ich kann das Problem reproduzieren und könnte mich darum kümmern.

**Comment by chriwen** [comment]
@danielappelt sehr gerne 😉. Wie könnte ich dich denn mal außerhalb von Github kontaktieren? Willst du mir mal ne Mail an mail@commonsbooking.org Scheiben? Viele Grüße. Christian
