### ISSUE TITLE
Fatal Error nach Installation

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#463]
Nutzer bekommt folgende Fehlermeldung nach Installation.

Ist ein Windows-Server.
PHP: aktuelle 7er Version

Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\HOMEPAGE\wordpress\wp-content\plugins\commonsbooking\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201 Stack trace: #0 D:\HOMEPAGE\wordpress\wp-content\plugins\commonsbooking\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\HOMEPAGE\wordpress\wp-content\plugins\commonsbooking\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\HOMEPAGE\wordpress\wp-content\plugins\commonsbooking\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(201): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object in D:\HOMEPAGE\wordpress\wp-content\plugins\commonsbooking\vendor\php-http\guzzle6-adapter\src\Promise.php on line 136

**Comment by markus-mw** [comment]
@chriwen : Ich befürchte da können wir nicht viel machen, weil die Webserver-Konfig angepasst werden muss. Hier ist ein Lösungsansatz für das Problem zu finden: https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738

**Comment by chriwen** [comment]
@markus-mw : Ok, Danke dir.
