### ISSUE TITLE
Permission Problem: Cannot upload Custom Marker to CB Map

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#464]
**Describe the bug**
* Even as an admin, i cannot upload images in the CB Map Screen (Both for maps i created myself, and maps of others)
* Error: "you do not have the permission to attach images"

**To Reproduce**
* Goto Maps
* Create new
* under "Custom marker", try to upload an image

**Expected behavior**
I should be able to upload and set

**Screenshots**
<img width="303" alt="CleanShot 2021-01-22 at 10 59 12@2x" src="https://user-images.githubusercontent.com/4009931/105476972-91c48e80-5ca1-11eb-976b-4ce216cd9e97.png">

**Comment by hansmorb** [comment]
Kein CB Fehler oder? Wahrscheinlich Dateiberechtigungen nicht richtig konfiguriert.
