### ISSUE TITLE
Buchungscodes: Doppelte Codes bei Standortänderung

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#466]
- Buchbarer Timeframe
- Codes werden generiert
- Standort wird durch Nutzer geändert
- Nach speichern werden nun neue Codes generiert
- Alte und neue Codes werden beide angezeigt (jeweils 2 pro Tag)

Gewünschtes Verhalten:
- Wenn Standort in vorhandenem Timeframe geändert wird, sollen die alten Buchungscodes gelöscht und durch neue ersetzt werden
- Wenn Timeframe gelöscht wird, sollen auch alle damit verbundenen Buchungscodes gelöscht werden.
- Evtl. in dem Zusammenhang einen Button einbauen, um alle für einen Timeframe generierten Codes zu löschen.

**Comment by markus-mw** [comment]
@chriwen : Die ersten beiden Punkte funktionieren. Beim dritten versteh ich den Use Case nicht ganz bzw. würde einen anderen Ansatz wählen:
Wenn der Nutzer den Haken bei "Buchungscodes generieren" entfernt und speichert, werden die Codes gelöscht. Solange das nicht getan wird, würden die Codes sowieso bei jeder Speicherung neu erzeugt werden. Was denkst du dazu?

**Comment by chriwen** [comment]
@hanneskasimir Bitte auf stage1 testen

**Comment by hanneskasimir** [comment]
läuft!

**Comment by Konafets** [comment]
Moin, 

mir wird gerade das gleiche Verhalten gemeldet. Wir wollten einen Zeitraum verlängern. Beim Speichern wurden dann zwei Codes pro Tag erstellt. Dieser Hinweis:

> Wenn der Nutzer den Haken bei "Buchungscodes generieren" entfernt und speichert, werden die Codes gelöscht.

funktioniert bei mir nicht. Wenn ich den Haken entferne und speichere, sind die Codes immer noch da.
