### ISSUE TITLE
CSV-Export Kodierung Umlaute falsch

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#467]
Nutzer hatten falschen Zeichensatz beim Importieren gewählt und deshalb Kodierungsfehler.

Zusätzlich werden Umbrüche in der CSV ausgegeben, wenn im Buchungscode-Pool (in den Optionen) die Codes mit Absätzen gespeichert sind.

Beispiel-Ausgabe der CSV:
2021-01-14,Eva,
Büropark Rodenkirchen
2021-01-15,Eva,
Büropark-Holweide
2021-01-16,Eva,
Bungalow-Siedlung
2021-01-17,Eva,
Cäcilien-Viertel
2021-01-18,Eva,
Chorweiler
2021-01-19,Eva,

Können wir
a) UTF-8 in die Datei hinzufügen
b) die Doku anpassen
c) die Umbrüche im CSV verhindern

**Comment by markus-mw** [comment]
@chriwen : UTF-8 Header ist gesetzt und die Umbrüche sind entfernt. (es kann sein, dass das nur für neue Timeframes funktioniert)
