### ISSUE TITLE
TAFELino-Fehler

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#470]
Es geht um den Freitag auf KASI-live:

- 1 Slot von 9-15 Uhr. Darauf liegt eine Dauerbuchung von 9 bis 15 Uhr
- 1 Slot von 15 Uhr (noch besser wäre 15:30 Uhr) bis 16 Uhr. Dieser Slot soll nur der Abholung für die Nutzung übers Wochenende dienen.
 
Im Frontend sieht es aber so aus, der eigentlich frei Slot von 15 Uhr bis 16 Uhr ist nicht buchbar.
![grafik](https://user-images.githubusercontent.com/28141760/106037361-df445f80-60d6-11eb-9621-9212387246fd.png)

Geht das nicht?

**Comment by chriwen** [comment]
@hanneskasimir Das Problem war denke ich die Konfiguration des Blocks. Blockierungen sollten am besten nicht über Buchungen erfolgen. Buchungen sind nicht dafür ausgelegt, intervalle etc zu berücksichtigen. Ich müsste nochmal nachprüfen, welche Regeln da genau greifen.

Aber so geht es:
Statt Dauerbuchung ein Timeframe vom Typ "Urlaub" anlegen, diesen im Intervall wöchentlich > freitags von 09:00 - 15:00 Uhr setzen. So kannst du verhindern, dass eine Buchung von Donnerstag auf Freitag nachmittag erfolgt, da zwischendrin quasi der Urlaub als Blocker gilt.
Dann einen Zeitrahmen "buchbar" Freitags von 15:00 -16:00 Uhr legen.
Hab das schon eingebaut. Schau mal ob es wie gewünscht funktioniert.

**Comment by hanneskasimir** [comment]
Danke, so geht es tatsächlich.
Ich lass das Ticket aber trotzdem mal offen, bis du die Regel geprüft hast.
Auch im Frontend ist es nicht ganz sauber, eigentlich ist Urlaub ja orange (siehe Dienstag), müsste der Freitag jetzt auch halborange sein.

![grafik](https://user-images.githubusercontent.com/28141760/106293847-be9f1580-624e-11eb-9848-f5a241a2a426.png)
