### ISSUE TITLE
Max Buchungsdauer sollte im Frontend auch abhängig von Buchungen sein

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#472]
d.h. der Mittwoch sollte hier nicht grün sein, oder? der Dienstag auch nicht?
![grafik](https://user-images.githubusercontent.com/28141760/106060560-808dde80-60f4-11eb-9a16-7ba6f1bfdd32.png)

**Comment by markus-mw** [comment]
@chriwen : Das sollte jetzt funktionieren.
