### ISSUE TITLE
Alte Nutzerrollen für ältere Installationen deaktiveren 

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#474]
die alten Nutzer-Rollen location_manager / item_manager sollen gelöscht werden. Sind in alten Installationen noch aktiv und verwirren die Nutzenden.

**Comment by flegfleg** [comment]
What should be the assigned role of the users that had item- or location- manager? 
When the role is deleted, the user has no role.

**Comment by chriwen** [comment]
die werden zum cb_manager / das Problem haben nur Instanzen, die noch eine sehr frühe Version von CB2 genutzt haben.

**Comment by flegfleg** [comment]
OK, ist die Rolle denn funktional? 
Überlegung: Wenn die Rolle nicht funktional ist, würde ich eher die Rollen löschen, so dass sie neu zugewiesen werden muss. 
Dann muss ich nicht die Benutzer an sich anfassen (würde ich in dem Rahmen gerne vermeiden, könnte Fehler produzieren).

**Comment by flegfleg** [comment]
* user roles deletion on activation
* users lose the role, need to be re-assigned
https://github.com/wielebenwir/commonsbooking/tree/bugfix/issue-474
