### ISSUE TITLE
Buchungsexport als CSV-Datei bereitstellen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#475]
- [x] Felder definierbar aus Location, Item, User
~~Zeitraum: von jetzt + x Tage~~
- [x] Konkreter Zeitraum: Datum von - bis
- [x] Cron: ja / nein (vordefinierter Zeitraum, 5 / 30 / täglich)
- [x] Dateipfad (wenn Datei angelegt werden soll)
- [x] Download-Button für manuellen Export
- [x] Filtermöglichkeit für Timeframe Typen

**Comment by chriwen** [comment]
@markus-mw : Wieviel Aufwand ist das denn etwa? Könntest du da ggf. noch diese Woche bis Donnerstag/Freitag was zaubern? Vielen Dank.

**Comment by chriwen** [comment]
@markus-mw : Bitte den Export, um alle Timeframe-Typen erweitern. Es sollte auch möglich sein, z.B. buchbare Timeframes, Stornierungn etc. zu exportieren. Per Filter

**Comment by markus-mw** [comment]
@chriwen : Wenn du magst, kannst du dir den Branch feature/issue-475 mal ansehen. Darin ist der manuelle Download soweit umgesetzt. Den cron muss ich noch umsetzen.

**Comment by markus-mw** [comment]
@chriwen : Ich hab das jetzt fertig. Da es anscheinend keine Standard-Möglichkeit für Commands gibt, hab ichs jetzt doch über den Standard WP-Cron gemacht. Bitte teste es mal. Branch feature/issue-475

**Comment by chriwen** [comment]
@markus-mw scheint nach erstem kurzen Test zu funktionieren. Supi. Es fehlen aber glaub ich noch ein paar Felder im Timeframe für Bookings z.B. Buchungscode. Wie könnten die hinzugefügt werden?

**Comment by markus-mw** [comment]
@chriwen : Die Timeframe Felder sind ein festes Paket. Ich könnte aber auch diese Felder frei definierbar machen.

**Comment by markus-mw** [comment]
@chriwen : Wie besprochen sind die Änderungen jetzt im master.

**Comment by hanneskasimir** [comment]
an welcher Stelle soll der Download-Button sein?

**Comment by markus-mw** [comment]
![image](https://user-images.githubusercontent.com/22905753/112645945-4e280580-8e47-11eb-8762-0e57a720100a.png)
