### ISSUE TITLE
Zeitrahmen-Urlaub soll auch ohne Enddatum funktionieren.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#477]
Kommt von TAFELino:
- Blocker für Eigennutzung immer Dienstags und Freitags (d.h. nicht überbuchbar)
- Grundsätzlich soll die Station aber überbuchbare Tage haben fürs Wochenende
- Damit die Blocker nicht auch immer wieder verlängert werden müssen, oder ggf. vergessen werden

**Comment by chriwen** [comment]
@hanneskasimir müsste jetzt eigentlich funktionieren, oder?
