### ISSUE TITLE
cb_manager hat zuviele Rechte für Multi-User-Szenario (Änderung item/location admin)

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commonsbooking#478]
Hi Leute, ich habe gerade CB getestet für den Multi-User-Einsatz auf Velogistics. Es funktioniert weitgehend alles so wie erwartet, was erst einmal super ist! Neue User können sich selbst auf der Seite registrieren und werden automatisch zu cb_manager Usern. Sie können dann ihre eigenen Locations/Items/Timeframes anlegen und verwalten, sehen aber nicht die Locations/Items/Timeframes der anderen. Genau so soll es sein.

Es gibt allerdings ein Recht, da cb_manager ungeeignet für dieses Szenario macht: cb_manager kann item und location admins zuweisen und bekommt dabei eine Liste *aller* registrierten cb_manager.  Wenn sich viele User registriert haben (die ja auf Velogistics gar nichts miteinander zu tun haben), erhält man dort dann die komplette Liste und kann viel Unfug stiften. Wenn ich einem fremden User z.B. aus Versehen mein Fahrrad zuweise, erscheint das dann auf einmal vollkommen unerwartet in seiner Liste.

Eine Lösung dieses Problems wäre die Einführung einer neuen User-Rolle cb_contributor (oder cb_author). Der einzige Unterschied zum cb_manager wäre, dass cb_contributor keine Admin-Rechte an andere User vergeben kann. Könntet Ihr eine solche User-Rolle ergänzen? Ich kann mir vorstellen, dass das auch in anderen Kontexten nützlich wäre.

**Comment by chriwen** [comment]
@christianvoigt Danke für deine Rückmeldung. Wir schauen uns das an. Ich denke, der einfachste Weg wäre, dass wir dem cb_manager das Recht entziehen, anderen Nutzern Admin-Rechte zu vergeben bzw. generell die Felder Standort-Admin und Artikel-Admin zu bearbeiten. Dann müsste das doch für euer Szenario passen oder?

**Comment by christianvoigt** [comment]
Ja, wenn das für Euch ok ist, für uns passt das.

**Comment by chriwen** [comment]
@markus-mw : Kannst du bitte die Rechte des cb_managers so anpassen, dass diese Rolle keine Änderungen an den Feldern Location-Admin und Item-Admin vornehmen kann. Mögliche Optionen:
- Felder für diese Rolle ausblenden
- Felder auf readonly setzen

So soll verhindert werden, dass sich cb_manager
- selbst Rechte entziehen kann
- anderen cb_managern Rechte zuweisen kann

**Comment by markus-mw** [comment]
@chriwen : Das kriegen wir hin. Ich kümmer mich drum ;)

**Comment by markus-mw** [comment]
@chriwen : Das Feld wird jetzt nur noch Administratoren angezeigt.

**Comment by chriwen** [comment]
@markus-mw Danke.

**Comment by chriwen** [comment]
@christianvoigt Ist dann im nächsten Update enthalten.

**Comment by chriwen** [comment]
@hanneskasimir Bitte finaler Test auf stage1 und Anpassung Doku
