### ISSUE TITLE
Abholhinweise in Karte anzeigen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#483]
Im Backend der Karte können aktuell "Öffnungszeiten" zum anzeigen ausgewählt werden:
![grafik](https://user-images.githubusercontent.com/28141760/106483493-dc6ab580-64ae-11eb-8cc3-20081bf05777.png)

Im neuen Commonsbooking sollten das dann die Abhol-Hinweise sein, oder? Bei aktiver Checkbox werden die jedoch aktuell nicht angezeigt.

**Comment by chriwen** [comment]
Abholhinweise und Konktatinfos wurden aus der Karte und den Optionen entfernt.
