### ISSUE TITLE
Reparatur Ayline

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#484]
Stundenweise wiederholende Reparaturen auf Ganztägige buchbare Zeitrahmen (live-KASIMIR) verursachen verrückte Darstellungen im Frontend. Screenshot ist von 17 Uhr und eigentlich sollte das Rad heute nicht mehr buchbar sein, ist es aber doch.
![grafik](https://user-images.githubusercontent.com/28141760/106484411-e345f800-64af-11eb-9b8c-a518e62b6c76.png)
![grafik](https://user-images.githubusercontent.com/28141760/106484451-eccf6000-64af-11eb-8a3e-14f7eeb48701.png)
![grafik](https://user-images.githubusercontent.com/28141760/106484526-fc4ea900-64af-11eb-9a52-998b963b6e2c.png)
![grafik](https://user-images.githubusercontent.com/28141760/106484636-1f795880-64b0-11eb-9a42-bdd374bc9789.png)

**Comment by chriwen** [comment]
@hanneskasimir Du machst aber auch echt wilde Dinge. Warum willst du die Reparatur nur stundenweise anlegen und zudem am Wochenende nicht? Kaputt ist doch kaputt ;-)
Wir müssen das im Interface nochmal optimieren und ggf. die Validierungen prüfen, aber versuch doch einfach mal, die Reparatur ganztägig ohne Wiederholung einfach von Start bis Enddatum anzulegen.

**Comment by hanneskasimir** [comment]
;-) ich war's nicht! das ist das was die Station halt so machen mit dem System

**Comment by chriwen** [comment]
@hanneskasimir ich mach das mal zu, oder?
