### ISSUE TITLE
Elementor Import nicht möglich

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#488]
Hallo,

die Artikel auf unserer Webseite, Freie Lasten, wurden mithilfe von Elementor erstellt. Bei einer Neuinstallation gehen sämtliche Elementor Informationen verloren. Wäre es möglich diese beizubehalten?

Vielen Dank und liebe Grüße

Hans

**Comment by chriwen** [comment]
@Fliwatt Vielen Dank für deine Rückmeldung. Ich kann deine Frage noch nicht ganz nachvollziehen. Kannst du mir nochmal etwas detaillierter erläutern, was genau passiert?
a) Meinst du mit Neuinstallation CommonsBooking?
b) Meinst du, dass die Elementor-Informationen nach einem Import (also dem Durchführen der Migration vom alten CommonsBooking Version 0.9.x zur neuen Version 2.x.x.) im neuen CommonsBooking nicht mehr vorhanden sind?

Oder habt ihr Wordpress neu installiert und nun fehlen die Elementor-Informationen?

Viele Grüße,
Christian

**Comment by Fliwatt** [comment]
Hallo, danke für eure Antwort. b) ist die richtige Antwort. Unsere Artikel wurden mit Elementor bearbeitet, diese Informationen werden beim Import aber nicht mit übernommen.

**Comment by chriwen** [comment]
Hi, wäre es möglich, dass du uns mal einen admin Zugang gibst? 
Würde mir das gerne mal anschauen. 

Eigentlich kopieren wir nur den kompletten Post. Deswegen wundert es mich, dass da etwas verloren geht. 

Viele Grüße
Christian

**Comment by markus-mw** [comment]
@chriwen : Ist erledigt und in den Master gemerged. Hab die Übernahme der Meta-Daten für Locations, Items und Timeframes gemacht...

**Comment by Fliwatt** [comment]
Danke! Braucht ihr noch den Admin Zugang?

**Comment by chriwen** [comment]
@Fliwatt Hallo, der Bugfix ist in der aktuellen Version enthalten. Bitte teste doch einmal, ob es bei dir nun funktioniert:
- Update auf die neue Version
- Anschließend nochmal die Migration starten

Bitte dann eine kurze Rückmeldung hier im Ticket, damit wir wissen, ob das Ticket erledigt ist.
Vielen Dank.

**Comment by Fliwatt** [comment]
Leider nicht. Bei dem Upgrade mit CB Version 2.4.2 wurden die Elementor Daten nicht mit übernommen. Bei Elementor wurden auch vor der Migration die neuen "Artikel" Seiten als mit Elementor bearbeitbar ausgewählt. Falls es zur Diagnose helfen könnte könnte ich versuchen eine anonymisierte Version der Webseite euch zum Testen zur Verfügung zu stellen.

**Comment by Fliwatt** [comment]
Vielleicht hilft das zum Beheben: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/blob/0e8a91875790fbc33d031ba31eccbef675d0ac3c/includes/Extensions/Post_Duplicator.php

Dieses Plugin kann ohne Probleme die Artikelseiten klonen, macht das dann aber anscheinend mit einer Datenbankabfrage:

`$post_meta = $wpdb->get_results( "SELECT meta_key, meta_value FROM $wpdb->postmeta WHERE post_id = $post_id" );`

Vielleicht klappt das ja so.

**Comment by chriwen** [comment]
Hallo @Fliwatt Wir haben hier einiges an Zeit investiert, um eine Migration der Elementor-Elemente möglich zu machen. Leider ist es mit der in Elementor enthaltenen und von dir vorgeschlagenen einfachen Funktion nicht so simpel umsetzbar, da wir bei der Migration auch noch einige Daten anpassen und umwandeln. Da wir leider sonst keine weiteren Anforderungen zu diesem Thema haben, müssen wir aus Ressourcengründen die weitere Arbeit an diesem Thema leider erstmal einstellen.

Es tut mir leid, dass wir hier euch eine kurzfristige Lösung anbieten können, aber wir würden hier leider nun unverhältnissmäßig viel Zeit investieren müssen, um die Kompatibilität mit einem Plugin zu lösen. Das geht dann leider zu Lasten der Entwicklung von weiteren allgemeinen Anforderungen oder Optimierungen.

Ich hoffe, ihr findet eventuell noch eine Lösung. Vielleicht wäre es auch möglich - und im Endeffekt weniger Aufwand - die Artikel und Standorte nach dem Import einmal manuell anzupassen?

Bei Fragen wende dich gerne auch per Mail an mail at commonsboking . org
Viele Grüße,
Christian

**Comment by chriwen** [comment]
@Fliwatt : Erfreuliches Update. Wir haben nochmal die Köpfe zusammengesteckt und nun doch eine für uns einfach umzusetzende Lösung gefunden. Im nächsten Release sollte dann der Import von Elementor-Einträgen möglich sein.
Wir würden uns sehr über dein Feedback freuen, ob alles geklappt hat.

**Comment by Fliwatt** [comment]
Hi, ich weiss nicht, ob das was mit dieser Issue zu tun hat aber bei mir bricht die Migration gerade ständig ab (GUI bleibt stehen und Migration wird nicht beendet) und muss dann wieder neu gestartet werden. Im Debugger steht dann:
```

10:28:13.712 Uncaught TypeError: cannot use 'in' operator to search for "length" in "<div id=\"error\">..."
    jQuery 2
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:14
    jQuery 8
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:7
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:17
    jQuery 8
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:7
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:17
    jQuery 8
    runMigration https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:7
    <anonymous> https://domain.de/flastneu/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:20
    jQuery 9
    <anonymous> https://domain.de/flastneu/wp-content/plugins/commonsbooking/assets/admin/js/admin.js?ver=5.7.1:4
    jQuery 13
        e
        t
        setTimeout handler*l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
load-scripts.php:2:1065

```

**Comment by chriwen** [comment]
@Fliwatt Danke für die Rückmeldung. Wir gehen der Frage nach, das Verhalten hatte ich so noch nicht gesehen bisher. Bei meinen Test lief das bislang erfolgreich durch.

**Comment by chriwen** [comment]
@markus-mw : Könntest du dir das nochmal anschauen, bitte?

**Comment by markus-mw** [comment]
@chriwen Ich kann das nicht reproduzieren.

**Comment by chriwen** [comment]
@hansmorb Das Ticket ist zwar schon etwas älter, lässt uns aber keine Ruhe und wird deshalb weiter bearbeitet. Habt ihr evtl. nochmal einen Versuch unternommen und neue Erkenntnisse? Ansonsten schicke uns doch gerne mal einen Admin-Zugang zu eurem System per mail an mail@commonsbooking.org - dann können wir ggf. auch mal über eine Videoschalte gemeinsam draufschauen. Irgendwie muss das ja lösbar sein.

**Comment by hansmorb** [comment]
Hi, ich bin gerade im Urlaub und komme erst
Ende des Monats zurück. Ich habe die gesamte Webseite (auch aus anderen
Gründen) jetzt von Grund auf ohne Elementor neu aufgebaut. Das gilt auch
für die Bearbeitungen an dem pull request, ich würde die gerne abnicken
aber habe meine Zugangsdaten nur auf meinem Laptop. Lg
christian-wlw ***@***.***> schrieb am Sa., 11. Sept. 2021,
20:21:
