### ISSUE TITLE
Fehler bei Klick auf "abbrechen" und "Buchung bestätigen" in einer unconfirmed-Buchung in der Buchungsliste

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#489]
![grafik](https://user-images.githubusercontent.com/28141760/107017213-23062b80-679f-11eb-9be0-6c6545506705.png)
https://stage1.commons-booking.org/cb_timeframe/jfc71h765xw96ahnx5x0geho/

**Comment by hanneskasimir** [comment]
ich konnte den Fehler erneut reproduzieren. Passiert nur, wenn man über die Buchungsliste auf die Buchungsseite kommt.

**Comment by hanneskasimir** [comment]
bei Refresh kommt der Fehler aber nicht mehr.

**Comment by hanneskasimir** [comment]
Fehler passiert egal, welche Rechte (cb_manager, Abonnent usw.)

**Comment by hanneskasimir** [comment]
ah, es fehlt ein "?" in der URL, ist das ggf. der Fehler?
![grafik](https://user-images.githubusercontent.com/28141760/107038703-31fbd680-67bd-11eb-809e-a031808044e2.png)

**Comment by hanneskasimir** [comment]
Fehler tritt jetzt auch beim Stornieren auf.

**Comment by markus-mw** [comment]
@chriwen : Das Problem war die Bestätigungsmail bzw. das Template-Rendering darin. Darin wird per CB:Get versucht Post-Informationen zu bekommen, jedoch ist dieser in dem Moment nicht per global erreichbar. Dadurch ist das SetupPost hingefallen.
