### ISSUE TITLE
Karte Kategorieren-Filter CSS rework 

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#494]
<img width="792" alt="CleanShot 2021-02-05 at 14 14 08@2x" src="https://user-images.githubusercontent.com/4009931/107038344-a84c0900-67bc-11eb-8476-f96d3e4b112b.png">

**Comment by chriwen** [comment]
@flegfleg Danke für das Update. Ich merge das jetzt in den master. Schaut gut aus soweit. Weitere Änderungen dann in nem neuen Branch.
