### ISSUE TITLE
Fatal Error GeoCoder bei Aufruf Admin-Page

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#499]
Fatal error: Uncaught Geocoder\Exception\QuotaExceeded in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/geocoder-php/common-http/Provider/AbstractHttpProvider.php:93 Stack trace: #0 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/geocoder-php/nominatim-provider/Nominatim.php(279): Geocoder\Http\Provider\AbstractHttpProvider->getParsedResponse(Object(Nyholm\Psr7\Request)) #1 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/geocoder-php/nominatim-provider/Nominatim.php(131): Geocoder\Provider\Nominatim\Nominatim->executeQuery('https://nominat...', 'en') #2 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/willdurand/geocoder/StatefulGeocoder.php(105): Geocoder\Provider\Nominatim\Nominatim->geocodeQuery(Object(Geocoder\Query\GeocodeQuery)) #3 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/src/Helper/GeoHelper.php(30): Geocoder\StatefulGeocoder->geocodeQuery(Object(Geocoder\Query\GeocodeQuery)) #4 /Applications/MAM in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/geocoder-php/common-http/Provider/AbstractHttpProvider.php on line 93
Es gab einen kritischen Fehler auf deiner Website. Bitte überprüfe den Posteingang deiner Website-Administrator-E-Mail-Adresse für weitere Anweisungen.

Erfahre mehr über die Fehlerbehebung in WordPress.

**Comment by markus-mw** [comment]
@chriwen : Das können wir dann ja auch erstmal wieder schließen, oder?

**Comment by chriwen** [comment]
@markus-mw Ja
