### ISSUE TITLE
Kalender wird ohne Enddatum nicht angezeigt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#508]
Problem mehrere Nutzenden:
- Speichern von Timeframes ohne Enddatum führt dazu, das Item als nicht verfügbar angezeigt wird.

Gewünschtes Verhalten:
- Enndatum im Timeframe leer lassen, führt dazu dass Item unbegrenzt verfügbar ist.

https://stage1.commons-booking.org/laschter%C3%A4der/e-lastenrad-buergerzentrum-vingst/
https://stage1.commons-booking.org/wp-admin/post.php?post=37866&action=edit

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben, habs gleich in den master gemerged. In dem Zuge hab ich außerdem noch eine kleine Anpassung zur Verbesserung der Performance ergänzt.

**Comment by chriwen** [comment]
@hanneskasimir bitte auf stage1 testen

**Comment by danielappelt** [comment]
@chriwen @markus-mw Wie verhalten sich Buchbare Zeitrahmen OHNE Enddatum MIT Buchungscodes. Mein Verständnis ist, dass die Buchungscodes vorgeneriert werden. In diesem Fall würde ich eine Endlossschleife und überlaufende Buchungscode-Tabelle erwarten!? Wenn dies der Fall ist, würde ich vorschlagen, dass Vorgenerieren von Buchungscodes grundsätzlich zu überdenken.

**Comment by chriwen** [comment]
@danielappelt Hast du es mal ausprobiert? Wir haben implementiert das Buchungscodes nur bei Zeiträumen MIT Enddatum generiert werden können, insofern sollte dieser Fall nicht auftreten.

**Comment by danielappelt** [comment]
@chriwen Nein :-) Wir benutzen keine Buchungscodes mehr. Ich hatte heute nur das Leer-Setzen des Enddatums bei einem Item getestet, dass ich mal bis 2038 mit Buchungscodes konfiguriert hatte - wo auch immer noch die lange Liste an Buchungscodes angezeigt wird. Wenn es bedacht wurde, passt es für mich auch so!
