### ISSUE TITLE
Station erstellen: Textanpassungen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#520]
- [ ] Link auf Stations-Seite im neuen Zab/Fenster öffnen
![grafik](https://user-images.githubusercontent.com/28141760/107777473-2a02e000-6d43-11eb-87a6-6a7834eff110.png)

**Comment by chriwen** [comment]
@hanneskasimir umgesetzt. ÜBersetzung muss über Wordpress nach Release erfolgen.
