### ISSUE TITLE
Zeitrahmen erstellen: Textanpassungen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#522]
- [ ] ![grafik](https://user-images.githubusercontent.com/28141760/107778695-acd86a80-6d44-11eb-92a1-fe9e174a1435.png)

ergänzen: "„Weitere Informationen findest Du in der Doku“→evtl. mit Link zu dieser Seite: https://commonsbooking.org/docs/erste-schritte/buchungszeitraeume-anlegen/" (neues Fenster)

- [ ] Text: „Wenn Du Wiederholung ausgewählt haben“→„hast“ nicht „haben“

- [ ] Text„Wenn Du "wöchentlich" wählen, kannst Du ...“ → „wählst“ statt „wählen“

**Comment by chriwen** [comment]
ist umgesetzt
