### ISSUE TITLE
Neue Buchungscodes aktivieren:

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#523]
Hinweis von Dominic aus Speyer, ich konnte das aber auch nachstellen:
Bzgl. der Buchungscodes: ich habe die einmal manuell geändert, aber die neuen sind noch nicht aktiv. Ich vermute, weil die vorherigen, von euch als Standard festgesetzten, schon für die zukünftigen Buchungen vorausgeplant wurden und erst ersetzt werden, wenn sie „aufgebraucht“ sind. Evtl. könntet ihr da eine Refresh-Logik implementieren? Ich werden das jetzt erstmal händisch versuchen, in der Datenbank umzubiegen.

**Comment by chriwen** [comment]
Ansatz: den bestehenden Zeitrahmen löschen und einen neuen anlegen, dann werden die Buchungscodes dafür auch wieder neu generiert.
