### ISSUE TITLE
Gendern bzw., besser: generisches Maskulinum vermeiden

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#525]
ist:

> "neuer Nutzer registrieren" 

Wunsch:

> "registrieren"

<img width="704" alt="CleanShot 2021-02-12 at 16 09 04@2x" src="https://user-images.githubusercontent.com/4009931/107785248-a51cc400-6d4c-11eb-8e2b-d2914a937dd3.png">

**Comment by chriwen** [comment]
@flegfleg erledigt
