### ISSUE TITLE
timeframe preview in frontend

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#526]
**Current behaviour:** 

* Goes to frontend, error message

**Wish:** 

* [Redirect the preview url for timeframes](https://stackoverflow.com/questions/8741485/wordpress-preview-post-link) to **item single post**

**Comment by chriwen** [comment]
@flegfleg erstmal gute Idee, aber auch evtl. verwirrend, weil mensch ja einen timeframe bearbeitet und dann plötzlich auf ner item-detailseite landet. wenn dort dann wieder auf "bearbeiten" geklickt wird, landet mensch im article editor ... 
das würd ich gern vermeiden.
ich schließe das deshalb erstmal hier. ggf. nochmal aufgreifen wenn wir advanced optimierungen machen.
