### ISSUE TITLE
Falsches Verhalten bei Abbruch von Pending-Bookings

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#532]
Klick auf "abbrechen" auf Buchungsbestätigungsseite soll zurück zum Kalender führen ohne Mail (Heute kommt Stornierungs-Hinweis und Stornierungbestätigungsmail)

aus Support-Forum dazu:

Zum Problem:

Nachdem ich angemeldet bin und Abholung und Rückgabe gewählt habe gehts mit “Weiter zur Buchungsprüfung” zur Bestätigungsseite.

Im Backend sehe ich, dass in dem Moment eine unconfirmed Buchung erstellt wird.

Wenn ich jetzt weder “Abbrechen” noch “Buchung bestätigen” drücke sondern stattdessen auf einen anderen Link klicke oder den zurück Button, dann bleibt die unconfirmed Buchung stehen und blockiert den Kalender mit den vorher gewählten Zeiten.

Das ist etwas unschön, zumal auch keine E-Mail ausgelöst wird um das zeitnah beheben zu können.

Liebe Grüße

**Comment by chriwen** [comment]
@chriwen Lösung im Zusammenhang mit Überarbeitung Mailing-Klasse implementieren

**Comment by danielappelt** [comment]
Ich kann das Problem bestätigen, dass sich so "unconfirmed" Buchungen im System anhäufen! Ein böswilliger Benutzer/Bot kann alle verfügbaren Artikel für andere Nutzer sperren, in dem er jeweils bis zur Buchungsprüfung geht und diese dann über einen beliebigen Link auf der Seite oder durch Schließen der Seite verlässt. Die "unconfirmed" Buchungen müssen dann händisch im Wordpress-Backend entfernt werden, um die Zeiträume wieder frei zu geben.

Eine erste Verbesserung wäre es, wenn ein Benutzer zu einem Zeitpunkt nur eine "unconfirmed" Buchung erzeugen kann - vorherige "uncofirmed" Buchungen also entfernt werden. Die letzte verbleibende "unconfirmed" Buchung könnte man versuchen über das Frontend abzufangen (beforeunload), was aber m.W. nicht immer zuverlässig klappt, oder aber bei Besuch der Artikel-Seite alle uncofirmed-Buchungen entfernen, die älter als x Stunden sind.

**Comment by chriwen** [comment]
@danielappelt  vielen Dank für deine Rückmeldung. Grundsätzlich ist es so, dass unconfimed Buchungen über einen Cronjob nach 10 Minuten gelöscht werden. Je nach Nutzung der Seite kann dies auch etwas länger dauern da WordPress den cronjob nur bei seiteninteraktionen auslöst. 

Als Optimierungsmaßnhme werden wir das Intervall auf 1 Min verkürzen so dass das das Problem nicht mehr so zum tragen kommen sollte.

**Comment by danielappelt** [comment]
@chriwen, alles klar. Ich habe das zugehörige Issue #201 auch gerade gefunden.
Ich kann das aktuelle Verhalten hier auch noch mal beobachten. Grundsätzlich sollte das als Lösung passen!

**Comment by danielappelt** [comment]
@chriwen: Hier scheint das Cron-Event schon zeitlich korrekt ausgeführt zu werden. Aber selbst wenn ich das Event [via wp cli](https://developer.wordpress.org/cli/commands/cron/event/run/) manuell triggere, werden hier unconfirmed-Buchungen, die schon älter als 30 Minuten sind, nicht gelöscht.

Meine Vermutung ist, dass es noch ein Problem [in der Query](https://github.com/wielebenwir/commonsbooking/blob/43f3b72512e03eba83051312ad016b1064064364/commonsbooking.php#L339) im zugehörigen Hook gibt. Vielleicht könnt ihr das noch mal testen?

**Comment by markus-mw** [comment]
@chriwen , @danielappelt : Der Query hat grundsätzlich funkioniert, aber der date_query hat nicht sauber funktioniert, weil die Serverzeitzone die für den Query verwendet wird nicht zwangsweise der in Wordpress eingestellten entsprach. Bei mir hat das dazu geführt, dass die Zeitangabe im Query eine Stunde in der Vergangenheit lag und dadurch nur Buchungen die älter als 1h 10m waren gelöscht wurden. Das ist im master-Branch korrigiert. Ich hoffe das löst das Problem.

**Comment by danielappelt** [comment]
@markus-mw : Okay, ich habe parallel auch eine Lösung implementiert (#562). Eine Vereinfachung der Query sollte in keinem Fall schaden.

**Comment by chriwen** [comment]
@danielappelt Vielen Dank für deine Fehleranalyse und dass Du direkt einen Lösungsansatz implementierst hat. Top 👍

**Comment by danielappelt** [comment]
Ich habe nun auch noch einen Lösungsvorschlag (#563) für das am Anfang genannte Mail-Problem eingereicht.

Offen wäre dann noch der Punkt, dass im Fall unconfirmed -> canceled direkt wieder auf die Artikel-Seite zurückgekehrt wird.

**Comment by markus-mw** [comment]
@danielappelt : Danke dafür. Habs gemerged.
