### ISSUE TITLE
Nur eine Kategorie wird bei der Migration übernommen

### ISSUE THREAD

**Issue by Fliwatt** [wielebenwir/commonsbooking#533]
**Describe the bug**
Unsere Artikel haben jeweils zwei Kategorien, einmal der Typ des Fahrrads und ob es gerade Ausleihbar ist oder nicht, die Kategorie "Ausleihbar" wird bei der  Migration nicht mit übernommen, der Haken wird entfernt, die Kategorie bleibt aber.

**To Reproduce**
Commons-Booking Version 0.9.4.14 mit Artikel, die jeweils zu mehreren Kategorien gehören erstellen, Migration mit CommonsBooking 2.4.2, eine Kategorie wird abgewählt sein.

**Expected behavior**
Beide Kategorieneinstellungen sollten übernommen werden.

**Comment by chriwen** [comment]
@Fliwatt Danke für deine Fehlermeldung. Kannst du mal probieren, ob der Fehler immer noch auftritt, wenn du nach der Migration CB 0.9.x deaktivierst? Bitte melde dich dann dazu kurz nochmal hier zurück. Grundsätzlich ist es so, dass wenn das alte CB noch aktiviert ist, es zu Problemen in der Darstellung der Kategorien kommen kann. Dies haben wir auch in der Doku beschrieben. Viele Grüße, Christian

**Comment by Fliwatt** [comment]
Hallo, danke für eure Antwort.
Leider tritt der Fehler auch auf nachdem CB 0.9. deaktiviert wurde.
LG

**Comment by chriwen** [comment]
@Fliwatt Ok, ich konnte den Fehler jetzt auch reproduzieren. Wir kümmern uns darum

**Comment by chriwen** [comment]
@markus-mw : Bei der Migration scheint tatsächlich nur eine Kategorie übernommen zu werden. Vielleicht hilft das hier? https://ben.lobaugh.net/blog/32372/wordpress-copy-taxonomies-from-one-post-to-another

**Comment by markus-mw** [comment]
@chriwen : Hat geholfen. Das Problem ist jetzt im master behoben.

**Comment by chriwen** [comment]
@Fliwatt Das Problem ist im nächsten Release behoben. Vielen Dank noch einmal für deine Rückmeldung.
