### ISSUE TITLE
Buchungliste: Filtermöglichkeiten für Abonnenten ausblenden/einklappen 

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#535]
o.ä. Hintergrund: die meisten werden nur eine Handvoll Buchungen haben und werden aktuell von den Filtern usw. erschlagen.

- [x] Filter erst nach Klick auf “Filtern” anwenden. Die Leute sind aufgrund der langen Ladezeiten verwirrt, weil nach Ändern der Einstellungn erstmal nichts passiert
- [x] Standardsortierung nach Startdatum absteigend. (also aktuellste Buchung am Anfang)
- [x] Filter zurücksetzen-Button einfügen
- [x] Filter-Button nicht so überdimensioniert groß 
- [x] Filter für "Alle Buchungen"

**Comment by markus-mw** [comment]
@chriwen : Schau dir doch bitte mal den aktuellen Stand an (feature/issue-535). Bis auf den Filter für "Alle Buchungen"  hab ich die Sachen soweit eingebaut.

**Comment by markus-mw** [comment]
@chriwen : Der "Alle Buchungen" Button macht nicht viel Sinn. Man muss dazu lediglich das Startdatum entfernen. Soll ich da trotzdem noch was einbauen?

**Comment by chriwen** [comment]
getestet in branch feature/issue-353

**Comment by chriwen** [comment]
ist bereits in master gemerged
