### ISSUE TITLE
Buchungskalender übersetzbar machen.

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#545]
Monate, Tage etc. sind im Kalender nur in Deutsch verfügbar, auch wenn als Sprache englisch gewählt wurde.

Gewünscht:
- Alle Ausgaben des Kalenders sollen übersetzbar sein und das Datums- und Zeitformat soll sich den lokalen Formaten anpassen (auch die Uhrzeit in der Zeitauswahl).

**Comment by markus-mw** [comment]
@chriwen : Sowohl die Sprache als auch das Zeitformat werden jetzt aus den Wordpresseinstellungen übernommen. 
Anmerkung: Damit die Änderungen greifen muss ein willkürlicher Zeitrahmen gespeichert werden, damit der Cache geleert wird. Vorher tut sich nichts.
