### ISSUE TITLE
Performance issue after plugin activation

### ISSUE THREAD

**Issue by cluk33** [wielebenwir/commonsbooking#546]
**Describe the bug**
Activation of the plugin increases page load time in the admin area from 50 ms to 6,74 s.
This does happen with version 2.2.4 and above, but not with the old plugin 'Commons Booking'.

**To Reproduce**
Install but disable the plugin, Load /wp-admin/edit.php?post_type=page => fast 
Activate the plugin, Load /wp-admin/edit.php?post_type=page => slow
Slow load times are also happening on loading a page including the calendar.

**Expected behavior**
Reasonable load times of ~2s per page.

Please let me know if I can help debugging.

**Comment by cluk33** [comment]
I have installed the Query Monitor Plugin to see if there are any slow queries involved.
What I found is that loading the admin dashboard /wp-admin/index.php with commonsbooking enabled show 50-70 slow queries while deactivating commonsbooking and reloading the dashboard shows 0 slow queries.

All those slow queries are updates on wp_options like:
UPDATE `wp_options` SET `option_value` = '....' WHERE `option_name` = 'wp_user_roles';
This query is repeated ~50 times. Each query takes ~ 0.1s summing up to ~5s.

The callstack for all those queries look like this:
    update_option()
    wp-includes/option.php:441
    WP_Roles->remove_cap()
    wp-includes/class-wp-roles.php:234
    WP_Role->remove_cap()
    wp-includes/class-wp-role.php:72
    CommonsBooking\Plugin::addCustomUserRoles()
    wp-content/plugins/commonsbooking/src/Plugin.php:408
    do_action('admin_init')
    wp-includes/plugin.php:484
    
    Any idea, what is happening here?

**Comment by chriwen** [comment]
Hi @cluk33 than you for reporting this issue. we put it on our todolist with high priority and we will keep you updated as soon as we find a solution.

**Comment by chriwen** [comment]
@markus-mw : Konnte das reproduzieren auf stage1.

**Comment by markus-mw** [comment]
@chriwen , @cluk33 : Ich glaube das bekommen wir recht leicht in den Griff, wenn die Nutzerrollen nur bei der Aktivierung erzeugt werden. Ich kümmere mich drum...

**Comment by cluk33** [comment]
Top, danke euch. Ich teste gerne eine Patch. :)

**Comment by markus-mw** [comment]
@chriwen : Ich habe ein paar Hooks geändert und ein paar Sachen verschoben. Kannst du bitte mal bugfix/issue-546 testen, ob vor allem in Sachen Rechte/Rollen für den cb_manager noch alles passt? Ich hatte mir lokal ein komplett frisches System aufgesetzt, da war alles fein. Eventuell kannst du ja auf Stage mal prüfen, ob noch alles wie vorher läuft...

**Comment by cluk33** [comment]
Die Performance im Admin Interface ist mit den Änderungen auf meinem System dramatisch besser. Die Aktivierung des Plugins macht keinen nennenswerten Unterschied mehr im Vergleich zum deaktivierten Plugin. Auch die Anzahl der SQL Queries bei Aufruf des Dashboards ist 140 auf 45 gesunken.

**Comment by markus-mw** [comment]
@cluk33 : Danke fürs testen ;)
@chriwen : Ich hab die Anpassungen jetzt mal in den master überführt. Kannst du dir bei Gelegenheit mal ansehen.
