### ISSUE TITLE
Timeframe-Editor: Validierung Uhrzeit Fehler

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#548]
**Describe the bug**
- Zeitrahmen anlegen
- Startzeit Uhrzeit eingeben (aber keine Endzeit)
- Modus zu "ganztägig" ändern
- speichern
- Fehlermeldung: Eine Abholzeit, aber keine Rückgabezeit wurde festgelegt. Lege bitte eine Rückgabezeit fest.

**To Reproduce**

**Expected behavior**
Wenn Modus "ganztägig" sollen evtl bereits eingegeben Uhrzeiten bei der Validierung ignoriert werden.

**Screenshots**
https://drive.google.com/file/d/1HR3ULTGNdKKYeTSu6BHTqf6tnBo95gYI/view

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben.
