### ISSUE TITLE
Add Linebreak output for pickup instructions and contact info for mail and template

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#555]

**Comment by hanneskasimir** [comment]
![grafik](https://user-images.githubusercontent.com/28141760/112637302-46b02e80-8e3e-11eb-870d-6db7de79902b.png)
![grafik](https://user-images.githubusercontent.com/28141760/112637360-5d568580-8e3e-11eb-965a-bf88073cbcdd.png)
![grafik](https://user-images.githubusercontent.com/28141760/112637402-69dade00-8e3e-11eb-8dca-fedc887765b7.png)
![grafik](https://user-images.githubusercontent.com/28141760/112637455-78c19080-8e3e-11eb-8b58-7f942484e199.png)

**Comment by danielappelt** [comment]
Das lässt sich im Frontend ggf. am einfachsten mit CSS lösen. Zum Beispiel auf der Buchungsbestätigungsseite via

```css
.cb-booking-single .cb-pickupinstructions > div:last-child {
	white-space: pre;
}

**Comment by chriwen** [comment]
@flegfleg : Kannst du das dir mal anschauen und ggf. daniels vorschlag implementieren? Merci
