### ISSUE TITLE
Optionaler "user"-Parameter für items shortcode

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commonsbooking#559]
Auf der Velogistics-Seite wird jeder cb_manager eine eigene Profilseite haben, auf der nur die Items aufgelistet werden sollen, die diesem user gehören. Ich würde dafür gerne den items shortcode verwenden. Könntet Ihr einen user-Parameter hinzufügen?

**Comment by markus-mw** [comment]
@christianvoigt : Wie soll sich der Parameter genau auswirken? Die Parameter "author" bzw. "author_name" können bereits verwendet werden. Geht es dir darum, dass auch die item_admins berücksichtigt werden sollen? So gesehen, "gehören" diese Items ja nicht dem cb_manager.

**Comment by christianvoigt** [comment]
Hi @markus-mw,
ich wußte nicht, dass es die beiden Parameter schon gibt. Uns reicht das völlig. Im Fall von Velogistics sind die cb_manager automatisch auch die Besitzer der Lastenräder. Ich kann also einfach `[cb_items author=cb_manager_user_id]` verwenden, richtig?
