### ISSUE TITLE
Templates: HTML-Formatierungen ermöglichen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#569]
Bei den Stationen sind in den Feldern z.B Öffnungszeiten, keine
Formatierungen mehr möglich. In der alten Version konnte ich mit <br>
einen Umbruch erzwingen. Jetzt bekomme ich das nicht mehr hin.

**Comment by chriwen** [comment]
@markus-mw Könntest du dir das mal anschauen? Das ist diese fullday-Info, die per Javascript integriert wird. 
Hier sollte das in der commonsbooking_sanitizeHTML erlaubte HMTL auch möglich sein.
Zusätzlich wirft das bei mir im Master ne null

![image](https://user-images.githubusercontent.com/12683634/111796077-1b6e9200-88c8-11eb-9e09-3e26f0a9cfec.png)

**Comment by chriwen** [comment]
@markus-mw Branch hatte ich schon angelegt. aber noch nichts geändert

**Comment by markus-mw** [comment]
@chriwen : Ist im master behoben.
