### ISSUE TITLE
Reparatur: Überbuchen möglich

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#570]
Setzt man in einer Station das Rad auf "Reparatur" ist das Überbuchen
auch da möglich.

**Comment by markus-mw** [comment]
@chriwen : Ich kann das Problem nicht nachvollziehen oO

**Comment by chriwen** [comment]
@markus-mw Ich auch nicht.. Ich hake da nochmal nach. Erstmal so lassen.

**Comment by hanneskasimir** [comment]
Überbuchen von Reparatur konnte ich auch nicht nachstellen. Allerdings sieht es auf den ersten Blick so aus, als wäre dies möglich:
![grafik](https://user-images.githubusercontent.com/28141760/112636566-8c202c00-8e3d-11eb-95e6-61a2215fe3b4.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Ja das mit der Darstellung ist noch etwas tricky, das hatten wir geschoben. Ich dächte da gibt's schon ein Ticket. @chriwen weiß du noch welches das war?

**Comment by chriwen** [comment]
Ich schließe das Ticket erstmal. Das Darstellungsthema machen wir dann separat.
