### ISSUE TITLE
Buchungskommentar hinzufügen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#578]

**Comment by markus-mw** [comment]
@chriwen : Ist im master.

**Comment by hanneskasimir** [comment]
funktioniert.
Ist das jetzt für alle immer da? Ggf. wäre es gut, wenn die Option (de)aktivierbar ist und sich die Überschrift ändern ließe damit Mensch weiß, worum es inhaltlich geht.

**Comment by markus-mw** [comment]
@hanneskasimir : Können wir machen. Wo wollen wir das unterbringen? Bei den Einstellungen im "Allgemein"-Bereich? Ich würde dort eine Checkbox "Kommentare für Buchungen aktivieren" einbauen und ein zweites Feld für den Titel, mit einem schlauen Label. Hast du eine Idee wie ich das nennen soll?

**Comment by hanneskasimir** [comment]
@markus-mw : Ja, gerne im Allgemein-Bereich, als eigener Abschnitt "Buchungs-Kommentar". 
Checkbox: "Kommentare auf Buchungsseite aktivieren"
Label des Felds "Überschrift über Eingabefeld"

**Comment by markus-mw** [comment]
@hanneskasimir : Ist erledigt und auf Stage zu sehen.

**Comment by hanneskasimir** [comment]
fein, funktioniert!
nur gab es leider diesen unschönen Hinweis nachdem ich die Checkbox wieder aktiviert hab und den Text geändert hatte:
![grafik](https://user-images.githubusercontent.com/28141760/112716742-803d7400-8ee8-11eb-922b-208e3e1af115.png)

**Comment by markus-mw** [comment]
@hanneskasimir, @chriwen : Ich kann da leider nichts machen. Das was zum Fehler führt ist eine Wordpress-Funktion, die die Rewrite Rules neu schreibt (wegen Artikel und Location Slug). Die allgemein anerkannte Lösung der Wordpress Community ist: erhöhe den Speicher. ;(

**Comment by hanneskasimir** [comment]
;-)

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Christian hatte mich noch auf was hingewiesen... Ich hab jetzt noch was geändert und nun funktionierts.
