### ISSUE TITLE
Backend/Map: Tooltip falsch angezeigt

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#580]
Tooltip in den Map-Einstellungen wird falsch angezeigt. @flegfleg hatte da was optimiert, aber scheinbar funktioniert das nicht bzw. ist irgendwie zerschossen werden.

![image](https://user-images.githubusercontent.com/12683634/112616972-a7cb0880-8e24-11eb-9cac-86f85d4e5824.png)

**Comment by markus-mw** [comment]
@chriwen : Ich hab das JS wieder auskommentiert, sodass die Standard-Title Logik greift. Ich weiß nicht wo/wie der Tooltip gestyled wurde. Jetzt sieht es erst einmal wieder "normal" aus.

**Comment by flegfleg** [comment]
> @chriwen : Ich hab das JS wieder auskommentiert, sodass die Standard-Title Logik greift. Ich weiß nicht wo/wie der Tooltip gestyled wurde. Jetzt sieht es erst einmal wieder "normal" aus.

@markus-mw css hatte ich [hier](https://github.com/wielebenwir/commonsbooking/pull/585) eingebunden.
