### ISSUE TITLE
Prevent Overlapping Bookings

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#581]
Nutzerfeedback:
hi, i don’t know how it happened, but somehow double booking happened, two overlapping reservations.
how can this happen, please?

![image](https://user-images.githubusercontent.com/12683634/112618154-22485800-8e26-11eb-92ae-057dedf25286.png)

**Comment by chriwen** [comment]
@markus-mw : Bitte nochmal Validierung prüfen, damit auch bei stundenweise Buchungen keine Überlappungen gebucht werden können.

**Comment by markus-mw** [comment]
@chriwen : Ich habe jetzt Backend-seitig noch eine Prüfung eingebaut die sicherstellt, dass keine überlappenden Buchungen angelegt werden können.

**Comment by hanneskasimir** [comment]
ich konnte im Backend überlappende Buchungen machen, eine hat dann Status "published"!?
![grafik](https://user-images.githubusercontent.com/28141760/112641795-fedfd600-8e42-11eb-9cc7-70e7ff572102.png)

**Comment by chriwen** [comment]
@markus-mw : Bitte nochmal prüfen.

**Comment by markus-mw** [comment]
@chriwen : Ich hab die Logik jetzt angepasst, dass es zumindest für ganztägige Buchungen sichergestellt wird, dass da keine Fehler passieren können. Bei Buchungen mit expliziten Zeiten, müssen wir nochmal an die Speicherung aus dem Backend ran, damit die eingestellten Uhrzeiten mit in den Timestamp übernommen werden. Wenn das ein ernstzunehmender Use-Case, lass es mich wissen.
