### ISSUE TITLE
Artikel nicht buchbar

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#588]
![grafik](https://user-images.githubusercontent.com/28141760/112634214-9856ba00-8e3a-11eb-954e-d3ded058603a.png)
![grafik](https://user-images.githubusercontent.com/28141760/112634239-a4db1280-8e3a-11eb-9ce0-a21ac5c96b16.png)
![grafik](https://user-images.githubusercontent.com/28141760/112634427-dce25580-8e3a-11eb-967a-7bf29cb681f4.png)
![grafik](https://user-images.githubusercontent.com/28141760/112634807-55491680-8e3b-11eb-85d2-4ecac1e587b7.png)

**Comment by hanneskasimir** [comment]
gilt auch für 
![grafik](https://user-images.githubusercontent.com/28141760/112640805-faff8400-8e41-11eb-8fc7-c7ccd0f82178.png)
dieser Zeitraum erscheint hier erst gar nicht:
![grafik](https://user-images.githubusercontent.com/28141760/112640943-2b472280-8e42-11eb-968a-515b2fc5fb88.png)

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Wie im Chat bereits geschrieben:
Das Startdatum muss jetzt bei buchbaren Zeiträumen gesetzt werden. Wenn nicht, wird der Timeframe ein Draft und es wird eine Fehler-Meldung ausgegeben. Generell kann ich das Feld nicht als Pflichtfeld machen, weil es dann in anderen Typen Probleme gibt, die das Feld nicht unbedingt benötigen.
