### ISSUE TITLE
Make CommonsBooking Menu entry fit better in the WP Admin

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#593]
With V 5.7, WordPress changed the sidebar Design. 
The menu entry "`CommonsBooking`" does not fit anymore:

<img width="166" alt="CleanShot 2021-03-26 at 15 43 03@2x" src="https://user-images.githubusercontent.com/4009931/112692144-c2ca6680-8e7e-11eb-841b-aae5732f13b3.png">

But menu items now wrap (or i just saw this the first time), so we could rename the menu entry "`Commons Booking`" so it looks like this: 

<img width="155" alt="CleanShot 2021-03-26 at 15 43 25@2x" src="https://user-images.githubusercontent.com/4009931/112692274-f6a58c00-8e7e-11eb-8748-7fb453c28898.png">

**Comment by chriwen** [comment]
@flegfleg Ist umgesetzt. Danke für den Hinweis.
