### ISSUE TITLE
Map: Fehlender Text für Geosearch-Buttons

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commonsbooking#595]
Wenn man den Geosearch-Filter für die Map aktiviert, erscheinen Buttons mit Icons, aber ohne Text. Die Buttons sind nicht selbsterklärend (insbesondere nicht der Undo-Button, dessen "Close-Icon" so ausschaut, als würde man die Sektion der Webseite schließen können).

Es wäre besser als Default einen Text hinzuzufügen. Den kann man leicht per CSS verbergen. Alternativ könnte man Settings hinzufügen, mit denen man diese Labels anpassen oder entfernen kann (analog zu den anderen Labels).

Falls man das Label verbirgt, wäre es gut, ein title-Attribut hinzuzufügen, damit ein Tooltip erscheint (und um die Accessibility zu verbessern).

**Comment by hansmorb** [comment]
Empfehlung: Neuen cb_search Shortcode verwenden.
