### ISSUE TITLE
Buchungskommentar wird bei stornierter Buchung nicht angezeigt.

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#596]
Wenn zu einer Buchung ein Kommentar gespeichert wird und diese Buchung dann storniert wird, ist der Buchungskommentar im Backen und Frontend nicht mehr zu sehen.

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben. Das Comment-Feld war in der Liste der benötigten Meta-Felder noch nicht enthalten.

**Comment by markus-mw** [comment]
@chriwen : Halt stop, da gibt's noch ein kleines anderes Problem.

**Comment by markus-mw** [comment]
@chriwen : Jetzt aber. :)
