### ISSUE TITLE
Fehler: Undefined ERROR_TYPE

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#597]
![grafik](https://user-images.githubusercontent.com/28141760/112829114-f250bd00-9090-11eb-82c5-675e1411bb7a.png)

**Comment by chriwen** [comment]
@hanneskasimir Hab auf stage1 keinen Fehler dieser Art mehr gefunden. Wo tauchte das bei dir auf? Bitte nochmal checken und wenn ok, Ticket schließen. Danke.

**Comment by hanneskasimir** [comment]
das war auf KASI-live, ist jetzt weg.
