### ISSUE TITLE
Cannot delete Timeframe if it overlaps

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#602]
**Describe the bug**

* Trying to delete overlapping timeframe as cb_manager
->You do not have the rights to do that
<img width="1229" alt="CleanShot 2021-04-07 at 10 54 34@2x" src="https://user-images.githubusercontent.com/4009931/113839428-f74bf580-978f-11eb-9065-2a5bd5ab048b.png">

**To Reproduce**
* Overlapping timeframes: 
   * 1 published, 
   * 1 Draft (could not bepublish because it was overlapping)
* Try deleting it

* admin can delete it

**Comment by markus-mw** [comment]
@flegfleg , @chriwen : CB Manager können nur eigenen Timeframes löschen. Timeframes anderer User, auch wenn sie als Admin ergänzt sind, können nicht gelöscht werden.
