### ISSUE TITLE
Timeframe-Editor: Falsche Validierung "There is an overlapping booking."

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#603]
Beschreibung:
- Vorhandenen buchbaren Timeframe öffnen.
- Zeitrahmen, der in der Vergangenheit lag, so anpassen, dass das End-Datum geleert wird.
- Speichern
- Fehlermeldung: There is an overlapping booking.

Gewünschtes Verhalten:
- Die Prüfung auf überlappende Buchungen soll nur den Typ Booking betreffen und nicht die anderen Zeitrahmen-Typen.

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben.

**Comment by danielappelt** [comment]
Ich habe hier in der aktuellen Version 2.4.3 ein vermutlich verwandtes Problem: Ich möchte als Admin / CommonsBooking-Manager im Backend eine Buchung verlängern (der Artikel kam nicht rechtzeitig zurück und soll entsprechend länger nicht reservierbar sein). Am einfachsten wäre, wenn man die existierende Buchung verlängern könnte. Ich bekomme hier jedoch oben genannten Fehler. Ich vermute, dies liegt daran, dass hier die maximale Buchungsdauer des buchbaren Zeitrahmens überschritten wird. In diesen Fall ist die Fehlermeldung aber zumindest Mal verwirrend.
Schön wäre darüber hinaus, wenn ein Admin Buchungen über die maximale Buchungsdauer hinaus anlegen / verändern könnte. Wir würdet ihr sonst den genannten Use Case abbilden?
