### ISSUE TITLE
Tabellenlisting verfügbare Räder (Flotte-Berlin-Plugin) integrieren

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#606]

**Comment by markus-mw** [comment]
@chriwen : Ist in feature/issue-606 umgesetzt. 
Mögliche Parameter sind:

- Days: Anzahl der Tage
- itemcat: Term-ID um nach Items zu filtern
- locationcat: Term-ID um nach Locations zu filtern

**Comment by chriwen** [comment]
Funktioniert auf den ersten Blick. Folgendes ist mir aufgefallen:

1. eigentlich komplett gebuchte Tage werden nur als halb gebucht angezeigt.
![image](https://user-images.githubusercontent.com/12683634/114263166-468a6400-99e4-11eb-8df6-828107d6364e.png)

![image](https://user-images.githubusercontent.com/12683634/114263171-4f7b3580-99e4-11eb-9392-14e6eabe8f30.png)




2. Folgende Fehler werden geworfen:
arnung | array_key_exists() expects parameter 2 to be array, string given | 1 | -wp-content/plugins/commonsbooking/src/View/Calendar.php:320array_key_exists()wp-content/plugins/commonsbooking/src/View/Calendar.php:320CommonsBooking\V\Calendar::renderTable()wp-includes/shortcodes.php:343do_shortcode_tag()Unbekannter Ortpreg_replace_callback()wp-includes/shortcodes.php:218do_shortcode()wp-includes/class-wp-hook.php:292apply_filters('the_content')wp-includes/post-template.php:253the_content()wp-content/themes/kasimir-theme/template-parts/content-page.php:19load_template('wp-content/themes/kasimir-theme/template-parts/content-page.php')wp-includes/template.php:676locate_template()wp-includes/general-template.php:204get_template_part('template-parts/content','page')wp-content/themes/kasimir-theme/page.php:23
-- | -- | -- | --

4. Styling im Kasimir-Theme ist noch arg wild... Können wir das noch etwas optimieren und komprimieren. Am liebsten so klein und kompakt wie möglich.

**Comment by markus-mw** [comment]
@chriwen : Ich hab die Styles für die versch. Themes angepasst und das Problem mit der falsch ausgegeben Buchung korrigiert. Wie du den Fehler hinbekommst, weiß ich nicht. Kannst du mir schreiben, wie der Tag konfiguriert ist?
