### ISSUE TITLE
Tags, Readme und Changelog

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#607]
Die Versionen, die im Readme aufgeführt sind, scheinen irgendwie nicht zu den Versions-Tags im Git zu passen (2.4.2 vs. 2.3.2). Idealerweise sollte eine neue Version jeweils getaggt werden in Git und dieselbe Version dann im Readme aufgeführt werden und anders herum keine Version im Readme aufgeführt werden, die man im Git nicht wirklich wieder finden kann.

Darüber hinaus schlage ich vor, aus Reamde.txt eine Readme.md zu machen, dann sieht das Ganze formatiert und professioneller aus. Außerdem könnte man die Release-Informationen in ein Changelog á la [KeepAChangelog](https://keepachangelog.com/en/1.0.0/) auslagern und dort die Releases mit Git-Tags und Change-Diffs verknüpfen.

Wenn ihr wollt, kann ich mich bei Gelegenheit darum kümmern.

**Comment by chriwen** [comment]
@danielappelt Die readme.txt ist für Wordpress notwendig und muss in diesem Format geliefert werden. Wordpress zieht sich da die stable tags etc. von Daher kann man die, soweit ich das verstehe, nicht in md umbennenen. 

Wir haben seit dem Zeitpunkt, in dem wir das Plugin auf Wordpress veröffentlicht haben in Github nicht immer jede Version getagged, das ist richtig. Bisher hielt sich die Anzahl externer Mitentwickelnder, die in Github aktiv sind sehr in Grenzen ;-)
Wir können das aber zukünftig gerne wieder konsequent etablieren. 
Ich werde das nächste Release entsprechend als Release anlegen. Und wenn du möchtest, darfst du hier natürlich gerne aktiv werden. 
Wo würden wir das Changelog hin auslagern?

**Comment by danielappelt** [comment]
@chriwen Alles klar. Ja, das hört sich dann doch sinnvoll an. Normalerweise würde man eine separate CHANGELOG.md anlegen. Dann hätte man die Infos aber nicht mehr direkt auf Wordpress. Vielleicht kann man die Change Diffs aber auch so sinnvoll einbauen. Ich schaue mir das mal an.

**Comment by danielappelt** [comment]
Andere Worpdress-Plugins scheinen eine separate README.md für Github zu haben. Wenn man ein größeres Entwickler-Publikum ansprechen möchte, wäre das sinnvoll. Man müsste dann aber natürlich eine weitere Datei aktuell halten. Beispiele: [Transient Cleaner](https://github.com/dartiss/transient-cleaner), [Advanced Custom Fields](https://github.com/AdvancedCustomFields/acf)
