### ISSUE TITLE
Validierungsfehler bei überlappenden Buchungen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#610]
<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/12683634/114263404-87cf4380-99e5-11eb-9f01-87acc2dfc1a1.png">

Liebes Commonsbooking Entwicklerteam,

nach gestrigem Update wurde bei uns eine Buchung am Vormittag nicht mehr im Kalender angezeigt. Daraufhin habe ich versucht, den Slot zu Überbuchen und das hat leider geklappt.
PastedGraphic-1.png

Wir haben für dieses Fahrrad drei Buchbar-Zeiträume angelegt, die sich jeweils wöchentlich wiederholen. Vormittags und Nachmittags, Mo bis Fr und einen für abweichende Öffnungszeiten am Samstag Nachmitta

**Comment by chriwen** [comment]
@markus-mw Kannst du das kurzfristig mal anschauen?

**Comment by markus-mw** [comment]
@chriwen : Ich schau es mir mal an.

**Comment by markus-mw** [comment]
@chriwen : Weißt du wie die Überbuchung gemacht wurde? Übers Backend oder im Frontend?
Unabhängig davon konnte ich ein Problem bei der Markierung von gebuchten Tagen gefunden, nachdem ich die Timeframe Konfiguration aus der Beschreibung nachgestellt hatte. Das Problem trat auf, wenn eine Buchung (nicht ganztägig) am Vortag startet, und bis zum folgenden Tag reicht. Es wurde dann am überbuchten Tag die Startzeit der Buchung für die Blockierung der Slots verwendet und nicht bei 0:00 Uhr gestartet. Das hat zu Fehldarstellungen geführt. Das Problem ist im master behoben.

**Comment by chriwen** [comment]
@markus-mw danke. Buchung wurde übers Frontend gemacht.

**Comment by markus-mw** [comment]
@chriwen : Ok, dann war das wahrscheinlich wegen dem vorher beschriebenen Fehler möglich. Nach dieser Anpassung sollte das nicht mehr passieren.
