### ISSUE TITLE
Fehlerhafte Anzeige bei mehreren buchbaren Timeframes

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#612]
ich hatte gestern monatliche Zeitrahmen definiert bis einschließlich
September 2021.
Heute ist mir aufgefallen, das mit immer nur der letzte definierte
Zeitrahmen angezeigt wird.

Wenn ich also 2021-04 und 2021-05 definiere, zeigt er mit nur
2021-Mai an. Siehe Anhang Zeitrahmen_2021_04 und 05.png,
BuchungskalenderApril_Mai.png

Wenn ich den Zeitrahmen 2021-05 lösche, wird
BuchungskalenderApril.png angezeigt.

Die Zeitrahmen habe ich wie in Zeitrahmenkonfiguration.png
konfiguriert.

Irgendwas ist also noch nicht richtig (konfiguriert?).

![Zeitrahmen_2021_04-und-05 (1)](https://user-images.githubusercontent.com/12683634/114304120-cf32fe00-9ad1-11eb-83c2-5e582f78b2f5.PNG)
![BuchungskalenderApril_Mai (1)](https://user-images.githubusercontent.com/12683634/114304122-d1955800-9ad1-11eb-9fdb-00d52ddad00f.PNG)

**Comment by markus-mw** [comment]
@chriwen : Das hatte sich doch erledigt, oder?
