### ISSUE TITLE
Kalender: Fehler bei Zeitauswahl

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#619]
Schritte:
- 2 Timframes angelegt mit slotweiser Buchung (siehe Screenrecording)

Bei der Buchung wird 
a) der Zeitraum nicht blau markiert, nachdem das Zeitdropdown bearbeitet wurde
b) in der Buchungsbestätigung nicht die gewählte Slotzeit, sondern die addierte Zeit aller Slots angezeigt.

Siehe hier:
https://drive.google.com/file/d/1MkcV8Xt7qJP-S9G2W2SAF_JetEidvpTo/view

**Comment by markus-mw** [comment]
@chriwen : Das war knifflig, funktioniert jetzt aber. Ich habe die Änderungen noch nicht gemerged. Du kannst das Ganze im Branch bugfix/issue-619 testen.

**Comment by chriwen** [comment]
Problem der falschen Zeitberechnung weiterhin beim Abholdatum vorhanden. Siehe. https://drive.google.com/file/d/1dlMHHl0-L0xzQ4-iOnlUvx7YDRmgsj7u/view
Es waren zwei Timframes angeleget mit jeweils den beiden dargestellten Zeitslots und slotweisem Intervall.

**Comment by hanneskasimir** [comment]
![grafik](https://user-images.githubusercontent.com/28141760/116089016-b7977000-a6a2-11eb-966a-4fc05f58805d.png)
![grafik](https://user-images.githubusercontent.com/28141760/116089051-c0884180-a6a2-11eb-9256-43521fb9ad02.png)

**Comment by hanneskasimir** [comment]
https://staging.commons-booking.org/kasimir-lastenrad.de/cb-items/kasimir/?location=3602

**Comment by markus-mw** [comment]
@chriwen : Kann ich nicht reproduzieren.
