### ISSUE TITLE
Tabelle soll nur aktuelle Zeitrahmen anzeigen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#620]

**Comment by chriwen** [comment]
@hanneskasimir Was meinst du damit genau? Nur Zeitrahmen die in der Range der Tabelle liegen?

**Comment by chriwen** [comment]
@hanneskasimir Ist das nicht schon umgesetzt? Kannst du das mal kurz checken? Dann gerne Ticket schließen, wenn ok. Danke

**Comment by hanneskasimir** [comment]
jo, ist umgesetzt.
