### ISSUE TITLE
Tabelle: Nach Erstellung neuer Zeitrahmen wirft die Tabelle beim ersten Laden erstmal einen kritischen Fehler.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#621]

**Comment by chriwen** [comment]
@hanneskasimir Ich konnte das nicht nachstellen. Wo genau ist das passiert? Ist es in der aktuellen Version immer noch so?

**Comment by hanneskasimir** [comment]
kann ich heute nichtmehr nachstellen.
