### ISSUE TITLE
Buchungs-Bestätigungs-Email bekommen, aber Buchung erscheint nicht in Buchungsliste

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#624]
Anruf von nutzendem 
id: 8257

**Comment by chriwen** [comment]
@flegfleg Ich kann alle Buchungen (aus Nutzersicht), auch die betreffende sehen. Bitte mal um einen Screenshot der Buchungsliste.

**Comment by flegfleg** [comment]
huhu, hab den anruf angenommen und war auf dem sprung da hatte ich keine Zeit das zu überprüfen
