### ISSUE TITLE
GBFS API bereitstellen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#627]
https://www.mobidata-bw.de/dataset?q=bikesharing&sort=score+desc%2C+metadata_modified+desc

**Comment by markus-mw** [comment]
@chriwen : Welche der Endpunkte sollen unterstützt werden? Hier ist eine Liste der definierten: https://github.com/MobilityData/gbfs-json-schema

**Comment by chriwen** [comment]
Ich denke es geht erstmal um diese beiden:
https://github.com/MobilityData/gbfs-json-schema/blob/master/station_information.json
https://github.com/MobilityData/gbfs-json-schema/blob/master/station_information.json

Beispieldaten hier:
https://www.mobidata-bw.de/data/LastenveloFR/station_information.json
https://www.mobidata-bw.de/data/LastenveloFR/station_status.json

**Comment by markus-mw** [comment]
@chriwen : Die Endpunkte sind jetzt umgesetzt. Die Rückgaben sind gegen die Schemata validiert und in Ordnung.
Die Routen:
Station Information: /wp-json/commonsbooking/v1/station_information
Station Status: /wp-json/commonsbooking/v1/station_status

Die Änderungen sind im master und können getestet werden.

**Comment by hbruch** [comment]
station_information.json und station_status.json (mit .json-Endung) wären die Standard-v1 Endpunkte. Weicht das System davon ab, sollte auch [gbfs.json](https://github.com/NABSA/gbfs/blob/v1.0/gbfs.md#gbfsjson) implementiert werden, das die Endpunkte ohne .json-Endung explizit angeben kann.

**Comment by chriwen** [comment]
@markus-mw Kannst du das noch anpassen? Entweder die .json-Endung dazu oder gbfs.json? Merci

**Comment by markus-mw** [comment]
@chriwen , @hbruch : Ich habe die Routen mit einer '.json'-Endung versehen. Passt das dann so?

**Comment by hbruch** [comment]
@markus-mw gegen welche Schemata läuft die Validierung? GBFS sieht als [top-level-properties](https://github.com/NABSA/gbfs/blob/v1.1/gbfs.md#output-format) jeweils `ttl`,`last_updated`,`data` vor. Weitere Anregungen/Fragen:
* zu station_information.json:
  * Haben die Standorte keinen Namen? `unknown` wäre nicht so schön in der Anzeige. 
  * post_code, address sind zwar optional, in der Anzeige aber hilfreich
  * [V1.1](https://github.com/NABSA/gbfs/blob/v1.1/gbfs.md#station_informationjson) führte `rental_uris` ein, die die Angabe eines Deep-Links zur Buchung ermöglichen.  Die wären sehr hilfreich.
* Laut GBFS-Standard ebenfalls `required` ist [system_information.json](https://github.com/NABSA/gbfs/blob/v1.1/gbfs.md#files)
  
Derzeit in Vorbereitung für kommende Versionen des Standards sind weitere für Lastenräder nützliche Ergänzungen, z.B. die Angabe von `vehicle_types`, und dort der `form_factor=cargobike` sowie `share_type=round_trip`

**Comment by hbruch** [comment]
Beispiel für eine statische Umsetzung, die wir in stadtnavi integriert haben: https://github.com/stadtnavi/static-gbfs-feeds/tree/master/bananologen

**Comment by markus-mw** [comment]
@hbruch : Wie hast du die Umsetzung getestet? In Teilen kann ich deine Punkte nicht nachvollziehen.

- die Standortnamen werden anhand des post_title gefüllt -> sollte also passen
- bzgl. post_code und address bin ich bei dir, dass es hiflreich ist,aber solange wir von optionalen Parametern sprechen, ja kein muss
- der rental_uris Part ist bereits für web vorgesehen, für android und ios gibt es keine explizit anderen URLs

Die system_information.json war nicht teil dieses Issues und wurde daher auch noch nicht umgesetzt. Können wir aber gern nachholen. Ebenfalls die Adress-Infos.

Bzgl. der Ergänzungen, wird es wahrscheinlich zu spezifisch, weil Commonsbooking zwar grundsätzlich in der Lastenrad-Szene zu Hause ist, aber dennoch für alle Güter nutzbar sein soll. Sehr spezifische Infos wie die vehicle_types sind daher leider erst einmal nicht drin.
Ich hatte mich maßgeblich an den Beispielen von @chriwen orientiert, darin werden diese Infos auch nicht abgebildet.

**Comment by hbruch** [comment]
Anhand des oben angegeben Links: https://www.mobidata-bw.de/data/LastenveloFR/station_information.json
Standortnamen lauten dort alle `unknown` und `rental_uris/web` sehe ich auch keine. Sollte ich einen anderen verwenden?

Was andere Güter als Fahrzeuge angeht, ist GBFS vielleicht ohnehin nicht das passende Format.

**Comment by chriwen** [comment]
Hallo @hbruch Wir hatten die GBFS-Integration auf Anregung des mobidata-Projekts umgesetzt. Ich würde dich bitten bei einem konkreten Bedarf bzw. Szenario an der Schnittstelle nochmal mit uns direkt Kontakt aufzunehmen (über commonsbooking.org) Dann können wir nochmal detaillierte Tasks bzgl. der API abstimmen. Ohne konkretes Szenario möchten wir derzeit jedoch zunächst keine weiteren Ressourcen in die API-Erweiterung investieren, da wir noch einige andere prioritäre Funktionen umsetzen wollen. Also, melde dich gerne bei Bedarf - oder wenn Interesse an einer Mitentwicklung besteht ;-)

**Comment by chriwen** [comment]
@hbruch wir schließen dieses Ticket hier, da die Erweiterungen von @vkrause übernommen und mit dem nächsten Update verfügbar sind. 
Testen könnt ihr im master-Branch.
Sollte es noch weitere Fragen oder Anmerkungen rund um die GBFS-Api geben, meldet euch gerne.
