### ISSUE TITLE
Collection field resets calendar on booking page

### ISSUE THREAD

**Issue by Ordinateur-Hack** [wielebenwir/commonsbooking#629]
_CB version: 2.4.3_

**Bug description**
Bookings are not working on [our webiste](https://inspeyerad.de/buchen) right now. This is because the collection field, where the user enters a time for collection of the bike, resets the date in the calendar. See this GIF:

![Commons Booking Calendar](https://user-images.githubusercontent.com/37160523/115958980-1a093880-a50a-11eb-9762-4072babce29e.gif)

**Expected behavior**
- User selects a date.
- Users clicks on the dropdown to select a collection time. Calendar date is NOT reset.
- The dropdown to select a return time is enabled. The user can select a return time and proceed with his/her booking.

**Maybe related**
I don't know if this is related to our theme [Talon](https://athemes.com/theme/talon/) or not or if this is an issue on your side. I haven't found this exact same issue here on GitHub. Maybe it relates to #619 ?

**Comment by Ordinateur-Hack** [comment]
**Workaround**
**Click on the date in the calendar twice before selecting any time slot.** However, this makes it really hard for new users. I guess a usual flow would be like this:

- Select the collection date in the calendar.
- Choose a timeslot for the collection.
- Select a return date.
- Choose a timeslot for return.
- Click on "Weiter zur Buchungsprüfung".

**Comment by chriwen** [comment]
@Ordinateur-Hack Hi, wir haben die Themen in der neuesten Entwicklungsversion behoben. Es wäre super, wenn du dir hier die neue Version 2.4.4 herunterladen und über die manuelle Installation einmal installieren könntest. https://downloads.wordpress.org/plugin/commonsbooking.zip
Bitte dann um kurze Rückmeldung, ob deine Probleme damit behoben sind. Wir werden die Version dann nach weiteren Tests in den nächsten Tagen auch veröffentlichen.

**Comment by Ordinateur-Hack** [comment]
@chriwen Sorry, sehe das erst jetzt. Das ging ja fix, vielen Dank euch. Das Problem ist jetzt behoben 🥳
