### ISSUE TITLE
Aktueller Zeitrahmen wird nicht angezeigt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#633]
KASIMIR-live: Bürgerhaus Stollwerk hat heute (27. April) für den Juni einen Zeitrahmen erstellt (monatliche Routine).
Nach Veröffentlichung beginnt der Kalender fälschlicherweise bei Juni:
![grafik](https://user-images.githubusercontent.com/28141760/116239868-74e99c80-a763-11eb-84a2-db1fbd22b5db.png)
![grafik](https://user-images.githubusercontent.com/28141760/116239907-7dda6e00-a763-11eb-8d15-b0f695d21356.png)

**Comment by chriwen** [comment]
@hanneskasimir : Danke. Problem ist bekannt. Wird hoffentlich schnellstmöglich behoben.

**Comment by chriwen** [comment]
@markus-mw : ich glaube ich hab da eine mögliche Ursache gefunden. In getCalendarDataArray wird hier
`            if(count($bookableTimeframes)) {
                /** @var \CommonsBooking\Model\Timeframe $firstBookableTimeframe */
                $firstBookableTimeframe = array_pop($bookableTimeframes);`

der erste Timeframe gesucht, in dem das letzte Element aus dem array extrahiert wird. 
Die $bookableTimeframes sind aber anscheinend nach ID oder so sortiert, auf jeden Fall wohl nicht nach repetition-start. 
Irgendwie müsste da noch ne Sortierung rein, bevor der erste Timeframe ermittelt wird.

**Comment by markus-mw** [comment]
@chriwen : Ist im master korrigiert.
