### ISSUE TITLE
Wochentag ergänzen in Buchungsbestätigungsmail

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#636]
Wunsch der Tafel Köln:

Schreibt doch den Wochentag vor das Datum, das erleichtert die Einschätzbarkeit.

Abholung: Do., 13. Mai 2021 09:00 - 15:59
Rückgabe: Do., 13. Mai 2021 09:00 - 16:00

**Comment by chriwen** [comment]
@hanneskasimir Das Format wird aus den Wordpress-Einstellungen übernommen. Kannst du selbst einstellen unter Einstellungen -> Allgemein.
