### ISSUE TITLE
Cache bei Shortcodes prüfen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#659]
in BookablePost->get wird der Cache auf Basis des PostTypes erstellt.
Bei der Verwendung von Attributen in den Shortcodes z.B. cb_items author=xx wird dann jedoch dieser Cache verwendet, da er ja nicht attributsabhängig ist. 

Es müsste sichergestellt werden, dass Attribute bei der Verwendung von Shortcodes im Cache berücksichtigt werden.

**Comment by markus-mw** [comment]
@chriwen Hast du in dem Kontext ein Problem festgestellt? Die übergebenen Funktionsparameter werden nämlich in der \CommonsBooking\Plugin::getCacheId in den Cache-Schlüssel mit aufgenommen.
