### ISSUE TITLE
Quick edit options remove values

### ISSUE THREAD

**Issue by antton** [wielebenwir/commonsbooking#661]
**Describe the bug**
When I try to quick edit my new timeframes for example, it removes previously added parameters and I need to edit again and reintroduce my parameters.

If we remove the quick-edit options and just let the normal edit one It would be enough.

**To Reproduce**
1.- Fill a new timeframe
2.- Quick edit the previous timeframe and rename the title for example
3.- Save and see how your parameters dissapear

**Expected behavior**
1.- Fill a new timeframe
2.- Edit the little options that let you change
3.- Save and keep at least the parameters we didn't touch like (item, data etc..)

**Comment by chriwen** [comment]
@antton Thanks for your bug report. The quick edit button will be removed in the next update.
