### ISSUE TITLE
Konfigurierbare Metadatensets ermöglichen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#662]
#### Meta-Datenset als separate Gruppe
Definition eines Meta-Datensets, welches an die Location bzw. Items als Meta-Felder angehängt werden kann. 
Format und Speicherung sind technisch noch zu klären. Mögliche Idee:
- Eingabe in ein Textarea-Feld auf Basis einer definierten Syntax (JSON)?
Hinweis: Bei der Definition müssen Meta-Feld-Name, Label, Typ etc. mitgegeben werden. Ist das im Standard-JSON schon definiert?

Umsetzung als Textarea / pro Feld eine Zeile mit folgenden Daten, Semikolon getrennt:
post_type(item/location);field-name;label,typ(checkbox,number,text),description

**Comment by christianvoigt** [comment]
Zwei Verbesserungsvorschläge: 

1. Das bisherige Konzept für die Metadatensets berücksichtigt nicht, dass sie auch auf mehrsprachigen Seiten funktionieren sollten (so wie der Rest von CB ja auch darauf reagieren kann, wenn man die Sprache umschaltet). 
2. Grundsätzlich wäre es meiner Meinung nach besser ein "selbstdokumentierendes Format" wie JSON zu verwenden, statt eine mit Semikolon separierte Liste da man dort schnell den Überblick verliert, wo welche Eigenschaft stehen muss (Reihenfolge ist bei einem Format wie JSON oder YAML egal). Wenn jetzt noch Labels für unterschiedliche Sprachen hinzukommen, wird das noch unübersichtlicher.

**Comment by chriwen** [comment]
@christianvoigt Mangels weiterem Bedarf schließen wir dieses Thema erstmal. Bzgl. der Übersetzung ist es so, dass in CB alle von Usern eingegeben Werte keine Übersetzung beinhalten / ermöglichen. Dies würde auch für die Metadaten dann gelten.
