### ISSUE TITLE
Zeitrahmen konfigurieren: Sprachenmischmasch

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#664]
![grafik](https://user-images.githubusercontent.com/28141760/121165928-edf30e00-c850-11eb-8a3e-70a068388392.png)

**Comment by chriwen** [comment]
irgendwas ist mit der Übersetzung von Wordpress defekt. Ich behalte das mal im Auge. Die Übersetzung scheint nicht aktualisiert zu werden.

**Comment by hanneskasimir** [comment]
fehler tritt immernoch auf.

**Comment by chriwen** [comment]
@hanneskasimir ist nun behoben. Es sollte nun immer die aktuelle Übersetzung geladen werden.
