### ISSUE TITLE
Monatliche Wiederholung funktioniert nicht.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#666]
![grafik](https://user-images.githubusercontent.com/28141760/121514287-21b66b00-c9ec-11eb-9397-44f58106f39e.png)
![grafik](https://user-images.githubusercontent.com/28141760/121514309-2844e280-c9ec-11eb-9b55-a54820d7a5e1.png)
![grafik](https://user-images.githubusercontent.com/28141760/121514336-2e3ac380-c9ec-11eb-992b-1cbf3883b3d7.png)

**Comment by markus-mw** [comment]
@chriwen, @hanneskasimir : Das Problem, dass die montatliche als auch die jährliche Wiederholung nicht funktioniert ist behoben. Es wird jetzt der erste Tag des Timeframes monatlich/jährlich verwendet.

@chriwen: Die Sache mit den diversen Config-Möglichkeiten sollten wir nochmal in Ruhe durchsprechen und runterschreiben, bevor ich da ins blaue entwickle.

**Comment by chriwen** [comment]
getestet. Funktioniert

**Comment by chriwen** [comment]
ist schon im master
