### ISSUE TITLE
Reparatur-Slots können fälschlicherweise überbucht werden.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#670]
gilt auch für Buchungen
![grafik](https://user-images.githubusercontent.com/28141760/121517624-e4ec7300-c9ef-11eb-8753-d53f4f1c3f54.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Habs probiert, geht nicht :)

**Comment by chriwen** [comment]
getestet und kann Fehler nicht reproduzieren.
