### ISSUE TITLE
Map: Maus-Zoom als Option einstellbar

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#673]
Option für scrollWheelZoom: true für User, um Mouse-Scrolling optional zu deaktivieren (Nutzerfeedback)

**Comment by hansmorb** [comment]
Ist schon Teil meines Pull request, bin mir nicht sicher ob ihr den gesehen habt. Dann spart man sich die doppelte Arbeit ;)

**Comment by chriwen** [comment]
@hansmorb : Super. Vielen Dank. Wir haben den PR übernommen. Ist im nächsten Release drin 👍
