### ISSUE TITLE
Bug / Plugin-Kompatibilität: All-in-one-Event-Plugin

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#675]
Nutzermeldug:

Problem:
Ich habe soweit alles probehalber eingerichtet, komme nun aber nicht
weiter, weil ich auf der Buchungsseite keinen Kalender sehe. Ich
dachte,  es läge ggf. am selbstgebauten Theme, aber auch mit einem
Standard-Wordpress Theme wird nix angezeigt, siehe

ich habe mal im all-in-one event calendar das error handling
ausgeschaltet. Nun bekomme ich immerhin folgende Fehlermeldung (nur auf
der Seite, auf der ich euer Plugin nutze - der Rest läuft problemlos):

Fatal error: Uncaught Exception: Invalid post param. Needed WP_Post or
ID (int) in
/home/www/wp/wp-content/plugins/commonsbooking/src/Model/CustomPost.php:34
Stack trace: #0
/home/www/wp/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Item.php(168):
CommonsBooking\Model\CustomPost->__construct(Object(stdClass)) #1
/home/www/wp/wp-includes/class-wp-hook.php(292):
CommonsBooking\Wordpress\CustomPostType\Item->getTemplate('Jeden
Mittwoch ...') #2 /home/www/wp/wp-includes/plugin.php(212):
WP_Hook->apply_filters('Jeden Mittwoch ...', Array) #3
/home/www/wp/wp-content/plugins/all-in-one-event-calendar/app/view/calendar/view/abstract.php(293):
apply_filters('the_content', 'Jeden Mittwoch ...') #4
/home/www/wp/wp-content/plugins/all-in-one-event-calendar/app/view/calendar/view/agenda.php(287):
Ai1ec_Calendar_View_Abstract->_add_runtime_properties(Object(Ai1ec_Event_Compatibility))
#5
/home/www/wp/wp-content/plugins/all-in-one-event-calendar/app/view/calendar/widget.php(353):
Ai1ec_Calendar_View_Agenda->get_agenda_l in
/home/www/wp/wp-content/plugins/commonsbooking/src/Model/CustomPost.php
on line 34

Ich habe spaßeshalber mal die Exception in Zeile 34 in CustomPost.php
rausgenommen und bekomme dann folgenden Stacktrace:

Fatal error: Uncaught Error: Object of class stdClass could not be
converted to string in
/home/www/wp/wp-content/plugins/commonsbooking/src/Repository/Timeframe.php:424
Stack trace: #0
/home/www/wp/wp-content/plugins/commonsbooking/src/Repository/Timeframe.php(424):
implode(',', Array) #1
/home/www/wp/wp-content/plugins/commonsbooking/src/Repository/Timeframe.php(58):
CommonsBooking\Repository\Timeframe::getPostIdsByType(Array, Array,
Array) #2
/home/www/wp/wp-content/plugins/commonsbooking/src/View/Calendar.php(293):
CommonsBooking\Repository\Timeframe::get(Array, Array, Array, NULL,
true) #3
/home/www/wp/wp-content/plugins/commonsbooking/src/View/Item.php(52):
CommonsBooking\View\Calendar::getCalendarDataArray(Object(stdClass),
4767) #4
/home/www/wp/wp-content/plugins/commonsbooking/templates/item-single.php(8):
CommonsBooking\View\Item::getTemplateData() #5
/home/www/wp/wp-includes/template.php(732):
require('/home/www/wp/wp...') #6
/home/www/wp/wp-content/plugins/commonsbooking/includes/Template.php(78): load_templat
in
/home/www/wp/wp-content/plugins/commonsbooking/src/Repository/Timeframe.php
on line 424

**Comment by chriwen** [comment]
@markus-mw Hast du da ne Idee?

**Comment by markus-mw** [comment]
@chriwen : Ja. Irgendwie sind alle Event-Plugins ähnlich und bügeln über gewisse Logiken einfach drüber. So auch das hier.

Im Stacktrace in den Schritt #3 wird das globale $post Objekt überschrieben. Auf dieses bauen wir aber auf und deshalb wird der Fehler geworfen, dass der entsprechende Post nicht gefunden werden kann. Da werden wir leider nicht viel machen können.

**Comment by chriwen** [comment]
Derzeit keine Lösung möglich. Wir haben den Support des verursachenden Plugins angeschrieben. Bislang keine Rückantwort.

**Comment by hansmorb** [comment]
Habe mich nochmal daran probiert

**Comment by hansmorb** [comment]
Leider stürzt das Buchungsformular auch immer ab, wenn gleichzeitig Veranstaltungen durch dieses Plugin aktiviert sind.

**Comment by hansmorb** [comment]
Das Problem scheint damit zusammenzuhängen, dass sich CommonsBooking für Posts zuständig fühlt die gar nicht CB Posts sind 

![image](https://user-images.githubusercontent.com/6433480/170075862-5cada9ec-70c8-4952-aacc-f443da9153c4.png)
