### ISSUE TITLE
Cache generates ghost records

### ISSUE THREAD

**Issue by antton** [wielebenwir/commonsbooking#677]
When the booking post is removed, I continue watching it on booking page but with null references, I attached an screenshot showing the "bug". I remove getCacheItem function from Timeframe.php to make it dissapear.

'' if (Plugin::getCacheItem($customId)) {
            return Plugin::getCacheItem($customId);
        } else {
}''

I know that there should be an other option on wordpress to clear cache after wp_delete_post but I don't know how to force. I'm not using any WPCache plugins, this test are on a fresh installation wordpress.

**To Reproduce**
- Add booking product
- Remove booking product, after confirmation.

**Expected behavior**
- If this records does not exist in the wp_posts they shouldn't appear.

**Screenshots**
![Captura de pantalla 2021-06-15 a las 11 17 18](https://user-images.githubusercontent.com/1666548/122027487-70d51500-cdcb-11eb-9945-bbbb3a8f9c31.png)

Expected result

![Captura de pantalla 2021-06-15 a las 11 23 26](https://user-images.githubusercontent.com/1666548/122028286-2dc77180-cdcc-11eb-9bd4-08b79cfbd9a8.png)

**Comment by markus-mw** [comment]
@antton : I'll care about a fix.

**Comment by markus-mw** [comment]
@antton : The problem should be fixed in master branch now. You can tast if you like to.
@chriwen : Neben dem eigentlichen Problem hab ich auch noch eine Fallback-Ausgabe für gelöschte Items/Locations ergänzt.

**Comment by chriwen** [comment]
getestet in master.
