### ISSUE TITLE
Gebuchte Uhrzeiten besser visualisieren.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#679]
14-00 Uhr ist in diesem Fall nicht wählbar, sieht aber gleich aus wie 10-14 Uhr
![grafik](https://user-images.githubusercontent.com/28141760/122523687-97878b80-d017-11eb-915f-93ee4ccf8a5f.png)

**Comment by chriwen** [comment]
@hanneskasimir das müsste mittlerweile besser sein, oder? bei mir ist das hellgrau. ich schließe mal. Wenn es noch besteht, bitte wieder öffnen.
