### ISSUE TITLE
Verwaltung Nutzungseinschränkungen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#681]
Möglichkeit für Admins, Nutzungseinschränkungen (Reparatur, Ausfall, Defekte) zu hinterlegen und entsprechende Aktionen auszulösen:

Es wird ein neuer CPT "Restrictions" angelegt:

Felder:
- [x] Auswahl Location Oder Item (@chriwen: Sollte hier auch beides möglich sein? -> JA)
- [x] Startzeit (@chriwen: Datum + Uhrzeit nehme ich an? -> JA
- [x] Vorraussichtliche Endzeit (@chriwen: Datum + Uhrzeit nehme ich an? -> JA
- [x] Typ: Totalausfall, Hinweis
- [x] Hinweistext: 
- [x] Status: Keiner / Aktiv / Erledigt
- [x] Senden-Button : E-Mail soll an Location bzw. Item-Manager und alle in dem betreffenden Zeitraum verknüpften Bookings gehen.

**Speichern**
- [x] Wenn der Typ == Hinweis ist und der Status == Erledigt, werden beim Klick auf "E-Mail verschicken" die Aufhebungs-Mails versendet. 

**Totalausfall**

- [x] automatische Stornierung
- [x] Hinweistext an alle betroffenen Stornierungen sowie Location und Item-Admins
- [x] Versand von Stornierungsmail inkl. Stornierungsgrund (aus Kommentarfeld)
- [x] Blockierung des ganzen Zeitraums (ist schon so, oder?)
- [x] Sollte der Repair-Zeitrahmen gelöscht werden, können neue Leute buchen. Keine Mails mehr an vorherige Buchende.

**Hinweis/Hint/Einschränkung**
- [x] Hinweismail an alle, die eine Buchung in dem Zeitraum haben sowie Location und Item-Admins
- [x] hint wird in Kommentarfeld bei Zeitrahmen geschrieben
- [x] keine Veränderung bestehender Buchungen

**Vorlagen:**
- [x] Vorlagen in den Einstellungen -> Vorlagen
- [x] Vorlage Ausfall
- [x] Vorlage Einschränkung
- [x] Vorlage Aufhebung Einschränkung 

**Templates**
- [x] Erweiterung Templates um einen Baustein "Hint", der im Loop alle jeweiligen Hints zu Location / Item anzeigt. Dieser Baustein wird dann dynamisch in die jeweils bestehenden Templates integriert (Item / Location / Booking)
@chriwen : Hier müssen wir noch einmal drüber sprechen wie die Funktionsweise aussehen soll. Ich habe jetzt zunächst mal vorgesehen, dass man mit {{restriction:[property]}} auf die Infos der Restriction zugreifen kann.

**Template-Beispiel**
```
<h2>Hallo {{user:first_name}},</h2>
<p>
das Lastenrad {{restriction:itemName}} ist von {{restriction:formattedStartDateTime}} bis {{restriction:formattedEndDateTime}} nicht nutzbar.
</p>
<p>
Der Grund dafür ist folgender:
{{restriction:hint}}
</p>
```

Flotte hat das so gelöst: https://github.com/flotte-berlin/commons-booking-item-usage-restriction
Ich denke, so ähnlich können wir es inhaltlich auch umsetzen.

**Comment by hanneskasimir** [comment]
Ich würde für einen eigenen CPT (was heißt das eigentlich?) plädieren:

1. Totalausfall (über CPT "repair") 
- automatische Stornierung 
- Versand von Stornierungsmail inkl. Stornierungsgrund (aus Kommentarfeld)
- Blockierung des ganzen Zeitraums (ist schon so, oder?)
- Sollte der Repair-Zeitrahmen gelöscht werden, können neue Leute buchen. Keine Mails mehr an vorherige Buchende.

2. Hinweis/Hint/Einschränkung (über CPT "hint")
- Hinweismail an alle, die eine Buchung in dem Zeitraum haben.
- hint wird in Kommentarfeld bei Zeitrahmen geschrieben
- keine Veränderung bestehender Buchungen
- Bei Löschung des Zeitrahmen: Infomail an alle Empfänger der Hinweismail, die noch eine Buchung in der Zukunft in dem Zeitraum haben
- Integration des Kommentars über dem Buchungsbutton mit Überschrift: "Aktueller Hinweis:" oder so.

**Comment by chriwen** [comment]
Bei der Ausgabe:
- Template-Baustein, der auch mehrere Hinweise untereinander anzeigen kann

**Comment by markus-mw** [comment]
@chriwen : Ich habe den Custom Post Type angelegt und die Kalenderlogik so erweitert, dass die Totalausfälle dazu führen, dass der jeweilige Timeframe in diesem Zeitraum nicht gebucht werden kann. Das nächste wäre die Info auf der Detailseite und anschließend die Mails. Vorher wäre es mir lieb, wenn du dir die Anmerkungen in der Beschreibung mal prüfen könntest.

**Comment by chriwen** [comment]
@markus-mw : Hab deine Anmerkungen kommentiert oben.

**Comment by markus-mw** [comment]
@chriwen : Bis auf die Benachrichtigung bei der Löschung eines Timeframes ist in feature/issue-681 erstmal alles drin. Wenn du wieder am Start bist, kannst du da schon einmal einen blick drauf werfen.

**Comment by chriwen** [comment]
@markus-mw Menüpunkt wird nicht angezeigt. Fehlermeldung sagt: keine ausreichende Berechtigung.

**Comment by markus-mw** [comment]
@chriwen : Ich habe jetzt die besprochenen Anpassungen vorgesehen. Du kannst testen.

**Comment by chriwen** [comment]
ist aktuell in feature/issue-732

**Comment by hanneskasimir** [comment]
@markus-mw : fein, Danke, jetzt wird es nur bei der richtigen Kombination angezeigt.
Nur werden leider aktuell keine Mails zu den restrictions verschickt (Mailversand, d.h. Buchungs- und Stornierungsmails, auf Stage funktioniert aber jetzt grundsätzlich, #776 ist geschlossen.)

**Comment by markus-mw** [comment]
@hanneskasimir : Bitte versuch es noch einmal. Die Logik hatte Buchungen die nicht komplett innerhalb der Restriction Grenzen liegen, nicht berücksichtigt. Wenn also die Restriction vom 26.-27.11. eingestellt war, wurden Buchungen vom 26.-28.11. nicht berücksichtigt und daher keine Mails verschickt.

**Comment by hanneskasimir** [comment]
Fein, hat jetzt funktioniert mit den Mails! Das fehlt noch:

- [ ] Blockierung des ganzen Zeitraums
- [ ] Hinweistext beim E-Mail-Versenden "Versand funktioniert erst nachdem die Störung veröffentlicht wurde" o.ä.
- [ ] In den E-Mails müssten noch die Details restlichen rein (Datum usw. oder sind es andere tags?): 
![grafik](https://user-images.githubusercontent.com/28141760/142645641-2806bfce-9077-4783-aff2-5b6ef9993377.png) 
![grafik](https://user-images.githubusercontent.com/28141760/142645711-edb824cb-3c02-4dee-8b49-7b392f7f5182.png)
- [ ] Hinweis im Frontend war jetzt weg, müsste wieder rein.

**Comment by chriwen** [comment]
@markus-mw : Hab die Templates angepasst. Auf stage1 wird der Tag {{booking:BookingLink}} nicht aufgelöst. Kannst das mal prüfen? Merci.

**Comment by chriwen** [comment]
@markus-mw : Und nach dem Versenden der Restriction wird die "Sent"-Information nicht angezeigt. Im Restriction-View beim Rendern des Buttons scheint da was eingebaut - wird aber nicht angezeigt.

**Comment by chriwen** [comment]
@markus-mw Und Bei Auswahl des Dropdowns "Problem gelöst" und anschließendem Senden werden keine Restriction Cancelled Mails versendet.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir 
{{booking:BookingLink}}: Das Booking Objekt wurde für die Templates noch nicht bereitgestellt. Das hab ich erweitert.

Die Ausgabe der Sent-Info ist korrigiert. Der Wert wurde vom CMB2 immer wieder geleert, weil der save_post später zog.

Die "Problem gelöst" Mails werden jetzt auch verschickt. Das war von der Logik so vorgesehen, dass die Info nur für Gecancelte Buchungen verschickt wird. Ich weiß nicht, ob das irgendwann mal so angedacht war.

**Was mir noch aufgefallen ist:** In der "Problem gelöst" Mail waren im Template ein paar Fehler beim einbinden der Infos zum User sowie zur Restriction. Es war immer ein Leerzeichen zwischen den {{ und }}. Das funktioniert so nicht.

**Comment by chriwen** [comment]
@markus-mw danke für die Korrekturen. Der Template Fehler hängt wahrscheinlich mit der Übersetzung zusammen. Das schau ich mir an

**Comment by hanneskasimir** [comment]
ganz neuer Fehler auf Stage1. Ich hatte die Einschränkung veröffentlicht. Die Fehlermeldung kam nach dem ich auf "Senden" geklickt habe.
![grafik](https://user-images.githubusercontent.com/28141760/143406948-85ac68e5-8d65-44b8-9335-9a7f21bc7869.png)

**Comment by hanneskasimir** [comment]
Beim 2. Versuch kam der Fehler nicht mehr.
Die Einschränkung-Mail ist aber nicht verschickt worden.

**Comment by markus-mw** [comment]
@hanneskasimir : Passiert das in der Einschränkung "asdf a"? Da ist der Zeitraum in der Vergangenheit, daher wird nix verschickt.

**Comment by chriwen** [comment]
@markus-mw Jetzt hatte ich den Fehler auch bei einem bereits gespeicherten Datensatz.

**Comment by chriwen** [comment]
Error-Log sagt:
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
cb-dev/stage1/wp-content/plugins/commonsbooking/src/Messages/RestrictionMessage.php Zeile 19

Uncaught Exception: item or location could not be found
cb-dev/stage1/wp-content/plugins/commonsbooking/src/View/Calendar.php Zeile 236
Backtrace
#0 cb-dev/stage1/wp-content/plugins/commonsbooking/src/View/Location.php(54): CommonsBooking\View\Calendar::getCalendarDataArray(NULL, 30202, '2021-11-01', '2022-02-25')
#1 cb-dev/stage1/wp-content/plugins/commonsbooking/templates/location-single.php(9): CommonsBooking\View\Location::getTemplateData()
#2 cb-dev/stage1/wp-includes/template.php(732): require('/home/webpages/...')
#3 cb-dev/stage1/wp-content/plugins/commonsbooking/includes/Template.php(79): load_template('/home/webpages/...', false)
#4 cb-dev/stage1/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Location.php(77): commonsbooking_get_template_part('location', 'single')
Relevante Hilfe-Artikel

**Comment by markus-mw** [comment]
Aach, das ist wegen PHP 7.3 und Typehinting. Ich dachte ich hätte das schon überall wieder rausgeworfen. Kümmere mich drum. Ist nur eine Kleinigkeit. Auf dem neuesten Stand seid ihr aber, oder?

**Comment by markus-mw** [comment]
@chriwen : Das Hauptproblem unter PHP 7.3 ist behoben. Um die Sache mit dem Ausgrauen kümmere ich mich noch.

**Comment by markus-mw** [comment]
@chriwen : Das disablen des Senden-Buttons ist jetzt auch umgesetzt. Musst wahrscheinlich deinen Cache mal komplett leeren, damit das zieht.

**Comment by chriwen** [comment]
@markus-mw : Hab das in 3 Browsern getestet. Der Senden-Button ist weiterhin initial aktiv. Hast du noch ne Idee?

**Comment by chriwen** [comment]
@hanneskasimir Kannst du mal auf stage1 prüfen, ob der Senden-Button ausgegraut ist, wenn eine neue Restriction angelegt wurde. Vorher einmal Browsercache löschen.

**Comment by markus-mw** [comment]
@chriwen : Initial deaktiviere ich den nicht, nur bei Änderung. Theoretisch muss initial ja auch was gewählt werden, sodass er dann inaktiv wird. Oder übersehe ich einen Case?

**Comment by chriwen** [comment]
@markus-mw Ah,ok. Alles ok. Ich hatte das geprüft direkt nach dem Erstellen der Restriction, ohne einen Wert zu belegen. Nach Auswahl eines Items wird der Button wie gewünscht deaktiviert.

**Comment by chriwen** [comment]
@hanneskasimir Bitte mal auf Stage prüfen.

**Comment by hanneskasimir** [comment]
Mail geht neben dem Nutzer auch Nils&Flo (@localhost). Ist das so korrekt?
![grafik](https://user-images.githubusercontent.com/28141760/144613707-2520dcf6-ae5e-4a66-ac68-64a4b1d7eaf3.png)

**Comment by chriwen** [comment]
@markus-mw : Das ist interessant. Die sind weder als Location, noch als Item-Admin hinterlegt. Wie kommen die in den Verteiler?

**Comment by chriwen** [comment]
@hanneskasimir : einen Grund für die abweichenden Absender-Adresse gibt es eigentlich nicht. Wir könnten das auch entfernen und den Standard nehmen.

**Comment by markus-mw** [comment]
@chriwen, @hanneskasimir : Die Mails an Flo und Nils kommen daher, dass Sie die Location bzw. das Item angelegt haben (Autor) und damit quasi "Admin" dafür sind. Das kann ich ausbauen, wenn ihr wollt.

**Comment by chriwen** [comment]
@markus-mw danke fürs rausfinden. Ja, bitte  Autor ausbauen.

**Comment by markus-mw** [comment]
@chriwen : Die Autoren der Locations/Items werden jetzt nicht mehr benachrichtigt.

**Comment by hanneskasimir** [comment]
- [ ] Leider werden bei einem Hinweis noch keine Mails verschickt. Beim Totalausfall funktioniert es.
- [ ] Wenn kein Ende der Einschränkung angegeben wird in die Vergangenheit verwiesen: 
![grafik](https://user-images.githubusercontent.com/28141760/144710813-95a07eb6-4855-4d10-a49e-6a32d98619da.png). da sollte dann besser nur "gültig ab #Datum" stehen.

**Comment by markus-mw** [comment]
@hanneskasimir : Versuchs bitte noch einmal. Dass der Hinweis nicht verschickt wurde, hing auch mit dem fehlenden Enddatum zusammen. Ich habe außerdem selbst noch einen Bug gefunden. In der Andrede des Users wurde noch der aktuell angemeldete User immer angesprochen. Das ist jetzt auch korrigiert.

**Comment by hanneskasimir** [comment]
Versand geht leider nicht, siehe Walther @ bei Nikola.

**Comment by chriwen** [comment]
@markus-mw Müsste in der CB.php Zeile 120 hier nicht auch die $cb_user-ID statt der $userID verwendet werden, wenn if($post instanceof \WP_User) wahr ist? Ansonsten holen wir dort ja weiterhin nur die User-Metadaten des Autors, oder?

**Comment by markus-mw** [comment]
@chriwen : Das ist korrekt. Jetzt sollte es passen. Ich hab außerdem noch einen Bug entdeckt der dafür sorgt, dass Restrictions ohne Enddatum wieder nicht verschickt wurden. Ich check das gleich nochmal auf Stage mit Walther \@ bei Nikola

**Comment by hanneskasimir** [comment]
so, liebe Leute, lieber @markus-mw und lieber @chriwen, ich mach jetzt was ganz verrücktes und schließe dieses, unser schönstes, längstes, wunderbarstes Ticket! Juchuu! Danke!
