### ISSUE TITLE
Timeframe-Export: Ausleihzeiten mit exportieren

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#690]
Beim Export der Zeitrahmen, sollen die Uhrzeiten bei Buchungen (von / bis) jeweils für Abholung und Rückgabe mit exportiert werden.

**Comment by markus-mw** [comment]
@chriwen : Ist ergänzt.

**Comment by chriwen** [comment]
@markus-mw könntest du noch die Buchungszeiten der Abholung und Rückgabe also den Slot hinzufügen. Sodass wir z.B. Abholung 12.03. 2021 14:00 - 18:00 Uhr noch zusätzlich haben?

**Comment by markus-mw** [comment]
@chriwen : Ist ergänzt.

**Comment by chriwen** [comment]
getestet in master
