### ISSUE TITLE
Erinnerungs- und Feedbackmail an Nutzende

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#695]
Die Nutzenden erhalten eine Erinnerung zu Ihrer Buchung sowie im Nachgang eine Feedback-E-Mail. Diese Optionen können von den Admins auf Wunsch einzeln aktiviert werden.

- [ ] Buchungserinnerung x Tage vor dem Ausleihtag (Zahl beliebig wählbar). Versand einer Kopie der Mail für bestätigte Buchungen erweitert um das Text "Erinnerung: " zu Beginn des Betreffs
- [ ] Feedback-Mail x Tage nach dem Rückgabetag (Zahl beliebig wählbar). Inhalt der Mail wird unter Vorlagen als eigenes Template definiert. Default soll die Vorlage leer sein.

Integration erfolgt unter eigenem Tab "Reminder" inkl. weiterer Optionen.

**Comment by Steffeng5** [comment]
Genau das Feature suchen wir in Wiesbaden. Gerne die 3 Tage auch konfigurierbar machen :-) wir haben eher an 1-2 Tage gedacht

**Comment by chriwen** [comment]
@markus-mw Options-Tab und Felder sind in feature/issue-695 angelegt. 
Hinweis: Die Uhrzeiten habe ich als einfaches numerisches Feld erfasst, da ich mit dem CMB2 text_time-Feld (inkl. Time-Picker) keine Möglichkeit gefunden habe eine default-Uhrzeit zu setzen. Ich hoffe, das klappt auch so, ansonsten ändere gerne den Feld-Typ nochmal.

**Comment by chriwen** [comment]
@markus-mw : Als Regel würde ich definieren:
-> Versende E-Mail x Tage vor Beginn der Buchung. Wenn Buchung weniger als X Tage vor Beginn erst angelegt wurde, dann erfolgt kein Versand der Reminder-Mail.

**Comment by markus-mw** [comment]
@chriwen : Die beiden Mail-Funktionen sind jetzt in feature/issue-695 umgesetzt. Bezüglich der Startzeit ist zu beachten, dass der Wordpress Scheduler Jobs nur startet, wenn jemand die Seite aufruft...
Um das sinnvoll testen zu können, hab ich den Versand der Mails in WP_DEBUG Umgebungen auf 10 Sekunden eingestellt. Um die Jobs zu testen ist es hilfreich einfach /wp-cron.php aufzurufen.

**Comment by chriwen** [comment]
@markus-mw Der Mailversand für die Post-Booking-Mail scheint zu funktionieren. Allerdings habe ich nun für ALLE jemals getätigten Buchungen in der Vergangenheit eine E-Mail erhalten ;-) Hier sollen wir noch einen Filter einbauen, dass die E-Mail maximal für die Buchungen der zurückliegenden 2 Tage gesendet wird. So sollten wir mögliche Altbuchungen verhindern, oder?

**Comment by markus-mw** [comment]
@chriwen : Du hast vollkommen Recht. Ich weiß schon was der Denkfehler ist, das bekomme ich sauber hin. Gedacht war es so, dass ich mir die Buchungen suche, die am "Feedback-Tag" enden. Ich habe jetzt aber alle gesucht, die vor oder an dem Tag enden... Kümmere ich mich heute Abend drum.

**Comment by markus-mw** [comment]
@chriwen : Die Logik ist jetzt korrigiert. Die Feedback-Mail geht nur an Buchungen raus, die am eingestellten Tag Enden. Probiers bitte noch einmal.

**Comment by Steffeng5** [comment]
Dann kommt die Mail aber im Zweifel bei eintägigen Buchungen vor der Abholung oder? Vllt lieber am Folgetag, bzw. konfigurierbar?

**Comment by markus-mw** [comment]
@Steffeng5 : Das kommt darauf an wie du es konfigurierst. eine sicher Bank ist einzustellen, dass die Mails immer erst am Tag nach dem letzten Buchungstag verschickt werden. Dann gibt es da keine Probleme. Wenn man den selben Tag für den Versand einstellt, sollte die Versandzeit dann recht spät eingestellt werden, damit sich der Versand nicht mit der Abholung überschneidet.

**Comment by chriwen** [comment]
@markus-mw : wie aufwändig wäre es, das so zu bauen, dass bei Versand am gleichen Tag die Mail erst nach Buchungsende (inkl. berücksichtigung der Uhrzeit) rausgeht? Dann würde ich die Zeiteinstellung wieder rausnehmen wollen.  Der Cron müsste dann halt zumindest stündlich getriggert werden. Oder wir bieten einfach nur per Standard einen Versand für alle Buchungen eines Tages um 00:01 des Folgetages an?

**Comment by markus-mw** [comment]
@chriwen 
Ansatz 1: Das hat Corner Cases die berücksichtigt werden müssten. (z.B. Versand an selben Tag und nach Versand erfolgt noch eine Buchung für diesen Tag -> keine Benachrichtigung) Hinzu kommt, dass der Cron, wenn er einmal gescheduled wurde dann wieder entfernt werden müsste. Kurz gesagt, halte ich das für recht anfällig und würde davon abraten.

Ansatz 2: Das kann mit der aktuellen Umsetzung gelöst werden, indem man einstellt, dass der Versand am Folgetag um 0 Uhr ausgelöst werden soll.

**Comment by chriwen** [comment]
@markus-mw ok. Dann machen wir Variante 2 ;-). Also per default wird die Mail am Folgetag versendet. Ohne weitere Einstellmöglichkeiten. Merci.

**Comment by markus-mw** [comment]
@chriwen : Ist erledigt. Die Zeit/Tageseinstellung für die Reminder-Mail hab ich gelassen wie sie ist oder soll das da auch zumindest von der Uhrzeit her gesehen statisch ohne Einstellmöglichkeit laufen?

**Comment by chriwen** [comment]
@markus-mw Die Einstellung der Reminder-Mail können wir erstmal so lassen. Ich hab lokal hier nun folgendes Verhalten. Anscheinend wurde die Post-Booking-Mail für eine Buchung mehrmals versendet. Hast du na Idee zu?
![image](https://user-images.githubusercontent.com/12683634/143554846-98a55489-6899-492a-9706-b66e95c8a206.png)

**Comment by markus-mw** [comment]
@markus-mw : Das liegt wahrscheinlich daran, dass ich den Scheduler lokal auf 10 Sekunden hab. Wenn die Funktion grundsätzlich funktioniert, können wir das wieder ausbauen...
