### ISSUE TITLE
Einschränkung Heavy-User  Funktion integriert

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#697]
Anforderungen:
- Prüfe Anzahl A von Buchungen von Nutzer X im Zeitraum Y (Tagen)
- Wenn Schwellenwert (einstellbar) von A im Zeitraum Y (gerechnet ab dem heutigen Tag zurück) überschritten ist, wende folgende Regeln an:
  - Blockiere Buchungen im Zeitraum von B Tagen ab dem End-Datum der letzten Buchung von X
  - und/oder Begrenzung des Vorausbuchungszeitraums auf C Tage (setze advance_bookinkdays dynamisch auf den eingestellten werden) 

Optional: 
- Mehrere Schwellenwerte mit entsprechenden Abhängigkeiten einstellbar (z.B. 3 feste Schwellenwerte)

Verortung der Einstellungen am Zeitrahmen mit folgenden Feldern:
- Zu betrachtender zurückliegender Zeitraum für Buchungen eines einzelnen Nutzenden in Tagen (Y):
- Schwellenwert für maximale Anzahl Buchungen (A) im Zeitraum Y (Zahl)
- Buchungen erst wieder möglich ab B Tagen gerechnet von letzter Buchung (Buchungspause) in Tagen
- Maximaler Vorausbuchungszeitraum in Tagen

**Comment by RalphBike** [comment]
Wir haben hierfür ebenfalls Verwendung, da wir mit einigen Intensiv-Ausleihern zu tun haben. 

Mein Use-Case ist:
ein Ausleiher kann maximal n Geschäftstage pro Interval von m Tagen ausleihen, über ALLE Räder. Z.B. 3 Tage innerhalb von 30 Tagen.
Die Begrenzung sollte nicht allen Nutzern explizit kommuniziert werden, sondern nur dann, wenn das Limit erreicht wurde. Es soll ebenfalls nicht kommuniziert werden, ab wann das Interval zu Ende ist und der Nutzer wieder ausleihen darf.  

Optional: Das ganze könnte kollidieren mit ausleihbarem Zubehör (da mehrere Buchungen). Außerdem könnte es sinnvoll sein, nur bestimmte Nutzer damit zu beschränken.

**Comment by chriwen** [comment]
@RalphBike Danke für die Ergänzungen. Wir nehmen eure Anregungen in die Planung für diese Funktion mit auf. Das mit dem Zubehör sollte sich auch regeln lassen, in dem wir ggf. Buchungen verknüpfen und das so festhalten können.
