### ISSUE TITLE
Hinweis auf eingeschränkte Buchbarkeit bei Einschränkung auf Gruppen/Rollen

### ISSUE THREAD

**Issue by JannSchulte** [wielebenwir/commonsbooking#698]
**Problembeschreibung:** 
Sobald ein Artikel zwar im Zeitraum buchbar ist, aber der Benutzer in keiner der für den Artikel freigeschalteten Gruppen ist, erscheint der Artikel mit leerem Kalender. 

Somit ist für den Benutzer nicht erkennbar, dass der Artikel zwar verfügbar ist, aber ihm die Berechtigung fehlt. 

**Lösung:** 
- Allg. Hinweis, dass der Artikel in bestimmten Zeiträumen nur für bestimmte Benutzer buchbar ist
- Erweiterung der Einfärbung/Legende im Kalender um die auf eine Gruppe beschränkte Verfügbarkeit

**Comment by chriwen** [comment]
@hansmorb Ich würde das eigentlich glaube ich nicht so prominent platzieren. Wenn ein Nutzender nicht einer freigeschaltete Gruppe zugeordnet ist, hat das ja in der Regel einen Grund. An dieser Stelle braucht es dann im Frontend nicht den prominenten Hinweis, dass der/die Nutzende hier nicht zu der Gruppe gehört, oder?
Zudem würden wir evtl. in Zukunft Nutzenden-Gruppen (Rollen) auch für die dynamische Zuweisung von Buchungsberechtigungen nutzen (Flotte macht das bereits so ähnlich).

Vorschlag: Wir passen das Kalender-Rendering so an, dass die mit Einschränkungen belegten Timeframes ohne Anmeldung garnicht berücksichtigt werden, d.h. im Zweifelsfall steht dann da "Item nicht verfügbar". Erst nach Anmeldung werden diese einbezogen und der Nutzende-Individuelle Kalender generiert. So verhindern wir den leeren Kalender und müssen nicht so kryptische Hinweise auf versteckte Nutzendengruppen einblenden. Was meinst du? @hansmorb

**Comment by hansmorb** [comment]
Ticket 599 hat das Thema nochmal aufgeworfen. Vielleicht sollten wir doch eine separate Meldung wie "Buchung eingeschränkt" oder so ausgeben.
