### ISSUE TITLE
Sortieren nach NutzerIn in Übersicht Zeitrahmen funktioniert nicht

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#701]
**Usecase**

Wir wollten gerade rausfinden, wie oft eine bestimmte NutzerIn bei uns ein Rad ausgeliehen hat. Dazu bin ich auf "Commons Booking | Zeitrahmen" gegangen und habe "Filter nach Typ" auf "Buchung" gesetzt und auf "Auswahl einschränken" geklickt. Dann wollte ich mir die Liste nach Nutzende*r sortieren lassen. Daraufhin ist die Liste leer und bleibt auch leer, wenn ich wieder auf die Spalte klicke. Es hilft hier nur der "Zurück"-Button.

Hier der direkte Link zu der Liste mit gesetzten Filter u
https://example.com/wp-admin/edit.php?post_type=cb_timeframe&orderby=timeframe-author&order=asc

**Expected behavior**
Ich möchte die Liste nach Username sortieren können.

**Comment by chriwen** [comment]
@Konafets Danke für den Hinweis. Um die Buchungen herauszufinden kannst du auch die Buchungsliste im Frontend benutzen. Als Admin hast du hier Zugriff auf alle Buchungen und kannst dann nach Nutzenden filtern und so die Buchungen einsehen. Derzeit muss noch  manuell gezählt werden, wir haben aber eine Art Nutzenden_Auswertung in der Planung ;-)

**Comment by hansmorb** [comment]
Ticket geschlossen, da diese Funktion jetzt auch nicht mehr angezeigt wird.
