### ISSUE TITLE
Überbuchen: Anzahl der pro Buchung abzuziehenden Tage bei Überbuchung anpassbar machen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#702]
Derzeit pauschaler Abzug von 1 Tag pro Buchung bei Überbuchungsoption. Dieser Wert soll in den Einstellungen pauschal für die gesamte Instanz anpassbar sein.

**Comment by markus-mw** [comment]
@chriwen : Das Feature ist in feature/issue-702 umgesetzt. Es gibt noch ein kleines Darstellungsproblem, wenn mehrere nicht buchbare Felder übersprungen werden. Funktional passt es aber. 
Hier ein Beispiel mit 4 buchbaren Tagen, ohne dass die nicht buchbaren Tage gezählt werden:
Hier dürfte der Samstag nicht sichtbar sein:
![image](https://user-images.githubusercontent.com/22905753/169559827-0e0315a2-c662-4ef1-adb7-e0c41223dd14.png)

Das ist ok:
![image](https://user-images.githubusercontent.com/22905753/169559891-1edac26c-3972-4dcc-848d-7869795393bb.png)

**Comment by hansmorb** [comment]
Wirklich noch in 2.8 @chriwen ?
