### ISSUE TITLE
Buttontext "Filter" unter der Karte ändern in "Karte filtern" bzw. "Filter map" oder den Text im Backend änderbar machen.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#714]

**Comment by chriwen** [comment]
@hanneskasimir Ist bereits vorhanden ;-) (hab ich vorher auch nicht gewusst) :-)
![image](https://user-images.githubusercontent.com/12683634/148379070-1039a1ba-2b12-498c-a986-89dddecb3ba5.png)
