### ISSUE TITLE
Anspache der Nutzer mit "sie" anstatt "du" ermöglichen.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#717]

**Comment by datengraben** [comment]
Da hat auch schon irgendwer mit begonnen, aktuell sogar schon bei 86 % https://translate.wordpress.org/locale/de/formal/wp-plugins/commonsbooking/

**Comment by hansmorb** [comment]
Hab mal die 30 fehlenden String noch erledigt, ansonsten würde ich das aber schließen weil die Übersetzungen ja über translate.wordpress.org laufen.
