### ISSUE TITLE
Buchungscode in Buchungsliste integrieren (mind. Frontendliste)

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#719]
Buchungscode in die Buchungsliste integrieren. Unterhalb von Artikel @ Location.
Code: CODE

**Comment by markus-mw** [comment]
@hanneskasimir : Der Code wird jetzt an der Stelle ausgegeben. Solltest du die Änderungen nicht sehen, musst du deinen Browser-Cache löschen. WP ist hartnäckig was die Speicherung davon angeht.
