### ISSUE TITLE
Map Clustering can not be disabled

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#733]
**Describe the bug**
The map clusters the markers based on some settings. To disable this, the tooltip mentions to set the value to "0".

![2021-09-04_13-06-44](https://user-images.githubusercontent.com/363363/132100692-7e646ec9-5b65-4937-8bc4-bd1fb03a4745.jpg)

When I do this and save the page, I get the error, that the value "0" is not allowed:

![2021-09-04_13-06-59](https://user-images.githubusercontent.com/363363/132100721-571bf0fe-8263-4804-8f5c-9e21c246c12c.jpg)

As a workaround I set the value to 10 px, but I consider this as a bug.

**Comment by chriwen** [comment]
@Konafets this is a workaround cause values <10 produced some rendering errors and performance problems in the map. we will keep this in our list for upcoming improvements.

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das nochmal anschauen. Bekommen wir das gelöst?

**Comment by markus-mw** [comment]
@chriwen : Schau ich mir an.

**Comment by markus-mw** [comment]
@chriwen : Wie äußern sich denn die Rendering-Fehler bzw. Performance Probleme? Ich konnte in meiner überschaubaren Testumgebung nichts feststellen.

**Comment by datengraben** [comment]
Rendering-Fehler: Wenn ich den Wert auf 0 Setze wird trotzdem geclustert. Also entweder die Dokumentation anpassen das man es nicht deaktiveren kann oder den Code.

Cluster auf 0px, 2 Locations liegen eine Hausnummer voneinander entfernt, sind also zwei versch. Marker, werden aber trotzdem geclustert.
![image](https://user-images.githubusercontent.com/105302830/209412428-51098a03-a32b-4aa7-ab1b-93bbdfa14c6a.png)


Bei höheren Werten funktioniert es tadellos.

Cluster auf 4000px, alle 3 Locations im Cluster.
![image](https://user-images.githubusercontent.com/105302830/209412371-13b26a4d-dc54-41ba-8218-01df81e6cc61.png)


Performance-Problem habe ich keines, habe aber auch nur drei Stationen.

**Comment by datengraben** [comment]
Ok also der `getBounds` Fehler kommt auf, wenn `markers` eine LayerGroup ist und somit kein `getBounds` implementiert. Und `center_position` fehlt zumindest bei mir, da habe ich noch nicht ganz verstanden wieso.

Ich berechne die `center_position` jetzt aus den Kooridnaten der existierenden Marker und so ist an der Stelle center_position auch nicht mehr undefined.

Ich habe mal einen PR gestellt, hoffe das ist ok.

**Comment by datengraben** [comment]
Hier noch ein Screenshot: Max radius ist auf 0 gesetzt, Marker werden nicht geclusterd.
![image](https://user-images.githubusercontent.com/105302830/209437641-2b187e44-4ada-4c84-b1b7-e886b54d0bad.png)
