### ISSUE TITLE
Typo in word

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#734]
The word "Export" is missing an x in https://fjordbeweger.de/wp-admin/admin.php?page=commonsbooking_options_export:

![2021-09-05_22-27-40](https://user-images.githubusercontent.com/363363/132140537-99e0656e-7994-4ada-bff3-09574567bc20.jpg)

**Comment by chriwen** [comment]
@Konafets thanks for reporting this issue. it will be fixed in the next update.
