### ISSUE TITLE
De/Activating the API in settings requires end date for export

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commonsbooking#735]
**Describe the bug**
I was going to activate the API in `/wp-admin/admin.php?page=commonsbooking_options_export` but when I click "Save" an error shows up, telling me I must insert an end date for the export.

![2021-09-05_22-31-26](https://user-images.githubusercontent.com/363363/132140630-0a445624-a93e-4531-aac3-b3dbec1f8b31.jpg)

**Comment by chriwen** [comment]
@Konafets thanks for reporting the issue. in the next update we will separate the api and export options in two tabs so this issue will be solved. in the meantime you can just type in any end date - it will not take any effect until you click export.
