### ISSUE TITLE
Kann die Commons API nicht aktivieren (access without API key)

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commonsbooking#739]
Ich kann die Commons API unter Settings momentan nicht erfolgreich aktivieren (gilt sowohl für den Master branch, als auch für feature/issue-660). Wenn ich "/wp-json/commonsbooking/v1/items" aufrufe erhalte ich die Fehlermeldung: 

```
{"code":"rest_no_route","message":"Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist.","data":{"status":404}}
```

Ich habe "Enable API Access without API-Key" aktiviert. Vielleicht funktioniert das nicht?

Es gibt dabei übrigens auch noch ein weiteres Problem: Commons Booking beschwert sich unter "Api shares/Api1", dass ich keinen API-Key eingegeben habe (obwohl ich ja obige Option aktiviert habe). Ich kann "Api1" auch nicht entfernen, um diesen Fehler loszuwerden.

Ich habe gesehen, dass die Commons Api ohne Api-Key erfolgreich unter "https://www.kasimir-lastenrad.de/wp-json/commonsbooking/v1/items" erreichbar ist. Handelt es sich dabei um die aktuelle Version oder läuft die API, weil es sich noch um einer ältere CB-Version handelt?

**Comment by chriwen** [comment]
@christianvoigt Kannst du es nochmal probieren. Ich habe das gerade lokal getestet und es hat soweit funktioniert. Evtl. mehrmals die Einstellungen speichern, damit die entsprechenden Werte korrekt gesetzt werden? 
Ich habe das API-Key nun nicht mehr required gesetzt, sodass der Fehler nicht mehr auftauchen sollte. Sind leider die Limitierungen von CMB2 , dass mindestens ein Eintrag vorhanden sein muss. 

Auf kasimir verwenden wir die offizielle Version 2.4.5, dort sind die aktuellen Änderungen noch nicht enthalten.

**Comment by christianvoigt** [comment]
Hi @chriwen, ich hab gerade feature/issue-660 gepullt, mehrmals die Settings geändert, das Plugin deaktiviert & reaktiviert und ein neues Item angelegt. Das hat leider alles nicht geholfen. Wenn ich die URL der items-Route aufrufe erhalte ich weiterhin nur den 404-Fehler.

Der Api-Key ist allerdings jetzt auch bei mir nicht mehr required.

**Comment by chriwen** [comment]
@christianvoigt Ist das ein System, auf das du mir auch mal Zugriff geben könntest vorübergehend? Würde mir das gerne mal anschauen. Kommt die Fehlermeldung denn auch bei den anderen Routen? Und was passiert, wenn du nur /wp-json/ aufrufst? Werden dann unter den Routen überhaupt commonsbooking-Routen angezeigt?

**Comment by christianvoigt** [comment]
Ist momentan meine lokale Installation. Unter wp-json erscheinen nur die Standard-Rest-Routen, keine commonsbooking-Routen.

Ich werde wohl mal versuchen müssen die Datenbank ganz platt zu machen und dann alles neu zu installieren. Wenn das auch nichts nützt, lade ich meine lokale Version mal hoch, damit Ihr Euch das anschauen könnt.

**Comment by chriwen** [comment]
@christianvoigt ok. Kannst du mal versuchen einfach Ne zweite neue WordPress Instanz mit dem 660 Branch auf deinem lokalen System zu erstellen. Dann könnten wir die Datenbank Themen erstmal ausschließen. Wobei ich mir auch gerade nicht vorstellen kann, was an der Datenbank da Probleme machen sollte.

**Comment by chriwen** [comment]
@christianvoigt So. Hab nen Bug gefunden, der im Zuge der Umstellung der Optionen-Tabs entstanden ist und der verhindert hat, dass die Routen initialisiert werden. Probier mal, ob es jetzt im 660 Branch geht?

**Comment by chriwen** [comment]
ich schließe das Ticket hier mal, da die Tests bei uns alle ok waren. @christianvoigt Wenn du dennoch weiter die oben beschriebene Probleme hast, öffne es gerne nochmal erneut.

**Comment by christianvoigt** [comment]
Vielen Dank für die schnelle Behebung des Bugs! Ich habe gerade gepullt und jetzt funktionieren die Rest-Routen auch wieder bei mir.
