### ISSUE TITLE
Nutzeraccount: Timeframe-Fehler beim Speichern

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#743]
Nach Speichern einer Buchung wird folgender Fehler geworfen:
Notice: map_meta_cap wurde fehlerhaft aufgerufen. Der Inhaltstyp cb_timeframe wurde nicht registriert. Es kÃ¶nnte deshalb unzuverlÃ¤ssig sein, die FÃ¤higkeit "edit_post" mit einem Inhalt dieses Typs abzugleichen. Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 4.4.0 hinzugefÃ¼gt.) in /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-includes/functions.php on line 5663 Notice: Undefined index: start-time in /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php on line 910 Notice: Undefined index: end-time in /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Timeframe.php on line 911 Warning: Cannot modify header information - headers already sent by (output started at /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-includes/functions.php:5663) in /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-includes/pluggable.php on line 1340 Warning: Cannot modify header information - headers already sent by (output started at /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-includes/functions.php:5663) in /mnt/web017/a2/31/511385531/htdocs/wordpress/wp-includes/pluggable.php on line 1343

Ebenso beim Aufruf einer Buchung über die Buchungsliste.

Ich erinnere mich, dass wir dieses map_meta_cap schon mal irgendwo hatten. Laut User ist das einfach so gekommen. Hast du da ne Idee?

**Comment by markus-mw** [comment]
@chriwen: Das Problem wurde schon vor einiger Zeit behoben (ist im master korrigiert). In der letzten Tag-Version ist das aber nicht  enthalten. Jetzt weiß ich nicht, ob der letzte Github Tag auch dem letzten Tag in WP entspricht.
