### ISSUE TITLE
E-Mail-Signatur integrieren

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#75]
E-Mail Signatur für Plugin in Options anlegen.
In E-Mail-Template integrieren

**Comment by datengraben** [comment]
Ists ok wenn ich mir das anschaue? Sieht nach einem guten ersten Issue aus.

**Comment by datengraben** [comment]
Ich gehe davon aus es ist eine generelle Signatur gemeint, welche zum Zweck hat, in den Buchungsmails die das Wordpress-System administrierende Partei zu referenzieren. Diese Signatur kann von einer Admin Rolle bearbeitet und im Template eingefügt werden. Von CommonsBooking Manager und allen anderen niedrigeren Rollen kann sie nicht verändert werden.

Stimmt das?
Gruß Chris

**Comment by genevievecory** [comment]
Hoert sich super an! Signatur im Sinne von Impressum einerseits und Hinweise auf kommende Veranstaltungen / Umfragen, sowas denke ich... nur von Admins bearbeitbar ist bestimmt wichtig.

**Comment by datengraben** [comment]
Ok. Und es ist dann per Shortcode im Mail-Template integrierbar?

**Comment by chriwen** [comment]
@datengraben super, vielen Dank, dass du dich damit beschäftigen möchtest. Und so wie du es beschreibst war es angedacht. Das Template kann in den CB Einstellungen im Bereich Vorlagen integriert werden. An dieser Stelle brauchst du aber keine Prüfung der Berechtigung vornehmen. Alle Einstellungen in CB haben keine definierte Berechtigungslogik. 
die Integration könnte dann über ein TemplateTag In der Form {{Email-Signature}} erfolgen. So können Nutzende es flexibel einsetzen. 
Für das Parsen des Template Tags haben wir bereits entsprechende Methoden. Schau dazu am besten mal in der Mail Klasse nach. 
wenn du fragen hast melde dich gerne. Können dazu auch mal nen Call machen. 

Viele Grüße und danke fürs Mitwirken. 
 Christian vom Commonsbooking-Team

**Comment by datengraben** [comment]
@chriwen Danke! Ok gemacht. Jetzt frage ich mich nur wo ich den TemplateTag festlege? Ist das der Name oder die Id aus dem OptionArray-Element?

**Comment by datengraben** [comment]
Das einzige was ich gefunden habe ist `{{Site-Registrierungs-Link}}` im po-File ...

**Comment by datengraben** [comment]
Mh ok, ich denke ich würde in Message.php die `$objects`  mit einem `E-Mail-Signature` befüllen und dazu den Wert mit `Settings::getOption` aus dem Settings Backend holen. Dann würde es immer gesetzt wenn der Template-Tag genutzt wird. Sonst nicht.

**Comment by datengraben** [comment]
Ok danke @chriwen 

Es wird jetzt immer an die Mail angefügt.

![image](https://user-images.githubusercontent.com/105302830/210555167-097c5c1a-0667-42c8-96e0-e76584d68eaa.png)

**Comment by datengraben** [comment]
In dieser Seite der Dokumentation: https://commonsbooking.org/docs/einstellungen-2/e-mail-vorlagen/

Würde ich diesen Satz nicht anpassen, in seiner Allgemeinheit enthält er ja schon alles.
```
In den Vorlagen kannst du die Inhalte der Buchungsmails und die Absender-Adresse der Buchungs-Mails festlegen.
```

**Comment by datengraben** [comment]
Da es jetzt geändert als Template-Tag zur Verfügung sollten wir es auf die Doku-Seite https://commonsbooking.org/docs/einstellungen/template-tags/ beschreiben.
