### ISSUE TITLE
restriction: wenn keine Uhzeit beim Enddatum eingetragen, wird beim veröffentlichen automatisch 12 AM eingetragen. sollte eher 12pm 59 sein oder ganzer Tag

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#750]
Vielleicht default-Wert auf 23:59 setzen. Geht das?

**Comment by chriwen** [comment]
@hanneskasimir  soweit mir möglich angepasst. Bitte mal checken. Statt 23:59 gehts auf 00:00 am nächsten Tag.

**Comment by chriwen** [comment]
@hanneskasimir sodele, jetzt 23:55 heutiger Tag als default Endwert
