### ISSUE TITLE
Zeitraum der restriction sollte im Hinweis im Frontend angezeigt werden.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#752]

**Comment by hanneskasimir** [comment]
Ja, Danke, die Funktionalität ist da!

- [ ] Der ein oder andere Umbruch könnte noch weg. 
- [ ] Vielleicht gar nicht zweispaltig, so wie über dem Kalender bei den Stationsdetails.
- [ ] einheitliche Achtung-Icons? das gelbe?

**Comment by chriwen** [comment]
@hanneskasimir hab das nochmal ein wenig angepasst. So besser?
