### ISSUE TITLE
Export anpassen (Buchungen, Standardfelder)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#763]
Export-Funktion so erweitern, dass der neue Buchungs-CPT mit berücksichtigt wird. 
Zusätzlich folgende Felder als Standard-Felder hinzufügen:

location: post_title
item: post_tltle
user: user_firstname, user_lastname, user_login

**Comment by markus-mw** [comment]
@chriwen : Ist in release/2.5-RC erledigt.

**Comment by hanneskasimir** [comment]
Bitte auch Buchungskommentar in Backend-Buchungsliste als eigene Spalte anzeigen und auch in den xls-Export aufnehmen.

**Comment by markus-mw** [comment]
@hanneskasimir : Ist erledigt.
