### ISSUE TITLE
Verhalten Neue Buchung Backend

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#767]
- [x] Uhrzeit soll ausblenden wenn "Ganzer Tag" gewählt ist.
- [x] Raster soll ausblenden bei "Ganzer Tag".

![grafik](https://user-images.githubusercontent.com/28141760/139291237-ec391fc1-d758-42f3-abfb-15abecc7545d.png)

- [x] Buchung hat keine Auswirkung auf Frontend & es werden keine Buchungsmails verschickt.
![grafik](https://user-images.githubusercontent.com/28141760/139294623-ccf4fe24-0cba-44e7-a579-a5488df4cddf.png)
![grafik](https://user-images.githubusercontent.com/28141760/139294716-12aff32c-92c1-467e-bb64-772d852b4378.png)

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen 

- die unnötigen Felder sind jetzt entfernt
- alles bis auf Start- und Enddatum sind nicht editierbar (im Zweifel mal mit Ctrl F5 neu laden, falls CSS nicht greift)
- man kann Buchungen nicht mehr überlappend speichern
- der Hinweis-Bereich bei den Buchungen ist eingefügt
- der Hinweis-Bereich bei den Timeframes für die Buchungs-Codes ist hinzugefügt
- das Timepicker Problem hat sich von selbst gelöst, weil die Felder rausgeflogen sind :)

**Comment by hanneskasimir** [comment]
die Checkbox "Ganzer Tag" lässt sich leider nicht aktivieren.

**Comment by hanneskasimir** [comment]
komisch, bei einem weiteren Versuch kann ich die Station und Artikel auch nicht auswählen.
![grafik](https://user-images.githubusercontent.com/28141760/145590005-f3bba663-fef6-451a-8849-559101372871.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Die hab ich mit Absicht nicht änderbar gemacht. Aber wenn ichs mir so überlege, kann das eigentlich auch komplett raus, weil das am Ende ja auch nur über die Start-/Endzeit gesteuert wird. Was denkst du?

**Comment by chriwen** [comment]
@markus-mw : Stimmt soweit. Jedoch müsste noch das Recht "Buchung hinzufügen" allen Rollen entzogen werden, da ansonsten Buchungen mit den von Hannes bereits vorbelegten Werten angelegt werden können.

**Comment by chriwen** [comment]
@markus-mw : und "ganzer Tag" kann noch komplett ausgeblendet werden.

**Comment by markus-mw** [comment]
@chriwen : Den Buchung hinzufügen Button hab ich versteckt. Das erstellen neuer Posts kann nur übergreifend für rollen definiert werden. Also entweder für alle Post-Types oder keinen.
Die Checkbox "ganzer Tag" ist entfernt.

**Comment by chriwen** [comment]
@markus-mw : vielleicht irgendwie damit? https://stackoverflow.com/questions/3235257/wordpress-disable-add-new-on-custom-post-type

**Comment by chriwen** [comment]
das hier noch gefunden. keine Ahnung ob es das tut:
`'capability_type'    => 'post',

        'capabilities'       => array( 'create_posts' => false ),       

        'map_meta_cap'       => true,`

**Comment by markus-mw** [comment]
@chriwen : Hat funktioniert. Top tipp!

**Comment by hanneskasimir** [comment]
sieht gut aus. jetzt nur noch den Erklärtext oben, @chriwen
