### ISSUE TITLE
Timeframe-Liste: Filter Start/End-Datum doppelt

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#770]
<img width="1468" alt="Bildschirmfoto 2021-10-29 um 09 50 59" src="https://user-images.githubusercontent.com/12683634/139396919-5921c5da-4094-4c54-a11a-2c6e9f2fd3a1.png">

**Comment by markus-mw** [comment]
@chriwen @hanneskasimir : Ist korrigiert.
