### ISSUE TITLE
Availability table does not scroll in some themes

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#771]
when `table-layout:fixed` is set in theme's css.

**Comment by chriwen** [comment]
@markus-mw Kannst du das einfach anpassen oder ist das was größeres?

**Comment by markus-mw** [comment]
@chriwen : Wenn ich es richtig sehe, hat @flegfleg das schon angepasst. oO

**Comment by chriwen** [comment]
@markus-mw Ok, hat er es direkt in 2.5-RC gepusht?

**Comment by flegfleg** [comment]
Moin, hier ist der PR dafür: https://github.com/wielebenwir/commonsbooking/pull/772

ist auch schon gemerged
