### ISSUE TITLE
Buchungszeiträume werden nicht angezeigt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#774]

**Comment by hanneskasimir** [comment]
Folgende Zeiträume werden auf stage bspw. nicht angzeigt:
- [ ] Ayline bei Janos
![grafik](https://user-images.githubusercontent.com/28141760/141450162-8718f4a4-a7e7-4d1b-ad48-20cb00704ce5.png)
![grafik](https://user-images.githubusercontent.com/28141760/141450248-ed13d1f3-ba4e-4cce-8244-ac78d3d72eae.png)
Fehlendes Enddatum ist ggf. der Grund?

- [ ] KASIMIR bei Anna
![grafik](https://user-images.githubusercontent.com/28141760/141450624-6c513c0d-0e60-47f5-b9dd-46f327b72671.png)

**Comment by hanneskasimir** [comment]
ah, ich glaube es liegt an der Vorrausbuchungsfrist. Die Zeiträume werden aktuell nur angezeigt, wenn sie länger sind als die Vorrausbuchungsfrist.

**Comment by markus-mw** [comment]
@hanneskasimir @chriwen : Ich hab das jetzt wie besprochen angepasst. Wenn der Start-Zeitpunkt des Timeframes in der Zukunft liegt, wird die Vorausbuchungsfrist ab diesem Zeitpunkt angesetzt. "Läuft" der Timeframe bereits, gilt der aktuelle Tag.
