### ISSUE TITLE
Aktueller Tag ist bei tageweiser Buchung halb rot

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#775]
![grafik](https://user-images.githubusercontent.com/28141760/141451669-49de4c97-afd5-4d73-9e86-9893a699b25c.png)
außerdem wird, wenn man ihn angklickt das Uhrzeitfeld eingeblendet.

**Comment by markus-mw** [comment]
@hanneskasimir : Das Problem ist behoben. Die Zahl selbst wird, weil es sich um den aktuellen Tag handelt noch rot dargestellt, das könnte ich aber auch noch ändern, wenn du möchtest.
