### ISSUE TITLE
auf stage1 werden keine Mails verschickt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#776]

**Comment by markus-mw** [comment]
@chriwen @hanneskasimir : Ich hab das Problem bzw. die Probleme gefunden. Eines davon lag im Code und der Verschiebung des Hooks für Änderungen an Posts, das war wieder eine Stelle die WP nicht so mag.
Das andere Problem bei mir lokal war, dass ich die Mail-Templates neu speichern musste, weil die Werte die dort angezeigt wurden komischerweise nicht gefunden wurden.

**Comment by markus-mw** [comment]
Was ich vergessen hab: Irgendwie scheinen gerade überhaupt keine Mails auf Stage rauszugehen (Einstellungen -> Log Mails). Ich weiß nicht woran das liegt bzw. wo man da was einstellen kann.

**Comment by chriwen** [comment]
Mails gehen grundsätlzich wieder.
