### ISSUE TITLE
Template-CSS-Optimierungen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#777]
Diverse kleinere CSS-Optimierungen auf folgenden Seiten:
# Buchungsliste
![image](https://user-images.githubusercontent.com/12683634/142065024-e342bfe7-ca86-4c08-bce4-18a21944e33f.png)
- [x] Größe der Label-Übesrchriften verkleinern
- [x] Überlappung der Buttons verhindern (in eigene Zeile)
- [x] Buttons kleiner

# Buchungsdetail
![image](https://user-images.githubusercontent.com/12683634/142065210-d88f4d0c-c47f-4dc5-8259-66d6671fa0d9.png)
- [x] Abbrechen-Button als einfachen Link

# Buchungskalender
![image](https://user-images.githubusercontent.com/12683634/142065655-c37d74ce-6c16-459a-bba9-0ddcc99b6e95.png)
- [x] Reset date Link in der Mitte positionieren und kleiner
- [x] Zeitauswahl-Dropdown weiter nach rechts positionieren und eckigen statt rundem Rahmen (oder ist ein Theme-Standard?)
- [x] in der Zeile mit dem Zeitauswahl-Dropdown soll das Datum horizontal mittig ausgerichtet werden, sodass die Zeit und das Datum in einer Linie sind.

**Comment by markus-mw** [comment]
@chriwen : Die Punkte sind alle erledigt. Lediglich beim Abbrechen der Buchung, hab ich keinen Link verwendet, sondern den Button umgebaut. Ansonsten hätte ich da mit Javascript ran gemusst.

**Comment by chriwen** [comment]
@markus-mw Perfekt. Schaut jetzt gleich viel hübscher aus ;-)
