### ISSUE TITLE
Alternative für guzzle / Geo-Coder

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#779]
Bekomme lokal beim Speichern von Locations einen Speicherfehler. Im Log steht folgendes:
/Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(201): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\Curl in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/php-http/guzzle6-adapter/src/Promise.php on line 129
[21-Nov-2021 12:17:29 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commonsbooking/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201
Stack trace:

Das Problem hatten wir auch desöfteren bei anderen Nutzenden. Es taucht wohl immer auf wenn dieses Guzzle-Ding auf einen Server mit nicht korrekter SSL-Verschlüsselung stößt. Dies scheint wohl seit Oktober oder so nach einem SSL-Update gehäuft aufzutreten.

Kannst du mal prüfen, ob wir
a) entweder den Fehler abfangen können und dann das Geo-Coding in diesem Fall nicht ausführen oder
b) eine Alternative finden (ggf. anderen Geo-Coding-Service?)

**Comment by markus-mw** [comment]
@chriwen : Ich hab das guzzle libary gegen ein anderes ausgetauscht. Bitte versuch es bei dir noch einmal. Ich kann den Fehler bei mir nicht nachstellen.

**Comment by chriwen** [comment]
@markus-mw : Supi. Das schaut gut aus.

**Comment by bemmim** [comment]
@markus-mw  Ich sehe den Fehler gerade in einer cb-Installation (nur zum Ausprobieren) auch. Bin leider nicht so firm im coden, dass ich nun wüsste was zu tun ist. Einfach auf neues Release warten, oder ist zuvor schon manuell Abhilfe möglich/sinnvoll?

**Comment by chriwen** [comment]
@bemmim hi. Der Fehler sollte im nächsten Release behoben sein. Wir sind gerade in den letzten Tests und hoffen in 2 Wochen veröffentlichen zu können. Abonniere am besten unseren Newsletter, dann wirst du direkt informiert.
