### ISSUE TITLE
Fehlerhaftes Template

### ISSUE THREAD

**Issue by Skuriles** [wielebenwir/commonsbooking#784]
Hallo zusammen,
danke für das tolle Plugin.
Ich bin mir nicht sicher, ob der Fehler schon adressiert wurde, aber in der 
shortcode-bookings.php 

Fehlt ein `</div>` am Ende. Das zerstört das WP Template (footer und sidebar rutschen beim Graphene Template z.B. in den Content hinein). 
Die letzte Zeile ist:
  `<div id="booking-list--pagination" style="display: none"></div>`
Hier muss anschließend noch ein 
`</div>`
als closing tag für `<div class="booking-list">` eingefügt werden.

Ansonsten ist mir noch aufgefallen, dass das Styling beim Buchen etwas verrutscht ist. Die Zeitauswahl ist zu klein und das Datum sollte eine Zeile tiefer stehen. 
![image](https://user-images.githubusercontent.com/7985622/142970274-ec792055-3120-42d2-8e33-b8074776a9a9.png)

Hab mir mal mit Custom css ausgeholfen

#booking-form-container select {
	height: 40px;
}

Wenn noch mehr Infos benötigt werden, einfach melden

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das mal anschauen?

**Comment by chriwen** [comment]
@Skuriles Vielen Dank für den Hinweis. Wir schauen uns das an und werden den Fehler ggf. korrigieren.

**Comment by markus-mw** [comment]
@chriwen , @Skuriles : Ich hab die Anpassung für Graphene ergänzt und noch ein paar weitere Kleinigkeiten ergänzt, damit das Datum nicht so gequetscht ist und die graue Box (border/background bei date span) nicht angezeigt wird.

**Comment by chriwen** [comment]
@Skuriles Wir haben das im neuen Release angepasst und schließen das Ticket hier aus technischen Gründen. Bitte prüfe im neuen Release (sollte in ca. 2 Wochen kommen), ob der Fehler weiterhin besteht. Wenn ja, melde dich bitte nochmal.
