### ISSUE TITLE
Migration anpassen: Nach Standard Migration die Booking-Konvertierung anschließen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#787]
Bitte die Migration von CB1 -> CB2 so anpassen, dass nach der Migration automatisch die Buchungs-Konvertierung auf den neuen CPT angestoßen wird. Sollten Nutzende ab Version 2.5 migrieren sollte direkt der neue Buchungs-Typ verwendet werden.

**Comment by markus-mw** [comment]
@chriwen : Das ist doch schon gemacht?! Die Migration erfolgt generell in den neuen CPT.
