### ISSUE TITLE
Datum der Tage nach einem Buchungszeitraum soll nicht in der Tabelle stehen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#788]
![grafik](https://user-images.githubusercontent.com/28141760/143565587-e232a9c5-18df-4607-8246-35b67906fed3.png)

**Comment by chriwen** [comment]
@markus-mw In einigen Fällen werden die Tage innerhalb der Tabelle ausgegeben. Dies soll nicht so sein. Kannst das beheben?

**Comment by markus-mw** [comment]
@chriwen : Passe ich an.

**Comment by markus-mw** [comment]
@chriwen : Ist erledigt. Die Felder werden jetzt alle wie "nicht verfügbar" in grau angezeigt.

**Comment by hanneskasimir** [comment]
in der Überschrift soll das Datum bitte bleiben.

so ist es auf stage1:
![grafik](https://user-images.githubusercontent.com/28141760/145553791-e5ea31a2-339c-46ab-8a58-99d880f1e5f4.png)

so ist  es auf live und so soll es auch wieder sein.
![grafik](https://user-images.githubusercontent.com/28141760/145553859-3ae17a12-b20f-4c2d-a3a7-dd9c49230df1.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Die Tage sind jetzt in der Kopfzeile wieder drin.
