### ISSUE TITLE
Bei Update Buchungen automatisch migrieren

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#793]
- [ ] Bei Update sind die neuen Post-Types (Einschränkungen, Buchungen) zunächst nicht da. Erst nach deaktivieren / aktivieren des Plugins. Diese sollten direkt nach dem Update verfügbar sein
- [x] Die Migration auf die neuen Buchungs-CPT soll automatisch im Rahmen des Updates erfolgen.

**Comment by markus-mw** [comment]
@chriwen : Den zweiten Punkt hab ich ergänzt und noch ein paar Kleinigkeiten angepasst. Das erste kann ich nicht reproduzieren. Verrätst du mir wie du das gemacht hast?
