### ISSUE TITLE
Migration bleibt hängen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#794]
Bei Testmigration von 0.9 auf 2.5-RC bleibt Migration bei Buchungen kurz vor Ende hängen.
![image](https://user-images.githubusercontent.com/12683634/145400305-fc3e3c74-62b5-40d9-ad72-53e17a428cde.png)

Bei einer erneuten Migration bleibt es genau an der gleichen Stelle also bei 3324 hängen.
Die Buchungen scheinen von der Anzahl her migriert zu sein. In der Buchungsliste sind 3363 Einträge.
Nur die nachfolgenden Elemente (Buchungscodes etc.) sind nicht migriert.

**Comment by markus-mw** [comment]
@hanneskasimir : Schau ich mir an.
Nur so am Rande: Der grüne Text liest sich ein wenig holperig. Vielleicht schaut ihr da nochmal. :)

**Comment by markus-mw** [comment]
@hanneskasimir : Das Problem ist behoben. War eine kleine Dummheit von meiner IDE.

**Comment by hanneskasimir** [comment]
ist leider wieder hängen geblieben:
![grafik](https://user-images.githubusercontent.com/28141760/145586053-bb79a264-3ed7-4ae9-9477-52ad7113042e.png)

**Comment by chriwen** [comment]
@markus-mw Kannst du das nochmal checken?

**Comment by markus-mw** [comment]
@chriwen : Schau ich mir direkt an.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Bei mir lief das durch. Kannst du bei dir nochmal probieren?

![image](https://user-images.githubusercontent.com/22905753/145599191-29c835ae-533c-4247-8d6b-977cad02c859.png)

**Comment by chriwen** [comment]
@markus-mw kann das irgendwas browsermäßiges sein, dass sich das ajax-ding aufhängt?

**Comment by markus-mw** [comment]
@chriwen : Schon möglich. Da kann ich dann aber nicht viel machen.

**Comment by flegfleg** [comment]
Wenn **Abruf von Geo-Coordination** aktiv ist, geht bei mir die Migration nicht: 
Er zeigt die Liste ("Standorte aktualisiert / gespeichert"), Zähler bleiben aber bei 0 stehen.

**Comment by chriwen** [comment]
@flegfleg Hast du an dieser Stelle mal mindestens eine Minute gewartet? Die Geo-Kodierung brauch pro Datensatz mind. 1 Sekunde und arbeitet in 50-er Blöcken. Wenn das auch nicht hilft, melde dich nochmal.

**Comment by flegfleg** [comment]
> @flegfleg Hast du an dieser Stelle mal mindestens eine Minute gewartet? Die Geo-Kodierung brauch pro Datensatz mind. 1 Sekunde und arbeitet in 50-er Blöcken. Wenn das auch nicht hilft, melde dich nochmal.
Hab ich, hatte sich aufgehängt. 

# Verhalten mit [2.6-RC](https://github.com/wielebenwir/commonsbooking/tree/release/2.6-RC): 

* Migration läuft jetzt auch wenn Schalter "Geocoordinaten" aktiv! 🎉
* Ich habe einen Ajax-Fehler (nur im Query Monitor sichtbar), der allerdings von einem anderen Plugin hervorgerufen wird. Hab das [in der Doku ergänzt](https://commonsbooking.org/docs/installation/migration-von-cb1/#2-migration-durchführen-daten-migrieren).  
* Die neue Migrations-Meldung ist super, viel klarer!
