### ISSUE TITLE
Feldbezeichnung Export-Options

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#795]
Die Feldbzeichung in OptionArray Z. 675 id'            => 'migration-custom-field', scheint hier irgendwie falsch benannt, oder? Es geht hier um den Export, nicht die Migration. Ist das Copy&Paste-Ding oder soll das so? Nicht dass es da mal noch Konflikte gibt?

**Comment by markus-mw** [comment]
@chriwen Ich habs geändert. Das sollte aber grundsätzlich keine Probleme gemacht haben.
