### ISSUE TITLE
Fristen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#799]
- [ ] Vorrausbuchungsfrist stimmt nicht (eingestellt sind 200 Tage)
- [ ] Maximal buchbare Tage sind auf 21 eingestellt, d.h. von einem zum anderen Tag sollte gar nicht gebucht werden können

Basis sind 2 verschiedene Zeitrahmen, mit jeweils nur einem Datum.

![grafik](https://user-images.githubusercontent.com/28141760/145586873-023bff21-a2ac-4a7c-9c7c-9520688f82e3.png)

![grafik](https://user-images.githubusercontent.com/28141760/145586952-edb18160-fc49-4b7d-bb64-38c1e94628fd.png)

**Comment by hanneskasimir** [comment]
ah, sorry das vergess ich immer wieder, zieh ich zurück ;-) nochmal kurz: und wie ist es bei den Wochenenden gelöst? warum kann ich Fr-Mo buchen, auch wenn nur 3 Tage Frist eingestellt sind?

**Comment by markus-mw** [comment]
@hanneskasimir : Dem Kalender sind die Wochentage egal. Wenn die grau (also nicht buchbar) sind, zählen die einfach nicht mit in die Rechnung. Du kannst also von Fr-Mo mit 3 Tagen Frist buchen, weil Samstag und Sonntag nicht Zählen. Theoretisch könntest du mit der 3er Frist sogar von Freitag bis Dienstag buchen.

Bezüglich der 107 Tage (anstelle von 200):
Hier könnte ich anbieten, dass in der Ausgabe einfach das Limit des ersten Timeframes im Kalender verwendet wird. Wär das in Ordnung?
(Du hast in deinem Beispiel 2 Timeframes mit der gleichen max. Vorausbuchung, das könnte aber theoretisch auch unterschiedlich eingestellt werden.)

**Comment by chriwen** [comment]
@markus-mw Ja, wir nehmen den ersten Timeframes im Kalender. damit ist aber nicht das Problem der 107 statt 200 gelöst oder? Hast du da auch schon die Ursache gefunden? 

@hanneskasimir  & @markus-mw : Ich glaube wir hatten mal definiert, dass für den überbuchten Zeitraum immer pauschal 1 Tag abgezogen wird, egal wie lange der überbuchte (graue) Bereich ist. So stehts auch in der Doku. Ist das so umgesetzt oder zählt der überbuchbare Zeitraum 0 Tage?

**Comment by markus-mw** [comment]
@chriwen : Du hast recht, das war immer nur ein Tag, richtig. Also kommt man mit 3 buchbaren Tagen von Fr-Mo.

Bzgl. der 107:
Die 107 Tage sind für die interne Rechnung und sind so korrekt. Die Rechnung dazu:

Wenn der erste buchbare Tag der 15.12. ist, wird für den Kalender der Zeitraum bis 31.03 vorberechnet und als Endzeitpunkt angenommen. Das ist immer der Monat des Startdatums + 3 Monate. Das sind dann die 107 Tage.

Dann wird ausgehend vom Startdatum des Timeframes das maximal vorausbuchbare Datum von 200 PT ausgerechnet.
Ist dieses Datum kleiner als der Standardzeitraum, wird es als Enddatum angenommen. Andernfalls bleibt es beim Startdatum + 3 Monate.

Da die 200 Tage nach dem Enddatum enden, bleibt es also bei den 107 Tagen. Diese Zahl wird aber nur für die interne Rechnung und die Darstellung des Kalenders benötigt.
Der Fehler ist jetzt, dass sich die Zahl in dem Hinweistext aus dem Start- und Enddatum des vorberechneten Kalenderzeitraums ergibt. Das macht aber keinen Sinn, daher würde ich einfach den Wert aus dem Timeframe laden.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Die Ausgabe im Hinweistext sollte jetzt passen.
