### ISSUE TITLE
Reihenfolge Verfügbarkeit chronologisch sortieren

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#800]
bitte oben der nächst folgende Zeitraum
![grafik](https://user-images.githubusercontent.com/28141760/145587299-ee471e22-924e-4df1-8631-095d8ea58de6.png)

**Comment by hanneskasimir** [comment]
nein, das ist leider noch nicht behoben.
Ich vermute die Sortierung ist aktuell abhängig vom Erstellungdatum (nicht Publikationsdatum) des posts:

![grafik](https://user-images.githubusercontent.com/28141760/148995876-107457e8-8db2-4c7f-b1c2-5f3eef5717d4.png)

![grafik](https://user-images.githubusercontent.com/28141760/148996101-101f23b0-4802-4cf9-86be-0023fd750a2f.png)

Viele Grüße übrigens (auf ein baldiges Kennenlernen)!

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das mal anschauen?

**Comment by hansmorb** [comment]
#845 hab nen pull request gestellt

**Comment by chriwen** [comment]
@markus-mw Bitte verknüpften Pull Request von Hans prüfen. Das sollte das lösen.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Ist im jetzt im Release.

**Comment by chriwen** [comment]
@markus-mw Irgendwie habe ich das Gefühl, dass das immer noch nicht passt. Schau mal hier
https://stage3.commons-booking.org/alle-lastenraeder/
Der Artikel ganz oben "Test". Hier steht 
![image](https://user-images.githubusercontent.com/12683634/150420936-0d57c2f3-b045-436d-9131-9ebca0976d3c.png)

Der Artikel selbst ist aber (auch innerhalb der Vorausbuchungslimits) noch anderen Tagen verfügbar. Hier müsste doch dann eigentlich diese Aufzählung kommen, oder?
![image](https://user-images.githubusercontent.com/12683634/150421029-9c90b1b2-1ce7-4013-8ba4-11f8e6e373f0.png)

Kannst du da nochmal schauen bitte?

**Comment by chriwen** [comment]
@markus-mw Das ist zuästzlich denke ich verknüpft mit #854

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Ich habe die Logik überarbeitet und den stande (release/2.6-RC) auf Stage3 ausgespielt. Für mich sieht das jetzt i.O. aus, aber ihr seid besser darin das zu bewerten ;)

**Comment by chriwen** [comment]
Hab auf Stage3 getestet. Das schaut gut aus. Auch die Vorausbuchungszeiten werden nun berücksichtigt. @hanneskasimir nochmal gegenchecken?

**Comment by hanneskasimir** [comment]
Reihenfolge ist richtig, daher schließe ich hier. Vorrausbuchungfrist stimmt nicht, mach ich im anderen Ticket.
