### ISSUE TITLE
Zeitrahmen: Freie Eingabe von einzelnen Tagen ermöglichen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#802]
Alternativ zur Auswahl von Startdatum und Enddatum gibt es beim Anlegen eines Zeitrahmens die Möglichkeit, einzelne Tage kommagetrennt in ein Textfeld einzugeben. 

- [x] Checkbox "Freie Eingabe von Tagen" unter dem Enddatum (default: nicht aktiv)
- [x] bei Aktivierung der Checkbox: Ausblenden von Startdatum und Enddatum, Einblenden eines Textfeld
- [x] Übernahme aller im Textfeld aufgelisteten Daten in den Zeitrahmen. Format z.B. (05.05.2021,06.03.2022,usw.)
- [x] Erklärtext zum Datumsformat inkl. Beispiele unter dem Textfeld

Vorteile:
Diese Option kann dann genutzt werden, um spezielle Datumskombinationen in nur einen Zeitrahmen einzugeben, anstatt viele Zeitrahmen nutzen zu müssen. Weiterhin ist es möglich, eine einmal zusammengestellte Kombination auch in weitere Zeitrahmen anderer Artikel/Stations-Kombinationen zu kopieren.

Nutzung z.B. für
- Feiertage
- Regelmäßige Ausleihtermine, die aktuell nicht abbildbar sind (z.B. jeder erste Donnerstag im Monat)

**Comment by chriwen** [comment]
Idee: sowohl feste Datumsangaben (kommasepariert) + relative Datumsangaben (http://docs.php.net/manual/en/datetime.formats.relative.php) ermöglichen.
