### ISSUE TITLE
Kalender bleibt hängen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#803]
![grafik](https://user-images.githubusercontent.com/28141760/146534700-6a29d433-4fe2-4893-967c-f0377e05fc9a.png)

Nachreproduzieren:

![grafik](https://user-images.githubusercontent.com/28141760/146534877-c0439af5-299b-46c6-9142-799d7b8bfcd8.png)

- Klick auf 18, 20, Datum zurücksetzen, 20, 21

**Comment by chriwen** [comment]
@markus-mw Testbar hier: https://staging.commons-booking.org/kasimir-lastenrad2/cb-items/walther/?location=3602

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Könnt ihr das bitte noch einmal testen?

**Comment by chriwen** [comment]
@markus-mw geht noch nicht.

**Comment by markus-mw** [comment]
@chriwen : https://staging.commons-booking.org/kasimir-lastenrad2/cb-items/walther/?location=3602 ist noch nicht auf dem neuesten Stand. Wo hast du getestet?

**Comment by chriwen** [comment]
Muss ich heut Abend nochmal schauen

**Comment by markus-mw** [comment]
@chriwen : Dort kann ich es nicht updaten. Meld dich dann einfach ob's geklappt hat.
