### ISSUE TITLE
Navipunkte "Buchung" und "Einschränkungen" im Backend sind nach Update nicht sichtbar.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#804]

**Comment by chriwen** [comment]
@markus-mw Erst nach De- und wieder Aktivierung. Vielleicht irgendwie damit lösbar? https://developer.wordpress.org/reference/hooks/upgrader_process_complete/
Die Registrierung der CPTs scheint da nicht zu laufen..

**Comment by markus-mw** [comment]
@chriwen : Ich glaub das hilft nicht, weil der Hook aus der alten Plugin Version ausgeführt wird, wenn es sich um Plugin selbst beim Update handelt -> https://developer.wordpress.org/reference/hooks/upgrader_process_complete/#more-information

Ich versuch das lokal nochmal nachzustellen.

**Comment by markus-mw** [comment]
@chriwen : Wir nähern uns an. Ich habs jetzt soweit hinbekommen, dass die Menüpunkte zumindest nach einem Reload der Seite angezeigt werden.

**Comment by markus-mw** [comment]
@chriwen : Ich hab die Funktion zum einbinden schon so früh wie nur möglich eingebaut, aber dennoch werden die Punkte erst nach einem Reload sichtbar. Aus Aufwands-/Nutzen-Sicht würde ich es daher so belassen. Ok?

**Comment by chriwen** [comment]
ok
