### ISSUE TITLE
Nichtverfügbarkeit wieder auf Artikelseite einblenden

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#806]
2.5
![grafik](https://user-images.githubusercontent.com/28141760/146638010-0612e653-4228-4ab6-b2a2-ddbbb16dcb21.png)

2.4...
![grafik](https://user-images.githubusercontent.com/28141760/146637993-25c46e57-1471-4523-ba1c-6099e03cf05d.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Hast du eine Url zu dem Beispiel für mich. Grundsätzlich gibt's die Meldung noch an der Stelle.

**Comment by hanneskasimir** [comment]
https://stage3.commons-booking.org/cb-items/buergerrad-nippes/
oder 
https://stage1.commons-booking.org/cb_item/adfc-moritz/

**Comment by chriwen** [comment]
@markus-mw Ich hab das denke ich gefunden. in View/Item.php, Z. 46 setzt du das locations-Array. Die Prüfung im Template lief aber auf !isset. Hab das im template angepasst. 
Jedoch ist die getTemplateData für Items nun an dieser Stelle anders aufgebaut als bei Locations. Hier fehlt das setzen des leeren items-Arrays (View/Location, Zeile: 44) 
Kannst du das mal checken und schauen, ob es Sinn macht das anzugleichen, damit wir uns nicht eines Tages wundern, warum wir hier unterschiedlich vorgehen?
Fix ist im RC-Branch enthalten
