### ISSUE TITLE
cb-Widget Anpassungen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#807]
- [x] E-Mail-Adresse in Begrüßung nehmen, wenn kein Vor- oder Nachname gepflegt ist
- [ ] Link zu "Mein Profil" im default-Zustand entfernen (führt raus ins Wordpress-Backend)

![grafik](https://user-images.githubusercontent.com/28141760/146638663-56d5500f-a379-4b59-aa9b-8c4e88d9935d.png)
Hintergrund: Ich habe das "Theme My Login" ausprobiert, das wir ja empfehlen.

**Comment by chriwen** [comment]
Standard-Profil-Link würde ich nicht anpassen. Das sollen die Menschen in dem jeweiligen Tool anpassen. Dort gibts meist eine Redirect-Funktion, mit der die neue URL definiert werden kann. WIrd ansonsten zu kompliziert.
