### ISSUE TITLE
Fehler Buchungszeiträume bei Slotbuchung

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#808]
Buchung bei slotweiser Buchung führt zu falscher Uhrzeitangabe in den E-Mails und der Buchungsbestätigungsseite.
Interessanterweise unterscheiden sich die Uhrzeiten in allen drei Ausgaben.

Beispiel: Buchung im Backend
![image](https://user-images.githubusercontent.com/12683634/146903174-b6064c13-7f85-45fb-8557-c17f094c2f9a.png)

Buchung im Frontend:
![image](https://user-images.githubusercontent.com/12683634/146903256-7a0f6641-662a-4367-9d5c-9239324714c2.png)

Buchung in der E-Mail:
![image](https://user-images.githubusercontent.com/12683634/146903329-f4b9b0eb-994c-442c-b0c4-402a8e8d6517.png)

Der zugrunde liegende Timeframe: (ID: 10380 auf Live-System kasimir)
![image](https://user-images.githubusercontent.com/12683634/146903606-5608032b-3d9d-41f4-8f3f-ee63f120e4da.png)

**Comment by markus-mw** [comment]
@chriwen : Wo tritt der Fehler auf? Auf stage1 scheint es meinen Nutzer nicht mehr zu geben...

**Comment by chriwen** [comment]
Auf live kasimir-lastenrad.de

**Comment by chriwen** [comment]
@markus-mw Auf live kasimir-lastenrad.de
