### ISSUE TITLE
Fehler: Reminder-Mails auch an unconfirmed Bookings verschickt

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#809]
Reminder-Mails werden auch an unconfirmed-Bookings verschickt. Hier fehlt in der Abfrage ein Filter nach confirmed.
Bitte in dem Zusammenhang auch prüfen, ob das bei den Restriction-Mails auch berücksichtigt wird. 
Zudem wundert es mich, dass überhaupt unconfirmed-Bookings so lange aktiv sind.
im Live-System sind 2 Buchungen mit Buchungsdatum am 20.12 immer noch unconfirmed vorhanden.

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist behoben. Beim Aufräumjob war noch nicht der neue Buchungstyp berücksichtigt.
