### ISSUE TITLE
als cb_manager sollte ich auf dem Dashboard nur die Buchungen sehen, die mit meinen Artikeln oder Station zu tun haben.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#817]

**Comment by chriwen** [comment]
@hanneskasimir bitte auf stage3 prüfen

**Comment by hanneskasimir** [comment]
geht leider nicht:
![grafik](https://user-images.githubusercontent.com/28141760/148401979-7e241d67-4da0-4cd3-83e1-be2522272176.png)
![grafik](https://user-images.githubusercontent.com/28141760/148402015-3e4dada0-83d7-49ca-9654-1e67ca666999.png)

**Comment by chriwen** [comment]
@hanneskasimir ah, mist. Jetzt aber, oder?

**Comment by hanneskasimir** [comment]
ja, die Buchung ist da. Jetzt sehe ich aber gar keine Einträge mehr bei STationen und ARtikeln.

**Comment by chriwen** [comment]
@hanneskasimir aargh ... jetzt??
