### ISSUE TITLE
cb-Widget soll es einen Link geben, der zu einer Seite führt, auf der der Account gelöscht werden kann. (müssen wir bestimmt anbieten aus Datenschutzgründen, oder?)

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#818]

**Comment by hansmorb** [comment]
Ja ich denke auch! Die DSGVO schreibt ja nur die Löschung **personenbezogener** Daten vor, sobald ein Nutzerprofil standardmäßig über WP gelöscht wurde, sind die Buchungsdaten ja nicht mehr auf einzelne Accounts zurückzuführen (da steht dann ja nur noch die User ID) und sind dann keine personenbezogenen Daten mehr. Aber vielleicht mach ich es mir da auch zu einfach.
