### ISSUE TITLE
Artikel an mehreren Stationen gleichzeitig buchbar

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#820]
Timeframe 1: Artikel X, Station A // Start- und Endzeit gesetzt, wöchentlich (alle Tage), Slotweise Buchung (ganzer Slot)
Timeframe 2: Artikel X, Station B // Nur Startzeit gesetzt (kein Enddatum), wöchentlich (alle Tage), Slotweise Buchung (ganzer Slot)
-> Die Buchungszeiten überschneiden sich bei beiden Timeframes
Timeframe konnte dennoch gespeichert werden.
Auch bei nachträglichem Eintragen eines Enddatums für Timeframe 2 wird kein Fehler geworfen. 

Im Frontend werden beide Buchungszeiträume angezeigt.

![image](https://user-images.githubusercontent.com/12683634/148298224-ded54e9a-ba7a-4c8b-876e-d66914a8c4c5.png)

Fehler

**Comment by chriwen** [comment]
@markus-mw In Branch bugfix/issue-820 hab ich daran gearbeitet. Logik zur Prüfung scheint zu funtionieren. Jedoch erfolgt die Prüfung immer erst auf Basis der gespeicherten Werte und wir so in der save_post-Action nicht mit den aktuellen Werten ausgeführt. Deshalb ziehen alle Validierungs-Prüfungen anscheinend momentan erst nach 2-maligem Speichern. 
Hab mit den Hooks ein wenig probiert, konnte es aber nicht lösen. 
Irgendwie müsste nach dem Save-Post die Validierung (inkl. Update und Anpassung) erfolgen und dann ein Redirect wieder zur Bearbeitungs-Seite, oder so?
Hast du ne Idee?

**Comment by markus-mw** [comment]
@chriwen : Das Problem ist, dass das Meta-Feld für den Type bei der Prüfung noch nicht gespeichert ist und die isValid Funktion daher true zurück gibt. Ich sehe mir das an.

**Comment by markus-mw** [comment]
@chriwen : Das Problem war, dass die Speicherung in CMB2 über den save_post Hook lief, beim Timeframe aber über den Custom Post Type spezifischen save_post_cb_timeframe Hook. Ich hab das geändert, jetzt greift deine Anpassung rechtzeitig. Teste es bitte noch einmal.

**Comment by chriwen** [comment]
@markus-mw Danke.. und ich hab da rumprobiert .. aaargh.
