### ISSUE TITLE
für cb_manager: Navi-Punkte der Kategorien aus Menü entfernen

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#824]
![grafik](https://user-images.githubusercontent.com/28141760/148518670-8421008a-e661-4046-8198-26b764b3aa9f.png)

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Ist erledgit und kann im Branch bugfix/issue-824 getestet werden.

**Comment by chriwen** [comment]
auf dev erfolgreich getestet
@hanneskasimir Bitte nochmal Gegencheck auf stage3
