### ISSUE TITLE
Einschränkungen anderer user für cb_manager nicht sichbar

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#825]
Aktuell werden dem cb_manager nur selbst angelegte Einschränkungen angezeigt. Eigentlich sollte der cb_manager auch alle Einschränkungen der ihm zugeordneten Artikel & Stationen sehen und bearbeiten können.

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Soll der Manager auch Einschränkungen sehen können, bei denen nur der Standort oder nur der Artikel ihm gehört/zugeordnet ist? Oder anders gefragt, wie soll das Verhalten aussehen, wenn der Standort dem CB Manger weder gehört noch zugeordnet ist, der Artikel jedoch schon (und umgekehrt)?

**Comment by hanneskasimir** [comment]
@markus-mw : Gerne genau so wie bei den Buchung und auf dem Dashboard. Dort sieht der cb_manager (glaube ich) alles was irgendwie mit einem zugeordneten Artikel oder einer Station zu tun hat, oder?

**Comment by chriwen** [comment]
@markus-mw Ja, Prüfung auf entweder zugeordneter Location ODER Item oder Autor der Restriction

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Das sollte im Branch bugfix/issue-825 jetzt wie bei Timeframes/Bookings funktionieren.
