### ISSUE TITLE
Tabelle: Farben für teilweise gebuchte Tage werden nicht immer angezeigt.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#827]
![grafik](https://user-images.githubusercontent.com/28141760/148603362-46625471-35d9-4b89-a87a-b9a387205713.png)

![grafik](https://user-images.githubusercontent.com/28141760/148603394-28a921c7-1ccc-44b0-ace8-f0d71761dd62.png)

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Das Problem ist in bugfix/issue-827 behoben. Da war ein Fehler in Logik wie die Felder in der Liste dargestellt werden.

**Comment by chriwen** [comment]
@markus-mw Die Ausrichtung der halben Tage stimmt noch nicht ganz:

![image](https://user-images.githubusercontent.com/12683634/148700270-06b616c3-a189-40ed-9e25-35067a1c56a3.png)


![image](https://user-images.githubusercontent.com/12683634/148700282-646603c9-474d-4e52-9261-a758fcadf495.png)
--> hier müsste der 13.01 unten rechts rot sein (da die erste hälfte des Tages noch frei ist)

**Comment by markus-mw** [comment]
@chriwen : Wo kann ich das sehen? Ich brauch bei sowas immer Beispiele, damit ich den Fall nachstellen kann...

**Comment by chriwen** [comment]
@markus-mw Das war bei mir lokal ;-)
Ist aber auch hier: https://stage3.commons-booking.org/bikes/  --> BismarckBike

**Comment by markus-mw** [comment]
@chriwen : Versuchs jetzt bitte noch einmal. Ich hab was ergänzt, damit das unterschiedlich dargestellt wird.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Das ist jetzt im release/2.6-RC erledigt.

**Comment by chriwen** [comment]
@hanneskasimir bitte auf stage3 testen

**Comment by hanneskasimir** [comment]
in der Stage3-Tabelle sind leider gar keine bunten Kästchen mehr: https://stage3.commons-booking.org/bikes/
![grafik](https://user-images.githubusercontent.com/28141760/149500104-2b5f2f56-80f0-480f-949c-678aa418d34c.png)

**Comment by hanneskasimir** [comment]
leider immer noch nicht da:
![grafik](https://user-images.githubusercontent.com/28141760/149500861-f2b42ada-3028-4ac9-bcb8-c3e44a429011.png)

**Comment by chriwen** [comment]
@markus-mw Hannes bezieht sich hier auf das Lasten Rad tafelino. Hier ist für freitags vormittags einen Zeitrahmen mit einem Blocker eingetragen. Auf der Detailseite wird diese auch ausgegeben. Fehlt aber hier in der Liste

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Reparatur und Holiday waren bisher nicht in der Liste der Timeframetypen die einen teilweise gebuchten Tag in der Ausgabe ergeben. Das ist jetzt angepasst. Ich habs auch erfolgreich auf Stage 3 testen können. 
Änderungen sind in Release Branch.
