### ISSUE TITLE
Barrierefreiheit: Farben in der Artikel-Tabelle

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#829]
In der Artikel Tabelle ([cb_items_table]) sind die Farben für Urlaub und Buchbar für Menschen mit Deuteranomalie nicht unterscheidbar. (von Mensch mit Deuteranomalie selber angemerkt). 

![image](https://user-images.githubusercontent.com/6433480/148646475-192aaafb-9581-4993-94b1-c0013ae7d36a.png)

**Comment by chriwen** [comment]
@hansmorb Vielen Dank für den Super-Hinweis. Welche Farben würden denn hier besser passen? Hättest du einen Vorschlag? Wir übernehmen dann gerne die Werte.

**Comment by hansmorb** [comment]
In meinem pull request 830 https://github.com/wielebenwir/commonsbooking/pull/830 habe ich ein Streifenmuster eingefügt, das ist aber auch nur ein Vorschlag. So sieht das dann aus: 
![image](https://user-images.githubusercontent.com/6433480/148701356-ed08817f-512e-41eb-94d5-83681e5008bf.png)

**Comment by hansmorb** [comment]
Mit dem merge von #884 ist das jetzt auch an allen Stellen übernommen worden.
