### ISSUE TITLE
Deprecated Warnungen uSort

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#838]
![image](https://user-images.githubusercontent.com/6433480/148789374-055d3490-8ee3-4197-aa88-b4028ba885ec.png)

**Comment by markus-mw** [comment]
@hansmorb : Teste bitte, ob das Problem im release/2.6-RC behoben ist. Ich hab deinen PR da reingemerged.

**Comment by hansmorb** [comment]
Soweit ja, habe auch keine alten Stellen mehr im Code gefunden.
