### ISSUE TITLE
Vorrausbuchungsfrist funktioniert nicht

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#840]
Heute war der 10. Januar:

![Screenshot_20220110-193034](https://user-images.githubusercontent.com/28141760/148819869-1bf9cca1-7450-45ac-a424-93341065a224.jpg)

**Comment by hanneskasimir** [comment]
geht leider nicht:
![grafik](https://user-images.githubusercontent.com/28141760/149500591-5d441598-8fa1-4bcd-8fa9-5026905d4c97.png)

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das bitte nochmal anschauen?

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Jetzt funktionierts. Ich habs mit dem Beispiel oben auf Stage3 durchgespielt. Der 16. März wird nur dann buchbar angezeigt, wenn im ersten verfügbaren Timeframe eine entsprechend hohe "Vorausbuchungstageszahl" eingetragen ist.

**Comment by chriwen** [comment]
@markus-mw Jetzt scheint die Vorausbuchungsfrist jedoch nicht mehr in der Tabelle zu greifen:
Bubi -> 10 Tage (wird alles angezeigt)
TEST-ARTIKEL: 10 Tage (wird alles angezeigt)

![image](https://user-images.githubusercontent.com/12683634/151439840-46bc91a1-9bb6-4b13-b17d-4c5c07822b43.png)

**Comment by hanneskasimir** [comment]
Hm, aber 2. März dürfte doch nicht buchbar sein, oder? https://stage3.commons-booking.org/cb-items/test-artikel/?location=3625
In allen Zeitrahmen steht 31

**Comment by hanneskasimir** [comment]
In der Liste steht falsch der 2. Und der 16. März
![Screenshot_20220127-215321](https://user-images.githubusercontent.com/28141760/151442177-047ca790-638b-4f7b-8c85-326897a716f6.png)

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Das Problem war, dass noch nicht überall die gleiche Logik bezüglich der max. vorausbuchbaren Tage gegriffen hat. Ich hab das jetzt nachgeholt. Sieht auf jeden Fall besser aus. Bitte testet nochmal. Die Änderungen sind auf Stage3.

**Comment by hanneskasimir** [comment]
im Kalender passt es, in der Liste steht leider immer noch der 2. März
![grafik](https://user-images.githubusercontent.com/28141760/151538202-4afe8636-ead8-4011-8ecd-a430830408d3.png)

**Comment by markus-mw** [comment]
> im Kalender passt es, in der Liste steht leider immer noch der 2. März ![grafik](https://user-images.githubusercontent.com/28141760/151538202-4afe8636-ead8-4011-8ecd-a430830408d3.png)

Der 2te März ist aber korrekt, weil der Vorbuchungszeitraum ja vom ersten buchbaren Tag aus gerechnet wird und nicht ab heute.

**Comment by hanneskasimir** [comment]
ah, das wusste ich nicht. dann ist es aber im Kalender falsch, dort ist der 2. März nicht drin.
warum fängt es nicht heute an zu zählen? das ergibt für mich mehr Sinn.

**Comment by markus-mw** [comment]
@hanneskasimir : Wir können das gern ändern. Wir hatten das aber schon einmal diskutiert und kamen zu dieser Variante. ;)

Das Problem mit dem Kalender hab ich noch behoben.
