### ISSUE TITLE
Vorrausbuchungsfrist auch in Tabelle berücksichtigen ?

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#841]
Die Vorausbuchungsfrist (advanceBookingDays) soll auch in der Tabelle berücksichtigt werden.

![Screenshot_20220110-193126](https://user-images.githubusercontent.com/28141760/148820290-b40b1f75-037d-46d3-a8a7-9f446ac1161d.png)

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Das ist jetzt im release/2.6-RC erledigt.
