### ISSUE TITLE
Bug Live-System: Location / Item-Liste hängt sich auf / Memory Exceeded

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#843]
Auf Live gerade folgendes Problem:
bei Aufruf von: https://www.kasimir-lastenrad.de/alle-lastenraeder/

kommt Fehler:
PHP Fatal error | Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)Line : 164/www/htdocs/w01c4357/kasimir-lastenrad.de/wp-includes/plugin.php
-- | --

Konnte das soweit eingrenzen, dass es wohl mit dem Item Tafelino zusammenhängt. Das hat relativ viele Bookable Timeframes, die übereinander geschachtelt sind. Wenn ich das auf Enwurf stelle, wird die Seite problemlos geladen.

**Comment by chriwen** [comment]
Hab hier sowas in nem Thread gefunden:
20

I had this problem. I searched the internet, took all advices, changes configurations, but the problem is still there. Finally with the help of the server administrator, he found that the problem lies in MySQL database column definition. one of the columns in the a table was assigned to 'Longtext' which leads to allocate 4,294,967,295 bites of memory. It seems working OK if you don't use MySqli prepare statement, but once you use prepare statement, it tries to allocate that amount of memory. I changed the column type to Mediumtext which needs 16,777,215 bites of memory space. The problem is gone. Hope this help.

**Comment by markus-mw** [comment]
@chriwen : Löst sich mit https://github.com/wielebenwir/commonsbooking/issues/827
