### ISSUE TITLE
Location-single Template funktioniert nicht wenn nur ein Artikel an Standort

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#846]
![image](https://user-images.githubusercontent.com/6433480/149232120-fb89e7b1-1522-4d36-a5fd-7400abe4c261.png)

Eigentlich sollte die Seite (in diesem Beispiel http://localhost/wordpress/index.php/cb_location/testort-3/) die Artikel an diesem Standort auflisten, stattdessen zeigt es aber ein kaputtes Buchungsformular.

Dieser Fehler tritt nur auf, wenn weniger als zwei Artikel an dem Standort einen Zeitrahmen haben.

**Comment by chriwen** [comment]
@hansmorb In welchem Branch testet du das?

**Comment by hansmorb** [comment]
Im Master und im 2.6-RC Branch
