### ISSUE TITLE
Einschränkungen sollen nur für Artikel/Station-Kombination gelten.

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#848]
https://stage3.commons-booking.org/cb-items/test-artikel/?location=3625
nimmt sich falscherweise die Einschränkung aus diesem post
https://stage3.commons-booking.org/wp-admin/post.php?post=10710&action=edit

Als Alternative "alle" ergänzen in Dropdown Artikel und Station.

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Ich habe die Logik jetzt angepasst. Ist eine explizite Kombination gewählt, muss diese auf den aktuellen Timeframe passen. Die "Nichts" Auswahl habe ich einfach in "Alle" umbenannt, weil "Nichts" und "Alle" im Grunde das gleiche machen und es so einfacher umzusetzen war. Sollte mir da ein Case entfallen sein lasst es mich wissen.
Die Änderungen sind in bugfix/issue-848

**Comment by chriwen** [comment]
@hanneskasimir Bitte auf stage3 prüfen
