### ISSUE TITLE
Restriction Adminliste Spalten erweitern

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#853]
Die Restriction-Admin-Liste um folgende Spalten erweitern:

- Location
- Item
- Start-Datum
- End-Datum
- Status

Wenn möglich Filter nach diesen Spalten integrieren

**Comment by hansmorb** [comment]
In branch feature/issue-853 , müsste funktionieren

**Comment by chriwen** [comment]
@hanneskasimir Bitte auf stage3 testen
