### ISSUE TITLE
Fehler auf Fahrrad & Familie

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#854]
Version: 2.6-RC-9 auf https://www.fahrrad-und-familie.de/verleih/

- [ ] In Items-Liste erscheint nur 1 Zeitrahmen, es müssten hier aber 2 sein (inkl. 24. März)
![grafik](https://user-images.githubusercontent.com/28141760/150314770-83635ae9-815f-4b22-a897-8a6dd073f3f6.png) vgl. #800 

- [ ] Tabelle ist leer (https://www.fahrrad-und-familie.de/tabelle/)
![grafik](https://user-images.githubusercontent.com/28141760/150313213-64b017ac-6ee5-4148-91a8-31f17132dc27.png)

- [ ] Vorraussbuchungsfrist wird nicht richtig berechnet (April-Termin dürfte da nicht stehen)
![grafik](https://user-images.githubusercontent.com/28141760/150313389-2159e05d-cfa5-4d83-83a9-3dab494d07eb.png) vgl. #840

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Das könnte sich durch die Anpassungen aus https://github.com/wielebenwir/commonsbooking/issues/800 erledigen. Ich kanns aber nicht testen...

**Comment by chriwen** [comment]
@hanneskasimir das schaut auf stage3 gut aus. Willst du nochmal checken?
