### ISSUE TITLE
Spalten und Filter in Timframes und Bookings anpassen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#855]
Spalten und Filter so anpassen, dass diese wieder sinnvoll passen.

**Comment by chriwen** [comment]
Verknüpft mit #863

**Comment by hanneskasimir** [comment]
Fein, die Spalten passen. Bitte aber noch die Filter nach Typ anpassen, da können noch Dinge ausgewählt werden, die es gar n7cht gibt, z.b. Buchungen bei Zeitrahmein oder Urlaub bei Buchungen.

**Comment by chriwen** [comment]
@hanneskasimir Hab die Filter angepasst und bei Buchungen die Typenfilter komplett rausgenommen. Die brauchts da ja nicht, wa?
