### ISSUE TITLE
Spalten bei Zeitrahmen im Backend ändern

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#863]
- [ ] Buchungszeitpunkt entfernen
- [ ] Buchungsstatus entfernen

![grafik](https://user-images.githubusercontent.com/28141760/150494731-4f53a02d-eb17-462d-8849-0db532f09fa9.png)

Bitte neu hinzufügen (gerne am Ende ganz rechts)

- [ ] Maximale Buchungsdauer
- [ ] Maximale Buchungstage im Voraus

**Comment by hansmorb** [comment]
Ist in Release 2.6
