### ISSUE TITLE
Einschränkung: Stornierung optional

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#866]

**Comment by markus-mw** [comment]
@chriwen : Meinst du hier die Buchungsstornierung bei Totalausfall?

**Comment by chriwen** [comment]
@markus-mw : Ja, das müssen wir aber nochmal kurz durchdenken. Bei Flotte ist es so, dass die betroffenen Buchungen einen neuen Status "Blocked" bekommen, ggf. noch ne Meta-Info "blocked-by-restriction". So ist nachvollziehbar das die Buchung nicht vom Nutzenden storniert wurde und kann ggf. - falls z.B. der Ausfallzeitraum doch kürzer ist als gedacht - wieder in den Ursprungszustand zurückversetzt werden. 
Das müssten wir aber nochmal durchspielen, wie das am sinnvollsten zu lösen ist.
