### ISSUE TITLE
Kompatibilität WP 5.9 testen

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#867]
Bitte testen, ob mit WP 5.9 kompatibel

Hello, wielebenwir e.V.!

WordPress 5.9 is scheduled to be released on January 25th. Are your plugins ready?

After testing your plugins and ensuring compatibility, it only takes a few moments to change the readme "Tested up to" value to 5.9. This information provides peace of mind to users and helps encourage them to update to the latest version of WordPress. You can find more information about plugin readmes here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/.

Here are the current "Tested up to:" values for each of your plugins:

* https://wordpress.org/plugins/commonsbooking/ (tested up to 5.7.5)

For each compatible plugin, you do not need to release a new version — simply update the stable version's "Tested up to" value to 5.9 in your readme file. As a reminder, plugins that are not updated as tested with the latest 3 major releases of WordPress have a notice displayed on their WordPress.org plugin page noting that the plugin may no longer be maintained or supported; it's in everyone's best interest to continue testing plugins against WordPress versions and updating the "Tested up to" value.

Looking to get more familiar with 5.9? Read this roundup post on the core development blog to learn more about the various changes coming to core with this major release:
https://make.wordpress.org/core/2022/01/10/wordpress-5-9-field-guide/

There are eight areas that need specific focus as plugin-related changes are coming in 5.9:

1.) Take more control over Inner Block Areas (as a block developer): https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/

2.) Using multiple stylesheets per block: https://make.wordpress.org/core/2021/12/15/using-multiple-stylesheets-per-block/

3.) Miscellaneous block editor changes: https://make.wordpress.org/core/2022/01/04/miscellaneous-block-editor-changes-in-wordpress-5-9/

4.) New functions and hooks to work with posts, post types, and taxonomies: https://make.wordpress.org/core/2021/12/13/posts-post-types-and-taxonomy-changes-in-wordpress-5-9/

5.) New capability queries: https://make.wordpress.org/core/2022/01/05/new-capability-queries-in-wordpress-5-9/

6.) State of the Customizer with block themes (https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/) If your plugin supports Customizer, test with Twenty Twenty-Two (https://github.com/wordpress/twentytwentytwo) and confirm Customizer is available for your plugin. To learn more about supporting global styles, please refer to Block Supports (https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/).

7.) WordPress 5.9 and PHP 8.0-8.1: https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/

8.) Changes to WordPress Core's PHP Test Suite: https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/

To ensure compatibility, here is how to download the latest release candidate for testing with your plugin: https://make.wordpress.org/core/handbook/testing/beta-testing/.

Thank you for all you do for the WordPress community, and we hope you will enjoy 5.9 as much as we do.

— WordPress core contributors

--------
This email has been sent to all people with commit access to plugins. We regularly contact developers to ensure they are informed about changes to WordPress core and to verify their contact information. As such, there is no 'unsubscribe' to these emails — they are a requirement for hosting your code on WordPress.org. In order to stop receiving emails from us, you must close your plugins which you can do yourself from the Advanced link on the sidebar of your plugin page.

If you believe we've contacted you in error, or if you need help closing your plugins, please let us know.

**Comment by RalphBike** [comment]
Scheint bei uns zu funktionieren, allerdings habe ich nur auf unserem Test-Instanz probiert, nicht auf Live.
