### ISSUE TITLE
Booking Menüpunkt

### ISSUE THREAD

**Issue by markus-mw** [wielebenwir/commonsbooking#87]
im Backend soll ein Menüpunkt "Buchungen" hinzugefügt werden.
Dieser soll dann alle Timeframes vom Typ "Booking" und "Booking closed" enthalten.

Die Liste soll folgende Spalten enthalten:
itte folgende Spalten einfügen

- [x]  Titel (verlinkt zur Detailansicht)
- [x]  Artikel-Name
- [x]  Buchungs-Start
- [x]  Buchungs-Ende
- [ ]  Buchungs-Code
- [x]  Nutzer*in, die gebucht hat (verlinkt zur Backend-Profilseite)
- [x]  Standort-Name
- [x]  Buchungszeitpunkt
- [x]  Buchungs-Status (pending, confirmed, canceled)

Bitte Filter für:

 

- [x] Artikel-Name
- [x]  Standort-Name
- [x]  Buchungs-Status

**Comment by markus-mw** [comment]
@farbschein : Wie wichtig ist dir das? Ist nämlich sehr aufwändig.

**Comment by farbschein** [comment]
@markus-mw  Okay, dann bitte erst mal die anderen Tasks umsetzen. Vielleicht kannst du stattdessen die zusätzlichen Filter noch mit einbauen in der time Frame Liste. Wie aufwändig wäre denn der Booking Menüpunkt?

**Comment by markus-mw** [comment]
> @markus-mw Okay, dann bitte erst mal die anderen Tasks umsetzen. Vielleicht kannst du stattdessen die zusätzlichen Filter noch mit einbauen in der time Frame Liste. Wie aufwändig wäre denn der Booking Menüpunkt?

Die Filter kann ich ergänzen. Für den eigenen Menüpunkt müsste ich eigentlich für die Bookings einen komplett eigenen CPT anlegen und die damit zusammenhängenden Prozesse alle überarbeiten. Da bin ich locker einen Tag mit beschäftigt...

**Comment by markus-mw** [comment]
Ich hab jetzt soweit alles in die Zeitrahmenliste ergänzt.

**Comment by farbschein** [comment]
ok. Danke. ich schließ das dann hier und lege ein neues Issue an, da wir das langfristig anders lösen müssen.
