### ISSUE TITLE
Admin-Buchung außerhalb im Frontend buchbarer Zeiträume

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#871]
- Es ist umständlich, hier erst eine andere Buchung zu machen um dann die Tage zu ändern
- Beim Ändern muss man erst speichern bevor man auf Vorschau klicken kann, das steht nicht in der Beschreibung
- Die Buchung für andere Nutzer ist somit nicht möglich.
Ich plädiere dafür, den Admins doch mehr Freiheiten bei den Backend-Buchungen zu lassen (natürlich auf eigene Gefahr ;-)

**Comment by chriwen** [comment]
@hanneskasimir was meinst du mit "bei nicht freigeschalteten Zeiträumen?" Ich verstehe da den Kontext gerade nicht ;-(
Sprich mich dazu nochmal an, ok? Ist mir gerade nicht ganz klar.

**Comment by hanneskasimir** [comment]
Fall ist: Als Admin möchte heute schon ein Rad für die Sternfahrt im Juni für eine bestimmte Nutzerin reservieren.

**Comment by RalphBike** [comment]
Mir fehlt das Feature ebenfalls und hält mich von der Migration auf CB 2.x ab. Als Anregung: die Backend-Implementierung im Flotte-Plugin (für CB Legacy) funktioniert gut.

**Comment by chriwen** [comment]
@flegfleg @RalphBike @hanneskasimir Verstanden ;-) Bauen wir in einem der nächsten Updates baldmöglichst ein.
Kleiner Tipp für möglichen Workaround: Über User-Switching Plugins wie https://de.wordpress.org/plugins/user-switching/ können sich Admins als ein anderer User vorüberhend anmelden und könnten dann ad hoc die Buchung vornehmen. So erhält dann auch der/die entsprechende Nutzer*in die Bestätigungsmail etc.
Wir schauen aber mal, dass wir noch eine Funktion einbauen, die für Admins die Möglichkeit bietet bei der Buchung dann einen anderen Account als Buchende*r anzugeben.
Was grundsätzlich eher kritisch ist, ist Admins komplett frei über das Backend buchen zu lassen, da wir hier keine gute Validierung zu bereits gebuchten Zeiträumen etc. machen können und so die Gefahr besteht ungewünschte Buchungskonstellationen zu erzeugen.

**Comment by RalphBike** [comment]
Zu viele Checks stören an der Stelle doch nur :)

Im Ernst, ich finde es an der Stelle tatsächlich sinnvoll, mich als Admin nicht an alle Regeln oder Grenzen halten zu müssen. Um z.B. ein Rad für mehrere Wochen am Stück zu blockieren.
