### ISSUE TITLE
Zeitrahmen im Frontend nicht buchbar (Madomobil live)

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#872]
https://www.kasimir-lastenrad.de/cb-items/madomobil/?location=3625
![grafik](https://user-images.githubusercontent.com/28141760/151404877-54d17c11-575a-4b0c-8811-a346b03abc5f.png)

sobald ich ein Enddatum eintrage, erscheint der Zeitrahmen im Frontend.
![grafik](https://user-images.githubusercontent.com/28141760/151404532-c2e5b662-1163-4cf3-9e0e-53d6eb42a23b.png)

**Comment by chriwen** [comment]
@markus-mw Das Problem ist auch auf stage3 reproduzierbar. Ich hatte ich in 2.6-RC-11 bei Madomobil das Enddatum entfernt, Zeitrahmen gespeichert und Buchungen waren nicht möglich. Mit End-Datum waren buchungszeiträume vorhanden.

**Comment by hanneskasimir** [comment]
Tafelino, auch ohne Enddatum, funktioniert aber.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Ohne Wiederholung ist der Timeframe nutzlos... Die anderen beiden für das Madomobil bei Anna sind bereits abgelaufen. Stage3 schau ich mir jetzt noch an.
![image](https://user-images.githubusercontent.com/22905753/151415091-26cadeb7-8b96-400b-a089-a299fc6c568a.png)

**Comment by hanneskasimir** [comment]
@markus-mw : ah, krass, stimmt natürlich. Komisch nur, dass es bis zum Update heute auch ohne Wiederholung funktioniert hat.

**Comment by chriwen** [comment]
@markus-mw Danke für die Aufklärung. Technisch ist das korrekt. Wir müssen dann evtl. nochmal an der Doku was machen bzw. sogar bei buchbaren Zeitrahmen diese Kombination (Startdatum > Enddatum && Ohne Widerholung) verhindern. Das würde ja sowieso keinen Sinn machen, oder?
