### ISSUE TITLE
Buchungs / Timeframe-Listen: Uhrzeit immer 00:00

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#874]
In Buchungs- und Zeitrahmen-Liste scheint die Uhrzeit bei Start- und Enddatum immer 00:00 sein.
Zumindest bei den Buchungen müsste da doch 23:59 stehen.
Hinweis: Hans hatte die Tage ja an den Listen gearbeitet. Vielleicht da irgendwas mit dieser ColumnsData durcheinander gekommen?

![image](https://user-images.githubusercontent.com/12683634/151448177-ed3941e8-de45-4a16-a795-f532b518801d.png)

**Comment by hansmorb** [comment]
Ich glaube es hat was mit dem Meta Key "repetition-end" zu tun, das timestamp wird zur Darstellung richtig umgewandelt,

**Comment by markus-mw** [comment]
@chriwen : Wie besprochen hab ich die Zeiten bei den Timeframes rausgenommen.

**Comment by hanneskasimir** [comment]
in den Timeframes sind sie raus.
Bitte noch aus der Liste im Backend nehmen, siehe Screenshot oben
