### ISSUE TITLE
Tabelle: Beschriftung Monate falsch

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#876]
![grafik](https://user-images.githubusercontent.com/28141760/151555932-f682ce7f-75e2-4d48-941c-fa17c562fe66.png)

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das evtl. nochmal kurz anschauen.  Bei mir lokal sieht das so aus:
![image](https://user-images.githubusercontent.com/12683634/151696610-18281707-3309-414a-9a02-4b91f80b4020.png)
Da ist irgendwas seltsam ...

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Ist korrigiert und im Release Branch. Auf Stage3 ist es auch ausgerollt.
