### ISSUE TITLE
Shortcode for single item? 

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#882]
[cb_items] shortcode should allow for filtering by post id: 

`[cb_items id=XXX]`

**Comment by chriwen** [comment]
@flegfleg  [cb_items p=postID]

**Comment by flegfleg** [comment]
Ahhhhhh. Sorry, hab ich sogar in der Doku überlesen. Hab's dort jetzt noch mal deutlicher gemacht.
