### ISSUE TITLE
Stationen-Geocoder: Gutenberg-Editor-Seite muss neu geladen werden um Geokoordinaten anzuzeigen

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#883]
**Describe the bug**
Geocoordinaten werden scheinbar abgerufen/gespeichert. Felder bleiben leer. 

**To Reproduce**
auf stage3 hab ich den "Classic Editor" deaktiviert. Dort eine neue Station anlegen, Adresse eingeben.

* Publish oder Update zeigt die Geokoordinaten nicht an
* Neu laden der Seite zeigt die Geokoordinaten an

WordPress 5.9

**Comment by hansmorb** [comment]
Die Felder werden erst aktualisiert, wenn der entsprechende Post veröffentlicht ist. Danach muss der Editor neu geladen werden um die Änderungen an den Felder anzuzeigen.

**Comment by flegfleg** [comment]
Hey Hans, danke für die Antwort!
Ich musste tatsächlich den Browser neu laden (CMD + R), "Update"-Button brachte nichts.

**Comment by hansmorb** [comment]
Genau, der Inhalt der Felder wird erst aktualisiert sobald der gesamte Editor neu geladen wird. Ich kann gerade aktuell keine Möglichkeit finden CMB2 Boxen zu aktualisieren ohne die gesamte Seite neu zu laden.

**Comment by flegfleg** [comment]
Ach, wie nervig. Vielleicht sollte das in den Beschreibungstext dann @chriwen ?

**Comment by chriwen** [comment]
@flegfleg @hansmorb Ich hab da ne Lösung im entsprechenden Branch. Noch nicht ganz komplett, aber scheint zu funktionieren. Würde ich dann als Update die Tage publizieren.
