### ISSUE TITLE
Positionskarte auf Standort Editorseite lädt nicht richtig

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#885]
![image](https://user-images.githubusercontent.com/6433480/152951523-27620dcc-6942-4727-899e-2a6d1699c5f8.png)

Die Karte hat in diesem Format bei mir immer Darstellungsprobleme, oft laden die Felder mit dem Kartenausschnitt gar nicht.

**Comment by chriwen** [comment]
@hansmorb Kanns du mal prüfen, ob das bei euch mit dem neuesten Update 2.6.3 behoben ist? Vielen Dank.
