### ISSUE TITLE
Fatal Error beim Versand der Restriction-Mail

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#887]
Nutzender meldet folgenden Fehler:

Nachdem eine neue Einschränkung erstellt wurde.
(Admin-Menü -> Common Bookings -> Einschränkungen -> neue Einschränkung -> Daten eingeben => speichern => "aktiv" => veröffentlichen => senden-Button

Mit WP_DEBUG erhält man die Fehlermeldung im Anhang.

<img width="765" alt="Bildschirmfoto-2022-02-09-um-21 27 27" src="https://user-images.githubusercontent.com/12683634/153371613-44410704-a57b-43f7-8c6c-8c94b1415c64.png">

<img width="756" alt="Bildschirmfoto-2022-02-09-um-21 27 37" src="https://user-images.githubusercontent.com/12683634/153371636-40b10a81-fc33-46f4-8b37-08e430ae9cdd.png">

<img width="1185" alt="Bildschirmfoto-2022-02-09-um-21 37 58" src="https://user-images.githubusercontent.com/12683634/153371654-8b4698f4-fa82-4b2e-b5e6-4acc1ae38c74.png">

<img width="1141" alt="Bildschirmfoto-2022-02-09-um-21 38 07" src="https://user-images.githubusercontent.com/12683634/153371671-4dbc0614-0790-4de6-a3ce-e5801b20eae2.png">

**Comment by chriwen** [comment]
Warning: Object of class WP_User could not be converted to int in /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php on line 44

Warning: Attempt to read property "post_author" on null in /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php on line 109

Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php:113 Stack trace: #0 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php(113): method_exists(false, 'first_name') #1 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php(47): CommonsBooking\CB\CB::lookUp('user', 'first_name', NULL, NULL) #2 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/includes/TemplateParser.php(49): CommonsBooking\CB\CB::get('user', 'first_name', NULL) #3 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/includes/TemplateParser.php(16): commonsbooking_parse_template_callback('user:first_name', Array) #4 [internal function]: {closure}(Array) #5 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/includes/TemplateParser.php(18): preg_replace_callback('/\\{{.*?\\}}/', Object(Closure), '<h2>Hallo {{use...') #6 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Messages/Message.php(76): commonsbooking_parse_template('<h2>Hallo {{use...', Array) #7 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Messages/RestrictionMessage.php(124): CommonsBooking\Messages\Message->prepareMail(Object(WP_User), '<h2>Hallo {{use...', 'Ausfall von {{i...', 'From: Vogelsber...', NULL, Array) #8 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Messages/RestrictionMessage.php(80): CommonsBooking\Messages\RestrictionMessage->prepareRestrictionMail('<h2>Hallo {{use...', 'Ausfall von {{i...') #9 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Messages/RestrictionMessage.php(47): CommonsBooking\Messages\RestrictionMessage->sendRepairMail() #10 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Messages/Message.php(117): CommonsBooking\Messages\RestrictionMessage->sendMessage() #11 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Model/Restriction.php(285): CommonsBooking\Messages\Message->triggerMail() #12 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Model/Restriction.php(239): CommonsBooking\Model\Restriction->sendRestrictionMails(Array) #13 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/Wordpress/CustomPostType/Restriction.php(532): CommonsBooking\Model\Restriction->apply() #14 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-includes/class-wp-hook.php(309): CommonsBooking\Wordpress\CustomPostType\Restriction->savePost(844, Object(WP_Post)) #15 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #16 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #17 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-includes/post.php(4686): do_action('save_post', 844, Object(WP_Post), true) #18 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-includes/post.php(4788): wp_insert_post(Array, false, true) #19 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-admin/includes/post.php(426): wp_update_post(Array) #20 /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-admin/post.php(227): edit_post() #21 {main} thrown in /homepages/26/xxx/htdocs/clickandbuilds/xxxLastenrad/wp-content/plugins/commonsbooking/src/CB/CB.php on line 113
Es gab einen kritischen Fehler auf deiner Website. Bitte überprüfe den Posteingang deiner Website-Administrator-E-Mail-Adresse für weitere Anweisungen.

Erfahre mehr über die Problembehandlung in WordPress.

**Comment by chriwen** [comment]
@markus-mw Ich glaube, die Ergänzung der Abfrage in CB.php, Z.44 um WP_User sollte das beheben:
	} else if(!($post instanceof \WP_Post) && !($post instanceof CustomPost) **&& !($post instanceof \WP_User)**) {
Zumindest ein erster Test auf dem betroffenen System scheint erfolgreich.
Kannst du mal checken, ob das von der Logik her passt oder ggf. an anderer Stelle Problemchen bereiten könnte?

**Comment by chriwen** [comment]
@markus-mw Weiteres Problemchen.
In der Ausfall-Mail wird {{item:post_title}} durch den Titel der Buchung "Buchung" ersetzt. Hier scheint irgendwie bei der Restriction die Objekte nicht richtig mitzukommen?

Beispiel:
Leider ist der von dir gebuchte Artikel **Buchung** beschädigt und von 14.02.2022 00:00 bis voraussichtlich 23.02.2022 23:55 nicht mehr verwendbar. 
Der Grund ist:

**Comment by markus-mw** [comment]
> @markus-mw Ich glaube, die Ergänzung der Abfrage in CB.php, Z.44 um WP_User sollte das beheben: ` } else if(!($post instanceof \WP_Post) && !($post instanceof CustomPost) **&& !($post instanceof \WP_User)**) {` Zumindest ein erster Test auf dem betroffenen System scheint erfolgreich. Kannst du mal checken, ob das von der Logik her passt oder ggf. an anderer Stelle Problemchen bereiten könnte?

Das kommt hin. Ich hab den PR, gemerged.

**Comment by chriwen** [comment]
@markus-mw Lokal läuft die Restriction erstmal durch. Allerdings wird als {{item:post_title}} immer noch "Buchung" ausgegeben. Irgendwas passt das im Lookup noch nicht ganz.
