### ISSUE TITLE
Map Javascript-Fehler

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#895]
Usermeldung:

das Filtern der Räder nach Verfügbarkeit in den Standorten funktioniert nicht mehr, es gibt einen Javascript-Fehler in der Chrome-Console.

<img width="1178" alt="Bildschirmfoto-2022-02-12-um-13 26 45" src="https://user-images.githubusercontent.com/12683634/153713156-2bfc5d8c-8909-4d32-8907-0fba77f4123a.png">

**Comment by chriwen** [comment]
@markus-mw  oder @hansmorb  Hat da jemand von euch ne Idee?

**Comment by hansmorb** [comment]
Ich glaube das Problem liegt daran, dass zwar ein Availability Filter eingestellt ist aber keine availability erfragt wird, da keine Availability Anzeige existiert. Den Fehler hat aber Markus in seinem PR #890 schon angegangen, bei meinen Tests hat das auch funktioniert.
