### ISSUE TITLE
Buchung vorzeitig beenden (als Admin bzw. StationsbetreuerIn)

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#90]
Admins und SationsbetreuerInnen sollen eine Buchung im Backend aufrufen und diese als beendet markieren, wenn der Buchungszeitraum noch nicht abgelaufen ist.

Dabei soll der ursprüngliche Buchungszeitraum zu Auswertungszwecken gespeichert bleiben.

Lösungsansätze:
- im Timframe-Editor wird ein zusätzliches Feld "Rückgabe erfolgt am" hinzugefügt (Date + Time).
Ist diese Feld befüllt, wird dieser Wert im Frontend-Kalender zur Berechnung der freien Slots mit ausgewertet und ersetzt quasi das ursprünglich gebuchte End-Datum der Buchung.

**Comment by hansmorb** [comment]
Das existiert doch mittlerweile schon mit der cancellation-time, oder?
Ich verbinde diese issue mal mit der #1163 weil da die cancellation-time auch bei der Stornierung übers Frontend gesetzt wird. Nur die Kalenderdarstellung ist so nicht mit drin.
