### ISSUE TITLE
Fatal Error beim Aufrufen von Location Seiten

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#900]
Fatal error: Uncaught Error: CommonsBooking\View\Location::CommonsBooking\View\{closure}(): Argument #1 ($item) must be of type CommonsBooking\Model\Item, WP_Post given

**Comment by markus-mw** [comment]
@chriwen : Ich hab deine Anpassungen nochmal überarbeitet. Das war ein Copy Paste Fehler. Die Location Ansicht gehört dummerweise nicht zu meinen üblichen Klickpfaden, deswegen hab ich das übersehen. Ich zeig dir Freitag mal Cypress. Damit kriegen wir das in den Griff.
