### ISSUE TITLE
Benutzer:innenfelder in Mail Template Tags

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commonsbooking#902]
Hallo zusammen, 
ich erinnere mich dunkel, dass die Mail-Template-Tags eigentlich auch selbst erzeugte Benutzer:innenfelder zurück geben, oder? 
Anwendungsfall: **Nutzenden-Adresse in der Buchungsbestätigungsmail ausgeben**. 

Feldname: `adress` (wp_usermeta)
Template-Tag (ausprobiert): `{{user:adress}}` 
Kein Ergebnis. 

Danke + Gruß

**Comment by danielappelt** [comment]
Kann es sein, dass hier etwas nicht mehr richtig funktioniert?

In der [Dokumentation](https://commonsbooking.org/docs/einstellungen/template-tags/) wird z.B. der Template-Tag `{{item:condition}}` für ein zusätzlich angelegtes postmeta-Feld erwähnt. Wir verwenden analog `{{item:deposit}}` und bekommen hierfür seit dem letzten großen Update keine Ausgabe mehr.

Es scheint also eher ein Bug zu sein.

**Comment by chriwen** [comment]
@markus-mw kannst du dir das mal anschauen?

**Comment by danielappelt** [comment]
@markus-mw der Fehler scheint [im Abruf der Meta-Daten](https://github.com/wielebenwir/commonsbooking/blob/04cd7ead3311707c1fe3e7d13fc0ca9b8c4b2d9f/src/CB/CB.php#L123) zu liegen.

[`get_post_meta()`](https://developer.wordpress.org/reference/functions/get_post_meta/) erwartet als ersten Parameter tatsächlich die Post-ID.

Eine Änderung zu `get_post_meta( $post->ID, $property, true )` liefert die erwarteten Werte.

**Comment by flegfleg** [comment]
Hey Daniel, 
danke für's Dranbleiben!

**Comment by markus-mw** [comment]
> {{user:adress}}

@flegfleg : Das hab ich gerade bei mir lokal getestet und in der neuesten Version funktioniert das. Kannst du das noch einmal probieren?

**Comment by chriwen** [comment]
@markus-mw und der Vorschlag von @danielappelt? Kannst du das prüfen und ggf. anpassen. Scheint mir erstmal nachvollziehbar.

**Comment by markus-mw** [comment]
@chriwen : Das hab ich gerade gemacht. Außerdem hab ich das Thema generell etwas überarbeitet und noch ein paar passende Tests ergänzt.
@danielappelt : Teste doch bitte einmal den Branch bugfix/issue-902, damit sollte es klappen.

**Comment by markus-mw** [comment]
@chriwen, @hanneskasimir : Die Anpassung ist inzwischen im master und auf stage3 ausgerollt. Schaut bei Gelegenheit bitte nochmal ob alles erwartungsgemäß funktioniert.

**Comment by chriwen** [comment]
@markus-mw ein Meta-Feld für ein Item konnte ich erfolgreich in der E-Mail ausgeben. Das hinterlegte User-Metafeld "address" kam leider nicht an.

**Comment by chriwen** [comment]
@flegfleg Falls du beizeiten auch nochmal testen willst. Das Feld schreibt sich so: address (doppel-D) 
momentan scheints aber noch nicht zu klappen.

**Comment by chriwen** [comment]
@markus-mw Lokal ging das bei mir, auf Stage3 jedoch nicht. auch mit einem anderen user-metfeld z.B. "phone"

**Comment by chriwen** [comment]
@markus-mw Kannst du dir das bitte nochmal anschauen?
