### ISSUE TITLE
REDIS Object Cache Unterstützung

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#908]
Habe versucht bei uns im System einen Object Cache zur schnelleren Seitendarstellung zu implementieren. Das führt jedoch dazu, dass die Buchungslisten nicht aktualisiert werden und so auch Doppelbuchungen möglich sind.

**Comment by hansmorb** [comment]
Nicht realisierbar, da der WP Object Cache genutzt werden müsste, damit das REDIS Object Cache plugin genutzt werden kann. Einzige Möglichkeit wäre unabhängig von dem Plugin mit dem REDIS Adapter von Symfony eine Verbindung zu einer REDIS Datenbank herzustellen. 

Leider führen die Inkompatibilitäten immer noch dazu, dass die beiden Plugins nicht zeitgleich genutzt werden können, weil sonst Doppelbuchungen auftreten können. (Der Cache wird anscheinend nicht richtig invalidiert).

**Comment by datengraben** [comment]
@hansmorb ist das jetzt doch mit #1109 umgesetzt?
