### ISSUE TITLE
Lazy-Load-Image verschwindet nicht (Version 2.6.8)

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#912]
**Describe the bug**
Nach dem Update auf Version 2.6.8 verschwindet in der Artikel-Ansicht und auf der Buchungsseite das Lazy-Load-Image beim Artikel-Standort bzw. dem Artikel nicht nach dem das eigentliche Bild geladen und angezeigt wurde.

**To Reproduce**
Die Seite für einen Artikel öffnen: beim Standort-Bild bleibt das Lazy-Load-Image stehen nach dem das Standort-Bild geladen wurde.

Die Seite für eine Buchung öffnen: beim Artikel-Bild bleibt das Lazy-Load-Image stehen nach dem das Artikel-Bild geladen wurde.

**Expected behavior**
Das Lazy-Load-Image verschwindet nach dem das gewünschte Bild geladen wurde.

**Screenshots**
![image](https://user-images.githubusercontent.com/3137880/154681661-9e6418ba-9c78-4754-becf-3bb71546ae6a.png)

**Comment by chriwen** [comment]
@danielappelt kannst du uns dazu noch eine url nennen wo wir das mal sehen können? Danke.

**Comment by danielappelt** [comment]
@chriwen hier kann man es sehen https://leihbarbonn.de/dinge/wanderstoecke-rot/
Auf allen anderen Seiten blende ich die Grafik jetzt via CSS aus.
