### ISSUE TITLE
Karte zeigt falschen Ort

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#916]
nach Update auf 2.8 auf KASIMIR live und bei Fahrrad & Familie:
es wird immer der selbe Ort in Berlin angezeigt:
![grafik](https://user-images.githubusercontent.com/28141760/154862008-b2cf8421-5c21-4e8f-a300-b6a3fa6f40a2.png)
![grafik](https://user-images.githubusercontent.com/28141760/154862032-de254bdd-8c84-4f83-af19-e26be8d2fd90.png)

**Comment by hansmorb** [comment]
Die Änderungen im commit 5a845b7 (oberhalb von remove unused CB::echo method) haben den bug aufgeworfen in der View/location.php Zeile 139 . Ich schau mal, ob ich es fixen kann.

**Comment by hansmorb** [comment]
Sollte wieder funktionieren

**Comment by hanneskasimir** [comment]
wo kann ich testen? auf stage3 funktioniert es noch nicht!

**Comment by markus-mw** [comment]
@hanneskasimir : Ich hab die Anpassungen auf stage3 ausgespielt. Schau bitte mal nach.
