### ISSUE TITLE
Kalender: Heutiger Tag wird falsch markiert

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#917]
Heute ist der 20. Februar, der müsste eigentlich blau sein und der 24. Februar grün, weil buchbar und frei:
![grafik](https://user-images.githubusercontent.com/28141760/154862353-afe8260d-3d8b-40e9-9139-0fa702534a0e.png)

**Comment by hansmorb** [comment]
Ich glaube das ist normales Verhalten, es wird immer automatisch der nächste buchbare Tag angewählt. Vorschlag: nur einen kleinen, blauen Rahmen um den aktuellen Tag machen und nichts automatisch anwählen.

**Comment by hanneskasimir** [comment]
ja, so wäre es richtig und ist es z.B. hier auch richtig:
https://www.kasimir-lastenrad.de/cb-items/kulturbunker-muelheim-e-lastenrad/?location=3618

**Comment by markus-mw** [comment]
@hanneskasimir , @hansmorb : Das "Problem" ist das Startdatum des Timeframes. Wenn dieses heute ist oder in der Vergangenheit liegt, dann wird der heutige Tag, unabhängig von seiner Buchbarkeit blau markiert. Wenn das Startdatum aber in der Zukunft liegt, wird dieses Datum blau hinterlegt. 
Das ist aktuell das Standardverhalten. Ich schau mal, dass ich das angepasst bekomme.

**Comment by hanneskasimir** [comment]
ah, ich sehe gerade, dass die Zahl des heutigen Tags manchmal rot ist:
![grafik](https://user-images.githubusercontent.com/28141760/155279387-c5a64918-906a-4cf4-9d70-a7865d31ab2f.png)
Wenn das immer so wäre, würde es ja auch passen und vermutlich einfacher als ein blauer Rahmen.

Zusammengefasst wäre das:

- rote Zahl = heutiger Tag (passt nur bei orange nicht richtig, würde ich aber erstmal akzeptieren, ist ja nur ein Tag)
- blaues Feld = ausgewählt (default = nix ausgewählt! da stimme ich Hans zu, das ist ein relevanter Punkt des Fehlers und wichtig fürs Verständnis)
- grün, rot, orange, grau wie bisher.

**Comment by markus-mw** [comment]
@hanneskasimir : Ich hab das jetzt mal mit der Rahmenvariante umgesetzt. Schau bitte mal auf Stage 3. Wenn du es nicht auf Anhieb siehst, aktualisiere die Seite mal mit Strg+F5 bzw. leere den Cache.

**Comment by chriwen** [comment]
@markus-mw Danke für die Umsetzung. Für mich würde es ausreichen, wenn nur die Zahl rot ist und der Rahmen per default weg ist. Dann ist es denke ich am klarsten. Der Rahmen verwirrt u.U. auch nur, weil nicht klar ist für was das nun steht.

**Comment by hanneskasimir** [comment]
Rahmen ist da, allerdings auch manchmal noch die rote Markierung.
Fälschlicherweise sind die nächsten Tage buchbar, hängt das damit zusammen?
Karla:
![Screenshot_20220224-151922](https://user-images.githubusercontent.com/28141760/155543604-93663f38-4d84-4e20-948d-7117cd96f347.png)

Tabelle ist richtig (karla)
![Screenshot_20220224-151933](https://user-images.githubusercontent.com/28141760/155543714-22c7fda5-d741-4060-a57c-afcb9987bf94.png)

**Comment by hanneskasimir** [comment]
Die falschen Tage lassen sich nicht alsmrückgabetag auswählen
![Uploading Screenshot_20220224-153626.png…]()

**Comment by markus-mw** [comment]
> @markus-mw Danke für die Umsetzung. Für mich würde es ausreichen, wenn nur die Zahl rot ist und der Rahmen per default weg ist. Dann ist es denke ich am klarsten. Der Rahmen verwirrt u.U. auch nur, weil nicht klar ist für was das nun steht.

Rot ist halt ungünstig wenn der Tag gebucht ist. Dann sieht man das nicht. Ist das in Ordnung?

**Comment by hanneskasimir** [comment]
Ja, gerne nur die rote Zahl. Blau nur für Markierung, s.o.

**Comment by chriwen** [comment]
Oder einfach gar keine Markierung für den aktuellen Tag? Die Tage vor dem aktuellen Tag sind ja sowieso nie buchbar, von daher ist das doch eigentlich auch nicht so wichtig, oder? Dann sparen wir uns den ganzen Zauber?

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Ihr macht mich fertig. Jetzt ist das rot markiert. Ich kann das aber auch gern wieder raus nehmen.

**Comment by markus-mw** [comment]
@hanneskasimir : Das "Karla-Problem" ist behoben.

**Comment by hanneskasimir** [comment]
Fehler ist leider heute wieder da: https://www.fahrrad-und-familie.de/verleih/
Version: 2.6.12

**Comment by markus-mw** [comment]
@hanneskasimir : Hilf mir bitte kurz. Was ist das Problem? Ich seh es nicht.

**Comment by hanneskasimir** [comment]
oh sorry, hab das Ticket verwechselt.

**Comment by chriwen** [comment]
@markus-mw  @hanneskasimir : Bringt es was, evtl. mal die 2.7 RC zu installieren?
https://downloads.wordpress.org/plugin/commonsbooking.2.7.zip
