### ISSUE TITLE
Buchung nicht möglich (KASI-live und weitere)

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#919]
KASIMIR live:
Nach Auswahl von Zeitraum im Frontend und klick auf "Weiter zur Buchungsüberprüfung" wurde heute Vormittag (Montag) vereinzelt die Seite neu geladen und die Nutzenden kamen nicht auf die Überprüfungsseite. Im Hintergrund wurde dennoch eine unconfirmte Buchung erstellt. (Ein Beispiel liegt auf KASI-live im Papierkorb). In der Buchnung fehlen die persönlichen Daten des Nutzers, der die Buchung erstellt hat.
Ich konnte den Fehler auch bei einem anderen Rad (Madomobil) kurzzeitig reproduzieren. Mittlerweile (ggf. seit ich die oben erwähnte Buchung in den Papierkorb gelegt habe) klappt es auf KASI-live wieder.

**Comment by hanneskasimir** [comment]
Selber Fehler wird uns auch von https://lastenrad-buchholz.de gemeldet.
Ich hab mich dort mal registriert und getestet.
Der Fehler kann dort bei jedem Aufruf reproduziert werden.

**Comment by hanneskasimir** [comment]
in Buchholz wird vermutlich keine Buchung erstellt (Zeitraum bleibt im Frontend grün)

**Comment by hanneskasimir** [comment]
in Buchholz wurde keine unconfirmed-Buchung ohne Nutzer gefunden.

**Comment by hanneskasimir** [comment]
ah, es hat was ggf. mit den Nutzungsrechten zu tun! Als Admin komm ich durch auf KASI-live. als cb_manager kommt ich immer wieder zurück zum Kalender.

**Comment by markus-mw** [comment]
> in Buchholz wird vermutlich keine Buchung erstellt (Zeitraum bleibt im Frontend grün)

Ich hab auch versucht mich zu registrieren, aber die Registrierung selbst läuft auf einen Fehler (an der Stelle an der man eine Aufgabe ausrechnen soll, zumindest laut Seitentitel).

**Comment by hanneskasimir** [comment]
noch ne Rückmeldung von einem anderen Projekt:

Seit der Installation des Updates heute funktioniert das Buchen oft nicht. Wenn man einen Zeitraum ausgewählt hat und auf „weiter zur Buchungsprüfung“ klickt, wird die Seite mit der Übersicht der Stationen geladen. Nachdem ich an einem anderen Standort einen Buchungszeitraum ausgewählt und auf die Seite Buchungsprüfung geleitet wurde, funktionierte auch die Buchung des ursprünglich geplanten Zeitraumes. ABER ...


… Nun trat ein weiteres Problem auf: Wenn ich bei einem Standort einen Buchungszeitraum anklicke und zur Bestätigung aufgefordert werden, das aber nicht tue, sondern auf „Abbrechen“ klicke oder die Seite einfach verlasse, dann wird der ausgewählte Buchungszeitraum weiterhin rot unterlegt angezeigt und steht in der Datenbank als „unconfirmed“. Den muss ich dann als Administrator manuell aus der Datenbank löschen.

**Comment by markus-mw** [comment]
@hanneskasimir : Das kann ich nachvollziehen. Die unconfirmed Buchungen sind normal, sollten aber den Tag nicht blockieren. Die werden nach 10 Minuten automatisch gelöscht, da muss man sich als Admin nicht drum kümmern.

Ich schau mir das Problem an, dass die im Kalender als gebucht angezeigt werden.

**Comment by markus-mw** [comment]
@chriwen , @hanneskasimir : Wie eben besprochen ist die Anpassung mit 2.6.10 getaggt.
