### ISSUE TITLE
Buchungseinschränkungen als Möglichkeit Urlaubstage zu hinterlegen

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#920]
An einem Standort mit hunderten Artikeln (https://leihbarbonn.de) möchten wir Urlaubstage hinterlegen bzw. Tage an denen es keine Öffnungszeiten gibt. Artikel können in diesem Zeitraum dann nicht abgeholt oder zurück gebracht werden. Sehr wohl soll es aber möglich sein, Gegenstände vor Beginn dieses Zeitraums abzuholen und sie danach zurück zu bringen.

Artikel haben bei uns eine maximale Ausleihdauer von ca. 6 Wochen. Die Standort-Einstellung "Überbuchen von geblockten Tagen erlauben" ist aktiviert. Aktuell haben wir keine praktikable Möglichkeiten Feitertage oder dergleichen abzubilden. Wir müssten dafür hunderte Zeitrahmen anpassen. Unsere Hoffnung war, dass Benutztungseinschränkungen uns dies nun einfach ermöglichen.

In Version 2.6.8 ist es jedoch leider nicht möglich Buchungseinschränkungen zu überbuchen. Dies ist beim tatsächlichen "Totalausfall" eines Artikels natürlich sinnvoll.

Für den oben beschriebenen Fall wäre es schön, wenn es einen weiteren Einschränkungstyp geben würde (Urlaub, Personalausfall oder dergleichen), für den Überbuchungen dann möglich wären.

**Comment by hansmorb** [comment]
Dopplung #1013
