### ISSUE TITLE
Maximale Buchungstage im Voraus automatisch auf existierende Zeitrahmen anwenden

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#921]
**Describe the bug**
Für Zeitrahmen, die vor dem Update auf eine CB-Version mit dem Feature "Maximale Buchungstage im Voraus" angelegt wurden, wird nicht der Standard-Wert für neue Zeitrahmen (365 Tage) angewendet. In der Zeitrahmen-Übersicht bleibt bei solchen Zeitrahmen die entsprechende Spalte leer. Bearbeitet man den Zeitrahmen wird dann jedoch 365 angezeigt (und beim Speichern auch hinterlegt).

Solange in einem Zeitrahmen kein Wert hinterlegt ist, wird der verfügbare Buchungszeitraum Tag für Tag kleiner! Anscheinend gelten nun 365 Tage seit Erstellungsdatum des Zeitrahmens als maximal buchbarer Zeitrahmen.

Um das erwartete Verhalten zu bekommen, müsste man jeden Zeitrahmen einmal öffnen und neu speichern. Wenn man etliche buchbare Zeitrahmen im System hat, ist das äußerst lästig. 

**To Reproduce**
Artikel zu einem buchbaren Zeitrahmen der vor dem Update auf das Feature "Maximale Buchungstage im Voraus" angelegt wurde, über mehrere Tage anschauen. Die Anzahl im Voraus buchbarer Tage im Artikel-Kalender wird täglich kleiner.

**Expected behavior**
Beim Update sollte der Standard-Wert entweder in alle buchbaren Zeitrahmen geschrieben werden oder aber das System gar kein Maximum annehmen.

Darüber hinaus wäre es gut, wenn Administratoren hier tatsächlich (nahezu) beliebig große Werte angeben könnten. Werte über 365 werden anscheinend ohne Benachrichtigung auf 365 zurückgesetzt.

**Screenshots**
![image](https://user-images.githubusercontent.com/3137880/155023652-34efc074-bf9d-4f53-b79f-fa279174f333.png)

![image](https://user-images.githubusercontent.com/3137880/155023816-49061e0e-2cf2-49f9-a600-7e2c744d41d4.png)

Siehe: https://leihbarbonn.de/dinge/sandwichmaker/

**Comment by chriwen** [comment]
@danielappelt danke für den Hinweis. Das schauen wir uns umgehend an.

**Comment by danielappelt** [comment]
@chriwen, ich bin nicht sicher, ob damit das Update auf 2.6.12 gemeint war?

Nach dem Update erhalte ich [für oben genannten Artikel](https://leihbarbonn.de/dinge/sandwichmaker/) einen anderen Wert ungleich 365 im Buchungskalender und weiterhin einen leeren Eintrag in der Zeitrahmenübersicht im WP-Dashboard.

Meine Erwartungshaltung war, dass es entweder keine Beschränkung im Buchungskalender gibt (entsprechend WP-Zeitrahmenübersicht) oder es aber 365 Tage sind. Ich befürchte darüber hinaus, dass der aktuelle Wert sich weiterhin täglich um 1 verringert.

**Comment by chriwen** [comment]
@danielappelt das ist noch nicht in 2.6.12 enthalten. Kommt erst im nächsten Update.
