### ISSUE TITLE
Seite ist sehr langsam & Artikelseiten öffnen nicht

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#924]
https://www.fahrrad-und-familie.de/ ist sehr langsam seit den letzten Updates.
Wenn ich cb deaktiviere ist die Seite wieder schnell.
Admin-Zugriff kann ich euch gerne geben.

**Comment by hanneskasimir** [comment]
ich hatte cb einmal deaktiviert und wieder aktiviert. 
Jetzt öffnen die Artikelseiten gar nicht mehr: https://www.fahrrad-und-familie.de/verleih/libelle-lastenrad/?location=12488

**Comment by markus-mw** [comment]
@hanneskasimir : Ich bräuchte Admin Zugangsdaten um das zu prüfen. Kannst du mir da was besorgen und in Signal schicken?

**Comment by markus-mw** [comment]
@hanneskasimir : Nachdem ich mich im Backend angemeldet und lediglich den Query Monitor installiert installiert hatte, lief die Seite plötzlich normal. Bitte teste das noch einmal. (Das Query Monitor Plugin hab ich wieder deinstalliert)
