### ISSUE TITLE
Heutiger Tag Fehlt

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#926]
Heute ist der 24. Februar, der heutige Tag sollte eigentlich buchbar sein:
Liste:
![grafik](https://user-images.githubusercontent.com/28141760/155468751-c858ac5e-a13b-4240-bcaf-180dcac00ab1.png)
Kalender:
![grafik](https://user-images.githubusercontent.com/28141760/155468832-5ac4240f-9e1d-4969-b306-2fd606cb985e.png)
in der Tabelle ist es korrekt:
![grafik](https://user-images.githubusercontent.com/28141760/155468880-8d3bc4e4-4a04-400d-bb66-f68629d68347.png)

**Comment by markus-mw** [comment]
@hanneskasimir : Der 24. ist doch buchbar. Einzig die ungünstige Darstellung lässt einen falschen Eindruck entstehen.

**Comment by hanneskasimir** [comment]
Achtung, es war der 24. FEBRUAR!

**Comment by chriwen** [comment]
@markus-mw Konnte das gerade auf stage3 nachvollziehen.
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/12683634/155883679-edd4eb7a-2aad-4cff-a408-f997595cd1da.png">

In Booking-Liste ist der heutige Tag 27.02. grün
Im Buchungskalender gehts erst ab März los

<img width="739" alt="image" src="https://user-images.githubusercontent.com/12683634/155883709-5964638d-a4a5-46a3-a1c8-6681f8a61c38.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/12683634/155883727-8b76cd28-1c4a-417c-ac7f-cc9b0eb2112f.png">

**Comment by markus-mw** [comment]
@hanneskasimir , @chriwen : Das Problem war hier, dass das Ende des Zeitrahmens um 0.00 Uhr des gewählten Tages gesetzt wird. Ich habe die Speicherung jetzt angepasst, sodass das Ende des Zeitrahmens auf 23.59 Uhr des Enddatums gesetzt wird.
Das einzige Problem an der Sache ist, dass die Anpassung nur dann greift, wenn der Zeitrahmen gespeichert wird.

**Comment by hanneskasimir** [comment]
Danke! das ist noch nicht auf stage3 zum testen, oder?

**Comment by chriwen** [comment]
@hanneskasimir ich habs gerade mal umgestellt. Kannst du testen?

**Comment by hanneskasimir** [comment]
sorry, ich meinte dieses Ticket:
Fehler ist leider heute wieder da: https://www.fahrrad-und-familie.de/verleih/
Version: 2.6.12

**Comment by markus-mw** [comment]
@hanneskasimir : Ich will dich wirklich nicht ärgern, aber was genau (Rad/Location) funktioniert nicht? Für mich sieht das soweit ok aus. Nahezu alle Räder haben als nächsten Termin den 29.04.

**Comment by markus-mw** [comment]
@hanneskasimir : Ok, jetzt hab ich es begriffen. Schau ich mir nochmal an.

**Comment by markus-mw** [comment]
Das ist mir ein Rätsel. Ich bekomme den Fall lokal nicht nachgestellt. Ich probiere/teste weiter...

**Comment by hanneskasimir** [comment]
hab das mal ganz im Geheimen hier gebaut:
siehe "Helm Bärchen" https://www.fahrrad-und-familie.de/tabelle/

**Comment by hanneskasimir** [comment]
ist vermutlich auch morgen (29.3.22) testbar.

**Comment by chriwen** [comment]
auch hier: @hanneskasimir willst du mal die 2.7. installieren?
https://downloads.wordpress.org/plugin/commonsbooking.2.7.zip
Vorher Backup machen.

**Comment by hanneskasimir** [comment]
nein, geht leider auch nicht.

**Comment by hanneskasimir** [comment]
nein, auf stage kann ich das leider auch nicht nachstellen.

ich hab nochmal weiterprobiert, vielleicht hilfts weiter?
- Ich hatte einen neuen Testartikel jetzt angelegt für heute. hier wird gar keine Kalender angzeigt, Artikel nicht buchbar: https://www.fahrrad-und-familie.de/verleih/testartikel/. 
- in der Liste https://www.fahrrad-und-familie.de/verleih/ ist der Testartikel gar nicht drin. Andere, nicht verfügbare Artikel werden dort aber aufgelistet.
- Die Seite ist außerdem unglaublich langsam, bspw. lädt die Tabelle seit 20 Minuten überhaupt nicht mehr. 

Wir haben ziemlich viele Zeitrahmen am laufen (162). vielleicht liegt es daran?

Wir können auch gerne mal zusammen draufschauen und Plugins (viele sind es aber eh nicht) deaktivieren oder ne Kopie machen o.ä.

**Comment by hanneskasimir** [comment]
ah, die Tabelle ist da, dort ist alles in ORdnung:
![grafik](https://user-images.githubusercontent.com/28141760/161221281-bb76f733-6b69-4601-8a7c-4bfcc7e67e84.png)

**Comment by hanneskasimir** [comment]
ahhgrr!
Jetzt, nachdem die Tabelle geladen hat, erscheint ist alles gut und der heutige Tag ist buchbar.

**Comment by chriwen** [comment]
Ich konnte gestern ein ähnliches Verhalten bei Lastenrad Münster feststellen. Die wollten migrieren, aber die cb_items-Liste war unendlich am laden bis zum Abbruch. Der Server ist zwar wohl auch nicht der schnellste, aber irgendwas ist das schief. Irgendwie hatte QueryMonitor auch eine hohe Anzahl an meta cache updates angezeigt (im WP Core). 
@markus-mw Kann das irgendwas mit CB zu tun haben?

**Comment by markus-mw** [comment]
@hanneskasimir : Ich habe jetzt alle Anpassungen von gestern auf Stage 4 ausgespielt. Du kannst testen.
