### ISSUE TITLE
Calendar does not show confirmed bookings

### ISSUE THREAD

**Issue by Splines** [wielebenwir/commonsbooking#930]
**Describe the bug**
Someone booked one of our cargo bikes for March, status is `confirmed` in the bookings view:

![buchung admin dashboard](https://user-images.githubusercontent.com/37160523/155620510-8317eb49-95d7-41c6-9d90-810bdf1f33e3.jpg)

However, the booking does not show up in the calendar (all days are marked green). Note that I've made sure to select the calendar for the right cargo bike:
![Calendar view](https://user-images.githubusercontent.com/37160523/155620248-0deec4f6-a287-4139-a0b4-9992bf6b9373.jpg)

**To Reproduce**
A user reported this issue today saying that this weird behavior is occurring since a few days. I've updated to version 2.6.11 a few days ago, so I guess that this is correlated.

Difficult for me to tell the steps to reproduce. User just booked one of our cargo bikes as usual.

**Expected behavior**
Day in calendar marked red instead of green.

**Comment by chriwen** [comment]
@Splines Danke für die Meldung. Kannst du uns dazu bitte eine Support-Mail unter mail@commonsbooking.org schreiben mit den Daten der betroffenen Seite, der URL und ggf. einem temporären Admin-Zugang. Dann schauen wir uns das gerne an.

**Comment by Splines** [comment]
https://github.com/wielebenwir/commonsbooking/commit/3697078c246f4f849ebc1258876eb93d8ef6d4e7

**Comment by Splines** [comment]
@markus-mw Vielen Dank nochmal fürs schnelle Kümmern. Da der Change ja bereits in master gemerged ist: soll ich dieses Issue hier schließen?
