### ISSUE TITLE
Filter-Hooks einheitlich benennen

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#938]
Die [Filter-Hooks](https://github.com/wielebenwir/commonsbooking/search?l=PHP&q=apply_filters) des Plugins sollten einheitlich benannt werden. Vorschlag: `cb_<snake_cased_identifier>`

In dem Zuge könnte man dann auch Dokumentation ergänzen. Ich könnte mich gerne bei Gelegenheit drum kümmern. Das wäre dann aber etwas für ein Feature-Release, da ggf. Filter-Implementierungen in Installationen nachgezogen werden müssen.

**Comment by hansmorb** [comment]
Ich wäre eher dafür, commonsbooking auszuschreiben um mögliche Kompatibilitätscrashs zu verhindern
