### ISSUE TITLE
Zeitrahmen-Export: Download ist immer leer

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#939]
**Describe the bug**
Ich erhalte immer nur eine leere Datei (Größe 0 Byte, kein Inhalt), egal welche Einstellungen ich im Abschnitt "Zeitrahmen-Export herunterladen" vornehme,

**To Reproduce**
Beliebigen Download-Export durchführen. Könnt ihr das bitte bei euch mal testen?

**Expected behavior**
Die heruntergeladene CSV-Datei enthält die Zeitrahmen entsprechend Selektion.

**References**
#538

**Comment by markus-mw** [comment]
@chriwen , @danielappelt : Ich kann es auch nachvollziehen und sehe es mir an.

**Comment by markus-mw** [comment]
@danielappelt , @chriwen : Das Problem ist behoben. Da hat sich beim hinzufügen der Escapings ein Fehler eingeschlichen. Ist im master korrigiert.

**Comment by babeene** [comment]
Hallo zusammen, bei mir tritt das Problem genauso auf, Export legt eine leere Datei an. Ich habe den cb-legacy#191 geschlossen, hatte den auf der falschen Version erstellt :-)
FYI: @flegfleg

**Comment by chriwen** [comment]
@babeene Das Problem wird mit dem nächsten Update (wahrschl. 2.7) behoben sein.
