### ISSUE TITLE
Export stornierter Buchungen funktioniert nicht

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#943]
**Describe the bug**
Ein Export-Download mit Typ-Beschränkung auf "Buchung storniert" liefert ein leeres Ergebnis, obwohl stornierte Buchungen im selektierten Zeitraum existieren.

**To Reproduce**
Buchung anlegen -> Buchung stornieren -> Export mit Typ-Beschränkung "Buchung storniert" mit passenden Selektionskriterien. Ergebnis ist leer.

**Expected behavior**
Es werden die stornierten Buchungen exportiert.

**Details**
So wie es aussieht, trifft die Typ-Filter-Auswahl "Buchung storniert" (BOOKING_CANCELED_ID / 7) gar nicht auf (über das Frontend) stornierte Buchungen zu. Für solche Buchungen bleibt der post_type unverändert BOOKING_ID / 6. Im Post zur Buchung wird hingegen das Feld post_status auf 'canceled' gesetzt.

In unserem System liefert so beispielsweise die Abfrage

`
SELECT * FROM 'wp_postmeta' WHERE 'meta_key' = 'type' AND 'meta_value' = '7'
`

keinen einzigen Treffer, obwohl wir zahlreiche stornierte Buchungen haben.

Darüber hinaus werden in der Funktion [getExportData](https://github.com/wielebenwir/commonsbooking/blob/216975932b4323b302dcbd6ad68be92f3616fcc7/src/View/TimeframeExport.php#L166) bei der Abfrage der Posts nach Typ keine post_status-Einschränkungen mit übergeben, was dazu führt, das nur Posts mit post_status `[ 'confirmed', 'unconfirmed', 'publish', 'inherit' ]` im Download-Ergebnis mit Typ-Filter-Auswahl "Buchung" landen, aber nicht die mit post_status 'canceled'.

**Comment by chriwen** [comment]
@markus-mw Lass mal prüfen, ob wir den Typ "stornierte Buchungen" aus dem Dropdown im Export nehmen können. Ich würde eher dafür plädieren alle Buchungen zu exportieren, unabhängig vom Status. den Status selbst geben wir ja im Export mit aus, oder? Das sollte dann ausreichen. Ist auch für Auswertungen dann einfacher, wenn das nicht getrennt wird.

**Comment by markus-mw** [comment]
@chriwen : Ich hab das jetzt entsprechend angepasst. Bei der Auswahl von "Buchungen" werden auch die stornierten mit exportiert und die Option "Buchungen storniert" ist entfernt.

**Comment by chriwen** [comment]
@danielappelt wir schließen die Tickets immer zentral, wenn wir einen finalen Test bei uns auf den Systemen gemacht haben. Wenn du bei dir Lokal einen Test machst dann am beste hier kurz kommentieren, aber ticketstatus bitte unverändert lassen. Das hilft uns, den Überblick zu behalten. Danke.
