### ISSUE TITLE
2.6.14 (draft): Kalender kein End-Datum setzen möglich

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#946]
in aktuellem Master / lokal:
2 Zeitrahmen buchbar, wöchentlich, stündlich:
A: 08:00 - 13:00
B: 14:00 - 18:00

Buchung angelegt:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/12683634/156570788-ac83472d-c6dd-4341-b189-2923b75e9494.png">

Ergebnis: Bei Versuch eine Anschlussbuchung vom bereits gebuchten (halben) Tage anzulegen, kann nach Auswahl des Startdatums kein End-Datum gesetzt werden:
siehe: https://watch.screencastify.com/v/KBsxN3mMUqR6lQ1oNRz2

Scheint wohl nur aufzutreten, wenn ein nicht definierter Zeitraum (in diesem Fall Sonntag) dazwischen ist. Unter der Woche kann auch von einem halben Tag aus normal das Enddatum angewählt werden.

**Comment by markus-mw** [comment]
@chriwen : It's not a bug, it's a feature. ;) Du musst an der Location aktivieren, dass geblockte Tage überbucht werden können:
![image](https://user-images.githubusercontent.com/22905753/156749524-36ceb5a5-8f3b-4afb-95de-0257f228f4c7.png)

**Comment by chriwen** [comment]
@markus-mw  aaah .. :-)
