### ISSUE TITLE
Doppelbuchungen durch Überbuchungen möglich

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#949]
Es ist möglich, dass ein Artikel zweimal für den gleichen Tag gebucht wird, wenn bei einem Standort Doppelbuchungen aktiviert sind.

Beispiel:
Artikel 1
Standort 1 : Überbuchungen aktiviert
Standort 2

Artikel 1 @ Standort 1 = Zeitrahmen 1: Wöchentliche Wiederholung, außer Sonntags
Artikel 1 @ Standort 2 = Zeitrahmen 2: Wöchentliche Wiederholung, nur Sonntags

Wenn jetzt eine Nutzerin den Artikel 1 bei Standort 1 von Samstag bis Montag überbucht, kann eine andere Nutzerin den gleichen Artikel an Standort 2 für Sonntag buchen. 

Screenshot:

![image](https://user-images.githubusercontent.com/6433480/156760182-11282243-676e-482a-8d03-d8072db62b7c.png)

**Comment by hansmorb** [comment]
Ah, das war irgendwie in einer älteren Version, hatte die Issues zurückgehalten. Jetzt ist es gar nicht mehr möglich, die Zeitrahmen wie oben beschrieben zu erstellen. Ist das gewollt?

**Comment by chriwen** [comment]
@hansmorb  Ja, wir hatten da kürzlich eine Prüfung eingebaut, um sicherzustellen, dass kein buchbarer Zeitrahmen für das Item an einem anderen Standort existiert. Ich denke, das greift dann in deinem Fall

**Comment by chriwen** [comment]
https://github.com/wielebenwir/commonsbooking/blob/8e0ca3764e467aef37610f19845ffa8b34212cc8/src/Model/Timeframe.php#L285

**Comment by hansmorb** [comment]
Okay, dann ist es halt nicht möglich, einen regelmäßigen Standortwechsel für einen Artikel zu machen. Ist vielleicht auch nicht so schlimm. Soll ich die issue offen halten?

**Comment by chriwen** [comment]
@hansmorb Den Wechsel kannst du ja schon machen, nur nicht mit überschneidenden Zeitrahmen. Ich würde das dann erstmal schließen. Ggf. ein anderes Ticket aufmachen, wenn es andere Anforderungen gibt (z.B. Buchungen bei "Umzug" erhalten)

**Comment by hansmorb** [comment]
Ich könnte aber zum Beispiel nicht sagen: Jeden Mo-Fr steht der Artikel bei Person A und jeden Sa-So steht der Artikel bei Person B ohne, dass ich irgendwie überschneidende Zeitrahmen erstelle.

**Comment by genevievecory** [comment]
Den Artikel zweimal anlegen, jeweils mit eigenem Zeitrahmen? Unschön aber müsste gehen.
