### ISSUE TITLE
Caching: Restriction Update leert Cache nicht

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#952]
Beim Update von Restrictions (Statusänderung, Verlängerung, Verkürzung) etc. wirken sich die Änderungen nicht auf den Buchungskalender aus, da der Cache für den entsprechenden Artikel nicht geleert wird. Als Workaround kann der betroffene Artikel erneut gespeichert werden, das leert den Cache.

**Comment by chriwen** [comment]
@markus-mw Kannst du das kurzfristig mal anschauen? Würde das gerne noch in das 2.7.-Update übernehmen.

**Comment by markus-mw** [comment]
@hansmorb , @chriwen : Das Problem sollte jetzt behoben sein. Bitte testet es noch einmal.

**Comment by hansmorb** [comment]
Irgendwie greift das bei mir leider nicht direkt nach der Veröffentlichung. Nur wenn ich nach dem Veröffentlichen nochmal manuell auf "Aktualisieren" klicke klappt es.

**Comment by hansmorb** [comment]
Beim Veröfffentlichen des Artikels ist der Post type noch "revision". Vorschlag, stattdessen den Hook wp_insert_post nehmen https://developer.wordpress.org/reference/hooks/wp_insert_post/

**Comment by hansmorb** [comment]
Okay, Problem isoliert: Das Postmeta wird erst nach dem Hook save_post aktualisiert. So kann kein zugewiesenes Postmeta ausgelesen werden, und der Cache wird mit falschen Daten befüllt. wp_insert_post wird nach dem Aktualisieren des Postmetas ausgeführt.
