### ISSUE TITLE
Tabelle ist um einen Tag verschoben

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#958]
Screenshot von KASI-live:
![Bildschirmfoto 2022-03-10 um 13 52 24](https://user-images.githubusercontent.com/28141760/157668408-1cc706f3-e054-4fae-9983-0195a74e0307.png)
![Bildschirmfoto 2022-03-10 um 13 52 12](https://user-images.githubusercontent.com/28141760/157668415-5af796b9-9195-45a2-9280-549e387cbe94.png)

**Comment by hansmorb** [comment]
Leider bei uns gerade auch, im 2.7 release branch:

https://freie-lasten.org/lastenraeder/

Ich habe die Vermutung, dass es mit dem aktuellen Datum zusammenhängt, gestern hat das noch ohne Probleme funktioniert.

**Comment by hansmorb** [comment]
Leider gibt es im aktuellen Release noch Probleme mit der Tabelle, die letzte Buchung wird z.B. hier nicht angezeigt:

![Screenshot_20220417-220849.png](https://user-images.githubusercontent.com/6433480/163730636-d5c69a59-91f3-4284-90e6-bbfc31b41876.png)

![Screenshot_20220417-220907.png](https://user-images.githubusercontent.com/6433480/163730639-946507d5-5905-4219-8327-de108a52c73d.png)

Zu betrachten auf:

freie-lasten.org/gemuese

**Comment by hansmorb** [comment]
Der Tageswechsel hat den Cache jetzt richtig geleert, trotzdem wurde anscheinend der Cache mit der Buchung nicht geleert

**Comment by chriwen** [comment]
@hanneskasimir @hansmorb Das hat sich doch mittlerweile erledigt, oder? DAnn bitte das Ticket schließen. Vielen Dank.

**Comment by markus-mw** [comment]
@hansmorb : Hast du das noch einmal gehabt? Falls nicht, würde ich das Ticket schließen, weil es recht schwierig ist, sowas ohne konkreten Case zu reproduzieren...

**Comment by hansmorb** [comment]
> @hansmorb : Hast du das noch einmal gehabt? Falls nicht, würde ich das Ticket schließen, weil es recht schwierig ist, sowas ohne konkreten Case zu reproduzieren...

Ja leider. Konnte es auch nicht mehr reproduzieren.
