### ISSUE TITLE
URL-Schema / Slug für CPT individualisierbar machen

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commonsbooking#96]
Es soll für Admins möglich sein, in den Plugin-Einstellungen individuelle Slugs für die CPTs zu definieren.

Hinweis: 
Ich glaube das geht über das rewrite-Argument in der Definition der Post-Types:
z.B, für Items: /Wordpress/CustomPostTypes/Item.php, Zeile 108

Wenn das so klappen könnte und sonst nicht viel Aufwand bedeutet, dann bitte so umsetzen.

**Comment by farbschein** [comment]
@markus-mw : ICh hab mal lokal nen Test gemacht. Konnte keine Probleme im Frontend feststellen.

**Comment by markus-mw** [comment]
@farbschein : Ich habe die Einstellung bei den CB-Options ergänzt. Das tut jetzt. Wichtig ist nur, dass man nach einer Änderung einmal die Permalinks-Einstellungsseite aufruft, weil Wordpress die Änderung sonst nicht auf die Kette bekommt. Einen schickeren Weg hab ich auf die Schnelle nicht gefunden.
