### ISSUE TITLE
jQuery UI-CSS beeinflusst Styling anderer Plugins

### ISSUE THREAD

**Issue by danielappelt** [wielebenwir/commonsbooking#960]
**Describe the bug**
Die CSS-Regeln von jQuery UI, wie es in CB eingebunden ist, beeinflussen i.A. auch andere Bereiche im Wordpress Backend, da die Regeln ohne Commonsbooking-spezifisches "Prefixing" eingebunden werden. Betroffen ist z.B. das DIVI-Theme-Backend.

**To Reproduce**
Plugins installieren, die im Backend ebenfalls jQuery UI verwenden oder vergleichbare CSS-Klassennamen. Im Zweifelsfall wirkt sich das Commonsbooking-jQuery UI-Theme auf das Styling anderer Plugins aus oder auch umgekehrt.

**Expected behavior**
CSS-Regeln, die über Commonsbooking eingebunden werden, wirken auch nur auf Commonsbooking.

**Screenshots**
![image](https://user-images.githubusercontent.com/3137880/157732425-053587f7-4214-4720-a7ff-968e1c809097.png)

**Mögliche Lösung**
jQuery-UI-CSS innerhalb einer Commonsbooking-CSS-Klasse einbinden und auf CB-Backend-Seiten die Klasse z.B. auf dem body-Element setzen.

**Comment by markus-mw** [comment]
Der PR von @danielappelt wurder gemerged, daher schließe ich das hier mal.
