### ISSUE TITLE
Ausfall E-Mails sollten nur einmal an eine Person gehen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#963]
![grafik](https://user-images.githubusercontent.com/6433480/158255178-d04d5831-577a-4730-a951-6dbea76559b1.png)

In diesem Falle hat die Person nicht nur den Artikel mehrfach in dem Einschränkungszeitraum gebucht, sie ist auch noch Standortadministrierende. Im Besten Falle, sollte diese E-Mail nur einmal an jede individuelle Nutzende Person gesendet werden.

**Comment by chriwen** [comment]
@hansmorb Bitte mal in Branch bugfix/issue-963 prüfen.

**Comment by hansmorb** [comment]
Passt, danke dir!
