### ISSUE TITLE
CB_items category_slug geht nicht mehr

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#964]
Der CB_items shortcode funktioniert nicht mehr mit dem category_slug Parameter, zu betrachten hier (weiter unten):

https://stage3.commons-booking.org/doppelkarte/

NACHTRAG: Auch dieser Fehler tritt nicht bei aktiviertem WP_DEBUG auf, vielleicht auch ein Caching Problem?

**Comment by markus-mw** [comment]
@hansmorb : Versuchs jetzt bitte nochmal. Sollte wieder funktionieren.

**Comment by hansmorb** [comment]
Leider noch nicht richtig, nach dem Update hatte sich erstmal nichts geändert, nachdem ich einmal WP_DEBUG aktiviert hatte, war die Liste dann auch noch deaktivieren wieder richtig. Wenn jetzt aber ein Artikel neu zu der betroffenen Kategorie hinzugefügt wird (Quick Edit-> Kategorie), dann spinnt die Liste wieder.

**Comment by markus-mw** [comment]
@hansmorb : Jetzt aber. Der Cache-Key war nicht ausreichend. Jetzt sollte es tun. Ich hab es in den master gemerged und auf Stage 3 ausgespielt.
