### ISSUE TITLE
Frontend Buchungsliste erfasst nicht alle Buchungen

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#965]
Leider werden im Frontend nicht alle Buchungen dargestellt, die auch im Backend existieren. 
Das Problem kann behoben werden, indem der entsprechende Artikel aktualisisiert wird, dann taucht die Buchung auch im Backend  auf. Wahrscheinlich ein Caching Problem.

**Comment by markus-mw** [comment]
@hansmorb : Das war etwas knifflig. Jetzt geht's aber. Ich musste an einigen stellen ein paar Tags ergänzen, damit der bei Änderungen sauber invalidiert wird.

**Comment by chriwen** [comment]
@markus-mw Wäre super, wenn du mir und/oder Hans diese Caching-Geschichte nochmal erläutern könntest. Ich habs glaub ich nur halb verstanden ;-)
Was mir aber auffiel:
Hier https://github.com/wielebenwir/commonsbooking/blob/4bd2cd36d0c8b8b05040ab268d6447e41f35b966/src/Helper/Wordpress.php#L228
kombinierst du ja alle IDS der Locations und Items und entfernst Duplikate. 
Die IDS können ja aber mal für ein Item oder für eine Location stehen. Also ggf. doppelt vorhanden sein für die jeweils verschiedenen Typen. Ist das in dem Fall dann egal? Oder wie ist das mit diesen Tags gedacht?

**Comment by markus-mw** [comment]
> @markus-mw vergiss den letzten Kommentar. Sind ja alles Posts mit fortlaufender ID ;-)

😉

**Comment by hansmorb** [comment]
Sieht gut aus, dankeschön!
