### ISSUE TITLE
Gerade erstellte Artikel tauchen nicht in Zeitrahmen Liste auf

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#966]
Wenn ein Artikel gerade erstellt wurde, taucht er oft nicht sofort in der Liste für die Erstellung der Zeitrahmen auf. Früher war es teilweise erst nach sehr langer Verzögerung. Jetzt war das einzige was geholfen hat, den Branch zu wechseln, vielleicht wird nach dem Update Task der Cache geleert und dann ist die Zeitrahmenliste wieder aktuell? Zu sehen auf stage3 bei dem "Artikel mit Kategorie" und "Artikel ohne Kategorie".

NACHTRAG: Sobald WP_DEBUG aktiviert ist, taucht der Artikel sofort auf, ist das eine Caching issue?

**Comment by chriwen** [comment]
@hansmorb Danke für den Hinweis. Ich denke ja, da bei aktiviertem DEBUG das Caching deaktiviert ist. 
@markus-mw : Kannst du das prüfen?

**Comment by hansmorb** [comment]
Funktioniert jetzt, danke dir!
