### ISSUE TITLE
Reminder-Mails werden nicht verschickt

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#972]
Auf kasimir-live (mit dem RC 2.7 Branch) werden derzeit keine Reminder-Mails versendet. 
Der Versand stoppte vor ca. 1 Woche als ich die letzte Version eingespielt habe. 

@markus-mw könntest du dir das mal anschauen?

**Comment by markus-mw** [comment]
@chriwen : Ist korrigiert.
