### ISSUE TITLE
Buchungsliste wird nicht aktualisiert

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commonsbooking#974]
Anscheinend wird die Frontend-Buchungsliste nicht zuverlässig aktualisiert. Nutzende berichtet, dass neue Buchungen nicht in der Liste erscheinen. 
Ich hatte das selbst auch schon mal bei einem Test wahrgenommen.

**Comment by chriwen** [comment]
@markus-mw Könntest du nochmal überprüfen, ob das Caching hier korrekt arbeitet und neue Buchungen in der Liste berücksichtigt?

**Comment by hansmorb** [comment]
Hat das was mit #965 zu tun? Weil das funktioniert im neuen Master jetzt problemlos.

**Comment by chriwen** [comment]
@markus-mw ich habs jetzt nicht nochmal getestet, aber schließe erstmal das Ticket.
