### ISSUE TITLE
Stornierungszeit ist zeitverschoben

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#985]
![image](https://user-images.githubusercontent.com/6433480/160933233-d9c4c2ad-11db-4d24-8aec-767c54fed055.png)

Systemzeit war 23:21, Serverzeit auch. Die Stornierungszeit wird immer als zwei Stunden früher angegeben.  Im aktuellen Master.

**Comment by markus-mw** [comment]
@hansmorb : Bei mir entspricht die Zeit der Serverzeit. Bist du dir ganz sicher was das angeht?

**Comment by hansmorb** [comment]
Das date Kommando gibt folgendes aus: 
![image](https://user-images.githubusercontent.com/6433480/161296499-d7af66a1-b43f-48e6-86a1-cb7a8ecf5b21.png)
Und die restlichen Zeiten von und in Wordpress sind auch korrekt. Tritt sowohl auf unserem Server als auch in meiner lokalen Installation auf

**Comment by hansmorb** [comment]
![image](https://user-images.githubusercontent.com/6433480/161324347-86311e42-cdf6-4bdd-b2d7-edd5e630838c.png)
Die Funktion date_i18n nimmt einen Timestamp MIT Offset als Input, deshalb muss der Offset extra berechnet werden. Ich kann das hier korrigieren, betrifft das eventuell  noch andere Stellen im Code?

**Comment by hansmorb** [comment]
Wenn die current_time Funktion statt der time() Funktion verwendet wird, wird ein lokalisierter Timestamp zurückgegeben, das behebt hier das Problem, könnte aber auch noch andere Stellen im Code betreffen.
