### ISSUE TITLE
nur noch ein Artikel in items_liste. Version 2.7. auf Fahrrad und Familie

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commonsbooking#986]
[Verleih – Fahrrad & Familie e.V_Verleihtool-Bug.pdf](https://github.com/wielebenwir/commonsbooking/files/8386960/Verleih.Fahrrad.Familie.e.V_Verleihtool-Bug.pdf)

**Comment by hanneskasimir** [comment]
ich hab jetzt die 2.6.11 installiert, damit ist alles in Ordnung.

**Comment by chriwen** [comment]
@hanneskasimir Besteht das Problem in der aktuellen, offiziellen 2.7 immer noch?
