### ISSUE TITLE
Reparaturslot blockiert ganzen Tag

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/commonsbooking#987]
Zu begutachten hier:

https://stage3.commons-booking.org/rundedinge/slotweise-reparatur/?location=3624

Der Artikel hat zwei Slots pro Tag, wenn jetzt ein Reparaturslot für nur einen der beiden Slots eingestellt wird, gilt gleich der ganze Tag als gebucht.

**Comment by markus-mw** [comment]
Die Option Reparatur gibt's ja nicht mehr. Tritt das Problem auch mit dem Typ "Feiertage oder Station geschlossen" auf?

**Comment by hansmorb** [comment]
Nein, das funktioniert mittlerweile!
